/**
 * Historical and narrative boundary for the fictional EnemyRear1941 county.
 *
 * This module deliberately separates fixed historical anchors from composite
 * local events. Game systems may consume the local events, but must never turn
 * them into claims that one fictional county changed the national outcome.
 */

function DeepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) {
    return value;
  }
  for (const child of Object.values(value)) {
    DeepFreeze(child);
  }
  return Object.freeze(value);
}

export const responsibilityStageDefinitions = DeepFreeze([
  { id: "Detect", label: "发现预警" },
  { id: "Prepare", label: "准备物资与路线" },
  { id: "Protect", label: "疏散与保护" },
  { id: "Resolve", label: "应对行动" },
  { id: "Recover", label: "救济与恢复" },
]);

export const historyBoundary = DeepFreeze({
  id: "CompositeTaihangCounty_1941_1942",
  title: "虚构合成太行县域：1941年9月至1942年12月",
  classification: "历史环境中的情境合成战役",
  geography: {
    region: "华北太行山区的虚构县域",
    mapRule: "村名、县城、车站、据点和道路均为合成地理，不对应一张真实县域地图。",
    antiCompressionRule: "不得把阜平、黄崖洞、西柏坡、冉庄、白洋淀等相距较远的真实地点压缩为相邻地块。",
  },
  time: {
    start: "1941-09",
    end: "1942-12",
    turnCount: 16,
    endpoint: "本局只结算至1942年12月；敌后抗战和全国抗战都仍在继续。",
  },
  claims: {
    local: "玩家影响的是一个合成县域能否保存群众、组织、交通和有限抗战能力。",
    national: "全国战略相持通常从1938年10月前后起算；本游戏的地方阶段名称不是全国抗战分期。",
    fixedVictory: "中国人民抗日战争的全国胜利属于固定历史，1945年日本投降不能被玩家提前、推迟或改写。",
  },
  scoringRules: [
    "不以击杀数量计分，也不设置可兑换奖励的歼敌榜。",
    "平民伤亡、拘押、流离与房屋损毁只记入责任和后果账本，不能兑换资源。",
    "战斗贡献不能抵消民生损失；保护群众、保存组织与履行救济责任是独立门槛。",
    "俘虏不是兵源或货币；投降、拘押、救治、甄别和自愿选择必须分别处理。",
  ],
  narrativeRules: [
    "真人只在档案说明、纪念条目或来源引文中出现，保持其真实身份与固定命运。",
    "可操作人物全部是明确标注的普通合成人物，不冒充真实英雄，不使用伪造名言。",
    "侵略、征粮、焚毁、拘捕与伤亡的责任归于侵华日军占领政策和具体占领行动，不归咎于受害群众。",
    "敌方角色采用职务、单位与可观察行为描述，不使用假日语、夸张口音或脸谱化外貌。",
    "每个任务遵循发现、准备、保护、应对、恢复的责任链；失败后果进入后续回合。",
  ],
  archivePolicy: {
    realPeoplePlacement: "ArchiveOnly",
    interactiveRealPeople: false,
    numericRewardForRealPeople: false,
    quotationRule: "只有能够追溯到公开来源的原文才可作为档案引文；任务对白不得仿造历史人物口吻。",
  },
  sourceIds: [
    "PeoplesDailyResistanceHistory",
    "ModernHistoryDocumentPlatform",
    "OnProtractedWar1938",
    "FrusChina1942",
    "UnitedNationsDeclaration1942",
    "CairoDeclaration1943",
    "PotsdamDeclaration1945",
    "JapanSurrender1945",
    "IcrcPrisonersOfWar1929",
  ],
});

export const localPhaseDefinitions = DeepFreeze([
  {
    id: "AutumnHarvestAndHiddenExpansion",
    classification: "地方阶段",
    title: "保秋收与隐蔽联络",
    turnRange: [1, 2],
    dateRange: ["1941-09", "1941-10"],
    description: "在据点、公路和征粮压力下先保存秋收，再谨慎扩展熟人联络。",
    notNationalPeriodization: true,
  },
  {
    id: "WinterBlockadeAndDispersal",
    classification: "地方阶段",
    title: "冬季封锁与分散坚持",
    turnRange: [3, 6],
    dateRange: ["1941-11", "1942-02"],
    description: "严查、寒冷和药品短缺迫使机构分散，交通线需要反复转移和修复。",
    notNationalPeriodization: true,
  },
  {
    id: "SpringHardshipAndWarning",
    classification: "地方阶段",
    title: "春荒救济与扫荡预警",
    turnRange: [7, 8],
    dateRange: ["1942-03", "1942-04"],
    description: "春荒、水源卫生与兵力异动同时出现，救济和预警必须并行。",
    notNationalPeriodization: true,
  },
  {
    id: "CounterSweepAndRecovery",
    classification: "地方阶段",
    title: "反扫荡与灾后恢复",
    turnRange: [9, 12],
    dateRange: ["1942-05", "1942-08"],
    description: "疏散和有限牵制之后，清点失散住户、恢复饮水、交通与生产。",
    notNationalPeriodization: true,
  },
  {
    id: "HarvestProtectionAndWinterPressure",
    classification: "地方阶段",
    title: "再保秋收与冬季压力",
    turnRange: [13, 16],
    dateRange: ["1942-09", "1942-12"],
    description: "保护收成、核验交通风险并转移民生机构，保存继续抗战的条件。",
    notNationalPeriodization: true,
  },
]);

export const ordinaryRoleDefinitions = DeepFreeze([
  {
    id: "TrafficWorker",
    role: "交通员",
    displayName: "林秋生",
    classification: "情境合成人物",
    description: "熟悉村际小路和联络规程，负责分段传递，不掌握整张网络。",
    agencyLimit: "只能确认自己经过的区段；失联时由备用交通关系接替，不能单人拯救全县。",
    isRealPerson: false,
  },
  {
    id: "VillageMedic",
    role: "乡村医护员",
    displayName: "乔兰",
    classification: "情境合成人物",
    description: "管理简陋药箱、饮水卫生和伤病转移，医疗能力受药品与道路约束。",
    agencyLimit: "不能独自完成运输、作战和全村疏散；重伤和疫病会留下持续照护负担。",
    isRealPerson: false,
  },
  {
    id: "CooperativeOrganizer",
    role: "合作社组织者",
    displayName: "孙禾",
    classification: "情境合成人物",
    description: "登记困难住户、协调互助劳力与修具，不把家庭当作可消耗资源。",
    agencyLimit: "物资分配必须经村民核对；生产自救需要时间、工具和劳力，不能凭空变出粮食。",
    isRealPerson: false,
  },
  {
    id: "RailwayWorker",
    role: "铁路工人",
    displayName: "郭平川",
    classification: "情境合成人物",
    description: "从班次、煤车、维修和岗哨变化判断运输异常，只提供有置信度的片段情报。",
    agencyLimit: "不能读取敌军完整计划；错误判断会增加交通线暴露并危及工友。",
    isRealPerson: false,
  },
  {
    id: "DisplacedFamily",
    role: "流离家庭",
    displayName: "何家三口",
    classification: "情境合成人物群体",
    description: "房屋受损后寄居邻村，拥有选择、记忆和亲属关系，不是抽象的受害数字。",
    agencyLimit: "是否转移、返村和提供帮助取决于安全、口粮、照护与信任，不能只作为推动情节的工具。",
    isRealPerson: false,
  },
]);

export const fixedHistoricalAnchors = DeepFreeze([
  {
    id: "NationalStrategicStalemateLate1938",
    classification: "固定史实锚点",
    date: "1938年10月以后",
    scope: "全国",
    statement: "全国抗战通常以武汉、广州失守前后作为由战略防御转入战略相持的节点。",
    gameplayConstraint: "1941至1942年的回合只能使用地方阶段名称，不能再次宣称全国刚进入战略相持。",
    sourceIds: ["PeoplesDailyResistanceHistory", "OnProtractedWar1938"],
  },
  {
    id: "BaseAreaHardship1941To1942",
    classification: "固定史实锚点",
    date: "1941年至1942年",
    scope: "华北敌后战场",
    statement: "敌后根据地在军事封锁、经济困难和反复扫荡中经历严重困难，生产、交通和群众保护彼此关联。",
    gameplayConstraint: "困难不能只表现为敌军伤害倍率，必须同时影响粮药、交通、组织和灾后恢复。",
    sourceIds: ["PeoplesDailyResistanceHistory", "ModernHistoryDocumentPlatform"],
  },
  {
    id: "PacificWarExpansionDecember1941",
    classification: "固定史实锚点",
    date: "1941年12月",
    scope: "国际与全国背景",
    statement: "太平洋战争扩大了战争范围，但不能据此推导本县守备力量会在某一回合自动撤走。",
    gameplayConstraint: "该锚点只提供背景；地方敌军变化仍须由可见调动、补给和守备账本决定。",
    sourceIds: ["UshmmPacificWar", "FrusChina1942"],
  },
  {
    id: "UnitedNationsDeclarationJanuary1942",
    classification: "固定史实锚点",
    date: "1942年1月1日",
    scope: "国际与全国背景",
    statement: "中国是《联合国家宣言》的签署国之一，抗战属于世界反法西斯战争的一部分。",
    gameplayConstraint: "国际史实只进入档案说明，不提供凭空出现的地方资源奖励。",
    sourceIds: ["UnitedNationsDeclaration1942", "FrusChina1942"],
  },
  {
    id: "CairoDeclarationDecember1943",
    classification: "固定史实锚点",
    date: "1943年12月1日公布",
    scope: "本局时间范围之后",
    statement: "《开罗宣言》属于本局结束后的固定国际史实。",
    gameplayConstraint: "只能在结局档案的后续时间线上出现，不能因1941至1942年的玩家行动而提前进入本局。",
    sourceIds: ["CairoDeclaration1943"],
  },
  {
    id: "PotsdamDeclarationJuly1945",
    classification: "固定史实锚点",
    date: "1945年7月26日",
    scope: "本局时间范围之后",
    statement: "《波茨坦公告》属于固定的战争终局时间线。",
    gameplayConstraint: "不得成为县域任务奖励，也不得成为由玩家开启的架空结局。",
    sourceIds: ["PotsdamDeclaration1945"],
  },
  {
    id: "NationalVictoryAndSurrender1945",
    classification: "固定史实锚点",
    date: "1945年8月至9月",
    scope: "全国与国际",
    statement: "中国人民抗日战争取得胜利，日本于1945年9月2日签署投降书。",
    gameplayConstraint: "任何本县胜负都不能提前结束全国战争，也不能抹去全国各抗日力量和人民的贡献。",
    sourceIds: ["PotsdamDeclaration1945", "JapanSurrender1945", "CairoDeclaration1943"],
  },
]);

export const sourceReferences = DeepFreeze([
  {
    id: "PeoplesDailyResistanceHistory",
    title: "中华民族抗日战争史（1931—1945）",
    publisher: "人民网党史频道",
    url: "http://dangshi.people.com.cn/GB/146570/396421/",
    kind: "公开历史专题",
    accessedOn: "2026-07-29",
    usedFor: [
      "Boundary.NationalPeriodization",
      "Anchor.NationalStrategicStalemateLate1938",
      "Anchor.BaseAreaHardship1941To1942",
    ],
  },
  {
    id: "ModernHistoryDocumentPlatform",
    title: "抗日战争与近代中日关系文献数据平台",
    publisher: "中国社会科学院近代史研究所等",
    url: "https://www.modernhistory.org.cn/",
    kind: "公开文献目录与数字资料平台",
    accessedOn: "2026-07-29",
    usedFor: [
      "Boundary.CompositeGeographyAndSourceDiscipline",
      "Anchor.BaseAreaHardship1941To1942",
      "Archive.SourceVerificationWorkflow",
    ],
  },
  {
    id: "OnProtractedWar1938",
    title: "On Protracted War（《论持久战》英译公开文本）",
    publisher: "Marxists Internet Archive",
    url: "https://www.marxists.org/reference/archive/mao/selected-works/volume-2/mswv2_09.htm",
    kind: "1938年原始文献公开转录",
    accessedOn: "2026-07-29",
    usedFor: [
      "Anchor.NationalStrategicStalemateLate1938",
      "Archive.RealPersonTextOnly",
      "Boundary.ProtractedWarDoesNotEqualLocalVictory",
    ],
  },
  {
    id: "FrusChina1942",
    title: "Foreign Relations of the United States, 1942, China",
    publisher: "United States Department of State, Office of the Historian",
    url: "https://history.state.gov/historicaldocuments/frus1942China",
    kind: "公开外交档案汇编",
    accessedOn: "2026-07-29",
    usedFor: [
      "Anchor.PacificWarExpansionDecember1941",
      "Anchor.UnitedNationsDeclarationJanuary1942",
      "Boundary.ChinaInInternationalWarContext",
    ],
  },
  {
    id: "UshmmPacificWar",
    title: "World War II in the Pacific",
    publisher: "United States Holocaust Memorial Museum",
    url: "https://encyclopedia.ushmm.org/content/en/article/world-war-ii-in-the-pacific",
    kind: "公共历史百科",
    accessedOn: "2026-07-29",
    usedFor: [
      "Anchor.PacificWarExpansionDecember1941",
      "Boundary.NoAutomaticLocalTroopWithdrawal",
    ],
  },
  {
    id: "UnitedNationsDeclaration1942",
    title: "Declaration by United Nations, January 1, 1942",
    publisher: "Yale Law School, Avalon Project",
    url: "https://avalon.law.yale.edu/20th_century/decade03.asp",
    kind: "公开外交文件转录",
    accessedOn: "2026-07-29",
    usedFor: [
      "Anchor.UnitedNationsDeclarationJanuary1942",
      "Boundary.FixedInternationalTimeline",
    ],
  },
  {
    id: "CairoDeclaration1943",
    title: "Cairo Declaration",
    publisher: "Yale Law School, Avalon Project",
    url: "https://avalon.law.yale.edu/wwii/cairo.asp",
    kind: "公开外交文件转录",
    accessedOn: "2026-07-29",
    usedFor: [
      "Anchor.CairoDeclarationDecember1943",
      "Anchor.NationalVictoryAndSurrender1945",
      "Boundary.PostScenarioArchiveOnly",
    ],
  },
  {
    id: "PotsdamDeclaration1945",
    title: "Proclamation Defining Terms for Japanese Surrender",
    publisher: "Yale Law School, Avalon Project",
    url: "https://avalon.law.yale.edu/20th_century/decade17.asp",
    kind: "公开外交文件转录",
    accessedOn: "2026-07-29",
    usedFor: [
      "Anchor.PotsdamDeclarationJuly1945",
      "Anchor.NationalVictoryAndSurrender1945",
      "Boundary.NationalOutcomeCannotBeRewritten",
    ],
  },
  {
    id: "JapanSurrender1945",
    title: "Surrender of Japan",
    publisher: "U.S. National Archives",
    url: "https://www.archives.gov/milestone-documents/surrender-of-japan",
    kind: "公开档案与投降书影像",
    accessedOn: "2026-07-29",
    usedFor: [
      "Anchor.NationalVictoryAndSurrender1945",
      "Boundary.Fixed1945Endpoint",
    ],
  },
  {
    id: "IcrcPrisonersOfWar1929",
    title: "Convention relative to the Treatment of Prisoners of War, Geneva, 27 July 1929",
    publisher: "International Committee of the Red Cross",
    url: "https://ihl-databases.icrc.org/en/ihl-treaties/gc-pow-1929",
    kind: "公开国际人道法文本",
    accessedOn: "2026-07-29",
    usedFor: [
      "Boundary.PrisonersAreNotResources",
      "Archive.DetainmentAndTreatmentContext",
    ],
  },
]);

function CreateResponsibilityChain(stageRows) {
  return responsibilityStageDefinitions.map((stageDefinition, stageIndex) => {
    const [action, actorRoleIds, consequenceIfMissed] = stageRows[stageIndex];
    return {
      stageId: stageDefinition.id,
      label: stageDefinition.label,
      action,
      actorRoleIds,
      consequenceIfMissed,
    };
  });
}

function CreateHistoricalTurn(definition) {
  return {
    turn: definition.turn,
    dateKey: definition.dateKey,
    date: definition.date,
    localPhaseId: definition.localPhaseId,
    title: definition.title,
    historicalFrame: definition.historicalFrame,
    event: {
      id: `CompositeEventTurn${definition.turn}`,
      classification: "情境合成",
      title: definition.eventTitle,
      synopsis: definition.eventSynopsis,
      roleIds: definition.roleIds,
      disclaimer: "人物、村庄与行动细节均为情境合成，不声称复原某一次真实行动。",
    },
    fixedAnchorIds: definition.fixedAnchorIds,
    responsibilityChain: CreateResponsibilityChain(definition.chain),
    failureCarryForward: {
      persists: true,
      cannotBeCanceledByCombatScore: true,
      text: definition.failureCarryForward,
    },
    archiveNote: definition.archiveNote,
  };
}

export const historicalTurnNarratives = DeepFreeze([
  CreateHistoricalTurn({
    turn: 1,
    dateKey: "1941-09",
    date: "1941年9月",
    localPhaseId: "AutumnHarvestAndHiddenExpansion",
    title: "先保住一季收成",
    historicalFrame: "合成县域进入秋收时节，占领军据点的征粮压力与流离住户的口粮缺口同时出现。",
    eventTitle: "合作社账簿上的空栏",
    eventSynopsis: "孙禾发现何家三口没有被列入分粮名册，附近公路又传来征粮车的消息。",
    roleIds: ["CooperativeOrganizer", "DisplacedFamily", "TrafficWorker"],
    fixedAnchorIds: ["NationalStrategicStalemateLate1938", "BaseAreaHardship1941To1942"],
    chain: [
      ["核对困难户、征粮传闻和各仓实际存量。", ["CooperativeOrganizer", "TrafficWorker"], "征粮方向和缺粮家庭都保持未知。"],
      ["把口粮分仓，预留转移工具并登记寄居家庭。", ["CooperativeOrganizer", "DisplacedFamily"], "集中粮仓和漏登家庭将在同一次冲击中受损。"],
      ["先为老幼和寄居户安排隐蔽去处，不强迫家庭充当诱饵。", ["DisplacedFamily", "TrafficWorker"], "流离家庭的饥饿与失散风险上升。"],
      ["以错峰收割和短途接力避开征粮路线，不组织夺粮竞赛。", ["CooperativeOrganizer", "TrafficWorker"], "秋收暴露将招致下一回合更严盘查。"],
      ["公开核对分配，补记失散住户并修复被踩坏的田埂。", ["CooperativeOrganizer", "DisplacedFamily"], "漏登与不信任进入后续分配。"],
    ],
    failureCarryForward: "未保护的口粮转为冬季短缺；漏登家庭在后续回合降低信任并增加救济负担。",
    archiveNote: "秋收、征粮和互助是时代环境；具体家庭与账簿事件为合成。",
  }),
  CreateHistoricalTurn({
    turn: 2,
    dateKey: "1941-10",
    date: "1941年10月",
    localPhaseId: "AutumnHarvestAndHiddenExpansion",
    title: "山口的陌生脚印",
    historicalFrame: "据点巡查沿山口延伸，扩展联络若脱离熟人关系会留下可追踪痕迹。",
    eventTitle: "两条不一致的巡逻消息",
    eventSynopsis: "林秋生与郭平川分别带回公路和车站消息，但时间相差半日，需要交叉核验。",
    roleIds: ["TrafficWorker", "RailwayWorker"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["把脚印、班次和岗哨变化分为已证实、可能和未知。", ["TrafficWorker", "RailwayWorker"], "未经核验的消息会被误当成确定敌情。"],
      ["启用两条分离交通线并约定失联时限。", ["TrafficWorker"], "一次盘查可能暴露整条联络链。"],
      ["通知受威胁住户先转移名册和药品，不公开召集。", ["TrafficWorker", "VillageMedic"], "机构与住户在同一地点暴露。"],
      ["只对已确认路段实施绕行和假痕迹，不寻找可疑者替罪。", ["TrafficWorker", "RailwayWorker"], "误判会伤害无辜并提高敌军证据置信度。"],
      ["复盘哪些消息得到验证，撤销过期口令并慰问受盘查家庭。", ["TrafficWorker", "CooperativeOrganizer"], "错误情报继续污染下一回合判断。"],
    ],
    failureCarryForward: "未经核验的路线会在冬季严查时增加暴露；被误判家庭的信任不能靠战斗贡献恢复。",
    archiveNote: "事件强调有限情报，不塑造无所不知的地下网络。",
  }),
  CreateHistoricalTurn({
    turn: 3,
    dateKey: "1941-11",
    date: "1941年11月",
    localPhaseId: "WinterBlockadeAndDispersal",
    title: "药箱过封锁线",
    historicalFrame: "入冬后交通和药品更紧张，救护点需要分散而非集中成为醒目标志。",
    eventTitle: "缺少退烧药的夜诊",
    eventSynopsis: "乔兰要照护发热儿童，林秋生只能在两段交通线上安排小批量转运。",
    roleIds: ["VillageMedic", "TrafficWorker", "DisplacedFamily"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["登记症状、药品余量和两条路线的盘查时段。", ["VillageMedic", "TrafficWorker"], "疾病与路线风险都无法排序。"],
      ["拆分药品，准备煮沸饮水、保暖物和备用诊疗点。", ["VillageMedic", "DisplacedFamily"], "药箱被截或诊疗点暴露后没有替代方案。"],
      ["优先转移重病者与照护者，避免让儿童独自移动。", ["VillageMedic", "TrafficWorker"], "病情恶化并增加家庭失散。"],
      ["交通员分段交接药品，医护员留在隐蔽点接诊。", ["TrafficWorker", "VillageMedic"], "单人承担全部路程会连带暴露两端。"],
      ["记录用药和接触者，补充清洁用具并安排复诊。", ["VillageMedic", "CooperativeOrganizer"], "感染与药品短缺延续到严冬。"],
    ],
    failureCarryForward: "未处置的病情形成持续医护负担，降低后续疏散速度和劳动力，而非三回合自动恢复。",
    archiveNote: "不指定真实医疗单位；诊疗能力遵守物资、道路与照护限制。",
  }),
  CreateHistoricalTurn({
    turn: 4,
    dateKey: "1941-12",
    date: "1941年12月",
    localPhaseId: "WinterBlockadeAndDispersal",
    title: "道路严查与战争扩大",
    historicalFrame: "太平洋战争扩大了国际战局，但本县没有因此自动获得守备空虚或奖励。",
    eventTitle: "车站煤堆旁的新岗哨",
    eventSynopsis: "郭平川观察到岗哨更换和煤车延误，只能判断交通趋紧，不能推断敌军已撤离。",
    roleIds: ["RailwayWorker", "TrafficWorker"],
    fixedAnchorIds: ["PacificWarExpansionDecember1941", "BaseAreaHardship1941To1942"],
    chain: [
      ["记录岗哨、维修和列车间隔，标注推断置信度。", ["RailwayWorker"], "国际新闻会被错误转换为本地兵力结论。"],
      ["暂停高暴露运输，准备不经过车站的短途接力。", ["TrafficWorker", "RailwayWorker"], "交通站在严查中留下连续痕迹。"],
      ["先转移交通名册、药品和寄居住户，不争抢象征性目标。", ["TrafficWorker", "VillageMedic", "DisplacedFamily"], "人员和机构被迫同时撤离。"],
      ["根据可见调动调整路线，不把国际事件当作敌军自动减员。", ["RailwayWorker", "TrafficWorker"], "错误乐观导致冒险行动和更高暴露。"],
      ["核实失联人员，更新班次档案并补偿受影响工友家庭。", ["RailwayWorker", "CooperativeOrganizer"], "工友关系断裂并削弱后续铁路情报。"],
    ],
    failureCarryForward: "错误的守备判断会影响下一回合敌情置信度；受牵连工友家庭需要持续救济。",
    archiveNote: "国际史实为固定锚点；车站与工人均为合成。",
  }),
  CreateHistoricalTurn({
    turn: 5,
    dateKey: "1942-01",
    date: "1942年1月",
    localPhaseId: "WinterBlockadeAndDispersal",
    title: "雪夜借宿名册",
    historicalFrame: "严冬增加口粮、燃料和照护负担，寄居关系需要得到明确保护。",
    eventTitle: "何家三口的第二次转移",
    eventSynopsis: "何家借住处靠近新巡逻线，是否再转移必须由家庭参与决定。",
    roleIds: ["DisplacedFamily", "CooperativeOrganizer", "VillageMedic", "TrafficWorker"],
    fixedAnchorIds: ["UnitedNationsDeclarationJanuary1942", "BaseAreaHardship1941To1942"],
    chain: [
      ["询问家庭意愿，核对巡逻、天气和病情。", ["DisplacedFamily", "TrafficWorker", "VillageMedic"], "家庭被当作无声任务目标，风险判断失真。"],
      ["准备保暖物、口粮、照护人和两处可选住地。", ["CooperativeOrganizer", "VillageMedic"], "转移途中或抵达后立即断粮。"],
      ["由家庭选择路线并保持亲属同行，隐藏借宿名册。", ["DisplacedFamily", "TrafficWorker"], "老幼失散或寄居家庭遭连带盘查。"],
      ["小组分段护送，不为争取分数与巡逻硬拼。", ["TrafficWorker", "DisplacedFamily"], "护送转为不必要战斗并危及被保护者。"],
      ["确认安置、补发口粮并登记原住地损失。", ["CooperativeOrganizer", "DisplacedFamily"], "流离损失从账本中消失，后续恢复无从安排。"],
    ],
    failureCarryForward: "失散、冻病和寄居矛盾持续影响民生与信任；国际外交锚点不会自动消除地方困难。",
    archiveNote: "《联合国家宣言》只在档案层出现，不会凭空带来本地物资。",
  }),
  CreateHistoricalTurn({
    turn: 6,
    dateKey: "1942-02",
    date: "1942年2月",
    localPhaseId: "WinterBlockadeAndDispersal",
    title: "重接一段交通线",
    historicalFrame: "短暂间隙适合修复分段联络，但旧口令和失踪原因必须先核验。",
    eventTitle: "迟到两日的竹签",
    eventSynopsis: "一枚旧交通凭据出现在约定地点，林秋生不能据此确认失联同伴安全。",
    roleIds: ["TrafficWorker", "RailwayWorker", "CooperativeOrganizer"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["用第二来源核对凭据、时间和沿线盘查记录。", ["TrafficWorker", "RailwayWorker"], "旧凭据可能成为诱导整网暴露的假线索。"],
      ["废止旧口令，设置只连接相邻两段的临时接点。", ["TrafficWorker"], "一名交通员仍能暴露整条网络。"],
      ["通知接点附近家庭暂停公开往来并准备短期安置。", ["CooperativeOrganizer", "TrafficWorker"], "联络恢复把风险转嫁给无准备的住户。"],
      ["先做无敏感内容的试递送，再逐步恢复必要通信。", ["TrafficWorker"], "一次错误确认造成不可逆网络损失。"],
      ["记录未解疑点，救济受盘查家庭并保留备用线路。", ["TrafficWorker", "CooperativeOrganizer"], "网络表面恢复但没有韧性。"],
    ],
    failureCarryForward: "未经核验的失联原因提高春季敌军情报质量；受牵连家庭的损失继续存在。",
    archiveNote: "反谍依靠证据链和区隔，不能因一次偶然接触便自动得出结论。",
  }),
  CreateHistoricalTurn({
    turn: 7,
    dateKey: "1942-03",
    date: "1942年3月",
    localPhaseId: "SpringHardshipAndWarning",
    title: "春荒与一口水井",
    historicalFrame: "存粮见底时，救济、生产和饮水卫生必须共同安排。",
    eventTitle: "井边的发热名单",
    eventSynopsis: "乔兰发现几户出现相似症状，孙禾同时面对种粮与救济粮的分配争议。",
    roleIds: ["VillageMedic", "CooperativeOrganizer", "DisplacedFamily"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["分别核对饮水、症状、口粮和困难户，不把相关性直接当病因。", ["VillageMedic", "CooperativeOrganizer"], "疫情与饥饿被混为单一数值。"],
      ["准备煮水、清洁、隔离照护和最低救济口粮。", ["VillageMedic", "CooperativeOrganizer"], "救济耗尽后没有恢复方案。"],
      ["保障病户、儿童和寄居家庭取水，不封死唯一水源。", ["VillageMedic", "DisplacedFamily"], "弱势家庭承担全部防疫成本。"],
      ["分开病患照护与春耕互助，避免带病集中劳动。", ["VillageMedic", "CooperativeOrganizer"], "短期生产换来更长疾病负担。"],
      ["复查水井、补种和营养情况，把未康复者带入下月照护表。", ["VillageMedic", "CooperativeOrganizer"], "疾病被回合结算抹去。"],
    ],
    failureCarryForward: "未康复人口减少可用劳力并增加药品、照护和信任压力，不能由破袭得分抵消。",
    archiveNote: "事件不宣称复原某次真实疫情，强调民生后果的持续性。",
  }),
  CreateHistoricalTurn({
    turn: 8,
    dateKey: "1942-04",
    date: "1942年4月",
    localPhaseId: "SpringHardshipAndWarning",
    title: "扫荡前的模糊信号",
    historicalFrame: "多种运输与巡查异常可能指向行动准备，但目标和时间仍不确定。",
    eventTitle: "维修班次突然加密",
    eventSynopsis: "郭平川发现线路维修和岗哨换防同时增加，林秋生需要把消息转成有范围的预警。",
    roleIds: ["RailwayWorker", "TrafficWorker", "VillageMedic", "CooperativeOrganizer"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["把维修、车次、征粮和巡逻信号交叉比对，标出可能方向。", ["RailwayWorker", "TrafficWorker"], "全县因单一传闻同时暴露或恐慌。"],
      ["按风险准备分仓、药箱、疏散名册和备用交通段。", ["CooperativeOrganizer", "VillageMedic", "TrafficWorker"], "预警没有转化为可执行准备。"],
      ["优先安排老幼、病患和暴露机构，允许低风险村庄维持必要生产。", ["VillageMedic", "CooperativeOrganizer"], "不分风险强行疏散会造成额外饥饿和流离。"],
      ["发出分级预警并隐藏来源，不公布铁路工人身份。", ["TrafficWorker", "RailwayWorker"], "情报来源及其工友遭连带风险。"],
      ["持续更新置信度，取消过期警报并补偿误工家庭。", ["TrafficWorker", "CooperativeOrganizer"], "警报疲劳降低下一回合响应。"],
    ],
    failureCarryForward: "漏报会放大扫荡伤害，误报会消耗粮食与信任；两者都进入五月结算。",
    archiveNote: "事件表达有限情报，不让玩家或敌军读取对方隐藏真相。",
  }),
  CreateHistoricalTurn({
    turn: 9,
    dateKey: "1942-05",
    date: "1942年5月",
    localPhaseId: "CounterSweepAndRecovery",
    title: "先让村庄空下来",
    historicalFrame: "合成县域遭遇多路搜剿压力，目标是保护群众和网络，不是争夺击杀数字。",
    eventTitle: "最后一辆手推车",
    eventSynopsis: "药箱、粮袋和行动不便的老人无法同时装车，各小组必须分担而非等待英雄解决。",
    roleIds: ["TrafficWorker", "VillageMedic", "CooperativeOrganizer", "DisplacedFamily"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["确认敌军轴线、尚未转移住户和可通行山路。", ["TrafficWorker", "RailwayWorker"], "疏散顺序失去依据。"],
      ["拆分药粮，组织多辆小车、担架与接应点。", ["VillageMedic", "CooperativeOrganizer"], "一辆车一旦受阻，整条疏散线便会中断。"],
      ["先送行动不便者和儿童，家庭成员在接应点重新点名。", ["DisplacedFamily", "VillageMedic"], "疏散本身制造失散。"],
      ["武装只在必要路口掩护脱离，达成时间目标后撤出。", ["TrafficWorker"], "恋战把敌军引向疏散路线。"],
      ["清点人员、伤病、遗失物资和被毁房屋，立即安排救济。", ["VillageMedic", "CooperativeOrganizer", "DisplacedFamily"], "受害事实被胜负提示覆盖。"],
    ],
    failureCarryForward: "失散、伤病、拘押和房屋损毁逐项进入永久账本，并影响随后四个月的恢复能力。",
    archiveNote: "扫荡规模与具体路线为情境合成；责任归于占领行动。",
  }),
  CreateHistoricalTurn({
    turn: 10,
    dateKey: "1942-06",
    date: "1942年6月",
    localPhaseId: "CounterSweepAndRecovery",
    title: "归村之后先清点",
    historicalFrame: "扫荡结束不等于村庄复原，失散、损毁与暴露需要逐项处置。",
    eventTitle: "少了一扇门的院子",
    eventSynopsis: "何家返回借住村，看见住处受损；合作社必须在修房、种田和照护之间排定劳力。",
    roleIds: ["DisplacedFamily", "CooperativeOrganizer", "VillageMedic"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["逐户核对返村、失散、伤病、拘押和房屋损毁。", ["DisplacedFamily", "CooperativeOrganizer", "VillageMedic"], "最困难家庭从恢复计划中消失。"],
      ["先准备临时住所、饮水、种子和医疗照护。", ["CooperativeOrganizer", "VillageMedic"], "劳力被全部投入象征性重建。"],
      ["允许不安全家庭继续异地居住，保护其口粮份额。", ["DisplacedFamily", "CooperativeOrganizer"], "家庭被强迫返村，并被据此评判立场。"],
      ["按紧急程度分派互助劳力，不用武器库存建设民生设施。", ["CooperativeOrganizer"], "修复消耗错误资源并挤压照护。"],
      ["记录未完成修缮、长期惊惧和身体伤病，下月继续。", ["VillageMedic", "CooperativeOrganizer"], "严重损失被一次处置草率抹去。"],
    ],
    failureCarryForward: "未修房屋、未归家庭和未愈伤病持续降低生产、信任与交通承载。",
    archiveNote: "返村不等于一次结算便全部恢复，而是一项长期责任。",
  }),
  CreateHistoricalTurn({
    turn: 11,
    dateKey: "1942-07",
    date: "1942年7月",
    localPhaseId: "CounterSweepAndRecovery",
    title: "雨季断路",
    historicalFrame: "泥泞和山洪降低交通可靠性，也加重病患与寄居家庭的风险。",
    eventTitle: "被冲走的便桥",
    eventSynopsis: "林秋生发现便桥中断，乔兰等待的一批清洁用品无法按原路送达。",
    roleIds: ["TrafficWorker", "VillageMedic", "RailwayWorker", "DisplacedFamily"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["查看水位、替代山路、病户需求和铁路巡查变化。", ["TrafficWorker", "VillageMedic", "RailwayWorker"], "运输被误写成没有人员与道路风险的轻易行动。"],
      ["拆小物资、准备绳索和两处暂存点，取消非必要行程。", ["TrafficWorker", "VillageMedic"], "人员与物资集中在危险河段。"],
      ["先保证病户饮水和寄居家庭住处，不强迫涉水。", ["VillageMedic", "DisplacedFamily"], "自然风险由弱势家庭承担。"],
      ["交通员试通短段，铁路工人只报告可观察的巡查空隙。", ["TrafficWorker", "RailwayWorker"], "不确定信息被当成安全保证。"],
      ["修临时便桥、复查污染水源并登记延误需求。", ["CooperativeOrganizer", "VillageMedic"], "交通恢复但健康后果继续扩大。"],
    ],
    failureCarryForward: "延误物资和污染饮水进入八月恢复清单；失修路线降低后续运输承载能力。",
    archiveNote: "天气是地方条件，不为任何一方提供无条件免疫。",
  }),
  CreateHistoricalTurn({
    turn: 12,
    dateKey: "1942-08",
    date: "1942年8月",
    localPhaseId: "CounterSweepAndRecovery",
    title: "修具而不是凭空增产",
    historicalFrame: "生产恢复依赖工具、劳力、时间和安全交通，不能凭空增加粮食。",
    eventTitle: "合作社里三把坏锄",
    eventSynopsis: "孙禾需要修复农具，郭平川能找到废旧零件，但取用过程必须保护工友。",
    roleIds: ["CooperativeOrganizer", "RailwayWorker", "DisplacedFamily"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["清点损坏农具、可用零件、劳力和暴露风险。", ["CooperativeOrganizer", "RailwayWorker"], "生产计划脱离真实能力。"],
      ["安排分批修具和替代工具，保留家庭基本劳动时间。", ["CooperativeOrganizer", "DisplacedFamily"], "互助变成无偿透支受灾家庭。"],
      ["隐藏零件来源并允许受伤、寄居家庭减少劳动。", ["RailwayWorker", "VillageMedic", "DisplacedFamily"], "工友与困难家庭被迫承担风险。"],
      ["先修关键农具，再恢复田间和小型修理点。", ["CooperativeOrganizer", "RailwayWorker"], "追求一次性产出导致更高暴露。"],
      ["记录工时、损耗和欠下的互助义务，准备秋收。", ["CooperativeOrganizer"], "劳力债务和工具损耗被忽略。"],
    ],
    failureCarryForward: "未修工具和透支劳力直接降低秋收准备；军械与抽象组织数字不能替代实际工具和劳力。",
    archiveNote: "生产自救体现持续的能力建设，不写成无需劳力与时间的突然增产。",
  }),
  CreateHistoricalTurn({
    turn: 13,
    dateKey: "1942-09",
    date: "1942年9月",
    localPhaseId: "HarvestProtectionAndWinterPressure",
    title: "再保一季秋收",
    historicalFrame: "一年后的秋收同时检验民生恢复、交通纪律和组织韧性。",
    eventTitle: "三处小粮窖",
    eventSynopsis: "孙禾建议分仓，何家担心寄居户仍会在分配时被遗漏。",
    roleIds: ["CooperativeOrganizer", "DisplacedFamily", "TrafficWorker"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["核对产量预估、受灾户、征粮迹象和粮窖安全。", ["CooperativeOrganizer", "TrafficWorker", "DisplacedFamily"], "去年的漏登与今年的风险同时重演。"],
      ["分仓、错峰收割并为每处粮窖安排独立知情范围。", ["CooperativeOrganizer", "TrafficWorker"], "一个口供或一次搜索暴露全部存粮。"],
      ["保障寄居户和失去劳力家庭的基本份额。", ["CooperativeOrganizer", "DisplacedFamily"], "最弱家庭被迫以危险劳动换口粮。"],
      ["只对确认的运输节点实施有限牵制，完成后撤离。", ["TrafficWorker", "RailwayWorker"], "把破袭贡献当成唯一目标，会挤占秋收保护所需的人力与物资。"],
      ["公开复核分粮、补种和冬粮缺口，保留救济储备。", ["CooperativeOrganizer", "DisplacedFamily"], "表面丰收掩盖持续困难。"],
    ],
    failureCarryForward: "秋粮缺口进入冬季，寄居户信任和劳力恢复受到长期影响。",
    archiveNote: "胜利条件是保存群众与组织，不是占领县城。",
  }),
  CreateHistoricalTurn({
    turn: 14,
    dateKey: "1942-10",
    date: "1942年10月",
    localPhaseId: "HarvestProtectionAndWinterPressure",
    title: "核验一条危险线索",
    historicalFrame: "交通网再次遭搜索，反谍必须避免以身份猜测代替证据。",
    eventTitle: "失踪的挑夫",
    eventSynopsis: "一名挑夫没有按时抵达，可能被盘查、迷路或改变路线，任何结论都需要旁证。",
    roleIds: ["TrafficWorker", "RailwayWorker", "DisplacedFamily"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["分别核对出发、沿途目击、岗哨和亲属消息。", ["TrafficWorker", "RailwayWorker", "DisplacedFamily"], "失踪立刻被解释为背叛。"],
      ["隔离受影响区段、废止局部口令并保留救援窗口。", ["TrafficWorker"], "整网继续暴露或被无依据摧毁。"],
      ["保护其亲属和同路人，不公开审判或连坐。", ["DisplacedFamily", "CooperativeOrganizer"], "无辜家庭遭惩罚并失去信任。"],
      ["用第二条路线查找，只对已证实泄露调整网络。", ["TrafficWorker", "RailwayWorker"], "误判造成不可逆组织损失。"],
      ["公布可公开的核验结果，救济受盘查者并修复被隔离区段。", ["TrafficWorker", "CooperativeOrganizer"], "猜疑长期割裂交通网。"],
    ],
    failureCarryForward: "误判降低信任和网络容量；真实泄露若未隔离则提高冬季搜索置信度。",
    archiveNote: "反谍必须依靠多方核验，不能因偶然接触便自动判明真相。",
  }),
  CreateHistoricalTurn({
    turn: 15,
    dateKey: "1942-11",
    date: "1942年11月",
    localPhaseId: "HarvestProtectionAndWinterPressure",
    title: "把机构拆成几只箱子",
    historicalFrame: "冬季搜索压力下，诊疗、合作社和交通站需要分散转移并保持基本服务。",
    eventTitle: "夜校屋里的临时诊疗点",
    eventSynopsis: "乔兰的诊疗点可能暴露，药品、记录和行动不便者必须由不同小组转移。",
    roleIds: ["VillageMedic", "TrafficWorker", "CooperativeOrganizer", "DisplacedFamily"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942"],
    chain: [
      ["确认搜索迹象、病患等级、药品和备用房屋。", ["VillageMedic", "TrafficWorker"], "机构转移被简化为等候期限，不再核对人员与物资。"],
      ["拆分药箱、匿名病历、照护名单和取暖物资。", ["VillageMedic", "CooperativeOrganizer"], "一次搜查摧毁全部服务能力。"],
      ["先转移重病者并征得寄居家庭同意，不强占民房。", ["VillageMedic", "DisplacedFamily"], "保护机构反而伤害接纳家庭。"],
      ["多组分路转移，交通员只掌握相邻接点。", ["TrafficWorker", "VillageMedic"], "捕获一组即可暴露全网。"],
      ["在新地点恢复最低诊疗，补偿接纳家庭并登记遗失物资。", ["VillageMedic", "CooperativeOrganizer", "DisplacedFamily"], "转移成功但公共服务长期中断。"],
    ],
    failureCarryForward: "未恢复的诊疗和合作服务降低终局民生门槛；遗失药品不会自动补满。",
    archiveNote: "机构建设与转移是持续能力，不是永久免疫建筑。",
  }),
  CreateHistoricalTurn({
    turn: 16,
    dateKey: "1942-12",
    date: "1942年12月",
    localPhaseId: "HarvestProtectionAndWinterPressure",
    title: "一册未完的账",
    historicalFrame: "本局只结算合成县域是否保存继续抗战的条件，历史不会在此提前结束。",
    eventTitle: "年末责任清册",
    eventSynopsis: "五组普通人共同核对幸存、失散、伤病、流离、生产和交通，任何军事贡献都不能抹去代价。",
    roleIds: ["TrafficWorker", "VillageMedic", "CooperativeOrganizer", "RailwayWorker", "DisplacedFamily"],
    fixedAnchorIds: ["BaseAreaHardship1941To1942", "CairoDeclarationDecember1943", "PotsdamDeclarationJuly1945", "NationalVictoryAndSurrender1945"],
    chain: [
      ["汇总人口去向、伤病、住房、粮药、组织和敌情证据。", ["TrafficWorker", "VillageMedic", "CooperativeOrganizer", "RailwayWorker", "DisplacedFamily"], "结局只剩一个抽象总分。"],
      ["为未完成救济、机构恢复和失联核验安排下一阶段责任人。", ["VillageMedic", "CooperativeOrganizer", "TrafficWorker"], "回合终点错误地等同于问题终点。"],
      ["确认每个家庭的去向与选择，记录尚未归还的住所和物资。", ["DisplacedFamily", "CooperativeOrganizer"], "受害者从胜利叙事中消失。"],
      ["评估是否保存了继续抗战的网络，不生成投降、占领全国或歼敌结局。", ["TrafficWorker", "RailwayWorker"], "地方成果被夸大为改写全国战争。"],
      ["展示永久后果账本和固定后续史实，把未完成责任带出结局。", ["VillageMedic", "CooperativeOrganizer", "DisplacedFamily"], "民生代价被战斗贡献抵消。"],
    ],
    failureCarryForward: "未完成责任留在结局账本；全国抗战仍按固定历史延续，并在1945年取得胜利。",
    archiveNote: "1943至1945年的锚点只作为不可操控的后续档案时间线。",
  }),
]);

export const historyMetadata = DeepFreeze({
  schemaVersion: 1,
  locale: "zh-CN",
  turnCount: 16,
  responsibilityStageOrder: responsibilityStageDefinitions.map((stage) => stage.id),
  eventClassification: "情境合成",
  fixedAnchorClassification: "固定史实锚点",
  realPeoplePolicy: "ArchiveOnly",
  victoryMetric: "根据地存续、群众保护、组织韧性与有限抗战贡献",
});

export function GetHistoricalTurnNarrative(turn) {
  if (!Number.isInteger(turn)) {
    return null;
  }
  return historicalTurnNarratives.find((definition) => definition.turn === turn) ?? null;
}

export function GetHistorySource(sourceId) {
  return sourceReferences.find((source) => source.id === sourceId) ?? null;
}

export function GetFixedHistoricalAnchor(anchorId) {
  return fixedHistoricalAnchors.find((anchor) => anchor.id === anchorId) ?? null;
}
