// Interaction strings for the September first-level replacement.
export const TEXT = Object.freeze({
  "firstLevel.interaction.bundle": "领取集束手榴弹 · 按住 H 瞄准，松开投掷",
  "firstLevel.interaction.gate": "打开院门，让担架通过",
  "firstLevel.interaction.carry": "接过老周担架后端",
  "firstLevel.interaction.place": "将老周放在卫生兵旁",
  "firstLevel.interaction.supply": "补充弹药、手榴弹和绷带",
  "firstLevel.hint.receiveFood": "接过幺娃递来的腊肉 · 可转头查看",
  "firstLevel.hint.trainProne": "卧倒，躲到车帮下",
  "firstLevel.hint.standAndUnload": "起身，跟罗班长下车",
  "firstLevel.hint.leaveTrain": "从打开的车门跟队下车",
  "firstLevel.hint.melee": "V 拔刀 · F 拨推 · 左键挥刀",
  "firstLevel.guide.distance": "{label} · {distance} 米",
  "firstLevel.guide.unload": "下车与集合",
  "firstLevel.guide.support": "沿交通壕进入阵地",
  "firstLevel.guide.gun": "接管机枪",
  "firstLevel.guide.bundle": "集束手榴弹",
  "firstLevel.guide.throw": "侧沟投掷位置",
  "firstLevel.guide.south": "南行道路",
  "firstLevel.guide.village": "灶屋入口",
  "firstLevel.guide.gate": "院门通道",
  "firstLevel.guide.gateThreat": "院门外追兵：探出缺口压住侧翼",
  "firstLevel.guide.transfer": "转运区东侧防线",
  "firstLevel.guide.carry": "老周担架后端",
  "firstLevel.guide.ditch": "西侧下沟口",
  "firstLevel.guide.retreat": "下一处断后位置",
  "firstLevel.guide.reception": "接收院入口",
  "firstLevel.guide.place": "卫生兵接收位置",
  "firstLevel.guide.exit": "城边联络巷",
  "firstLevel.guide.rearCover": "后门外侧：压住西侧追兵",
  "firstLevel.hint.rearQueue": "还有 {remaining} 副担架等待撤出",
  "firstLevel.hint.guards": "守军已撤回 {safe} 人 · 仍在前沿 {remaining} 人 · 压住敌军火力，让他们撤回",
  "firstLevel.hint.gunSupply": "机枪弹药不足：F 离位，身后弹药箱可补充弹匣",
  "firstLevel.hint.bundle": "按住 H 调整投掷，松开 H 出手；炸履带，炮塔仍能开火",
  "firstLevel.hint.bundleEmpty": "集束弹已用完：回侧沟弹药箱补充后继续投掷",
  "firstLevel.hint.queue": "担架已通过 {passed}/{total} · 已装车 {loaded} 副",
});
export const DYNAMIC_PREFIXES = ["firstLevel.interaction.", "firstLevel.guide."];
export const GATED_MODULES = ["Script_FirstLevelMissionRuntime.mjs", "Script_FirstLevelMissionVoice.mjs"];
