import { MISSION_TRAIN } from "./Data_FirstLevelMissionTrain.mjs";
import { CHAPTER } from "./Data_MissionCh1.mjs";
import { MISSION_LAYOUT, MISSION_ANCHORS as A, MISSION_ROUTES } from "./Data_FirstLevelMissionLayout.mjs";
export const MISSION_VERSION = "first-level-20260907-r4";
import { MISSION_TUNING } from "./Data_Tuning_FirstLevel.mjs";
export { MISSION_TUNING } from "./Data_Tuning_FirstLevel.mjs";
const Stage = (id, objective, target, requirements, cue, extra = {}) =>
  Object.freeze({ id, objective, target, requirements, cue, ...extra });
export const MISSION_STAGES = Object.freeze([
  Stage("Train", "整理装备，随军列抵达卸载点。", A.train, ["trainShelling"], "TrainMeal"),
  Stage(
    "Unloading",
    "炮击！留在车内躲避，停稳后跟罗班长下车。",
    A.unload,
    ["trainStopped", "unloaded"],
    "TrainShelling",
  ),
  Stage(
    "Support",
    "沿交通壕支援前沿守军，掩护他们撤回。",
    A.front,
    ["frontReached", "frontContact"],
    "SupportOrder",
  ),
  Stage(
    "MachineGun",
    "接手机枪，压住火力点，掩护前方守军撤回。",
    A.gun,
    ["gunUsed", "guardsSafe"],
    "TakeMachineGun",
  ),
  Stage(
    "Tank",
    "领取集束手榴弹，沿侧沟炸停战车。",
    A.bundle,
    ["bundleTaken", "tankImmobilized"],
    "GuardsSafe",
  ),
  Stage(
    "Orders",
    "随罗班长接收后送命令，带老周离开阵地。",
    A.front,
    ["volunteerHeard", "zhouOnLitter"],
    "Volunteer",
  ),
  Stage(
    "South",
    "向南开路，跟随后送纵队前往转运点。",
    A.village,
    ["southTraversed", "southHopeHeard"],
    "SouthSecret",
    { minimumSeconds: MISSION_TUNING.quietSouthSeconds },
  ),
  Stage("Village", "从右侧灶屋绕进内院，夺取伤员通道。", A.melee, ["innerCourtReached"], "VillageAmbush"),
  Stage("Melee", "近距离接敌：V 切大刀，F 拨推枪身，左键挥刀。", A.melee, ["meleeResolved"], null),
  Stage(
    "Courtyard",
    "清理窗口机枪，打开院门，掩护担架分批通过。",
    A.gate,
    ["villageGunSilent", "courtyardGateOpen", "courtyardPassed"],
    "CourtyardOpen",
  ),
  Stage(
    "Transfer",
    "守住村东来路，等待伤员完成转运。",
    A.transfer,
    ["transferArrived", "vehiclesDeparted", "zhouNext", "followVehicleHeard"],
    "TransferDefense",
    { minimumSeconds: MISSION_TUNING.transferSeconds },
  ),
  Stage(
    "AirFirst",
    "日机来袭！利用掩体，压住村东追兵。",
    A.transfer,
    ["firstAirPassComplete", "firstAirOrdersHeard"],
    "AircraftFirst",
  ),
  Stage("Carry", "接替老周担架后端，抬往西侧下沟口。", A.queue, ["zhouCarried", "atDitchMouth", "carryOrdersHeard"], "CarryZhou"),
  Stage("Dive", "下沟！", A.ditch, ["diveComplete"], "AircraftReturn"),
  Stage(
    "Rescue",
    "拿枪断后，掩护幺娃把老周拖回担架。",
    A.ditch,
    ["zhouRecovered", "rescuePassageClear"],
    "RescueZhou",
  ),
  Stage(
    "RetreatFirst",
    "守住排水沟折角，让担架从身后通过。",
    A.retreatA,
    ["retreatFirstPassed"],
    "WestRetreat",
  ),
  Stage(
    "RetreatWall",
    "退到院墙缺口，补弹并继续掩护担架。",
    A.retreatB,
    ["retreatWallPassed"],
    "RetreatBleeding",
  ),
  Stage(
    "RetreatYard",
    "从后院门窗阻击，掩护最后一副担架撤离。",
    A.retreatC,
    ["retreatYardPassed"],
    "RetreatCold",
  ),
  Stage(
    "Reception",
    "守住接收院入口，让最后一批伤员进入。",
    A.reception,
    ["receptionPassed"],
    "ReceptionDefense",
  ),
  Stage("FinalCarry", "接过老周担架，抬入接收院，放到卫生兵旁。", A.zhouPickup, ["zhouPlaced"], "FinalCarry"),
  Stage("Death", "老周……", A.zhouDrop, ["deathSceneComplete"], "ZhouDeath"),
  Stage(
    "FinalDefense",
    "掩护医护和伤员撤离接收院。",
    A.finalCover,
    ["rearLaneClear", "medicsEscaped"],
    "ReceptionWithdrawal",
  ),
  Stage("Exit", "从后门撤入城边联络巷，跟上罗班长。", A.end, ["playerAtHandoff", "finalExitHeard"], "FinalExit"),
  Stage("Complete", "第一关完成 · 往南的路", A.end, [], null),
]);
export const MISSION_ENCOUNTERS = Object.freeze({
  front: [
    { id: "FrontGunner", x: 25, z: -161, weapon: "Type11", hold: true },
    { id: "FrontRifleA", x: -18, z: -159 },
    { id: "FrontRifleB", x: -9, z: -164 },
    { id: "FrontRifleC", x: 14, z: -154 },
    { id: "FrontRifleD", x: 30, z: -151 },
    { id: "FrontRifleE", x: -29, z: -171 },
    { id: "FrontRifleF", x: -22, z: -178 },
    { id: "FrontRifleG", x: -10, z: -180 },
    { id: "FrontRifleH", x: 2, z: -177 },
    { id: "FrontRifleI", x: 9, z: -170 },
    { id: "FrontRifleJ", x: 20, z: -179 },
    { id: "FrontSupportGunner", x: 33, z: -181, weapon:"Type11", hold:true },
  ],
  tank: [
    { id: "TankEscortA", x: 24, z: -145 },
    { id: "TankEscortB", x: 28, z: -152 },
    { id: "FlankA", x: 58, z: -139 },
    { id: "FlankB", x: 63, z: -144 },
  ],
  village: [
    { id: "VillageGunner", x: 43, z: 8, weapon: "Type11", hold: true },
    { id: "VillageCorner", x: 35, z: -12 },
    { id: "KitchenGuard", x: 58, z: -7 },
    { id: "RearWindow", x: 66, z: 16 },
    { id: "SideYard", x: 40, z: 27 },
  ],
  melee: [{ id: "MeleeTutor", x: 61, z: 4, weapon: "Type38", bayonet: true }],
  courtyard: [
    { id: "CourtyardPursuerA", x: 91, z: 24 },
    { id: "CourtyardPursuerB", x: 97, z: 21 },
    { id: "CourtyardPursuerC", x: 98, z: 29 },
  ],
  transfer: [
    { id: "TransferGunner", x: 113, z: 80, weapon: "Type11", hold: true },
    { id: "TransferRifleA", x: 111, z: 90 },
    { id: "TransferRifleB", x: 117, z: 97 },
    { id: "TransferRifleC", x: 119, z: 85 },
  ],
  air: [
    { id: "AirPursuerA", x: 113, z: 89 },
    { id: "AirPursuerB", x: 108, z: 94 },
    { id: "AirPursuerC", x: 115, z: 100 },
    { id: "AirPursuerD", x: 106, z: 107 },
  ],
  retreat: [
    { id: "RetreatPursuerA", x: 64, z: 114 },
    { id: "RetreatPursuerB", x: 61, z: 108 },
    { id: "RetreatPursuerC", x: 70, z: 113 },
    { id: "RetreatPursuerD", x: 74, z: 109 },
  ],
  reception: [
    { id: "ReceptionGunner", x: -111, z: 32, weapon: "Type11", hold: true },
    { id: "ReceptionRifleA", x: -111, z: 43 },
    { id: "ReceptionRifleB", x: -117, z: 47 },
  ],
  final: [
    { id: "FinalFlankerA", x: -139, z: 67 },
    { id: "FinalFlankerB", x: -155, z: 69 },
    { id: "FinalStreetGunner", x: -112, z: 34, weapon: "Type11", hold: true },
  ],
});
export const FIRST_LEVEL_MISSION_PHASE = Object.freeze({
  id: "FirstLevelP012Whitebox",
  contentId: CHAPTER.id,
  sandbox: true,
  sandboxKey: "firstLevelP012Whitebox",
  chapter: true,
  artId: CHAPTER.id,
  date: "一九三八年三月",
  label: "第一关 · 往南的路",
  place: "滕县外围",
  sky: "testSceneDay",
  ambience: "smokyDay",
  music: null,
  minutes: 32,
  brief: [
    "军列遭到炮击。支援前沿守军，然后为伤员打开往南的路。",
    "WASD 移动 · Shift 冲刺 · C 蹲伏 · Z 卧倒 · F 交互 · V 大刀 · G 手榴弹 · H 集束手榴弹",
  ],
  metaText: ["第一关完整流程白盒", "Notion 2026.09.07", "人物动作简化"],
  level: CHAPTER,
  roster: ["luo", "yaowa", "heyoutian", "liuwencai"],
  playerCast: "shunzi",
  mechanics: { pinFinalZone: true },
  objectives: MISSION_STAGES.map((stage) => stage.objective),
  mechanic: "掩护伤员，完成当前任务。",
  hud: { objectiveMarkers: false, targetDistance: false },
  nraPool: 60,
  poolGain: 0,
  ijaPool: 60,
  ijaPressure: 0,
  ijaSpawn: CHAPTER.tuning.ijaSpawn,
  ijaSupport: [],
  ijaForce: CHAPTER.tuning.ijaForce,
  loadoutOverride: {
    primary: "HanYang",
    secondary: null,
    melee: "Dadao",
    throwables: { Grenade: 3, GrenadeBundle: 0 },
    spareClips: 12,
  },
  bounds: MISSION_LAYOUT.bounds,
  cameraFar: 650,
  zones: MISSION_STAGES.map((stage, index) => ({
    id: stage.id,
    name: stage.objective,
    ...stage.target,
    radius: 8,
    index,
  })),
  spawn: { ...A.train, ry: 0 },
  whitebox: {
    p012: true,
    fullMission: true,
    triggerAimBeforeRecoil: true,
    layout: MISSION_LAYOUT,
    anchors: A,
    routes: MISSION_ROUTES,
    friendlyLimit: 4,
    actualEventsOnly: true,
    storyBeats: [],
    activities: { arrivalGuideStart: { x: -76, z: 71 }, trainColumn: { extraCount: MISSION_TRAIN.extraCount } },
  },
});
