// Generated by _import/Script_LocomotionProfileBake.mjs from shipped GLBs at 120 Hz.
export const ACTOR_LOCOMOTION_PROFILES = {
  "LugouIja01": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.879451,
      "contacts": {
        "L": [
          [
            0.220339,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.084746,
            0.231638
          ],
          [
            0.581921,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouIja01.glb",
      "sha256": "23fa4ef88891bd14d49dfb9a3e61b9f0dcaf45b8956a720aab24d9c4c23eb9c7"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "LugouIja02": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.879451,
      "contacts": {
        "L": [
          [
            0.220339,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.084746,
            0.231638
          ],
          [
            0.581921,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouIja02.glb",
      "sha256": "8c4860ec2d4dd3076b06ff7e593e5dcfd4d23aefe2fedf6f9fdec3b0e12cc9aa"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "LugouIja03": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.879451,
      "contacts": {
        "L": [
          [
            0.220339,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.084746,
            0.231638
          ],
          [
            0.581921,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouIja03.glb",
      "sha256": "6d97c801f7ea62430e5397fde980ad0964ab5081fa5f15249434bce4cbf3f89d"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "LugouIja04": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.879451,
      "contacts": {
        "L": [
          [
            0.220339,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.084746,
            0.231638
          ],
          [
            0.581921,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouIja04.glb",
      "sha256": "42297be34dc548b2e49ddecb833ef3e860834db51f23f193182fa2d727b311ac"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "LugouIja05": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.879451,
      "contacts": {
        "L": [
          [
            0.220339,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.084746,
            0.231638
          ],
          [
            0.581921,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouIja05.glb",
      "sha256": "671f37cc3eca26409a4200750f2cf9f5b5afdf76b94ba73d0c08fa9c08de383a"
    }
  },
  "LugouNra01": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.913821,
      "contacts": {
        "L": [
          [
            0.231638,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.231638
          ],
          [
            0.514124,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouNra01.glb",
      "sha256": "d9c6c14884444ab18b61aa41ce4df32df81f1a2207295a26bc2c3683bcf4e170"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.599706,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_LugouNraBackRifleRun.glb",
      "sha256": "e0896129040976c2e37ad71c2d4f13ca4a4319214db64687be5d4a6dea229649"
    }
  },
  "LugouNra02": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.913821,
      "contacts": {
        "L": [
          [
            0.231638,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.231638
          ],
          [
            0.514124,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouNra02.glb",
      "sha256": "39c08ca82148e140ee2952caffdd0dee99750fb734038a5263d216c9a7345225"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.599706,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_LugouNraBackRifleRun.glb",
      "sha256": "e0896129040976c2e37ad71c2d4f13ca4a4319214db64687be5d4a6dea229649"
    }
  },
  "LugouNra03": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.913821,
      "contacts": {
        "L": [
          [
            0.231638,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.231638
          ],
          [
            0.514124,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouNra03.glb",
      "sha256": "d4b7b487387cca2e7758d1c0bbcd51a299ee7a500a193ea14d9754e6563aa74d"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.599706,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_LugouNraBackRifleRun.glb",
      "sha256": "e0896129040976c2e37ad71c2d4f13ca4a4319214db64687be5d4a6dea229649"
    }
  },
  "LugouNra04": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.913821,
      "contacts": {
        "L": [
          [
            0.231638,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.231638
          ],
          [
            0.514124,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouNra04.glb",
      "sha256": "06bfff4d100d766767f8516584de0c9ac62b2f50a6ac10ce3b4285f24889a073"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.599706,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_LugouNraBackRifleRun.glb",
      "sha256": "e0896129040976c2e37ad71c2d4f13ca4a4319214db64687be5d4a6dea229649"
    }
  },
  "LugouNra05": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 1.913821,
      "contacts": {
        "L": [
          [
            0.231638,
            0.497175
          ],
          [
            0.745763,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.231638
          ],
          [
            0.514124,
            0.728814
          ]
        ]
      },
      "source": "Model/Character/Model_LugouNra05.glb",
      "sha256": "acbc9184da059bdf6c3c18d051f3eba77d1dd3acba469e8dbc876b092f174250"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.599706,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_LugouNraBackRifleRun.glb",
      "sha256": "e0896129040976c2e37ad71c2d4f13ca4a4319214db64687be5d4a6dea229649"
    }
  }
};
