// Generated by _import/Script_LocomotionProfileBake.mjs from shipped GLBs at 120 Hz.
export const ACTOR_LOCOMOTION_PROFILES = {
  "TengxianIja01": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.04209,
      "contacts": {
        "L": [
          [
            0.254237,
            0.480226
          ],
          [
            0.819209,
            0.971751
          ]
        ],
        "R": [
          [
            0.022599,
            0.20339
          ],
          [
            0.553672,
            0.711864
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianIja01.glb",
      "sha256": "0acb11411d2984cf7bd9dd578141ffcc8541e9bbe8c83b0cf3dcff76f3a2d9b1"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "TengxianIja02": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.04209,
      "contacts": {
        "L": [
          [
            0.254237,
            0.480226
          ],
          [
            0.819209,
            0.971751
          ]
        ],
        "R": [
          [
            0.022599,
            0.20339
          ],
          [
            0.548023,
            0.711864
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianIja02.glb",
      "sha256": "ab73c68de776e30c22d074fa816ac85fed3d767cf227f759188528f3bd0a0d61"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "TengxianIja03": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.04209,
      "contacts": {
        "L": [
          [
            0.254237,
            0.480226
          ],
          [
            0.819209,
            0.971751
          ]
        ],
        "R": [
          [
            0.022599,
            0.20339
          ],
          [
            0.548023,
            0.711864
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianIja03.glb",
      "sha256": "652df6a3e31f26257754d6e7fe5bc1e5f56af6372bc0d4df2db0e753b5d8a952"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "TengxianIja06": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.04209,
      "contacts": {
        "L": [
          [
            0.254237,
            0.480226
          ],
          [
            0.819209,
            0.971751
          ]
        ],
        "R": [
          [
            0.022599,
            0.20339
          ],
          [
            0.548023,
            0.711864
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianIja06.glb",
      "sha256": "433015bec29e79fa7508b86f51f4d31bb1e669b3cc0d668745f5e202945d613e"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "TengxianNra02": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.038773,
      "contacts": {
        "L": [
          [
            0.248588,
            0.491525
          ],
          [
            0.80226,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.214689
          ],
          [
            0.542373,
            0.717514
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianNra02.glb",
      "sha256": "d6b7b88112afd64e0f41a7bbcf8746a24b5919288ef76c36f345bc367ab666de"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.59972,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_TengxianNraBackRifleRun.glb",
      "sha256": "9a81b95623f6228d3162fc1fe72bbac162c5a0ed05ed72bc4eb5c7c5a782efd8"
    }
  },
  "TengxianNra05": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.040157,
      "contacts": {
        "L": [
          [
            0.248588,
            0.491525
          ],
          [
            0.80226,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.214689
          ],
          [
            0.542373,
            0.711864
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianNra05.glb",
      "sha256": "0c1f2b1e822be08d0a477aaae4ca27cc34f3d66e71a1d22754dff043e5966e72"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.59972,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_TengxianNraBackRifleRun.glb",
      "sha256": "9a81b95623f6228d3162fc1fe72bbac162c5a0ed05ed72bc4eb5c7c5a782efd8"
    }
  },
  "TengxianNra06": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.038773,
      "contacts": {
        "L": [
          [
            0.248588,
            0.491525
          ],
          [
            0.80226,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.214689
          ],
          [
            0.542373,
            0.717514
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianNra06.glb",
      "sha256": "7d3dcde8195b3070178b31fc5184ef45808acc8306ee9bf806252d680b6ed961"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.59972,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_TengxianNraBackRifleRun.glb",
      "sha256": "9a81b95623f6228d3162fc1fe72bbac162c5a0ed05ed72bc4eb5c7c5a782efd8"
    }
  }
};
