import { OPENING } from "./Data_FirstLevelOpening.mjs";
import { FRONT_FIELD_MEN, FRONT_RESERVES, FRONT_APPROACH_ENEMIES } from "./Data_FirstLevelMissionFront.mjs";
import { MISSION_TRAIN } from "./Data_FirstLevelMissionTrain.mjs";
import { CHAPTER } from "./Data_MissionCh1.mjs";
import { MISSION_LAYOUT, MISSION_ANCHORS as A, MISSION_ROUTES } from "./Data_FirstLevelMissionLayout.mjs";
export const MISSION_VERSION = "first-level-20260910-opening-r2";
import { MISSION_TUNING } from "./Data_Tuning_FirstLevel.mjs";
export { MISSION_TUNING } from "./Data_Tuning_FirstLevel.mjs";
const Stage = (id, objective, target, requirements, cue, extra = {}) =>
  Object.freeze({ id, objective, target, requirements, cue, ...extra });
export const MISSION_STAGES = Object.freeze([
  Stage("Train", "随军列前行，和同伴待在车厢内。", A.train, ["trainShelling"], "TrainMeal"),
  Stage(
    "Unloading",
    "伏低，听罗班长指挥！脱离车厢后借掩体进入交通壕。",
    A.unload,
    ["trainStopped", "trainDerailed", "luoRescueComplete", "unloadOrdersHeard", "unloaded"],
    "TrainShelling",
  ),
  Stage("TrenchEntry", "侧沟有日军！清出折角，跟班长进掩蔽处。", OPENING.shelter, ["trenchEntered", "trenchCleared", "shelterReached"], null),
  Stage("Shelter", "守住折角，照看从前方撤下来的伤兵。", OPENING.shelter, ["escapeWhisperHeard", "woundedSeen", "supportOrdersHeard"], "EscapeWhisper"),
  Stage(
    "Support",
    "沿交通壕支援前沿守军，掩护他们撤回。",
    A.front,
    ["frontReached", "frontContact", "frontRifleDefense", "rifleWithdrawalResolved", "zhouGunWounded"],
    null,
  ),
  Stage(
    "MachineGun",
    "接手机枪，压住火力点，掩护前方守军撤回。",
    A.gun,
    ["gunUsed", "guardWithdrawalResolved"],
    "TakeMachineGun",
  ),
  Stage(
    "Tank",
    "领取集束手榴弹，沿侧沟炸停战车。",
    A.bundle,
    ["bundleTaken", "tankImmobilized"],
    "GuardsSafe",
  ),
  Stage(
    "Orders",
    "撤回交通壕，与罗班长接令，带老周离开阵地。",
    A.orders,
    ["ordersReached", "volunteerHeard", "zhouOnLitter"],
    "Volunteer",
  ),
  Stage(
    "South",
    "向南开路，跟随后送纵队前往转运点。",
    A.village,
    ["southTraversed", "southHopeHeard"],
    "SouthSecret",
    { minimumSeconds: MISSION_TUNING.quietSouthSeconds },
  ),
  Stage("Village", "从右侧灶屋绕进内院，夺取伤员通道。", A.melee, ["innerCourtReached"], "VillageAmbush"),
  Stage("Melee", "近距离接敌：V 切大刀，F 拨推枪身，左键挥刀。", A.melee, ["meleeResolved"], null),
  Stage(
    "Courtyard",
    "清理窗口机枪，打开院门，掩护担架分批通过。",
    A.gate,
    ["villageGunSilent", "courtyardGateOpen", "courtyardPassed"],
    "CourtyardOpen",
  ),
  Stage(
    "TransferApproach",
    "沿院后道路前往转运棚，掩护伤员交接。",
    A.transfer,
    ["transferApproachReached", "transferHopeHeard"],
    "TransferHope",
    { minimumSeconds: MISSION_TUNING.transferApproachSeconds },
  ),
  Stage(
    "Transfer",
    "压住东侧火力，盯住南侧绕行，掩护车辆分批出发。",
    A.transfer,
    ["transferArrived", "vehiclesDeparted", "transferAttacksResolved", "zhouNext", "followVehicleHeard"],
    "TransferDefense",
    { minimumSeconds: MISSION_TUNING.transferSeconds },
  ),
  Stage(
    "AirFirst",
    "日机来袭！利用掩体，压住村东追兵。",
    A.transfer,
    ["firstAirPassComplete", "firstAirOrdersHeard"],
    "AircraftFirst",
  ),
  Stage("Carry", "接替老周担架后端，抬往西侧下沟口。", A.queue, ["zhouCarried", "atDitchMouth", "carryOrdersHeard"], "CarryZhou"),
  Stage("Dive", "下沟！", A.ditch, ["diveComplete"], "AircraftReturn"),
  Stage(
    "Rescue",
    "拿枪断后，掩护幺娃把老周拖回担架。",
    A.ditch,
    ["zhouRecovered", "rescuePassageClear"],
    "RescueZhou",
  ),
  Stage(
    "RetreatFirst",
    "守住排水沟折角，让担架从身后通过。",
    A.retreatA,
    ["retreatFirstPassed"],
    "WestRetreat",
  ),
  Stage(
    "RetreatWall",
    "退到院墙缺口，压住北侧横射火力，为担架打开缺口。",
    A.retreatB,
    ["retreatWallPassed"],
    "RetreatBleeding",
  ),
  Stage(
    "RetreatYard",
    "随最后一副担架后撤，压住后院追兵，把伤员送到接收院。",
    A.retreatC,
    ["retreatYardPassed"],
    "RetreatCold",
  ),
  Stage(
    "Reception",
    "守住接收院入口，让最后一批伤员进入。",
    A.reception,
    ["receptionPassed"],
    "ReceptionDefense",
  ),
  Stage("FinalCarry", "接过老周担架，抬入接收院，放到卫生兵旁。", A.zhouPickup, ["zhouPlaced"], "FinalCarry"),
  Stage("Death", "老周……", A.zhouDrop, ["deathSceneComplete"], "ZhouDeath"),
  Stage(
    "FinalDefense",
    "打开后门外的撤退窗口，随医护退出接收院。",
    A.finalCover,
    ["rearLaneClear", "medicsEscaped"],
    "ReceptionWithdrawal",
  ),
  Stage("Exit", "从后门撤入城边联络巷，跟上罗班长。", A.end, ["playerAtHandoff", "finalExitHeard"], "FinalExit"),
  Stage("Complete", "第一关完成 · 往南的路", A.end, [], null),
]);
export const MISSION_ENCOUNTERS = Object.freeze({
  surface: OPENING.surface,
  intrusion: OPENING.intruders,
  approach: [],
  // The roster itself lives in Data_FirstLevelMissionFront: the assault lanes and the cover rows
  // are derived from it, and a list split across two files drifts.
  front: [...FRONT_FIELD_MEN,...FRONT_RESERVES],
  tank: [
    { id: "TankEscortA", x: 24, z: -145 },
    { id: "TankEscortB", x: 28, z: -152 },
    { id: "FlankA", x: 58, z: -139 },
    { id: "FlankB", x: 63, z: -144 },
  ],
  village: [
    { id: "VillageGunner", x: 43, z: 8, weapon: "Type11", hold: true },
    { id: "VillageCorner", x: 54, z: -12 },
    { id: "KitchenGuard", x: 58, z: -7 },
    { id: "RearWindow", x: 66, z: 16 },
    { id: "SideYard", x: 40, z: 27 },
  ],
  melee: [{ id: "MeleeTutor", x: 61, z: 4, weapon: "Type38", bayonet: true }],
  courtyard: [
    { id: "CourtyardPursuerA", x: 91, z: 24 },
    { id: "CourtyardPursuerB", x: 97, z: 21 },
    { id: "CourtyardPursuerC", x: 98, z: 29 },
  ],
  transfer: [
    { id: "TransferGunner", x: 113, z: 80, weapon: "Type11", hold: true },
    { id: "TransferRifleA", x: 111, z: 90 },
    { id: "TransferRifleB", x: 117, z: 97 },
    { id: "TransferRifleC", x: 119, z: 85 },
  ],
  transferFlank: [
    {id:"TransferFlankA",x:112,z:114},{id:"TransferFlankB",x:105,z:122},
    {id:"TransferFlankC",x:104,z:141},{id:"TransferFlankD",x:103,z:140},
  ],
  transferLast: [
    {id:"TransferLastGunner",x:113,z:80,weapon:"Type11",hold:true},
    {id:"TransferLastA",x:118,z:89},{id:"TransferLastB",x:120,z:98},
    {id:"TransferLastC",x:111,z:110},
  ],
  transferRear: [
    {id:"TransferRearA",x:91,z:65},{id:"TransferRearB",x:96,z:70},{id:"TransferRearC",x:88,z:66},
  ],
  air: [
    { id: "AirPursuerA", x: 113, z: 89 },
    { id: "AirPursuerB", x: 108, z: 94 },
    { id: "AirPursuerC", x: 115, z: 100 },
    { id: "AirPursuerD", x: 106, z: 107 },
  ],
  retreat: [
    { id: "RetreatPursuerA", x: 64, z: 114 },
    { id: "RetreatPursuerB", x: 61, z: 108 },
    { id: "RetreatPursuerC", x: 63, z: 116 },
    { id: "RetreatPursuerD", x: 74, z: 109 },
  ],
  retreatWall: [
    {id:"WallFlankerA",x:-29,z:65},{id:"WallFlankerB",x:-35,z:60},
    {id:"WallGunner",x:-27,z:57,weapon:"Type11",hold:true},
  ],
  retreatYard: [
    {id:"YardPursuerA",x:-80,z:51},{id:"YardPursuerB",x:-81,z:54},
    {id:"YardPursuerC",x:-82,z:51},
  ],
  reception: [
    { id: "ReceptionGunner", x: -111, z: 32, weapon: "Type11", hold: true },
    { id: "ReceptionRifleA", x: -111, z: 46 },
    { id: "ReceptionRifleB", x: -117, z: 47 },
  ],
  final: [
    { id: "FinalFlankerA", x: -139, z: 67 },
    { id: "FinalFlankerB", x: -155, z: 69 },
    { id: "FinalStreetGunner", x: -112, z: 34, weapon: "Type11", hold: true },
  ],
});
// Finite squads cross authored openings while the shared AI owns fire and damage.
export const MISSION_TRANSFER_BEATS=Object.freeze([
  {id:"transfer",earliestS:0,latestS:0,loaded:0,restS:0,hint:"transferEast"},
  {id:"transferFlank",earliestS:35,latestS:60,loaded:4,restS:12,hint:"transferFlank"},
  {id:"transferLast",earliestS:95,latestS:115,loaded:8,restS:12,hint:"transferLast"},
  {id:"transferRear",earliestS:155,latestS:190,loaded:9,restS:12,hint:"transferRear"},
]);
export const MISSION_PURSUIT_ROUTE=Object.freeze([
  {x:100,z:120.5},{x:74,z:120.5},{x:61,z:120.5},{x:60,z:114},...MISSION_ROUTES.evacuation,
]);
export const MISSION_GUIDANCE = Object.freeze({
  Unloading: {label:'unload'}, TrenchEntry:{label:'support',route:'opening'}, Shelter:{label:'support'}, Support:{label:'support',route:'support'},
  MachineGun:{label:'gun'},Tank:{label:'bundle'},Orders:{label:'orders'},
  South:{label:'south',route:'south'},Village:{label:'village',route:'village'},
  Courtyard:{label:'gate'},TransferApproach:{label:'transfer',route:'village'},Transfer:{label:'transfer'},AirFirst:{label:'transfer'},
  Carry:{label:'carry'},Rescue:{label:'ditch'},
  RetreatFirst:{label:'retreat'},RetreatWall:{label:'retreat'},RetreatYard:{label:'retreat'},
  Reception:{label:'reception'},FinalCarry:{label:'carry'},FinalDefense:{label:'rearCover'},Exit:{label:'exit',route:'exit'},
});
// Front riflemen no longer use point tactics: they bound between FRONT_ASSAULT lines (runtime UpdateAssault).
export const MISSION_TACTICS = Object.freeze({
  ...Object.fromEntries(Object.entries(OPENING.intruderRoutes).map(([id,points],i)=>[id,{delay:i*2,points}])),
  CourtyardPursuerA: { delay: 1, points: [{x:86,z:37},{x:62,z:40},{x:53,z:38}] },
  CourtyardPursuerB: { delay: 12, points: [{x:89,z:39},{x:66,z:43},{x:59,z:40}] },
  CourtyardPursuerC: { delay: 25, points: [{x:91,z:41},{x:70,z:44},{x:64,z:40}] },
  TransferRifleA: { delay: 5, points: [{x:108,z:90},{x:102,z:91}] },
  TransferRifleB: { delay: 9, points: [{x:112,z:106},{x:104,z:112}] },
  TransferRifleC: { delay: 13, points: [{x:114,z:90},{x:107,z:94}] },
  TransferFlankA: {delay:0,points:[{x:104,z:117},{x:100,z:117}]},
  TransferFlankB: {delay:3,points:[{x:103,z:124},{x:96,z:125}]},
  TransferFlankC: {delay:6,points:[{x:108,z:135},{x:96,z:137}]},
  TransferFlankD: {delay:9,points:[{x:102,z:136},{x:94,z:134}]},
  TransferLastA: {delay:0,points:[{x:110,z:90},{x:102,z:92}]},
  TransferLastB: {delay:4,points:[{x:109,z:108},{x:102,z:114}]},
  TransferLastC: {delay:8,points:[{x:104,z:115},{x:99,z:116}]},
  TransferRearA: {delay:0,points:[{x:91,z:77},{x:90,z:91}]},
  TransferRearB: {delay:3,points:[{x:96,z:81},{x:100,z:92}]},
  TransferRearC: {delay:6,points:[{x:84,z:80},{x:86,z:95}]},
  WallFlankerA: {delay:0,points:[{x:-37,z:66},{x:-41,z:79}]},
  WallFlankerB: {delay:4,points:[{x:-40,z:63},{x:-42,z:70}]},
  YardPursuerA: {delay:0,points:[{x:-80,z:51},{x:-81,z:43},{x:-94,z:43}]},
  YardPursuerB: {delay:4,points:[{x:-81,z:53},{x:-81,z:41},{x:-99,z:42},{x:-103,z:41.62}]},
  YardPursuerC: {delay:8,points:[{x:-81,z:51},{x:-81,z:41},{x:-99,z:42},{x:-110,z:40.95}]},
  AirPursuerA: { delay: 0, points: [{x:106,z:90},{x:102,z:92}] },
  AirPursuerB: { delay: 3, points: [{x:105,z:98},{x:104,z:111}] },
  AirPursuerC: { delay: 5, points: [{x:109,z:109},{x:100,z:114}] },
  AirPursuerD: { delay: 8, points: [{x:106,z:113},{x:99,z:115}] },
  ReceptionRifleA: { delay: 3, points: [{x:-116,z:46},{x:-121,z:46}] },
  ReceptionRifleB: { delay: 10, points: [{x:-121,z:47},{x:-131,z:47}] },
  FinalFlankerA: { delay: 2, points: [{x:-143,z:62},{x:-147,z:56}] },
  FinalFlankerB: { delay: 9, points: [{x:-165,z:65},{x:-170,z:48}] },
});
export const FIRST_LEVEL_MISSION_PHASE = Object.freeze({
  id: "FirstLevelP012Whitebox",
  contentId: CHAPTER.id,
  sandbox: true,
  sandboxKey: "firstLevelP012Whitebox",
  chapter: true,
  artId: CHAPTER.id,
  date: "一九三八年三月",
  label: "第一关 · 往南的路",
  place: "滕县外围",
  sky: "testSceneDay",
  ambience: "smokyDay",
  music: null,
  minutes: 32,
  brief: [
    "军列遭到炮击。支援前沿守军，然后为伤员打开往南的路。",
    "WASD 移动 · Shift 冲刺 · C 蹲伏 · Z 卧倒 · F 交互 · V 大刀 · G 手榴弹 · H 集束手榴弹",
  ],
  metaText: ["第一关完整流程白盒", "Notion 2026.09.07", "人物动作简化"],
  level: CHAPTER,
  roster: ["luo", "yaowa", "heyoutian", "liuwencai"],
  playerCast: "shunzi",
  mechanics: { pinFinalZone: true },
  objectives: MISSION_STAGES.map((stage) => stage.objective),
  mechanic: "掩护伤员，完成当前任务。",
  hud: { objectiveMarkers: false, targetDistance: false },
  nraPool: 60,
  poolGain: 0,
  ijaPool: 60,
  ijaPressure: 0,
  ijaSpawn: CHAPTER.tuning.ijaSpawn,
  ijaSupport: [],
  ijaForce: CHAPTER.tuning.ijaForce,
  loadoutOverride: {
    primary: "HanYang",
    secondary: null,
    melee: "Dadao",
    throwables: { Grenade: 3, GrenadeBundle: 0 },
    spareClips: 12,
  },
  bounds: MISSION_LAYOUT.bounds,
  cameraFar: 650,
  zones: MISSION_STAGES.map((stage, index) => ({
    id: stage.id,
    name: stage.objective,
    ...stage.target,
    radius: 8,
    index,
  })),
  spawn: { ...A.train, ry: 0 },
  whitebox: {
    p012: true,
    fullMission: true,
    triggerAimBeforeRecoil: true,
    layout: MISSION_LAYOUT,
    anchors: A,
    routes: MISSION_ROUTES,
    friendlyLimit: 4,
    actorCapacity:112,
    crowdCellM:MISSION_TUNING.frontCrowdCellM,
    // Real first-battle actors plus dormant village and NRA; casualties release capacity.
    actorPool: { ija: 48, nra: 40 },
    actualEventsOnly: true,
    storyBeats: [],
    activities: { arrivalGuideStart: { x: -76, z: 71 }, trainColumn: { extraCount: MISSION_TRAIN.extraCount } },
  },
});
