// First-level whitebox pacing and handling. Notion 2026-09-07: calm walk 1–2 min, transfer 2–4 min, dive 2 s, death 8–12 s.
export const MISSION_TUNING = Object.freeze({
  trainTravelM: 34,
  trainShellAtS: 28,
  trainBrakeSeconds: 27,
  trainApproachDecayS: 80,
  unloadStaggerSeconds: 0.8,
  quietSouthSeconds: 75,
  transferSeconds: 150,
  vehicleLoadSeconds: 16,
  litterCount: 20,
  walkingWoundedCount: 36,
  medicCount: 14,
  civilianCount: 8,
  litterSpeedMps: 1.4,
  walkSpeedMps: 1.7,
  squadSpeedMps: 3.05,
  diveSeconds: 2,
  deathSeconds: 12,
  frontEngageDistanceM:110,
  tankRevealDistanceM:85,
  tankSpeedMps: 0.6,
  tankStopZ: -123,
  tankShellIntervalS: 13,
  tankMachineGunIntervalS: 2.4,
  tankTrackRadiusM: 5,
  tankTrackMinDamage: 35,
  threatSuppression: 0.5,
  passageRangeM: 36,
  interactionRangeM: 2.5,
  litterSpacingM: 3.4,
  queueSpacingM: 3.4,
  cartCapacity: 4,
  zhouQueueIndex: 11,
  cartSpeedMps: 3.2,
  loadingReachM: 0.2,
  boardingWitnessM: 2,
  rescueSeconds: 4,
  rescueReachM: 3,
  guardCount: 8,
  guardSpeedMps: 2.7,
  finalEvacSpeedMps: 1.5,
  meleeWindowS: 2.7,
  meleeStrength: 0.6,
  meleeApproachMps: 2.3,
  meleeTriggerRadiusM: 2.7,
  meleeBindRadiusM: 1.7,
  squadSpacingM: 1.8,
  squadRouteCornerM: 2.4,
  squadRouteSampleM: 2,
  squadRouteCornerFraction: .3,
  squadRouteCornerSamples: 4,
  squadRouteExitBlendM: 3,
  squadLaneClearanceM: .85,
  squadRouteLanesM: [-0.62, 0.6, -0.3, 0.32],
  squadStrideScales: [1, 0.94, 1.06, 0.97],
  squadTurnSpeedFloor: 0.62,
  squadSpeedBlendS: 0.35,
  squadGapEaseM: 1.2,
  squadCatchupDistanceM: 18,
  squadWaitDistanceM:26,
  squadCatchupMps: 4.5,
  flankSpeedMps: 2.8,
  southVehiclesAtS: 18,
  southHopeAtS: 43,
  followVehicleLeadS: 12,
  interactionSeconds: 0.55,
  supplyCooldownS: 15,
  limitedLookRadians: 0.28,
  diveTravelM: 3.8,
  medicApproachMps: 2.5,
  rescuerApproachMps: 2.6,
  pursuerSpeedMps: 1.65,
  airPassSeconds: 8,
  secondAirLeadS: 4.58,
  bridgeBombAtS: 3,
  cartBombAtS: 3.3,
  zhouStrafeAtS: 2.6,
});
