// Generated by _import/Script_LocomotionProfileBake.mjs from shipped GLBs at 120 Hz.
export const ACTOR_LOCOMOTION_PROFILES = {
  "TengxianIja01": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.04209,
      "contacts": {
        "L": [
          [
            0.254237,
            0.480226
          ],
          [
            0.819209,
            0.971751
          ]
        ],
        "R": [
          [
            0.022599,
            0.20339
          ],
          [
            0.553672,
            0.711864
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianIja01.glb",
      "sha256": "fc6c84ad51c9752066127b148a1f9db307da9659dea441989861265693b02c6b"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "TengxianIja02": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.04209,
      "contacts": {
        "L": [
          [
            0.254237,
            0.480226
          ],
          [
            0.819209,
            0.971751
          ]
        ],
        "R": [
          [
            0.022599,
            0.20339
          ],
          [
            0.548023,
            0.711864
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianIja02.glb",
      "sha256": "fc429bafc6973e54e8d1fa72ac99c8740c81be25f895ddb1417bb47707578788"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "TengxianIja03": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.04209,
      "contacts": {
        "L": [
          [
            0.254237,
            0.480226
          ],
          [
            0.819209,
            0.971751
          ]
        ],
        "R": [
          [
            0.022599,
            0.20339
          ],
          [
            0.548023,
            0.711864
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianIja03.glb",
      "sha256": "17163f830cdf91b2b8bbe9b6e197855bf739a48116464b19eb24738d921b4f74"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.23864468053263868
    }
  },
  "TengxianNra02": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.038773,
      "contacts": {
        "L": [
          [
            0.248588,
            0.491525
          ],
          [
            0.80226,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.214689
          ],
          [
            0.542373,
            0.717514
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianNra02.glb",
      "sha256": "67550199849f78d581b356580f25595f361bece70fef0c82d7bd08a954197790"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.59972,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_TengxianNraBackRifleRun.glb",
      "sha256": "9a81b95623f6228d3162fc1fe72bbac162c5a0ed05ed72bc4eb5c7c5a782efd8"
    }
  },
  "TengxianNra05": {
    "RifleRun": {
      "duration": 1.466667,
      "referenceMps": 2.040157,
      "contacts": {
        "L": [
          [
            0.248588,
            0.491525
          ],
          [
            0.80226,
            0.977401
          ]
        ],
        "R": [
          [
            0.022599,
            0.214689
          ],
          [
            0.542373,
            0.711864
          ]
        ]
      },
      "source": "Model/Character/Model_TengxianNra05.glb",
      "sha256": "b85b90fac1843261d40fbf257470a933819a9302dff1727a591feda1a5327b55"
    },
    "RifleCrouchAdvance": {
      "referenceMps": 0.2554529916490837
    },
    "BackRifleRun": {
      "duration": 0.733333,
      "referenceMps": 2.59972,
      "contacts": {
        "L": [
          [
            0,
            0.393258
          ]
        ],
        "R": [
          [
            0.449438,
            0.898876
          ]
        ]
      },
      "source": "Animation/BackRifleRun/Animation_TengxianNraBackRifleRun.glb",
      "sha256": "9a81b95623f6228d3162fc1fe72bbac162c5a0ed05ed72bc4eb5c7c5a782efd8"
    }
  }
};
