import assert from 'node:assert/strict';
import {ParticleSystem,NormalizeParticleModules,EvaluateCurve,EvaluateGradient,IntegrateCurve} from './Script_ParticleModules.mjs';
import {BurningParticleModules} from './Data_Tuning_Particles.mjs';
const Near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
Near(EvaluateCurve([[0,0],[.2,4],[1,0]],.1),2);
Near(IntegrateCurve({mode:'curve',curve:[[0,0],[.2,4],[1,0]]},1),2);
Near(EvaluateCurve({mode:'twoCurves',min:[[0,1],[1,2]],max:[[0,3],[1,6]]},.5,.25),2.25);
Near(EvaluateCurve({mode:'twoCurves',min:1,max:3,multiplier:2},.5,.5),4);
assert.throws(()=>NormalizeParticleModules({main:{startLifetime:{mode:'curve',curve:1,multiplier:0}}}));
assert.deepEqual(EvaluateGradient([[0,[0,1,2,0]],[1,[2,3,4,1]]],.5),[1,2,3,.5]);
assert.throws(()=>NormalizeParticleModules({collision:{enabled:true}}),/Unsupported/);
assert.throws(()=>NormalizeParticleModules({main:{startLifetime:NaN}}));
assert.throws(()=>NormalizeParticleModules({main:{simulationSpace:'screen'}}));
assert.throws(()=>NormalizeParticleModules({renderer:{fakeGlow:3}}));
assert.throws(()=>NormalizeParticleModules({main:{toString:'invalid'}}));
assert.throws(()=>new ParticleSystem({}).Configure({noise:null}));
assert.throws(()=>new ParticleSystem({}).Configure(JSON.parse('{"__proto__":{"enabled":true}}')));
assert.throws(()=>NormalizeParticleModules({sizeOverLifetime:{curve:[[.5,1],[.2,0]]}}));
const config={main:{startLifetime:3,randomSeed:917,maxParticles:256},emission:{rateOverTime:20},shape:{type:'cone',angle:20,radius:2}};
const a=new ParticleSystem(config),b=new ParticleSystem(config);a.Play();b.Play();
for(let i=0;i<60;i++)a.Update(1/60);
for(let i=0;i<10;i++)b.Update(.1);
assert.equal(a.emitted,20);assert.deepEqual(a.particles,b.particles,'frame partition does not change births or seeded motion');
const replay=structuredClone(a.particles);a.Simulate(1);assert.deepEqual(a.particles,replay,'restart reproduces exact live samples');
const frozen=a.time;a.Update(.5);assert.equal(a.time,frozen,'simulation finishes paused');
a.Play();a.Update(.1);assert.ok(a.time>frozen);a.Stop();a.Update(4);assert.equal(a.particles.length,0);assert.equal(a.state,'stopped');
a.Emit(5);a.Update(4);assert.equal(a.particles.length,0,'explicit emit while stopped drains');
const burst=new ParticleSystem({main:{loop:false,duration:.5,startLifetime:.2},emission:{rateOverTime:0,bursts:[{time:0,count:3},{time:.2,count:2,cycles:2,repeatInterval:.1}]}});
burst.Play();burst.Update(.6);assert.equal(burst.emitted,7);assert.equal(burst.state,'stopped');
burst.Play();burst.Update(.1);assert.equal(burst.emitted,3,'completed one-shot can be played again');
const looping=new ParticleSystem({main:{duration:.5,startLifetime:2},emission:{rateOverTime:0,bursts:[{time:0,count:1}]}});
looping.Play();looping.Update(1.2);assert.equal(looping.emitted,3,'time-zero burst repeats at each cycle boundary');
const delayed=new ParticleSystem({main:{startDelay:.1,loop:false,duration:1},emission:{rateOverTime:0,bursts:[{time:0,count:4}]}});
delayed.Play();delayed.Update(.2);assert.equal(delayed.emitted,4,'delayed time-zero burst fires exactly once on a step boundary');
const endBurst=new ParticleSystem({main:{duration:.5,loop:false},emission:{rateOverTime:0,bursts:[{time:.5,count:2}]}});
endBurst.Play();endBurst.Update(.6);assert.equal(endBurst.emitted,2,'a burst at duration is included once');
const distance=new ParticleSystem({emission:{rateOverTime:0,rateOverDistance:2}});distance.Play();distance.Move([3,0,0]);distance.Update(1/60);assert.equal(distance.emitted,6);
distance.Move([10,0,0]);distance.Simulate(.1);assert.equal(distance.emitted,0,'restart does not count teleport distance');
const bounded=new ParticleSystem({main:{maxParticles:4},emission:{rateOverTime:1000}});bounded.Play();bounded.Update(.1);assert.equal(bounded.particles.length,4);assert.ok(bounded.dropped>0);
const colors=new ParticleSystem({main:{startColor:[1,0,0,1]}});colors.Emit(1);colors.Configure({main:{startColor:[0,0,1,1]}});colors.Emit(1);
assert.deepEqual(colors.particles.map(p=>p.color),[[1,0,0,1],[0,0,1,1]],'start color is captured at birth');
const warm=new ParticleSystem({main:{duration:2,prewarm:true,startLifetime:1},emission:{rateOverTime:10}});warm.Play();assert.ok(warm.particles.length>=9&&warm.particles.length<=10);
for(const p of b.particles){assert.ok(Math.hypot(p.origin[0],p.origin[2])<=2.00001);assert.ok(p.velocity[1]>0);}
const ground=BurningParticleModules({fire:1,fireShape:'ground'}),column=BurningParticleModules({fire:1,fireShape:'column'});
assert.ok(ground[1].modules.renderer.aspect<column[1].modules.renderer.aspect&&ground[1].modules.main.startSpeed.max<column[1].modules.main.startSpeed.max,'ground fire keeps its low flame profile');
console.log('ok modular particles: curves, validation, deterministic replay, pause/drain, burst cycles, distance emission, budgets, prewarm');
