// 采耳工具数据表 —— 全套专业采耳工具「是什么、怎么用、参数多合理」的唯一真相。
//
// 设计原则：
//  1. realWorldNote 全部来自实际查证（传统采耳店的工具清单/手法口诀 + 耳科器械规格表 +
//     耵聍生理学），不是编的。参考链接见文件末尾 TOOL_SOURCES。
//  2. 参数不是「越大越好」的数值游戏：耳道全长只有 28mm（Data_Contract §2），
//     分区为 软骨部 0-9 / 骨部 9-21 / 危险区 21-25 / 鼓膜 25-28。
//     所以大量工具的 idealDepthRange 落在 0-16，只有「看得见」的器械才允许更深。
//  3. 现实里会伤人的工具，游戏里必须如实保留代价：棉签 crackRisk 高且带「推进」副作用，
//     音叉不软化硬结就没用，干性耵聍用线圈勺无效（见 TOOL_SOURCES 的 Ear pick 词条）。
//
// 单位：长度 mm，速度 mm/s，角度 deg（相对耳道壁的理想夹角）。

// ── 耵聍科学常识（写 tooltip / 教学卡用，不要散落在各模块里重复写）──
export const CERUMEN_FACTS = {
  // 耵聍腺与皮脂腺只分布在外 1/3 软骨部 —— 这就是为什么「越往里掏越没收获，只有痛」
  glandZone: "耵聍由外 1/3 软骨部的耵聍腺（变态汗腺）与皮脂腺分泌，内 2/3 骨部皮肤极薄且无腺体。",
  glandZoneDepth: [0, 9],
  composition: "干重约 60% 是脱落的角质细胞，另有 12-20% 长链脂肪酸与醇、角鲨烯，6-9% 胆固醇。",
  dryWetGenetics: "干性/湿性耵聍由 ABCC11 基因单碱基多态（rs17822931）决定：AA 纯合为干性（隐性），至少一个 G 为湿性（显性）。东亚多为干性，这正是耳勺在东亚流行、而在欧美只由医护操作的原因。",
  selfCleaning: "耳道皮肤会随咀嚼、说话时的下颌运动向外迁移，正常耳道自带「传送带」自洁功能。",
  impaction: "耵聍栓塞会让耳道被完全堵塞、压到鼓膜，导致传导性听力下降。",
  cottonSwab: "棉签会把大部分耵聍推得更深，只带出黏在棉纤维上的表层一点点；还可能擦伤耳道、把棉头落在耳道里、甚至顶破鼓膜。所以棉签只应用来清洁外耳。",
  softeningNeeded: "耵聍溶解剂应在取耵聍前使用：每日 2-3 次、连用 3-5 天，硬结软化后器械才有用。",
  irrigationWarmth: "冲洗液要温到接近体温；比体温冷或热的液体冲耳会引起眩晕。",
  irrigationTechnique: "冲洗时要把耳廓向后上方牵拉拉直耳道，喷嘴略朝上后方，让水流沿耳道「顶棚」成瀑布流下，再从「地板」带着耵聍流出。",
};

// ── 全套工具（20 件）────────────────────────────────────────────────
// category: pick 掏取 | clean 清扫 | stimulate 刺激放松 | inspect 检查 | care 护理
// 参数标定依据见每条的 noteRefs，对应 TOOL_SOURCES 的 id。
export const EAR_TOOLS = [
  {
    id: "earPickBamboo",
    name: "Bamboo Ear Pick",
    cnName: "竹耳勺",
    category: "pick",
    realWorldNote: "传统采耳最常见的当家工具，勺口朝下、手腕找好支撑点（行话叫「搭桥」），贴着耳壁慢慢伸入后轻推、轻刨、轻带；因为竹子有弹性、手感温润不冰耳，采耳师比不锈钢款更偏爱它。",
    material: "bamboo",
    mechanic: "scoop",
    lengthMm: 140,
    tipRadiusMm: 1.6,
    // 勺头只在外 1/3 软骨部有收获；再深既没有耵聍腺也是骨部薄皮，只会痛
    idealDepthRange: [2, 10],
    idealSpeedRange: [8, 45],
    idealAngleDeg: 30,
    comfortGain: 0.55,
    painRisk: 0.25,
    crackRisk: 0.2,
    unlockAt: 0,
    sfx: { contact: "scrape_bamboo", success: "scoop_pop", fail: "bump_soft" },
    noteRefs: ["maigoo", "taobaoBamboo", "wikipick"],
  },
  {
    id: "earPickSteel",
    name: "Stainless Ear Pick",
    cnName: "不锈钢耳勺",
    category: "pick",
    realWorldNote: "同款勺型但更薄更利，清洁力强、一刮就下，代价是手感「硬」：对耳壁的压力反馈很直接，手不稳就容易刮出痛感。采耳师的说法是新手用竹、老手才敢用钢。",
    material: "steel",
    mechanic: "scoop",
    lengthMm: 138,
    tipRadiusMm: 1.3,
    idealDepthRange: [2, 11],
    idealSpeedRange: [6, 35],
    idealAngleDeg: 28,
    comfortGain: 0.45,
    painRisk: 0.4,
    crackRisk: 0.3,
    unlockAt: 30,
    sfx: { contact: "scrape_metal", success: "scoop_pop", fail: "bump_hard" },
    noteRefs: ["maigoo", "wikipick"],
  },
  {
    id: "earSpoonRound",
    name: "Round Ear Scoop",
    cnName: "圆头耳扒",
    category: "clean",
    realWorldNote: "勺头做成圆润的浅碗，用来大面积贴壁刮扫、把整片松动的耵聍一次带出来；圆头的好处是不会像尖钩那样戳到皮肤，属于「扫而不挑」的收尾工具。",
    material: "steel",
    mechanic: "sweep",
    lengthMm: 142,
    tipRadiusMm: 2.4,
    idealDepthRange: [2, 12],
    idealSpeedRange: [15, 60],
    idealAngleDeg: 22,
    comfortGain: 0.6,
    painRisk: 0.2,
    crackRisk: 0.15,
    unlockAt: 0,
    sfx: { contact: "sweep_metal", success: "scoop_pop", fail: "bump_soft" },
    noteRefs: ["maigoo", "wikipick"],
  },
  {
    id: "earCurette",
    name: "Ear Curette (Wax Hook)",
    cnName: "耵聍钩 / 刮匙",
    category: "pick",
    realWorldNote: "细钩，专门对付已经硬掉的耳结。行话叫「风勾」，用法严苛：勾针要平着极慢伸入，手不能抖、不能摇摆，否则极易挂伤耳壁；到位后勾尖朝目标旋转 90°，勾住再极慢极轻往外拖。",
    material: "steel",
    mechanic: "pinch",
    lengthMm: 180,
    tipRadiusMm: 0.9,
    idealDepthRange: [3, 16],
    idealSpeedRange: [2, 18],
    idealAngleDeg: 12,
    comfortGain: 0.25,
    painRisk: 0.65,
    crackRisk: 0.35,
    unlockAt: 45,
    sfx: { contact: "hook_scrape", success: "wax_chunk_out", fail: "bump_hard" },
    noteRefs: ["maigoo", "fizza", "wikipick"],
  },
  {
    id: "earRake",
    name: "Multi-Tooth Ear Rake",
    cnName: "耳扒（多齿小耙）",
    category: "clean",
    realWorldNote: "3-5 齿的迷你耙子，用来「疏松」成片贴在壁上的干性耵聍——先把片状耵聍耙散成屑，再用勺头或吸引器收走。真实器械的齿尖一律是圆钝的，绝不能做成尖刺，否则等同于自伤。",
    material: "steel",
    mechanic: "rake",
    lengthMm: 145,
    tipRadiusMm: 2.2,
    idealDepthRange: [2, 12],
    idealSpeedRange: [20, 70],
    idealAngleDeg: 18,
    comfortGain: 0.5,
    painRisk: 0.28,
    crackRisk: 0.22,
    unlockAt: 20,
    sfx: { contact: "rake_scratch", success: "crumble", fail: "bump_soft" },
    noteRefs: ["maigoo"],
  },
  {
    id: "gooseFeatherBig",
    name: "Large Goose-Feather Stick",
    cnName: "大鹅毛棒",
    category: "stimulate",
    realWorldNote: "采耳店的招牌「酥麻」来源，用鹅绒毛细软羽毛扎成。手法是旋转着慢慢进入，触到鼓膜就停，先半周慢转「听摩擦声」，再由慢到快全周快转、不断换方向。它只负责放松刺激，不负责清理。",
    material: "feather",
    mechanic: "sweep",
    lengthMm: 148,
    tipRadiusMm: 9,
    idealDepthRange: [6, 20],
    idealSpeedRange: [30, 220],
    idealAngleDeg: 0,
    comfortGain: 1.0,
    painRisk: 0.1,
    // 羽毛本身不会弄破耵聍，但它贴着鼓膜转，转速过高会把耵聍「搡」向鼓膜
    crackRisk: 0.05,
    unlockAt: 0,
    sfx: { contact: "feather_whirl", success: "tingle_shiver", fail: "too_deep" },
    noteRefs: ["maigoo", "wikipick"],
  },
  {
    id: "gooseFeatherSmall",
    name: "Small Goose-Feather Stick",
    cnName: "小鹅毛棒",
    category: "stimulate",
    realWorldNote: "同工艺但更细更短的一支，能越过耳道口那道窄处进得更深，触到鼓膜的摩擦声更清晰、更「钻」，是酥麻感最强的一支，也最考验师傅对深度的把握。",
    material: "feather",
    mechanic: "sweep",
    lengthMm: 152,
    tipRadiusMm: 5.5,
    idealDepthRange: [9, 22],
    idealSpeedRange: [25, 200],
    idealAngleDeg: 0,
    comfortGain: 1.0,
    painRisk: 0.18,
    crackRisk: 0.08,
    unlockAt: 55,
    sfx: { contact: "feather_whirl_fine", success: "tingle_shiver", fail: "too_deep" },
    noteRefs: ["maigoo"],
  },
  {
    id: "horsehairStick",
    name: "Horsehair Stick",
    cnName: "马尾棒",
    category: "stimulate",
    realWorldNote: "几十根马尾毛扎成一束，毛尖散开，是「极致细痒」的代表：扫的是耳道壁而不是耵聍，让人全身起酥。马尾柔到几乎不会伤耳，所以可以比鹅毛进得更深，但也一样清不出东西。",
    material: "horsehair",
    mechanic: "sweep",
    lengthMm: 150,
    tipRadiusMm: 4,
    idealDepthRange: [10, 23],
    idealSpeedRange: [20, 160],
    idealAngleDeg: 0,
    comfortGain: 0.95,
    painRisk: 0.12,
    crackRisk: 0.03,
    unlockAt: 40,
    sfx: { contact: "horsehair_tickle", success: "tingle_shiver", fail: "too_deep" },
    noteRefs: ["maigoo"],
  },
  {
    id: "chickenFeather",
    name: "Chicken-Feather Stick",
    cnName: "鸡毛棒",
    category: "stimulate",
    realWorldNote: "毛质介于鹅毛与马尾之间：比鹅毛挺、比马尾软，主要用来扫掉耳道里的碎屑，也常用来旋转耳道。通常是常采耳、耳道较宽的人更吃这一支。",
    material: "feather",
    mechanic: "sweep",
    lengthMm: 146,
    tipRadiusMm: 7,
    idealDepthRange: [5, 18],
    idealSpeedRange: [30, 190],
    idealAngleDeg: 0,
    comfortGain: 0.9,
    painRisk: 0.12,
    crackRisk: 0.06,
    unlockAt: 25,
    sfx: { contact: "feather_sweep", success: "tingle_shiver", fail: "too_deep" },
    noteRefs: ["maigoo"],
  },
  {
    id: "tuningFork",
    name: "Tuning Fork (Vibrator)",
    cnName: "音叉 / 振子",
    category: "stimulate",
    realWorldNote: "采耳行话叫「振子」，本身不进耳：先把一根鹅毛棒插进耳道轻触鼓膜，一手托住棒尾，另一手拿振子敲响后贴着棒身由里到外上下轻震，靠棒身传振把细散耵聍震落、同时带来「音颤」快感。医学上音叉查听力用 C512（512Hz），乐用标准是 A440。",
    material: "steel",
    mechanic: "vibrate",
    lengthMm: 122,
    tipRadiusMm: 6,
    // 振子自己不进耳道，这里给的是它作用的鹅毛棒所处深度
    idealDepthRange: [8, 20],
    idealSpeedRange: [0, 30],
    idealAngleDeg: 0,
    comfortGain: 0.85,
    painRisk: 0.08,
    // 共振会让硬结「震松」；但没软化的硬结被高频震反而可能压向鼓膜
    crackRisk: 0.12,
    unlockAt: 35,
    sfx: { contact: "fork_hum", success: "vibrate_relief", fail: "harsh_buzz" },
    noteRefs: ["maigoo", "wikiFork", "taobaoFork"],
    // 对外暴露的物理参考值，Script_Audio / Script_Wax 想用可以直接取
    vibrationHz: 512,
  },
  {
    id: "earForceps",
    name: "Ear Forceps (Tilley / Crocodile)",
    cnName: "耳镊 / 膝状镊",
    category: "pick",
    realWorldNote: "采耳套装里叫「铗子」，是镊子的一种但尖头特意做钝，避免夹伤耳壁，用来夹出耳垢块、耳结，也用来夹耳毛。耳科器械表里 Tilley 敷料镊 12.5-15cm，Hartmann 鳄鱼镊工作长度 8-14cm。",
    material: "steel",
    mechanic: "pinch",
    lengthMm: 128,
    tipRadiusMm: 1.2,
    // 镊子要看得见才敢夹，所以只在口前段用；强行深夹是耳道划伤的头号成因
    idealDepthRange: [1, 8],
    idealSpeedRange: [0, 25],
    idealAngleDeg: 15,
    comfortGain: 0.3,
    painRisk: 0.5,
    crackRisk: 0.3,
    unlockAt: 15,
    sfx: { contact: "forceps_close", success: "wax_chunk_out", fail: "pinch_ouch" },
    noteRefs: ["maigoo", "fizza"],
  },
  {
    id: "cottonSwab",
    name: "Cotton Swab",
    cnName: "棉签",
    category: "clean",
    realWorldNote: "真实警告：棉签会把大部分耵聍推得更深，只能带出黏在棉纤维上的表层一点点；还可能擦伤耳道、把棉头掉在耳道里、甚至顶破鼓膜。所以它只应用于清洁外耳——游戏里这一支会如实地把耵聍往鼓膜方向推进。",
    material: "cotton",
    mechanic: "wipe",
    lengthMm: 76,
    tipRadiusMm: 2.6,
    // 棉签的「有效深度」其实很短，因为越深越是在推而不是在取
    idealDepthRange: [1, 6],
    idealSpeedRange: [5, 40],
    idealAngleDeg: 10,
    comfortGain: 0.2,
    // 痛感不高但风险极高：它的问题不是疼，是悄悄把耵聍压实
    painRisk: 0.3,
    crackRisk: 0.85,
    unlockAt: 0,
    sfx: { contact: "cotton_wipe", success: "wipe_clean", fail: "push_wax_deeper" },
    noteRefs: ["wikiwax", "verywell"],
    // 副作用标记：Script_Wax.Probe 看到这个就把耵聍沿 +depth 方向推进
    sideEffect: { pushWax: 0.55, packRisk: 0.4 },
  },
  {
    id: "earDrops",
    name: "Ear Drops (Sodium Bicarbonate)",
    cnName: "滴耳液 / 碳酸氢钠滴耳液",
    category: "care",
    realWorldNote: "耵聍溶解剂，作用是「软化」而不是「取出」：医学建议每日 2-3 次、连用 3-5 天再上器械。采耳店里也常用植物油浸泡硬耳结后再上双氧水。用完之后必须等，急着掏等于白滴。",
    material: "glass",
    mechanic: "spray",
    lengthMm: 92,
    tipRadiusMm: 1.5,
    // 药液滴在耳道口即可，靠重力与毛细作用渗进去
    idealDepthRange: [0, 4],
    idealSpeedRange: [0, 10],
    idealAngleDeg: 45,
    comfortGain: 0.35,
    painRisk: 0.05,
    crackRisk: 0.0,
    unlockAt: 10,
    sfx: { contact: "drop_fall", success: "soften_sizzle", fail: "cold_drip" },
    noteRefs: ["wikiwax", "pubmedBicarb"],
    // 交给 Script_Wax.Soften 的强度与生效延迟（秒）
    soften: { amount01: 0.34, delaySec: 3.0 },
  },
  {
    id: "earSyringe",
    name: "Ear Irrigation Syringe",
    cnName: "洗耳球 / 冲洗器",
    category: "care",
    realWorldNote: "软化之后才用冲洗。要把耳廓向后上方牵拉拉直耳道，喷嘴略朝上后方，让温水沿耳道「顶棚」成瀑布流下、再从「地板」带着耵聍流出；水温必须接近体温，过冷过热都会引起眩晕。鼓膜有穿孔的人禁止冲洗。",
    material: "glass",
    mechanic: "irrigate",
    lengthMm: 130,
    tipRadiusMm: 2.0,
    // 冲洗嘴不进深，靠水流走完全程
    idealDepthRange: [0, 5],
    idealSpeedRange: [0, 15],
    idealAngleDeg: 35,
    comfortGain: 0.4,
    painRisk: 0.2,
    // 有穿孔鼓膜时冲洗会把感染推进中耳，风险主要在这里
    crackRisk: 0.25,
    unlockAt: 50,
    sfx: { contact: "water_jet", success: "wash_clean", fail: "cold_water_dizzy" },
    noteRefs: ["wikiwax", "fpnotebook"],
    // 需要接水盆（lead 侧 UI/场景可以用这个标记提醒）
    requiresBasin: true,
    waterTempIdealC: 37,
  },
  {
    id: "earVacuum",
    name: "Ear Vacuum (Microsuction)",
    cnName: "电动吸引器",
    category: "clean",
    realWorldNote: "就是耳科的 microsuction：一根细金属吸管接负压泵，把碎屑和冲洗残液吸走，好处是不往耳道里灌水、通常比冲洗快、还能配合内窥镜直视操作。注意：家用「耳吸」在临床对比里效果不如 Jobson-Horne 刮匙。",
    material: "steel",
    mechanic: "vacuum",
    lengthMm: 165,
    tipRadiusMm: 1.1,
    // Zoellner 吸引管管径 1.0-2.5mm，可以比勺子进得深一些，但仍不进危险区
    idealDepthRange: [2, 17],
    idealSpeedRange: [0, 30],
    idealAngleDeg: 5,
    comfortGain: 0.5,
    painRisk: 0.3,
    crackRisk: 0.15,
    unlockAt: 70,
    sfx: { contact: "vacuum_hiss", success: "suck_debris", fail: "too_loud_tinnitus" },
    noteRefs: ["wikiwax", "fizza"],
    // 噪声离鼓膜太近会引起耳鸣/眩晕，深度越深噪声代价越大
    noiseRiskAtDepth: 20,
  },
  {
    id: "otoscope",
    name: "Otoscope",
    cnName: "检耳镜 / 耳内窥镜",
    category: "inspect",
    realWorldNote: "看，是采耳的第一步：操作前先检查耳道、了解情况再定方案。检耳镜头部有光源和约 3× 的放大镜，前端接一次性耳漏斗（Hartmann 耳镜 2.5-6.0mm，要选到能越过有毛的软骨部、看进骨部才算合格），检查时把耳廓向后上方拉直耳道。",
    material: "glass",
    mechanic: "light",
    lengthMm: 150,
    tipRadiusMm: 3.0,
    // 耳漏斗只停在耳道口，靠光看进去
    idealDepthRange: [0, 6],
    idealSpeedRange: [0, 12],
    idealAngleDeg: 20,
    comfortGain: 0.5,
    painRisk: 0.12,
    crackRisk: 0.0,
    unlockAt: 0,
    sfx: { contact: "scope_click", success: "reveal", fail: "angry_glare" },
    noteRefs: ["wikiotoscope", "fizza", "maigoo"],
    // 视野增益：让玩家看清深处（UI 可用来开「透视」提示）
    revealDepthBonusMm: 8,
    magnify: 3,
    speculumSizesMm: [2.5, 3.0, 3.5, 4.0, 4.5, 5.0, 5.5, 6.0],
  },

  // ── 追加：采耳套装里真实存在、且能查证到的 4 件 ──
  {
    id: "earHairScissors",
    name: "Ear Hair Scissors",
    cnName: "耳毛剪",
    category: "care",
    realWorldNote: "采耳前先用它剪短耳道口过长、挡视线的耳毛（软骨部才有耳毛，正是因为那里有毛囊和腺体）。剪毛是为了看得清、也避免耳毛把耵聍拦住结成团；刀头必须圆钝或带限深齿，剪不到深处。",
    material: "steel",
    mechanic: "pinch",
    lengthMm: 95,
    tipRadiusMm: 1.0,
    idealDepthRange: [0, 5],
    idealSpeedRange: [0, 20],
    idealAngleDeg: 25,
    comfortGain: 0.15,
    painRisk: 0.35,
    crackRisk: 0.05,
    unlockAt: 5,
    sfx: { contact: "snip", success: "hair_trimmed", fail: "nip_pain" },
    noteRefs: ["maigoo", "wikiwax"],
  },
  {
    id: "thumbLight",
    name: "Thumb Light (Head Lamp)",
    cnName: "拇指灯 / 充电头灯",
    category: "inspect",
    mechanic: "light",
    realWorldNote: "采耳师套在拇指上或戴在头上的聚光灯，作用是「打开头灯对准耳廓」再动手——采耳全程是凭光看深浅的，光打不到就等于盲掏。现在的主流是 USB 充电三档亮度款，市场上也有带灯的发光耳勺可替代。",
    material: "glass",
    lengthMm: 52,
    tipRadiusMm: 6,
    idealDepthRange: [0, 3],
    idealSpeedRange: [0, 10],
    idealAngleDeg: 30,
    comfortGain: 0.45,
    painRisk: 0.05,
    crackRisk: 0.0,
    unlockAt: 0,
    sfx: { contact: "light_click", success: "reveal", fail: "glare" },
    noteRefs: ["maigoo", "taobaoLamp"],
    revealDepthBonusMm: 5,
  },
  {
    id: "peroxideBottle",
    name: "Hydrogen Peroxide Solution",
    cnName: "双氧水（清洁消毒液）",
    category: "care",
    realWorldNote: "采耳店用来消毒「油耳」、软化耳结：硬耳结先用植物油浸泡，再上双氧水软化。配合棉签做清洗消毒是采耳收尾的固定动作；也能用来消毒耳扒本身。注意 75% 酒精只用于器械消毒和耳廓外的清凉感，不进耳道。",
    material: "glass",
    mechanic: "spray",
    lengthMm: 88,
    tipRadiusMm: 2.2,
    idealDepthRange: [0, 4],
    idealSpeedRange: [0, 10],
    idealAngleDeg: 40,
    comfortGain: 0.3,
    painRisk: 0.15,
    crackRisk: 0.05,
    unlockAt: 12,
    sfx: { contact: "fizz", success: "soften_sizzle", fail: "sting" },
    noteRefs: ["maigoo", "yilianmeiti"],
    soften: { amount01: 0.28, delaySec: 2.0 },
    // 双氧水偏「消毒油耳」，对干性耵聍软化收益低
    effectiveOn: ["wet", "impacted"],
  },
  {
    id: "visualEarPick",
    name: "Smart Visual Ear Pick",
    cnName: "可视耳勺（内窥镜带摄像头）",
    category: "inspect",
    realWorldNote: "Bebird 这一类「可视耳勺」：杆端集成微型摄像头 + LED 环灯，无线连手机看耳道，有的型号直接集成可视镊子/滴管，号称能在直视下取耵聍。优点是终于能看着掏；风险是耳道皮肤很薄，看不见手抖照样会划伤甚至顶破鼓膜。",
    material: "steel",
    mechanic: "light",
    lengthMm: 155,
    tipRadiusMm: 2.8,
    // 可视耳勺能看着往深处走，所以允许进到骨部；但危险区依旧禁入
    idealDepthRange: [2, 19],
    idealSpeedRange: [4, 40],
    idealAngleDeg: 15,
    comfortGain: 0.6,
    painRisk: 0.35,
    crackRisk: 0.2,
    unlockAt: 85,
    sfx: { contact: "scope_buzz", success: "reveal_precise", fail: "abrasion" },
    noteRefs: ["wikiwax", "bebird"],
    revealDepthBonusMm: 14,
  },
];

// ── 资料出处（realWorldNote 与参数标定的依据）──────────────────────
export const TOOL_SOURCES = [
  { id: "maigoo", title: "采耳工具全部名称和用法 · 采耳的步骤及工具介绍（含耳扒/鹅毛棒/鸡毛棒/铗子/马尾/振子/耳钩/耳起/刮耳刀/头灯/双氧水/酒精，以及云刀、耳勺、耳起、风勾、弹性耳扒、马尾鸡毛鹅毛棒、振子、棉签八种用法与「刮掏转震洗」五步）", url: "https://www.maigoo.com/goomai/285710.html" },
  { id: "wikipick", title: "Wikipedia · Ear pick（耳勺定义；ladle 勺头 2-5mm；loop 线圈勺与 Jobson-Horne 开窗环勺；down puff 鹅绒球；safety stop 限深；东亚因干性耵聍而流行）", url: "https://en.wikipedia.org/wiki/Ear_pick" },
  { id: "wikiwax", title: "Wikipedia · Earwax / Cerumen（外 1/3 软骨部产耵聍；60% 角质 + 12-20% 长链脂肪酸 + 6-9% 胆固醇；ABCC11 干湿性遗传；棉签把耵聍推深；软化剂每日 2-3 次连用 3-5 天；microsuction；冲洗要温到体温、牵拉耳廓向后上方；耳烛无效且危险；家用耳吸不如 Jobson-Horne 刮匙）", url: "https://en.wikipedia.org/wiki/Earwax" },
  { id: "wikiFork", title: "Wikipedia · Tuning fork（医用于听力检查通常 C512=512Hz；查振动觉用 C128；乐用标准 A=440Hz）", url: "https://en.wikipedia.org/wiki/Tuning_fork" },
  { id: "wikiotoscope", title: "Wikipedia · Otoscope（手柄 + 头，头内有光源与约 8 屈光度≈3× 放大镜；前端接一次性耳漏斗；检查时先牵拉耳廓拉直耳道；可换透镜插入吸引管取耵聍）", url: "https://en.wikipedia.org/wiki/Otoscope" },
  { id: "fizza", title: "Fizza Surgical · Aural Instruments: Ear Specula, Jobson Horne and Tilley（耳科器械规格表：Hartmann 耳镜 2.5-6.0mm；Jobson Horne 15-18cm；Tilley 敷料镊 12.5-15cm；鳄鱼镊 8-14cm；取蜡钩钝头 90°/45°；Zoellner 吸引管管径 1.0-2.5mm）", url: "https://www.fizzasurgical.com/aural-instruments-ear-specula-jobson-horne-tilley/" },
  { id: "karlstorz", title: "KARL STORZ · Jobson-Horne Probe 18 cm（厂商规格，确认耳科刮匙总长 18cm）", url: "https://www.karlstorz.com/de/en/product-detail-page.htm?cat=1000071971&productID=1000131013" },
  { id: "pubmedBicarb", title: "PubMed · Cerumenolytic Efficacy of 2.5% Sodium Bicarbonate Versus Docusate Sodium: A Randomized Controlled Trial（碳酸氢钠滴耳液软化耵聍的随机对照试验）", url: "https://pubmed.ncbi.nlm.nih.gov/32658399/" },
  { id: "fpnotebook", title: "FPnotebook · Warm Water Ear Lavage — Procedure（温水洗耳操作，体温水温与操作要点）", url: "https://mobile.fpnotebook.com/ENT/Procedure/WrmWtrErLvg.htm" },
  { id: "childrensmercy", title: "Children's Mercy · Cerumen Removal: Manual Removal and Irrigation（耵聍手动取出与冲洗的临床路径）", url: "https://www.childrensmercy.org/health-care-providers/evidence-based-practice/cpgs-cpms-and-eras-pathways/cerumen-impaction/cerumen-removal/" },
  { id: "verywell", title: "Verywell Health · The Dangers of Using Q-Tips for Earwax（棉签的风险：推深、擦伤、棉头遗留、鼓膜穿孔）", url: "https://www.verywellhealth.com/the-dangers-of-q-tips-1048870" },
  { id: "medscape", title: "Medscape · Dealing With Cerumen Impaction（耵聍栓塞的处理）", url: "https://www.medscape.com/viewarticle/875560_4" },
  { id: "taobaoBamboo", title: "淘宝江湖 · 为什么越来越多采耳师偏爱竹制耳勺而不是不锈钢款？（竹子有弹性、手感温润，采耳师偏好竹勺）", url: "https://jianghu.taobao.com/detail/47598_78944869" },
  { id: "taobaoFork", title: "淘宝江湖 · 音叉采耳工具的共振频率原理与人体耳道适配性解析（振子/音叉震耳的共振原理）", url: "https://jianghu.taobao.com/detail/47500_75029338" },
  { id: "taobaoLamp", title: "淘宝江湖 · 为什么越来越多人开始用充电头灯采耳？（采耳照明：光打不到就是盲掏）", url: "https://jianghu.taobao.com/detail/47500_79207200" },
  { id: "bebird", title: "Bebird Earsight Plus / R1 Max（可视耳勺产品：摄像头 + LED 环灯 + 集成镊子/滴管的家庭采耳套装）", url: "https://www.amazon.ca/dp/B0FB3RPNW9/" },
  { id: "yilianmeiti", title: "一览医美 · 油耳可以用双氧水吗（双氧水用于油耳的清洁消毒）", url: "https://m.yilianmeiti.com/audio/182781.html" },
  { id: "sohu", title: "搜狐 · 采耳工具介绍及步奏（采耳工具与操作步骤补充）", url: "https://m.sohu.com/a/348987919_120397846/" },
  { id: "toutiao", title: "今日头条 · 采耳整套流程(左耳) 操作手法及注意细节（采耳完整流程：消毒备具 → 调床与角度 → 先检查耳道定方案 → 按摩放松耳部 → 再操作）", url: "https://m.toutiao.com/w/1763861701753863/" },
];

// id → 规格 的快速索引；给 UI 和判定用，避免每次 find
export const EAR_TOOL_BY_ID = Object.fromEntries(EAR_TOOLS.map((tool) => [tool.id, tool]));

// 采耳标准流程（行话「刮 · 掏 · 转 · 震 · 洗」），UI 可用来做引导/成就
export const EAR_TOOL_FLOW = [
  { step: 1, name: "刮", desc: "用刮耳刀/云刀轻刮耳廓四周，让客人先放松下来", tools: [] },
  { step: 2, name: "掏", desc: "打开头灯对准耳廓，轮换耳勺、软刨、风勾、镊子，轻掏慢取", tools: ["earPickBamboo", "earPickSteel", "earSpoonRound", "earCurette", "earRake", "earForceps"] },
  { step: 3, name: "转", desc: "把毛棒伸入耳道，捏住尾端快速旋转，把耳屎粘在毛上带出", tools: ["gooseFeatherBig", "gooseFeatherSmall", "chickenFeather", "horsehairStick"] },
  { step: 4, name: "震", desc: "插入新毛棒，用振子（音叉）震击棒身，把细散耵聍震落后转出", tools: ["tuningFork"] },
  { step: 5, name: "洗", desc: "棉签沾药水（或双氧水）伸入耳道清洗、吸干，保持干爽清新", tools: ["earDrops", "peroxideBottle", "earSyringe", "earVacuum", "cottonSwab"] },
];

export default EAR_TOOLS;
