import assert from 'node:assert/strict';
import {CreatePeelBody,GripPeelBody,StepPeelBody,UngripPeelBody} from './Script_PeelPhysics.mjs';
const Body=type=>CreatePeelBody({position:[0,0,0],rotation:[0,0,0,1],normal:[0,0,1],size:.7,type});
const Step=(body,target,n,softness=0)=>{for(let i=0;i<n;i++)StepPeelBody(body,{target,softness},1/120);};
const idle=Body('dry');Step(idle,null,1200);assert.equal(idle.detached,false);
const micro=Body('dry');GripPeelBody(micro,[0,-.4,.2]);
for(let i=0;i<1200;i++)StepPeelBody(micro,{target:[Math.sin(i*.2)*.025,-.4,.2]},1/120);
assert.equal(micro.anchors.filter(a=>a.alive).length,5,'小幅重复移动不能刷掉粘附');
const pressed=Body('dry');GripPeelBody(pressed,[0,0,.2]);Step(pressed,[0,0,-2],180);
assert.ok(pressed.position[2]>=-.001,'内壁阻止穿透');assert.equal(pressed.detached,false,'向皮肤内压不能凭里程清除');
const lifted=Body('dry');GripPeelBody(lifted,[0,-.4,.2]);Step(lifted,[0,-.8,1.3],180);
assert.equal(lifted.detached,true,'托起边缘会逐个撬开粘附点');
assert.ok(Math.hypot(...lifted.rotation.slice(0,3))>.01,'偏心拉力产生真实转动');
const canceled=Body('dry');GripPeelBody(canceled,[0,-.3,.2]);Step(canceled,[.02,-.3,.24],60);UngripPeelBody(canceled);Step(canceled,null,240);
assert.ok(Math.hypot(...canceled.position)<.025,'中途松手会由粘附弹簧拉回');
const hard=Body('impacted'),soft=Body('impacted');for(const body of [hard,soft])GripPeelBody(body,[0,-.4,.2]);
Step(hard,[0,-.4,.62],75);Step(soft,[0,-.4,.62],75,1);
assert.ok(soft.anchors.filter(a=>a.alive).length<hard.anchors.filter(a=>a.alive).length,'滴液会降低同样受力下的粘附强度');
const supported=Body('dry');GripPeelBody(supported,[0,-.4,.1]);Step(supported,[0,-.5,1.4],180);
const holdRotation=[-Math.SQRT1_2,0,0,Math.SQRT1_2];
for(let i=0;i<600;i++)StepPeelBody(supported,{target:[0,-.5,1.4],supportRotation:holdRotation},1/120);
assert.ok(Math.abs(supported.rotation.reduce((sum,v,i)=>sum+v*holdRotation[i],0))>.995,'松脱后勺面角向支撑防止翻滚');
console.log('PASS 8 physical interaction checks: rest, no gesture farming, wall support, peel, torque, return, softening, angular support');
