function DeepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.values(value).forEach((child) => DeepFreeze(child));
  return Object.freeze(value);
}

const commonHistoricalBoundary =
  "本行动的县域、村庄、人物、敌军编制与事件均为原创综合化设定，不对应某场具体战斗。小队只能改变一次地方行动的代价与成果，不能改写战争进程或1945年日本投降这一历史终点。";

const commonCostLedgerPolicy = {
  scoreFromEnemyCasualties: false,
  rewardFromCivilianProperty: false,
  rewardFromCivilianSuffering: false,
  civilianCosts: ["risk", "harm", "displacement"],
  note: "群众风险、受害与被迫转移只进入代价账本；护送和归还民物属于行动责任，不产出可消费资源。",
};

export const operationLayoutDefinitions = DeepFreeze([
  {
    id: "infiltrateSignalStation",
    operationId: "cutline",
    name: "槐树峪潜台",
    chapter: "第一行动",
    date: "1941年10月17日",
    timeOfDay: "拂晓前",
    weather: "薄雾，北风",
    location: "太行山前虚构综合县域 · 槐树峪",
    layoutFamily: "splitRavineCompound",
    gameplayIdentity:
      "狭长沟谷潜入关：先从三条高低不同的接近线侦察，再穿越电话站内外两层警戒，取图、断线并在天亮前脱离。",
    summary: "潜入临时有线情报站，取得换防线路图，切断总机；不以清除守军为目标。",
    historicalBoundary: commonHistoricalBoundary,
    costLedgerPolicy: commonCostLedgerPolicy,
    bounds: { minimumX: -68, maximumX: 66, minimumZ: -46, maximumZ: 48 },
    camera: {
      position: { x: -70, y: 58, z: -60 },
      target: { x: 4, y: 0, z: 2 },
    },
    playerSpawns: [
      { x: -58, z: -33 },
      { x: -61, z: -30 },
      { x: -56, z: -29 },
      { x: -62, z: -26 },
    ],
    objectives: {
      mandatory: [
        { id: "stationLedger", label: "取得换防线路图", carryToExtract: true },
        { id: "stationSwitchboard", label: "切断手摇电话总机", carryToExtract: false },
        { id: "allExtracted", label: "小队撤出封锁区", carryToExtract: false },
      ],
      optional: [
        { id: "returnSeedRegister", label: "带走征粮名册并交交通站", nonRewardingDuty: true },
        { id: "disableSearchlight", label: "关闭探照灯发电机" },
      ],
      failForward: "线路图遗失则本行动失败并重复；被发现不会立即失败，但会启动分区封锁和传令兵。",
    },
    tacticalPhases: [
      {
        id: "readApproaches",
        label: "摸清谷口",
        trigger: "missionStart",
        decision: "从高粱地、干河沟或风化山脊接近；三条路分别牺牲速度、视野或隐蔽。",
      },
      {
        id: "crossOuterWatch",
        label: "越过外哨",
        trigger: "enterZone:outerWatch",
        decision: "利用换岗空隙、投石声源或切断岗楼灯，不要求击倒外哨。",
      },
      {
        id: "breakCommunications",
        label: "取图断线",
        trigger: "enterZone:signalCompound",
        decision: "拿图后总机员会核对档案；先断总机更安全，但会派出查线兵。",
      },
      {
        id: "breakContact",
        label: "脱离",
        trigger: "objective:stationLedger",
        decision: "按敌方封锁方向选择塌桥、芦苇渡口或来路，避免恋战。",
      },
    ],
    extractionZones: [
      { id: "ravineMouth", name: "西南谷口", x: -61, z: -35, radius: 6, unlocked: true },
      { id: "reedFord", name: "北沟芦苇渡", x: -30, z: 42, radius: 6, unlocked: false },
      { id: "brokenCauseway", name: "东南塌桥便道", x: 58, z: -37, radius: 6, unlocked: true },
    ],
    zones: [
      { id: "westSorghum", kind: "foliage", x: -42, z: -22, width: 34, depth: 18, visibility: 0.42, sound: 0.76, elevation: 1.2, elevationSlope: { x: 0.6, z: 0.4 } },
      { id: "dryRavine", kind: "ditch", x: -25, z: 2, width: 9, depth: 68, visibility: 0.58, sound: 0.64, elevation: -2.4, elevationSlope: { x: 0, z: 0.5 }, elevationPriority: 3 },
      { id: "northReeds", kind: "foliage", x: -24, z: 35, width: 30, depth: 16, visibility: 0.34, sound: 0.69, elevation: 0.4, elevationSlope: { x: 0.4, z: 0.2 } },
      { id: "outerWatch", kind: "open", x: -2, z: -6, width: 26, depth: 25, visibility: 1.08, sound: 1, elevation: 0.7, elevationSlope: { x: 0.5, z: 0.2 } },
      { id: "signalCompound", kind: "open", x: 34, z: 8, width: 37, depth: 34, visibility: 1.16, sound: 1.04, elevation: 1.4, elevationSlope: { x: 0.4, z: 0.3 } },
      { id: "ridgePath", kind: "rock", x: 8, z: -35, width: 52, depth: 8, visibility: 1.2, sound: 1.12, elevation: 3.4, elevationSlope: { x: 1, z: 0.2 }, elevationPriority: 2 },
    ],
    lightingZones: [
      { id: "compoundSearchlight", kind: "circle", x: 31, z: 5, radius: 18, generatorDependent: true },
      { id: "northGateLamp", kind: "circle", x: 20, z: 22, radius: 10, generatorDependent: true },
      { id: "operatorLantern", kind: "box", x: 40, z: 8, width: 9, depth: 7, generatorDependent: false },
    ],
    obstacles: [
      { id: "switchHouse", kind: "building", impactMaterial: "earth", x: 37, z: 7, width: 14, depth: 10, height: 5.4, color: 0x6a5742 },
      { id: "recordsRoom", kind: "building", impactMaterial: "earth", x: 51, z: 20, width: 12, depth: 8, height: 4.7, color: 0x62503d },
      { id: "outerGuardRoom", kind: "building", impactMaterial: "earth", x: 4, z: -3, width: 11, depth: 8, height: 4.2, color: 0x705c45 },
      { id: "northWatchTower", kind: "tower", impactMaterial: "wood", x: 19, z: 23, width: 4, depth: 4, height: 8.5, color: 0x51483b },
      { id: "compoundWallSouth", kind: "wall", impactMaterial: "stone", x: 37, z: -10, width: 40, depth: 1.3, height: 2.1, color: 0x6d624f },
      { id: "compoundWallEast", kind: "wall", impactMaterial: "stone", x: 57, z: 8, width: 1.3, depth: 37, height: 2.1, color: 0x6d624f },
      { id: "compoundWallNorth", kind: "wall", impactMaterial: "stone", x: 40, z: 27, width: 34, depth: 1.3, height: 2.1, color: 0x6d624f },
      { id: "outerStoneWall", kind: "wall", impactMaterial: "stone", x: -4, z: 8, width: 29, depth: 1.2, height: 1.6, color: 0x766f60 },
      { id: "telephoneCrates", kind: "crate", impactMaterial: "wood", x: 28, z: 16, width: 5, depth: 3, height: 2, color: 0x59452f },
      { id: "lineCart", kind: "wagon", impactMaterial: "wood", x: 45, z: -16, width: 7, depth: 3.2, height: 2.5, color: 0x59442e },
    ],
    interactables: [
      {
        id: "stationLedger",
        kind: "objective",
        name: "换防线路图",
        x: 48,
        z: 19,
        radius: 2.8,
        duration: 3.8,
        action: "collect",
        description: "标出各炮楼的换岗、电话支线与车辆通过时刻；必须由携带者带出。",
      },
      {
        id: "stationSwitchboard",
        kind: "objective",
        name: "手摇电话总机",
        x: 37,
        z: 5,
        radius: 3,
        duration: 6,
        action: "sabotage",
        description: "拆下接线塞绳并剪断进出线，使邻近据点改用传令兵。",
      },
      {
        id: "stationGenerator",
        kind: "environment",
        name: "探照灯发电机",
        x: 18,
        z: 20,
        radius: 3,
        duration: 3.5,
        action: "sabotage",
        description: "熄灭两处电灯；停机声消失后，岗楼会派人下去查看。",
      },
      {
        id: "lineJunction",
        kind: "environment",
        name: "谷口接线匣",
        x: -5,
        z: -7,
        radius: 2.6,
        duration: 3.2,
        action: "sabotage",
        description: "提前剪断北支线，使报警只能沿南路送出，但会暴露线路遭人为破坏。",
      },
      {
        id: "returnSeedRegister",
        kind: "civilian",
        name: "征粮名册",
        x: 51,
        z: 22,
        radius: 2.4,
        duration: 2.8,
        action: "collectForReturn",
        description: "只交给交通站通知各村转移种粮，不换取营地资源。",
      },
    ],
    patrols: [
      {
        id: "ravineSweep",
        points: [
          { x: -38, z: -27 },
          { x: -22, z: -15 },
          { x: -12, z: -7 },
          { x: -29, z: 0 },
        ],
      },
      {
        id: "outerTriangle",
        points: [
          { x: -8, z: -9 },
          { x: 11, z: -5 },
          { x: 10, z: 14 },
          { x: -5, z: 9 },
        ],
      },
      {
        id: "compoundCircuit",
        points: [
          { x: 18, z: -5 },
          { x: 50, z: -4 },
          { x: 52, z: 22 },
          { x: 25, z: 23 },
        ],
      },
      {
        id: "generatorInspection",
        activeWhen: "flag:stationPowerDisabled",
        points: [
          { x: 35, z: 6 },
          { x: 24, z: 14 },
          { x: 18, z: 20 },
          { x: 8, z: 12 },
        ],
      },
      {
        id: "southMessenger",
        activeWhen: "flag:stationTelephoneCut",
        points: [
          { x: 39, z: 4 },
          { x: 22, z: -8 },
          { x: 33, z: -29 },
          { x: 61, z: -38 },
        ],
      },
    ],
    enemies: [
      { id: "ravineOne", role: "patrol", patrol: "ravineSweep", patrolOffset: 0, x: -38, z: -27 },
      { id: "ravineTwo", role: "patrol", patrol: "ravineSweep", patrolOffset: 2, x: -12, z: -7 },
      { id: "outerOne", role: "patrol", patrol: "outerTriangle", patrolOffset: 0, x: -8, z: -9 },
      { id: "outerTwo", role: "patrol", patrol: "outerTriangle", patrolOffset: 2, x: 10, z: 14 },
      { id: "northTower", role: "sentry", x: 19, z: 23, facing: -2.25, elevated: true },
      { id: "compoundOne", role: "patrol", patrol: "compoundCircuit", patrolOffset: 0, x: 18, z: -5 },
      { id: "compoundTwo", role: "patrol", patrol: "compoundCircuit", patrolOffset: 2, x: 52, z: 22 },
      { id: "switchboardOperator", role: "operator", x: 38, z: 6, facing: Math.PI },
      { id: "dutyLeader", role: "leader", patrol: "compoundCircuit", patrolOffset: 1, x: 50, z: -4 },
    ],
    civilianRoutes: [
      {
        id: "charcoalCarrierRoute",
        name: "炭夫回村路",
        groupSize: 1,
        scheduleSeconds: 255,
        behavior: "pauseAndYield",
        points: [
          { x: -57, z: 12 },
          { x: -30, z: 14 },
          { x: -8, z: 17 },
          { x: 12, z: 30 },
        ],
        note: "玩家可等候其通过，不得把行人当作诱饵；交火靠近路线会记群众风险。",
      },
    ],
    civilianRouteObjectives: [],
    reinforcementRoutes: [
      {
        id: "telephoneTruck",
        mode: "vehicle",
        arrivalSeconds: 105,
        disabledByFlag: "stationTelephoneCut",
        entry: { x: 64, z: -34 },
      },
      {
        id: "southRunner",
        mode: "messenger",
        arrivalSeconds: 205,
        enabledByFlag: "stationTelephoneCut",
        disabledByFlag: "southMessengerIntercepted",
        entry: { x: 61, z: -38 },
      },
    ],
    environmentInteractions: [
      {
        id: "disableStationPower",
        interactableId: "stationGenerator",
        allowedRoles: ["hanShilei"],
        duration: 3.5,
        requirements: {},
        effects: {
          setFlags: ["stationPowerDisabled"],
          disableLighting: ["compoundSearchlight", "northGateLamp"],
          setPatrolRoutes: { compoundOne: "generatorInspection" },
          emitEvents: ["lightsOut", "generatorInspectionOrdered"],
          completeObjectives: ["disableSearchlight"],
        },
        tradeoff: "院内暗区扩大，但一名巡逻兵离开原环线检查发电机，短时形成交叉移动。",
      },
      {
        id: "cutStationTelephone",
        interactableId: "stationSwitchboard",
        allowedRoles: ["hanShilei"],
        duration: 6,
        requirements: {},
        effects: {
          setFlags: ["stationTelephoneCut"],
          disableReinforcements: ["telephoneTruck"],
          enableReinforcements: ["southRunner"],
          delayReinforcements: 100,
          setPatrolRoutes: { switchboardOperator: "southMessenger" },
          emitEvents: ["lineSilenced", "messengerDispatched"],
          completeObjectives: ["stationSwitchboard"],
        },
        tradeoff: "快速电话增援失效，但总机员会尝试沿南路派出传令兵；可截断路线而不必肃清院落。",
      },
      {
        id: "cutNorthJunction",
        interactableId: "lineJunction",
        allowedRoles: ["hanShilei"],
        duration: 3.2,
        requirements: {},
        effects: {
          setFlags: ["northBranchCut"],
          unlockExtractions: ["reedFord"],
          revealIntel: ["northReedsSafeWindow"],
          emitEvents: ["northBranchGoesQuiet"],
        },
        tradeoff: "北侧据点无法电话封锁芦苇渡，但外哨会在下一轮报点时发现线路异常。",
      },
      {
        id: "takeStationLedger",
        interactableId: "stationLedger",
        duration: 3.8,
        requirements: {},
        effects: {
          setFlags: ["stationLedgerTaken"],
          startCarryItems: ["stationLedger"],
          revealIntel: ["compoundCircuit", "southMessenger", "telephoneTruck"],
          emitEvents: ["recordsCheckMissed"],
        },
        tradeoff: "携带者一旦倒地，线路图掉落在原地；只有携带者撤出才算带回。",
      },
      {
        id: "secureSeedRegister",
        interactableId: "returnSeedRegister",
        duration: 2.8,
        requirements: {},
        effects: {
          setFlags: ["seedRegisterSecuredForReturn"],
          emitEvents: ["villagesCanBeWarned"],
          completeObjectives: ["returnSeedRegister"],
        },
        tradeoff: "这是保护群众的责任，不增加营地物资、分数或敌情优势。",
      },
    ],
    scheduledEvents: [
      { atSeconds: 180, unlessFlag: "stationPowerDisabled", event: "searchlightSweepsWestRidge" },
      { atSeconds: 300, unlessFlag: "stationTelephoneCut", event: "routineTelephoneCheck" },
      { atSeconds: 420, event: "firstLightRaisesOpenGroundVisibility" },
    ],
    narrativeRefs: {
      briefing: "signalBriefing",
      field: ["signalRavineWhisper", "signalLedgerChoice"],
      debrief: "signalDebrief",
    },
  },
  {
    id: "nightRendezvous",
    operationId: "northVillageRelief",
    name: "北庄接应",
    chapter: "第二行动",
    date: "1941年10月22日",
    timeOfDay: "深夜",
    weather: "无月，间歇细雨",
    location: "太行山前虚构综合县域 · 北庄河套",
    layoutFamily: "villageCreekLanes",
    gameplayIdentity:
      "村落保护关：道路不是空白通道而是群众生活空间。小队需要辨认联络暗号、安排村民分批离开，并利用雨声、水渠和熄灯制造无交火窗口。",
    summary: "接回应当转移的交通员与药箱，掩护两组村民沿不同路线离开夜间封锁。",
    historicalBoundary: commonHistoricalBoundary,
    costLedgerPolicy: commonCostLedgerPolicy,
    bounds: { minimumX: -60, maximumX: 62, minimumZ: -52, maximumZ: 54 },
    camera: {
      position: { x: -67, y: 62, z: -65 },
      target: { x: 2, y: 0, z: 2 },
    },
    playerSpawns: [
      { x: -50, z: 43 },
      { x: -54, z: 40 },
      { x: -48, z: 39 },
      { x: -53, z: 36 },
    ],
    objectives: {
      mandatory: [
        { id: "contactLiu", label: "辨认并接应交通员刘婶", carryToExtract: false },
        { id: "clinicSatchel", label: "带回救护药箱", carryToExtract: true },
        { id: "escortHouseholds", label: "掩护两组村民离村", nonRewardingDuty: true },
        { id: "allExtracted", label: "小队与交通员撤出", carryToExtract: false },
      ],
      optional: [
        { id: "quietDeparture", label: "不敲响村口铜锣" },
        { id: "returnDraftAnimal", label: "解开被扣牲口并交还村民", nonRewardingDuty: true },
      ],
      failForward: "交通员死亡或药箱遗失则行动失败并重复；群众受害不会用其他成果抵扣。",
    },
    tacticalPhases: [
      {
        id: "verifyContact",
        label: "对暗号",
        trigger: "enterZone:northOrchard",
        decision: "先观察窗纸记号和三短一长敲击，贸然接触错误院落会引来便衣哨。",
      },
      {
        id: "shapeVillageFlow",
        label: "分流村民",
        trigger: "objective:contactLiu",
        decision: "先开水闸用流水声掩护东巷，或先熄路灯放空西巷；同时行动更快但会让巡逻交叠。",
      },
      {
        id: "recoverMedicine",
        label: "取回药箱",
        trigger: "flag:householdsMoving",
        decision: "药箱在被封的祠堂偏房；可等巡查离开，也可制造远处声源，不必强攻。",
      },
      {
        id: "escortUnderPressure",
        label: "护送离村",
        trigger: "event:curfewTightens",
        decision: "队员在前探路、在后掩护；村民不是可直接操纵的战术诱饵。",
      },
    ],
    extractionZones: [
      { id: "northOrchardExit", name: "北坡枣林", x: -49, z: 47, radius: 7, unlocked: true },
      { id: "eastCanalExit", name: "东渠暗口", x: 56, z: 37, radius: 7, unlocked: false },
      { id: "westThreshingExit", name: "西场麦秸垛", x: -55, z: -35, radius: 7, unlocked: true },
    ],
    zones: [
      { id: "northOrchard", kind: "foliage", x: -37, z: 38, width: 32, depth: 19, visibility: 0.38, sound: 0.7, elevation: 3.2, elevationSlope: { x: 0.6, z: 0.8 }, elevationPriority: 2 },
      { id: "creekBed", kind: "ditch", x: 16, z: 4, width: 10, depth: 86, visibility: 0.52, sound: 0.58, elevation: -2.6, elevationSlope: { x: 0, z: 0.6 }, elevationPriority: 3 },
      { id: "eastReeds", kind: "foliage", x: 42, z: 30, width: 25, depth: 24, visibility: 0.3, sound: 0.64, elevation: -0.8, elevationSlope: { x: 0.4, z: 0.5 } },
      { id: "westVillageLane", kind: "lane", x: -20, z: 3, width: 10, depth: 66, visibility: 0.94, sound: 1.06, elevation: 1.4, elevationSlope: { x: 0.2, z: 1 } },
      { id: "eastVillageLane", kind: "lane", x: 33, z: 0, width: 11, depth: 60, visibility: 0.94, sound: 1.06, elevation: 0.8, elevationSlope: { x: 0.2, z: 0.6 } },
      { id: "threshingGround", kind: "open", x: -37, z: -26, width: 30, depth: 22, visibility: 1.18, sound: 1.02, elevation: 0.2, elevationSlope: { x: 0.3, z: 0.2 } },
      { id: "templeYard", kind: "open", x: 9, z: -18, width: 29, depth: 22, visibility: 1.1, sound: 1, elevation: 1.7, elevationSlope: { x: 0.4, z: 0.3 } },
    ],
    lightingZones: [
      { id: "westStreetLamp", kind: "box", x: -18, z: -1, width: 15, depth: 24, generatorDependent: true },
      { id: "templeGateLamp", kind: "circle", x: 1, z: -15, radius: 12, generatorDependent: true },
      { id: "eastCheckpointBrazier", kind: "circle", x: 43, z: 7, radius: 10, generatorDependent: false },
      { id: "contactWindow", kind: "box", x: -24, z: 25, width: 6, depth: 4, generatorDependent: false },
    ],
    obstacles: [
      { id: "contactHouse", kind: "building", impactMaterial: "earth", x: -25, z: 22, width: 13, depth: 10, height: 4.5, color: 0x6f5942 },
      { id: "eastHouse", kind: "building", impactMaterial: "earth", x: 31, z: 22, width: 14, depth: 9, height: 4.4, color: 0x66523e },
      { id: "southHouse", kind: "building", impactMaterial: "earth", x: -17, z: -22, width: 14, depth: 10, height: 4.4, color: 0x705942 },
      { id: "ancestralHall", kind: "building", impactMaterial: "earth", x: 10, z: -22, width: 18, depth: 11, height: 5.3, color: 0x5f4d3b },
      { id: "waterMill", kind: "building", impactMaterial: "wood", x: 31, z: -31, width: 12, depth: 9, height: 4.6, color: 0x594b3b },
      { id: "westLaneWall", kind: "wall", impactMaterial: "stone", x: -7, z: 7, width: 1.2, depth: 31, height: 1.8, color: 0x746955 },
      { id: "templeWallNorth", kind: "wall", impactMaterial: "stone", x: 9, z: -7, width: 31, depth: 1.2, height: 2, color: 0x6d624f },
      { id: "templeWallEast", kind: "wall", impactMaterial: "stone", x: 24, z: -20, width: 1.2, depth: 26, height: 2, color: 0x6d624f },
      { id: "eastCheckpoint", kind: "wall", impactMaterial: "stone", x: 44, z: 8, width: 15, depth: 1.5, height: 1.6, color: 0x716552 },
      { id: "rainCart", kind: "wagon", impactMaterial: "wood", x: -2, z: 15, width: 7, depth: 3.2, height: 2.5, color: 0x59442e },
      { id: "hayStack", kind: "foliage", impactMaterial: "earth", x: -42, z: -28, width: 8, depth: 6, height: 3.3, color: 0x75633f },
    ],
    interactables: [
      {
        id: "contactLiu",
        kind: "rescue",
        name: "交通员刘婶",
        x: -25,
        z: 25,
        radius: 3,
        duration: 4,
        action: "verifyAndEscort",
        description: "按约定辨认窗纸和敲击暗号；她熟悉村路，但不是无敌的任务道具。",
      },
      {
        id: "clinicSatchel",
        kind: "objective",
        name: "救护药箱",
        x: 8,
        z: -19,
        radius: 2.8,
        duration: 3,
        action: "collect",
        description: "由救护站托付的纱布、消毒用品和常用药，必须由携带者撤出。",
      },
      {
        id: "irrigationSluice",
        kind: "environment",
        name: "东渠木闸",
        x: 26,
        z: 34,
        radius: 3.2,
        duration: 4.2,
        action: "open",
        description: "放水后流水声掩护东巷脚步，同时让巡查沿渠查看。",
      },
      {
        id: "lampFuse",
        kind: "environment",
        name: "村西路灯线",
        x: -8,
        z: 13,
        radius: 2.6,
        duration: 3,
        action: "sabotage",
        description: "熄灭西巷和祠堂门灯；岗哨会先封住开阔打谷场。",
      },
      {
        id: "warningGong",
        kind: "environment",
        name: "村口铜锣绳",
        x: 43,
        z: 8,
        radius: 2.8,
        duration: 2.8,
        action: "sabotage",
        description: "卸下锣槌可阻止快速全村报警，但近处哨兵会发现异常。",
      },
      {
        id: "draftMule",
        kind: "civilian",
        name: "被扣的骡子",
        x: 36,
        z: -28,
        radius: 3,
        duration: 3.4,
        action: "return",
        description: "交还村民用于转运伤员和粮食，不转化为营地物资。",
      },
    ],
    patrols: [
      {
        id: "westCurfew",
        points: [
          { x: -44, z: -19 },
          { x: -19, z: -12 },
          { x: -18, z: 18 },
          { x: -38, z: 28 },
        ],
      },
      {
        id: "eastCurfew",
        points: [
          { x: 41, z: -18 },
          { x: 43, z: 8 },
          { x: 32, z: 26 },
          { x: 25, z: 5 },
        ],
      },
      {
        id: "templeCheck",
        points: [
          { x: -2, z: -12 },
          { x: 19, z: -10 },
          { x: 18, z: -30 },
          { x: -1, z: -29 },
        ],
      },
      {
        id: "sluiceInspection",
        activeWhen: "flag:sluiceOpened",
        points: [
          { x: 34, z: 11 },
          { x: 39, z: 28 },
          { x: 26, z: 34 },
          { x: 12, z: 30 },
        ],
      },
      {
        id: "darkLaneBlock",
        activeWhen: "flag:villageLampsDisabled",
        points: [
          { x: 1, z: -15 },
          { x: -14, z: -6 },
          { x: -37, z: -25 },
          { x: -48, z: -33 },
        ],
      },
    ],
    enemies: [
      { id: "westOne", role: "patrol", patrol: "westCurfew", patrolOffset: 0, x: -44, z: -19 },
      { id: "westTwo", role: "patrol", patrol: "westCurfew", patrolOffset: 2, x: -18, z: 18 },
      { id: "eastOne", role: "patrol", patrol: "eastCurfew", patrolOffset: 0, x: 41, z: -18 },
      { id: "eastTwo", role: "patrol", patrol: "eastCurfew", patrolOffset: 2, x: 32, z: 26 },
      { id: "templeOne", role: "patrol", patrol: "templeCheck", patrolOffset: 0, x: -2, z: -12 },
      { id: "templeTwo", role: "patrol", patrol: "templeCheck", patrolOffset: 2, x: 18, z: -30 },
      { id: "checkpointSentry", role: "sentry", x: 43, z: 9, facing: -2.6 },
      { id: "curfewLeader", role: "leader", patrol: "eastCurfew", patrolOffset: 1, x: 43, z: 8 },
      { id: "plainclothesWatcher", role: "sentry", x: -11, z: 29, facing: -2.9 },
    ],
    civilianRoutes: [
      {
        id: "eastHouseholds",
        name: "东巷两户",
        groupSize: 5,
        scheduleSeconds: null,
        startsByFlag: "eastHouseholdsMoving",
        behavior: "followSafeWindows",
        points: [
          { x: 30, z: 22 },
          { x: 37, z: 31 },
          { x: 46, z: 38 },
          { x: 56, z: 37 },
        ],
        note: "开闸后的水声可降低被听见概率；东渠出口必须先解锁。",
      },
      {
        id: "westHouseholds",
        name: "西巷三户",
        groupSize: 7,
        scheduleSeconds: null,
        startsByFlag: "westHouseholdsMoving",
        behavior: "waitAtCover",
        points: [
          { x: -25, z: 22 },
          { x: -31, z: 5 },
          { x: -42, z: -14 },
          { x: -55, z: -35 },
        ],
        note: "熄灯后沿墙阴影移动；若打谷场被封锁，会停在麦秸垛后等待。",
      },
    ],
    civilianRouteObjectives: [
      {
        objectiveId: "escortHouseholds",
        routeIds: ["eastHouseholds", "westHouseholds"],
      },
    ],
    reinforcementRoutes: [
      {
        id: "eastCheckpointSection",
        mode: "foot",
        arrivalSeconds: 150,
        disabledByFlag: "warningGongDisabled",
        entry: { x: 61, z: 7 },
      },
      {
        id: "northSearchPair",
        mode: "foot",
        arrivalSeconds: 260,
        enabledByFlag: "curfewTightened",
        entry: { x: -12, z: 53 },
      },
    ],
    environmentInteractions: [
      {
        id: "verifyContactLiu",
        interactableId: "contactLiu",
        allowedRoles: ["qinSuqiu", "luLanzhi"],
        duration: 4,
        requirements: {},
        effects: {
          setFlags: ["contactVerified", "westHouseholdsMoving"],
          startCivilianRoutes: ["westHouseholds"],
          revealIntel: ["eastCurfew", "templeCheck", "contactWindowCode"],
          emitEvents: ["contactRecognized", "westHouseholdsDepart"],
          completeObjectives: ["contactLiu"],
        },
        tradeoff: "联络员会加入撤离队列并提供夜间岗次；她受伤不会被叙事性免死。",
      },
      {
        id: "openIrrigationSluice",
        interactableId: "irrigationSluice",
        allowedRoles: ["hanShilei"],
        duration: 4.2,
        requirements: { allFlags: ["contactVerified"] },
        effects: {
          setFlags: ["sluiceOpened", "eastHouseholdsMoving"],
          addSoundMasks: ["creekBed", "eastVillageLane"],
          unlockExtractions: ["eastCanalExit"],
          startCivilianRoutes: ["eastHouseholds"],
          setPatrolRoutes: { eastOne: "sluiceInspection" },
          emitEvents: ["waterMasksFootsteps", "eastHouseholdsDepart"],
        },
        tradeoff: "东渠成为低声通道，但巡逻会离开东巷原路线检查木闸。",
      },
      {
        id: "disableVillageLamps",
        interactableId: "lampFuse",
        allowedRoles: ["hanShilei"],
        duration: 3,
        requirements: {},
        effects: {
          setFlags: ["villageLampsDisabled"],
          disableLighting: ["westStreetLamp", "templeGateLamp"],
          setPatrolRoutes: { curfewLeader: "darkLaneBlock" },
          blockRoutes: ["openThreshingCrossing"],
          emitEvents: ["westLaneDark", "threshingGroundBlocked"],
        },
        tradeoff: "西巷获得阴影，敌班长却会封锁打谷场，迫使队伍沿房后绕行。",
      },
      {
        id: "disableWarningGong",
        interactableId: "warningGong",
        allowedRoles: ["hanShilei", "qinSuqiu"],
        duration: 2.8,
        requirements: {},
        effects: {
          setFlags: ["warningGongDisabled"],
          disableReinforcements: ["eastCheckpointSection"],
          emitEvents: ["gongCannotSound"],
          completeObjectives: ["quietDeparture"],
        },
        tradeoff: "全村警报被延缓，但铜锣旁固定哨会在下一次巡检中发现锣槌不见。",
      },
      {
        id: "takeClinicSatchel",
        interactableId: "clinicSatchel",
        duration: 3,
        requirements: { allFlags: ["contactVerified"] },
        effects: {
          setFlags: ["clinicSatchelTaken"],
          startCarryItems: ["clinicSatchel"],
          emitEvents: ["medicineCarrierMarked"],
        },
        tradeoff: "药箱只在携带者撤出后计入行动完成；不能在战场即时转化为无限治疗。",
      },
      {
        id: "returnDraftMule",
        interactableId: "draftMule",
        duration: 3.4,
        requirements: {},
        effects: {
          setFlags: ["draftMuleReturned"],
          emitEvents: ["draftAnimalReturned"],
          completeObjectives: ["returnDraftAnimal"],
        },
        tradeoff: "归还牲口不会增加营地物资，只在叙事和群众代价记录中确认责任已履行。",
      },
    ],
    scheduledEvents: [
      { atSeconds: 210, unlessFlag: "contactVerified", event: "contactChangesWindowSignal" },
      { atSeconds: 360, setFlags: ["curfewTightened"], event: "curfewTightens" },
      { atSeconds: 510, unlessFlag: "warningGongDisabled", event: "checkpointTestsWarningGong" },
    ],
    narrativeRefs: {
      briefing: "rendezvousBriefing",
      field: ["rendezvousPassword", "rendezvousMedicine", "rendezvousDeparture"],
      debrief: "rendezvousDebrief",
    },
  },
  {
    id: "quarryInterdiction",
    operationId: "quarryInterdiction",
    name: "采石坡封路",
    chapter: "第三行动",
    date: "1941年10月28日",
    timeOfDay: "午后",
    weather: "干冷，大风扬尘",
    location: "太行山前虚构综合县域 · 采石坡",
    layoutFamily: "terracedQuarryRoad",
    gameplayIdentity:
      "立体破袭关：山脊、采坑和盘山路形成三层火力与声场。落石不是按键即胜，必须先辨认工棚、疏散被强征的民工，再选择落石、矿车或断线组合阻滞车队。",
    summary: "在不伤及被强征民工的前提下，切断电话、阻断盘山路并撤离采石坡。",
    historicalBoundary: commonHistoricalBoundary,
    costLedgerPolicy: commonCostLedgerPolicy,
    bounds: { minimumX: -72, maximumX: 70, minimumZ: -50, maximumZ: 51 },
    camera: {
      position: { x: -76, y: 72, z: -62 },
      target: { x: 5, y: 1, z: 0 },
    },
    playerSpawns: [
      { x: -61, z: 36 },
      { x: -65, z: 33 },
      { x: -59, z: 32 },
      { x: -64, z: 29 },
    ],
    objectives: {
      mandatory: [
        { id: "cutQuarryTelephone", label: "切断采石坡电话线", carryToExtract: false },
        { id: "blockMountainRoad", label: "阻断东侧盘山路", carryToExtract: false },
        { id: "allExtracted", label: "小队撤出采石坡", carryToExtract: false },
      ],
      optional: [
        { id: "evacuateQuarryWorkers", label: "先疏散被强征民工", nonRewardingDuty: true },
        { id: "militaryDetonators", label: "取走军用雷管", carryToExtract: true },
        { id: "leaveVillageTools", label: "不取用民工自带工具", nonRewardingDuty: true },
      ],
      failForward: "落石造成群众受害不会被判定为优秀完成；雷管遗失不妨碍封路，但不可计入营地物资。",
    },
    tacticalPhases: [
      {
        id: "readVerticalSpace",
        label: "辨认三层地形",
        trigger: "missionStart",
        decision: "上层山脊视野远但暴露，中层盘山路巡逻密，下层采坑声响大且有民工。",
      },
      {
        id: "separateWorkers",
        label: "分离群众与目标",
        trigger: "enterZone:quarryFloor",
        decision: "接触石匠范伯并敲响约定的两短一长木梆，或等待收工换班后行动。",
      },
      {
        id: "chooseInterdiction",
        label: "选择破袭链",
        trigger: "objective:evacuateQuarryWorkers",
        decision: "落石封锁最久但声响最大；放矿车较快但只封一段；两者组合会切断敌方追击路线。",
      },
      {
        id: "escapeDustAndSweep",
        label: "借尘撤离",
        trigger: "objective:blockMountainRoad",
        decision: "尘幕遮蔽短暂存在，电话若未先切断，南哨增援会从另一条山路夹击。",
      },
    ],
    extractionZones: [
      { id: "northRidgeExit", name: "北脊羊道", x: -58, z: 43, radius: 7, unlocked: true },
      { id: "westGullyExit", name: "西侧泄洪沟", x: -67, z: -27, radius: 7, unlocked: true },
      { id: "eastDustExit", name: "东坡尘幕口", x: 62, z: -36, radius: 7, unlocked: false },
    ],
    zones: [
      { id: "northRidge", kind: "rock", x: -23, z: 39, width: 74, depth: 12, visibility: 1.24, sound: 1.14, elevation: 8 },
      { id: "upperTerrace", kind: "rock", x: 13, z: 18, width: 76, depth: 16, visibility: 1.15, sound: 1.12, elevation: 5 },
      { id: "mountainRoad", kind: "road", x: 20, z: -5, width: 86, depth: 10, visibility: 1.2, sound: 1.08, elevation: 2 },
      { id: "quarryFloor", kind: "ditch", x: -2, z: -27, width: 54, depth: 27, visibility: 0.78, sound: 0.52, elevation: -3 },
      { id: "workerSheds", kind: "civilian", x: -40, z: -20, width: 22, depth: 18, visibility: 0.96, sound: 0.9 },
      { id: "blastFace", kind: "rock", x: 44, z: 20, width: 23, depth: 27, visibility: 1.1, sound: 1.18, elevation: 7 },
    ],
    lightingZones: [
      { id: "quarrySun", kind: "box", x: 7, z: 1, width: 116, depth: 82, generatorDependent: false },
      { id: "powderShedShade", kind: "box", x: 27, z: -25, width: 15, depth: 10, generatorDependent: false, visibilityMultiplier: 0.72 },
    ],
    obstacles: [
      { id: "foremanOffice", kind: "building", impactMaterial: "wood", x: 14, z: 12, width: 13, depth: 8, height: 4.2, color: 0x5f4d39 },
      { id: "powderShed", kind: "building", impactMaterial: "stone", x: 28, z: -25, width: 13, depth: 9, height: 4.5, color: 0x615749 },
      { id: "workerShedOne", kind: "building", impactMaterial: "wood", x: -44, z: -18, width: 12, depth: 7, height: 3.8, color: 0x66513a },
      { id: "workerShedTwo", kind: "building", impactMaterial: "wood", x: -31, z: -24, width: 11, depth: 7, height: 3.8, color: 0x66513a },
      { id: "upperBlockhouse", kind: "building", impactMaterial: "stone", x: 6, z: 35, width: 12, depth: 9, height: 5, color: 0x5e574b },
      { id: "roadCheckpoint", kind: "wall", impactMaterial: "stone", x: 47, z: -4, width: 2, depth: 17, height: 2, color: 0x6b6252 },
      { id: "lowerRetainingWall", kind: "wall", impactMaterial: "stone", x: -6, z: -12, width: 48, depth: 1.5, height: 2.8, color: 0x6b6252 },
      { id: "upperRetainingWall", kind: "wall", impactMaterial: "stone", x: 18, z: 26, width: 54, depth: 1.5, height: 2.8, color: 0x6b6252 },
      { id: "oreCartOne", kind: "wagon", impactMaterial: "metal", x: 1, z: -5, width: 6, depth: 3.3, height: 2.3, color: 0x4b4840 },
      { id: "oreCartTwo", kind: "wagon", impactMaterial: "metal", x: 9, z: -5, width: 6, depth: 3.3, height: 2.3, color: 0x4b4840 },
      { id: "stoneCrib", kind: "crate", impactMaterial: "wood", x: 42, z: 17, width: 8, depth: 6, height: 4, color: 0x514636 },
    ],
    interactables: [
      {
        id: "quarryTelephone",
        kind: "objective",
        name: "采石坡电话接线柱",
        x: 7,
        z: 33,
        radius: 3,
        duration: 4,
        action: "sabotage",
        description: "剪断通往南哨和车队的支线；守军随后只能派人沿上层山道传令。",
      },
      {
        id: "workerForeman",
        kind: "civilian",
        name: "石匠范伯",
        x: -37,
        z: -20,
        radius: 3,
        duration: 4.5,
        action: "coordinateEvacuation",
        description: "用工地木梆组织民工分批离开采坑；疏散是落石前的安全条件。",
      },
      {
        id: "rockfallTimber",
        kind: "environment",
        name: "落石木撑",
        x: 45,
        z: 23,
        radius: 3.2,
        duration: 5,
        action: "trigger",
        description: "拆除木撑引发定向落石，封闭东路并形成短时尘幕；未疏散时会危及民工。",
      },
      {
        id: "oreCartBrake",
        kind: "environment",
        name: "矿车制动楔",
        x: 3,
        z: -4,
        radius: 3,
        duration: 3.6,
        action: "release",
        description: "放下两辆矿车撞入盘山路，封住中段并制造沿轨传播的大声响。",
      },
      {
        id: "militaryDetonators",
        kind: "supply",
        name: "军用雷管盒",
        x: 27,
        z: -24,
        radius: 2.5,
        duration: 3,
        action: "collect",
        description: "敌军火药棚内的制式雷管，可补充工兵破袭物资；必须带出。",
      },
      {
        id: "workerTools",
        kind: "civilian",
        name: "民工自带石匠工具",
        x: -31,
        z: -20,
        radius: 2.8,
        duration: 2,
        action: "inspectOnly",
        description: "这些工具归民工所有，不可搜集为营地资源。",
      },
    ],
    patrols: [
      {
        id: "ridgePatrol",
        points: [
          { x: -45, z: 38 },
          { x: -8, z: 36 },
          { x: 22, z: 31 },
          { x: 49, z: 35 },
        ],
      },
      {
        id: "roadPatrol",
        points: [
          { x: -38, z: -4 },
          { x: -8, z: -5 },
          { x: 21, z: -4 },
          { x: 47, z: -3 },
        ],
      },
      {
        id: "floorPatrol",
        points: [
          { x: -25, z: -18 },
          { x: 5, z: -17 },
          { x: 23, z: -28 },
          { x: -5, z: -37 },
        ],
      },
      {
        id: "telephoneRunner",
        activeWhen: "flag:quarryTelephoneCut",
        points: [
          { x: 7, z: 33 },
          { x: -7, z: 39 },
          { x: -33, z: 43 },
          { x: -65, z: 48 },
        ],
      },
      {
        id: "dustSearch",
        activeWhen: "flag:mountainRoadBlocked",
        points: [
          { x: 48, z: -4 },
          { x: 32, z: 8 },
          { x: 17, z: 19 },
          { x: 2, z: 4 },
        ],
      },
    ],
    enemies: [
      { id: "ridgeOne", role: "patrol", patrol: "ridgePatrol", patrolOffset: 0, x: -45, z: 38 },
      { id: "ridgeTwo", role: "patrol", patrol: "ridgePatrol", patrolOffset: 2, x: 22, z: 31 },
      { id: "roadOne", role: "patrol", patrol: "roadPatrol", patrolOffset: 0, x: -38, z: -4 },
      { id: "roadTwo", role: "patrol", patrol: "roadPatrol", patrolOffset: 2, x: 21, z: -4 },
      { id: "floorOne", role: "patrol", patrol: "floorPatrol", patrolOffset: 0, x: -25, z: -18 },
      { id: "floorTwo", role: "patrol", patrol: "floorPatrol", patrolOffset: 2, x: 23, z: -28 },
      { id: "roadSentry", role: "sentry", x: 47, z: -4, facing: -2.9 },
      { id: "blockhouseSentry", role: "sentry", x: 6, z: 35, facing: -2.3, elevated: true },
      { id: "quarryLeader", role: "leader", patrol: "roadPatrol", patrolOffset: 1, x: -8, z: -5 },
    ],
    civilianRoutes: [
      {
        id: "quarryWorkersToGully",
        name: "民工撤离采坑",
        groupSize: 11,
        scheduleSeconds: null,
        startsByFlag: "quarryWorkersEvacuating",
        behavior: "stagedEvacuation",
        points: [
          { x: -8, z: -29 },
          { x: -29, z: -31 },
          { x: -48, z: -28 },
          { x: -67, z: -27 },
        ],
        note: "民工分三组撤离；最后一组离开危险半径后才会设置quarryWorkersClear。",
      },
      {
        id: "roadPorters",
        name: "挑夫过路",
        groupSize: 3,
        scheduleSeconds: 280,
        behavior: "leaveRoadOnAlarm",
        points: [
          { x: 63, z: -7 },
          { x: 39, z: -5 },
          { x: 11, z: -5 },
          { x: -20, z: -4 },
        ],
        note: "若落石前未让挑夫离开道路，行动会记录群众风险；敌军伤亡不能抵扣。",
      },
    ],
    civilianRouteObjectives: [
      {
        objectiveId: "evacuateQuarryWorkers",
        routeIds: ["quarryWorkersToGully"],
      },
    ],
    reinforcementRoutes: [
      {
        id: "southRoadTruck",
        mode: "vehicle",
        arrivalSeconds: 95,
        disabledByFlag: "quarryTelephoneCut",
        entry: { x: 68, z: -5 },
      },
      {
        id: "ridgeRunnerResponse",
        mode: "foot",
        arrivalSeconds: 220,
        enabledByFlag: "quarryTelephoneCut",
        entry: { x: -69, z: 47 },
      },
    ],
    environmentInteractions: [
      {
        id: "cutQuarryTelephone",
        interactableId: "quarryTelephone",
        allowedRoles: ["hanShilei"],
        duration: 4,
        requirements: {},
        effects: {
          setFlags: ["quarryTelephoneCut"],
          disableReinforcements: ["southRoadTruck"],
          enableReinforcements: ["ridgeRunnerResponse"],
          delayReinforcements: 125,
          setPatrolRoutes: { blockhouseSentry: "telephoneRunner" },
          emitEvents: ["quarryLineCut", "ridgeRunnerDispatched"],
          completeObjectives: ["cutQuarryTelephone"],
        },
        tradeoff: "车辆增援失去电话引导，但岗楼会派传令兵走北脊，改变安全撤离窗口。",
      },
      {
        id: "coordinateWorkerEvacuation",
        interactableId: "workerForeman",
        allowedRoles: ["luLanzhi", "qinSuqiu"],
        duration: 4.5,
        requirements: {},
        effects: {
          setFlags: ["quarryWorkersEvacuating"],
          startCivilianRoutes: ["quarryWorkersToGully"],
          emitEvents: ["workerClapperSignal", "workersLeaveInGroups"],
        },
        deferredEffects: {
          whenRouteComplete: "quarryWorkersToGully",
          setFlags: ["quarryWorkersClear"],
          emitEvents: ["blastAreaClear"],
          completeObjectives: ["evacuateQuarryWorkers"],
        },
        tradeoff: "疏散需要时间并会被下层巡逻看见；这是落石安全门，不提供物资奖励。",
      },
      {
        id: "triggerSafeRockfall",
        interactableId: "rockfallTimber",
        allowedRoles: ["hanShilei"],
        duration: 5,
        requirements: { allFlags: ["quarryWorkersClear"] },
        effects: {
          setFlags: ["mountainRoadBlocked", "rockfallTriggeredSafely"],
          blockRoutes: ["eastMountainRoad", "roadPatrolEastArc"],
          unlockExtractions: ["eastDustExit"],
          addConcealmentZones: ["rockfallDust"],
          setPatrolRoutes: { roadOne: "dustSearch" },
          emitEvents: ["controlledRockfall", "dustCloudRaised"],
          completeObjectives: ["blockMountainRoad"],
        },
        tradeoff: "封路持续时间最长并提供短暂尘幕，但巨响使全区进入警戒。",
      },
      {
        id: "triggerUnsafeRockfall",
        interactableId: "rockfallTimber",
        allowedRoles: ["hanShilei"],
        duration: 5,
        requirements: { noneFlags: ["quarryWorkersClear"] },
        effects: {
          setFlags: ["mountainRoadBlocked", "rockfallTriggeredBeforeClear"],
          blockRoutes: ["eastMountainRoad", "roadPatrolEastArc"],
          addConcealmentZones: ["rockfallDust"],
          emitEvents: ["uncontrolledRockfall", "workersCaughtInDangerArea"],
          completeObjectives: ["blockMountainRoad"],
          addCivilianCosts: { risk: 5, harm: 1, displacement: 0 },
        },
        tradeoff: "道路同样被封，但会造成不可抵扣的群众受害，最高评价永久封顶。",
      },
      {
        id: "releaseOreCarts",
        interactableId: "oreCartBrake",
        allowedRoles: ["hanShilei"],
        duration: 3.6,
        requirements: {},
        effects: {
          setFlags: ["oreCartsReleased", "mountainRoadBlocked"],
          blockRoutes: ["centralMountainRoad"],
          addSoundMasks: ["quarryFloor"],
          setPatrolRoutes: { floorOne: "dustSearch" },
          emitEvents: ["oreCartsCrash", "guardsInspectTrack"],
          completeObjectives: ["blockMountainRoad"],
        },
        tradeoff: "矿车迅速封住中段并掩盖脚步，但东端仍可通行，敌人会从上下两层绕路。",
      },
      {
        id: "recoverMilitaryDetonators",
        interactableId: "militaryDetonators",
        duration: 3,
        requirements: {},
        effects: {
          setFlags: ["militaryDetonatorsCarried"],
          startCarryItems: ["militaryDetonators"],
          emitEvents: ["detonatorCarrierMarked"],
        },
        tradeoff: "雷管属于敌军军用物资，只有携带者撤出后才能进入工坊库存。",
      },
      {
        id: "inspectWorkerTools",
        interactableId: "workerTools",
        duration: 2,
        requirements: {},
        effects: {
          setFlags: ["workerToolsLeftInPlace"],
          emitEvents: ["civilianPropertyRespected"],
          completeObjectives: ["leaveVillageTools"],
        },
        tradeoff: "查看会明确标记所有权；工具不可拾取，不产生任何资源。",
      },
    ],
    scheduledEvents: [
      { atSeconds: 240, event: "roadPortersEnter" },
      { atSeconds: 360, unlessFlag: "quarryWorkersEvacuating", event: "workerShiftMovesTowardBlastFace" },
      { atSeconds: 480, unlessFlag: "mountainRoadBlocked", event: "supplyTruckCrossesQuarry" },
    ],
    narrativeRefs: {
      briefing: "quarryBriefing",
      field: ["quarryWorkerMeeting", "quarrySafetyChoice", "quarryRoadBlocked"],
      debrief: "quarryDebrief",
    },
  },
]);

export function GetOperationLayout(operationId) {
  return (
    operationLayoutDefinitions.find(
      (operation) => operation.id === operationId || operation.operationId === operationId,
    ) ?? null
  );
}

export function GetOperationLayoutByCampaignIndex(completedMissions = 0) {
  const index = Math.max(0, Math.trunc(Number(completedMissions) || 0)) % operationLayoutDefinitions.length;
  return operationLayoutDefinitions[index];
}

export function GetOperationInteraction(operationId, interactionId) {
  return (
    GetOperationLayout(operationId)?.environmentInteractions.find(
      (interaction) => interaction.id === interactionId,
    ) ?? null
  );
}

export function GetOperationPatrol(operationId, patrolId) {
  return GetOperationLayout(operationId)?.patrols.find((patrol) => patrol.id === patrolId) ?? null;
}
