export const missionDefinition = Object.freeze({
  id: "locustRavineCutline",
  title: "山火 · 一九四一",
  operation: "槐树峪断线",
  date: "1941 年 10 月 · 黎明前",
  location: "太行山前虚构综合县域",
  summary: "取回换防传令簿与电话线路图，剪断据点有线联络，带队撤离。",
  historicalBoundary:
    "本关地点、人物与行动均为原创综合化设定，不对应某次具体战斗。侵略暴行按史实背景克制呈现；1945 年日本投降的历史结局不可改写。",
  bounds: Object.freeze({ minimumX: -54, maximumX: 58, minimumZ: -40, maximumZ: 43 }),
  playerSpawns: Object.freeze([
    Object.freeze({ x: -45, z: -31 }),
    Object.freeze({ x: -47, z: -29 }),
    Object.freeze({ x: -43, z: -28 }),
    Object.freeze({ x: -48, z: -26 }),
  ]),
  camera: Object.freeze({
    position: Object.freeze({ x: -58, y: 46, z: -53 }),
    target: Object.freeze({ x: 12, y: 0, z: 4 }),
  }),
  extractionZones: Object.freeze([
    Object.freeze({ id: "ridge", name: "西南观察岭", x: -48, z: -34, radius: 6, unlocked: true }),
    Object.freeze({ id: "reeds", name: "北侧芦苇渡口", x: -22, z: 38, radius: 6, unlocked: false }),
    Object.freeze({ id: "quarry", name: "东南采石山路", x: 52, z: -32, radius: 6, unlocked: true }),
  ]),
  zones: Object.freeze([
    Object.freeze({ id: "sorghum", kind: "foliage", x: -28, z: -19, width: 30, depth: 19, visibility: 0.44, sound: 0.78 }),
    Object.freeze({ id: "reeds", kind: "foliage", x: -17, z: 31, width: 26, depth: 18, visibility: 0.38, sound: 0.7 }),
    Object.freeze({ id: "ditch", kind: "ditch", x: -19, z: -3, width: 7, depth: 54, visibility: 0.58, sound: 0.68 }),
    Object.freeze({ id: "yard", kind: "open", x: 28, z: 8, width: 33, depth: 29, visibility: 1.12, sound: 1 }),
  ]),
  lightingZones: Object.freeze([
    Object.freeze({ id: "yardSearchlight", kind: "circle", x: 25, z: 7, radius: 16, generatorDependent: true }),
    Object.freeze({ id: "northWallLamp", kind: "circle", x: 19, z: 19, radius: 10, generatorDependent: true }),
    Object.freeze({ id: "barracksLantern", kind: "box", x: 43, z: 15, width: 11, depth: 7, generatorDependent: false }),
  ]),
  obstacles: Object.freeze([
    Object.freeze({ id: "relayHouse", kind: "building", impactMaterial: "earth", x: 27, z: 8, width: 12, depth: 9, height: 5.2, color: 0x6b5842 }),
    Object.freeze({ id: "barracks", kind: "building", impactMaterial: "earth", x: 43, z: 16, width: 14, depth: 8, height: 4.8, color: 0x5d5040 }),
    Object.freeze({ id: "cowshed", kind: "building", impactMaterial: "wood", x: -3, z: 29, width: 12, depth: 7, height: 3.8, color: 0x65543f }),
    Object.freeze({ id: "farmhouseWest", kind: "building", impactMaterial: "earth", x: -19, z: 23, width: 11, depth: 9, height: 4.2, color: 0x705b43 }),
    Object.freeze({ id: "farmhouseNorth", kind: "building", impactMaterial: "earth", x: 12, z: 31, width: 13, depth: 8, height: 4.6, color: 0x6a543c }),
    Object.freeze({ id: "watchTower", kind: "tower", impactMaterial: "wood", x: 19, z: 19, width: 4, depth: 4, height: 8, color: 0x51483b }),
    Object.freeze({ id: "bridgeWest", kind: "wall", impactMaterial: "stone", x: -1, z: -3, width: 16, depth: 2, height: 1.3, color: 0x6f6654 }),
    Object.freeze({ id: "yardWallSouth", kind: "wall", impactMaterial: "stone", x: 29, z: -7, width: 34, depth: 1.2, height: 2.2, color: 0x6d624f }),
    Object.freeze({ id: "yardWallEast", kind: "wall", impactMaterial: "stone", x: 46, z: 7, width: 1.2, depth: 29, height: 2.2, color: 0x6d624f }),
    Object.freeze({ id: "yardWallNorth", kind: "wall", impactMaterial: "stone", x: 34, z: 22, width: 24, depth: 1.2, height: 2.2, color: 0x6d624f }),
    Object.freeze({ id: "villageWall", kind: "wall", impactMaterial: "stone", x: -4, z: 19, width: 29, depth: 1.1, height: 1.8, color: 0x766b56 }),
    Object.freeze({ id: "stoneWallSouth", kind: "wall", impactMaterial: "stone", x: -31, z: -11, width: 22, depth: 1.1, height: 1.6, color: 0x766f60 }),
    Object.freeze({ id: "stoneWallWest", kind: "wall", impactMaterial: "stone", x: -39, z: 4, width: 1.2, depth: 20, height: 1.7, color: 0x766f60 }),
    Object.freeze({ id: "crateStack", kind: "crate", impactMaterial: "wood", x: 37, z: 4, width: 5, depth: 3, height: 2, color: 0x5a4934 }),
    Object.freeze({ id: "wagon", kind: "wagon", impactMaterial: "wood", x: 37, z: -13, width: 7, depth: 3.2, height: 2.5, color: 0x59442e }),
  ]),
  interactables: Object.freeze([
    Object.freeze({
      id: "relay",
      kind: "objective",
      name: "手摇电话交换机",
      x: 27,
      z: 4,
      radius: 3.2,
      duration: 6,
      action: "sabotage",
      description: "剪断进出线并拆去接线塞绳，使附近据点只能派人传令。",
    }),
    Object.freeze({
      id: "ledger",
      kind: "objective",
      name: "换防传令簿与线路图",
      x: 24,
      z: 2.8,
      radius: 3,
      duration: 3.6,
      action: "collect",
      description: "记录哨位换班、电话支线和汽车队通过时刻；情报会随时间失效。",
    }),
    Object.freeze({
      id: "medicines",
      kind: "supply",
      name: "被征用的医药箱",
      x: 39,
      z: -13,
      radius: 3.4,
      duration: 2.8,
      action: "collect",
      description: "归还救护站，可供营地处理伤势。",
    }),
    Object.freeze({
      id: "radioParts",
      kind: "supply",
      name: "无线电零件",
      x: 34.5,
      z: 1.4,
      radius: 2.5,
      duration: 3,
      action: "collect",
      description: "可修复营地的收报机。",
    }),
    Object.freeze({
      id: "tools",
      kind: "supply",
      name: "工具卷",
      x: 43,
      z: -8,
      radius: 2.5,
      duration: 2.6,
      action: "collect",
      description: "补充工坊工具，不从民居征取。",
    }),
    Object.freeze({
      id: "detainee",
      kind: "rescue",
      name: "被扣押的交通员",
      x: -4,
      z: 23,
      radius: 3,
      duration: 4.5,
      action: "rescue",
      description: "解开绑绳，护送至村北安全院。",
    }),
    Object.freeze({
      id: "generator",
      kind: "environment",
      name: "探照灯发电机",
      x: 18,
      z: 16,
      radius: 3,
      duration: 3.5,
      action: "sabotage",
      description: "关闭后降低北墙照明，但会引来检查。",
    }),
    Object.freeze({
      id: "alarmBell",
      kind: "environment",
      name: "警报铃索",
      x: 14,
      z: -5,
      radius: 2.8,
      duration: 2.8,
      action: "sabotage",
      description: "剪断院内警报链，延缓集结。",
    }),
    Object.freeze({
      id: "rockfall",
      kind: "environment",
      name: "采石坡木楔",
      x: 51,
      z: -22,
      radius: 3.2,
      duration: 4.5,
      action: "trigger",
      description: "封住东公路，制造尘幕与巨大声响。",
    }),
    Object.freeze({
      id: "seedGrain",
      kind: "civilian",
      name: "被扣的种粮",
      x: 33.5,
      z: 21,
      radius: 3,
      duration: 3.2,
      action: "return",
      description: "只能归还村民，不转化为营地物资。",
    }),
  ]),
  patrols: Object.freeze([
    Object.freeze({
      id: "outerPatrol",
      points: Object.freeze([
        Object.freeze({ x: -32, z: -20 }),
        Object.freeze({ x: -20, z: -14 }),
        Object.freeze({ x: -15, z: -25 }),
      ]),
    }),
    Object.freeze({
      id: "bridgePatrol",
      points: Object.freeze([
        Object.freeze({ x: -12, z: -7 }),
        Object.freeze({ x: 2, z: -3 }),
        Object.freeze({ x: 13, z: 1 }),
        Object.freeze({ x: 8, z: 10 }),
        Object.freeze({ x: -4, z: 7 }),
      ]),
    }),
    Object.freeze({
      id: "yardPatrol",
      points: Object.freeze([
        Object.freeze({ x: 16, z: -4 }),
        Object.freeze({ x: 42, z: -4 }),
        Object.freeze({ x: 42, z: 12 }),
        Object.freeze({ x: 21, z: 18 }),
      ]),
    }),
    Object.freeze({
      id: "villagePatrol",
      points: Object.freeze([
        Object.freeze({ x: 16, z: 24 }),
        Object.freeze({ x: 2, z: 32 }),
        Object.freeze({ x: -18, z: 33 }),
        Object.freeze({ x: -25, z: 22 }),
      ]),
    }),
    Object.freeze({
      id: "leaderCircuit",
      points: Object.freeze([
        Object.freeze({ x: 28, z: 4 }),
        Object.freeze({ x: 14, z: -2 }),
        Object.freeze({ x: 39, z: -12 }),
        Object.freeze({ x: 20, z: 18 }),
      ]),
    }),
  ]),
  enemies: Object.freeze([
    Object.freeze({ id: "outerOne", role: "patrol", patrol: "outerPatrol", patrolOffset: 0, x: -32, z: -20 }),
    Object.freeze({ id: "bridgeOne", role: "patrol", patrol: "bridgePatrol", patrolOffset: 0, x: -12, z: -7 }),
    Object.freeze({ id: "bridgeTwo", role: "patrol", patrol: "bridgePatrol", patrolOffset: 2, x: 13, z: 1 }),
    Object.freeze({ id: "gateSentry", role: "sentry", x: 13, z: -4, facing: -2.4 }),
    Object.freeze({ id: "towerSentry", role: "sentry", x: 19, z: 19, facing: -2.2, elevated: true }),
    Object.freeze({ id: "yardOne", role: "patrol", patrol: "yardPatrol", patrolOffset: 0, x: 16, z: -4 }),
    Object.freeze({ id: "yardTwo", role: "patrol", patrol: "yardPatrol", patrolOffset: 2, x: 42, z: 12 }),
    Object.freeze({ id: "villageOne", role: "patrol", patrol: "villagePatrol", patrolOffset: 0, x: 16, z: 24 }),
    Object.freeze({ id: "villageTwo", role: "patrol", patrol: "villagePatrol", patrolOffset: 2, x: -18, z: 33 }),
    Object.freeze({ id: "operator", role: "operator", x: 29, z: 5, facing: Math.PI }),
    Object.freeze({ id: "barracksGuard", role: "sentry", x: 43, z: 20, facing: -1.8 }),
    Object.freeze({ id: "leader", role: "leader", patrol: "leaderCircuit", patrolOffset: 0, x: 28, z: 4 }),
  ]),
});

export const campaignOperationDefinitions = Object.freeze([
  Object.freeze({
    id: "cutline",
    name: "槐树峪断线",
    dateOffsetDays: 0,
    mainObjectiveIds: Object.freeze(["ledger", "relay"]),
    summary: "取回换防传令簿与线路图，剪断据点有线联络，带队撤离。",
    resultTitle: "线路已断，小队撤出",
    resultSummary: "有线联络已经切断，换防情报安全带回。",
    campOutcomeTitle: "情报带回，线路暂歇",
  }),
  Object.freeze({
    id: "northVillageRelief",
    name: "北村接应",
    dateOffsetDays: 5,
    mainObjectiveIds: Object.freeze(["detainee", "medicines", "generator"]),
    summary: "关闭北墙探照灯，救出被扣交通员并取回救护药箱，护送行动组撤出。",
    resultTitle: "交通员接回，药箱入手",
    resultSummary: "北墙探照灯已经熄灭，交通员与救护物资安全撤出。",
    campOutcomeTitle: "人已接回，伤员有药",
  }),
  Object.freeze({
    id: "quarryInterdiction",
    name: "采石坡封路",
    dateOffsetDays: 11,
    mainObjectiveIds: Object.freeze(["rockfall", "radioParts", "alarmBell"]),
    summary: "剪断警报铃索，取回通信零件并引发采石坡落石，阻滞东公路增援。",
    resultTitle: "落石封路，小队撤出",
    resultSummary: "警报铃索已经剪断，通信零件与落石破袭成果安全带回。",
    campOutcomeTitle: "公路受阻，增援迟滞",
  }),
]);

export function GetPatrol(patrolId) {
  return missionDefinition.patrols.find((patrol) => patrol.id === patrolId) ?? null;
}

export function GetInteractable(interactableId) {
  return missionDefinition.interactables.find((interactable) => interactable.id === interactableId) ?? null;
}
