// 序 · 那天 —— 过场分镜表（第八稿，对齐 Script_Core.mjs c1_thatday / c1_descend / c1_hide / c1_open 收尾）
// 画风锚：用户提供的两张剪纸横版参考（地表井台 / 地窖剖面）

export const BoardMeta = Object.freeze({
  title: "序 · 那天",
  chapter: "第一章 · 蓝底白花",
  source: "Notion 第八稿（代码落地版）",
  aspect: "16:9",
  style: "handmade paper-cut / parchment grain / 2D side-scroll",
});

export const Shots = Object.freeze([
  {
    id: "00",
    file: "Texture_PrologueShot00_BlackDin.jpg",
    beat: "c1_thatday",
    dur: "3.4+2.6",
    cam: "dark",
    picture: "全黑。村外狗先叫，远处一枪。听得懂的只有那一句喊。",
    line: "伪军：「出来！都出来！」",
    audio: "din 由远及近；gunshot；shout",
  },
  {
    id: "01",
    file: "Texture_PrologueShot01_DoorTremble.jpg",
    beat: "c1_thatday",
    dur: "4.0",
    cam: "free 后拉 · 屋里",
    picture: "画面从黑暗里显出来。柱子立在屋当间，妹妹缩在炕沿下捂耳朵。门闩没有插——外面每一声撞击，门板就轻轻震一下。",
    line: "",
    audio: "doorCreak ×2",
  },
  {
    id: "02",
    file: "Texture_PrologueShot02_MotherBurst.jpg",
    beat: "c1_thatday",
    dur: "4.6",
    cam: "free 低机位追人",
    picture: "一阵急促脚步冲进院子。门板猛地向里打开，撞在墙上——娘冲进来。蓝底白花的短褂被树枝扯开一道口，袖口沾着土。不切衣裳特写。",
    line: "",
    audio: "doorCreak + knock；din 灌满",
  },
  {
    id: "03",
    file: "Texture_PrologueShot03_PullClose.jpg",
    beat: "c1_thatday",
    dur: "5.2",
    cam: "free 缓推到怀抱",
    picture: "院外又响一枪。娘猛地回头，把门推回去，却没顾上关严——转身冲到妹妹面前，一把将她拉进怀里，上下摸了一遍。",
    line: "",
    audio: "gunshot；doorCreak；clothLift",
  },
  {
    id: "04",
    file: "Texture_PrologueShot04_CallZhuozi.jpg",
    beat: "c1_thatday",
    dur: "1.8+2.0",
    cam: "free 正反打",
    picture: "娘抬头找柱子。气还没有喘匀。柱子完整站在画框右侧接这句话。",
    line: "娘：「柱子。」 / 「抱她。」",
    audio: "",
  },
  {
    id: "05",
    file: "Texture_PrologueShot05_HatchSlip.jpg",
    beat: "c1_thatday",
    dur: "5.4",
    cam: "free 俯角窖口",
    picture: "娘去拉菜窖翻板。手指第一次从铁环上滑开。她在衣襟上蹭了一把汗，第二次攥住铁环，将翻板猛地掀开。",
    line: "",
    audio: "crank（滑开）；clothLift（蹭汗）；vault + drop（掀开）",
  },
  {
    id: "06",
    file: "Texture_PrologueShot06_HatchOpen.jpg",
    beat: "c1_thatday",
    dur: "2.2",
    cam: "free 仰角 · 孩子这头",
    picture: "贴着孩子那头的低机位仰看跪在窖口的娘。掀开的洞口黑在画框下沿。",
    line: "娘：「快。」",
    audio: "",
  },
  {
    id: "07",
    file: "Texture_PrologueShot07_ScoopSister.jpg",
    beat: "c1_descend",
    dur: "可玩",
    cam: "玩法机位",
    picture: "柱子蹲下去，把妹妹抱起来。她两条胳膊立刻搂住他的脖子。",
    line: "",
    audio: "clothLift",
  },
  {
    id: "08",
    file: "Texture_PrologueShot08_BlockDoor.jpg",
    beat: "c1_descend",
    dur: "1.8+1.6",
    cam: "shot → insert",
    picture: "玩家抱着她往屋门走：娘挡在门前，朝菜窖指。",
    line: "娘：「下去！」",
    audio: "",
  },
  {
    id: "09",
    file: "Texture_PrologueShot09_LowerLadder.jpg",
    beat: "c1_descend",
    dur: "3.4",
    cam: "shot 窖沿",
    picture: "柱子先坐到窖沿，把妹妹放上梯子。妹妹抓着他的衣襟不肯松手。",
    line: "",
    audio: "ladder；clothLift",
  },
  {
    id: "10",
    file: "Texture_PrologueShot10_CutawayDescend.jpg",
    beat: "c1_descend",
    dur: "可玩",
    cam: "剖面 · 上下同框",
    picture: "沿梯子下到窖底。上头娘掀着翻板守着；外头脚步已经到了院门口。",
    line: "",
    audio: "din 压在头顶",
  },
  {
    id: "11",
    file: "Texture_PrologueShot11_HatchSpeak.jpg",
    beat: "c1_descend",
    dur: "3.2+2.2+3.0",
    cam: "insert 仰看窖口",
    picture: "娘跪在窖口，一只手压着翻板。只探进半张脸。",
    line: "娘：「搂紧她。」 / 「不叫你们，别上来。」",
    audio: "step（院门口）",
  },
  {
    id: "12",
    file: "Texture_PrologueShot12_SleeveVanish.jpg",
    beat: "c1_descend",
    dur: "4.0",
    cam: "insert 同仰角 · 不切特写",
    picture: "翻板合上。最后消失在板缝里的，是她那截蓝底白花的袖子。三束天光收成缝。",
    line: "",
    audio: "doorCreak；drop（落到底）",
  },
  {
    id: "13",
    file: "Texture_PrologueShot13_HugDust.jpg",
    beat: "c1_hide",
    dur: "15 长按",
    cam: "窖底 · dark",
    picture: "长按搂紧。松手她的呼吸立刻变响，头顶的脚步就停住。靴子踩上翻板，灰从板缝落下来。",
    line: "",
    audio: "踹门→碗碎→拖箱→割粮袋→踩板→喊→离开",
  },
  {
    id: "14",
    file: "Texture_PrologueShot14_SlantLight.jpg",
    beat: "c1_hide → c1_open",
    dur: "4.2",
    cam: "shot 窖底",
    picture: "柱子仍然搂着妹妹。板缝里的光从直的变成斜的，又一点点暗下去。",
    line: "",
    audio: "din 退尽",
  },
  {
    id: "15",
    file: "Texture_PrologueShot15_CutawayAftermath.jpg",
    beat: "c1_open",
    dur: "2.8+3.6",
    cam: "dark + 章名卡",
    picture: "没人来叫。上下两层都空了。章名出现在序的末尾，不在开局。",
    line: "旁白：「没人来叫。」  章名卡：「第一章 · 蓝底白花」  「三天后。」",
    audio: "",
  },
]);
