function DeepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) DeepFreeze(child);
  return value;
}

// These sequences never alter historical outcomes or gameplay rewards. They
// only reframe state that the rules layer has already produced, keeping the
// story in the same continuous 3D space as play.
export const CinematicSequences = DeepFreeze({
  schoolOpening: {
    id: "schoolOpening",
    duration: 12.4,
    skippableAfter: 0.9,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 3.6,
        camera: { anchorX: 560, viewDistance: 44.5, lift: 6.5, lookLift: 1.84, targetZ: -9.4, fov: 27.8, trackX: 60, dolly: -1.8, crane: -0.3 },
        actors: { player: "listen", mother: "listen" },
        blocking: { playerX: [4.35, 3.55], playerFacing: -1, playerVelocity: -0.32, motherX: [1.65, 2.2], motherFacing: 1, motherVelocity: 0.24 },
        caption: "封锁线外，村子还在。空教室比人先知道，今晚不会有上课铃。",
        soundCue: "wind",
      },
      {
        from: 3.6,
        to: 6.3,
        camera: { anchorX: 390, viewDistance: 8.9, lift: 1.02, lookLift: 0.26, targetZ: -1.18, fov: 22.2, trackX: -16, dolly: -0.35 },
        actors: { player: "listen", mother: "write" },
        blocking: { playerX: 3.42, playerFacing: -1, playerVelocity: 0, motherX: 2.42, motherFacing: 1, motherVelocity: 0 },
        caption: "六双鞋留在桌下。周禾写一个名字，就把一双鞋尖摆正。",
        soundCue: "cloth",
      },
      {
        from: 6.3,
        to: 9.2,
        camera: { anchorX: 300, viewDistance: 9.8, lift: 1.58, lookLift: 0.74, targetZ: -0.58, trackX: 8, dolly: -0.45 },
        actors: { player: "listen", mother: "write" },
        blocking: { playerX: [3.48, 3.22], playerFacing: -1, playerVelocity: -0.12, motherX: 2.38, motherFacing: 1, motherVelocity: 0 },
        caption: "点名簿上先有六行。每一笔，都在等一声不同的“到”。",
        soundCue: "paper",
      },
      {
        from: 9.2,
        to: 12.4,
        camera: { anchorX: 620, viewDistance: 22.4, lift: 3.42, lookLift: 1.28, targetZ: -3.2, fov: 25.8, trackX: 28, dolly: 0.8 },
        actors: { player: "shield", mother: "listen" },
        blocking: { playerX: 3.18, playerFacing: -1, playerVelocity: 0, motherX: 2.36, motherFacing: 1, motherVelocity: 0 },
        caption: "阿苇还不知道，天亮以前，簿子会多出“阿苇”和“周禾”。",
        soundCue: "soft",
      },
    ],
  },
  blockadeOpening: {
    id: "blockadeOpening",
    duration: 7.2,
    skippableAfter: 0.8,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 3.0,
        camera: { anchorX: 1510, viewDistance: 46.5, lift: 7.0, lookLift: 2.0, targetZ: -10, fov: 27.8, trackX: 80, dolly: -1.8 },
        actors: { player: "listen", followers: "peek" },
        caption: "封锁沟从岗楼脚下一直切到看不见的村口。人在里面，只剩一粒会动的黑点。",
        soundCue: "water",
      },
      {
        from: 3.0,
        to: 5.1,
        camera: { anchorX: 980, viewDistance: 20.4, lift: 3.18, lookLift: 1.18, targetZ: -2.6, trackX: -32, dolly: -0.65 },
        actors: { player: "peek", followers: "shield", followerStagger: 0.08 },
        caption: "灯扫过去，水面先亮；灯回来以前，旧船必须先替他们发出声音。",
        soundCue: "water",
      },
      {
        from: 5.1,
        to: 7.2,
        camera: { anchorX: 360, viewDistance: 13.2, lift: 2.28, lookLift: 0.96, targetZ: -0.55, trackX: 18, dolly: -0.45 },
        actors: { player: "listen", followers: "shield" },
        caption: "阿苇不看灯，只看苇梢什么时候一起低头。",
        soundCue: "wind",
      },
    ],
  },
  tunnelOpening: {
    id: "tunnelOpening",
    duration: 7.4,
    skippableAfter: 0.8,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 3.2,
        camera: { anchorX: 1510, viewDistance: 32.5, lift: 5.1, lookLift: 1.7, targetZ: -7.8, fov: 26.8, crane: -0.44, dolly: -1.2 },
        actors: { player: "listen", followers: "peek" },
        caption: "头顶是整座村庄的重量。井口只漏下一线天，烟却认得每条裂缝。",
        soundCue: "smoke",
      },
      {
        from: 3.2,
        to: 5.3,
        camera: { anchorX: 910, viewDistance: 16.4, lift: 2.24, lookLift: 1.04, targetZ: -1.7, trackX: -28, dolly: -0.55 },
        actors: { player: "listen", followers: "shield", followerStagger: 0.07 },
        caption: "六口气挤在木梁下面，谁先咳嗽，烟就先找到谁。",
        soundCue: "smoke",
      },
      {
        from: 5.3,
        to: 7.4,
        camera: { anchorX: 590, viewDistance: 11.6, lift: 1.66, lookLift: 0.9, targetZ: -0.3, dolly: -0.38 },
        actors: { player: "lift", followers: "shield" },
        caption: "先给烟一条向上的路，再去找黑暗里的回声。",
      },
    ],
  },
  ferryOpening: {
    id: "ferryOpening",
    duration: 8.2,
    skippableAfter: 0.9,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 3.4,
        camera: { anchorX: 2380, viewDistance: 49.5, lift: 7.4, lookLift: 2.08, targetZ: -12.2, fov: 28, trackX: 90, dolly: -2.0, crane: -0.32 },
        actors: { player: "count", followers: "count", mother: "listen" },
        caption: "北汊的船只有一叶，南汊的灯却铺满半条河。六个孩子在堤上，小得像六颗苇籽。",
        soundCue: "water",
      },
      {
        from: 3.4,
        to: 5.9,
        camera: { anchorX: 1160, viewDistance: 21.8, lift: 3.42, lookLift: 1.22, targetZ: -3.2, trackX: -38, dolly: -0.7 },
        actors: { player: "count", followers: "huddle", mother: "listen" },
        caption: "阿苇先看远岸，再回头看每张脸。少一个，船就不能开。",
        soundCue: "wind",
      },
      {
        from: 5.9,
        to: 8.2,
        camera: { anchorX: 520, viewDistance: 13.8, lift: 2.32, lookLift: 0.98, targetZ: -0.62, trackX: 18, dolly: -0.42 },
        actors: { player: "count", followers: "peek", mother: "listen" },
        caption: "点名不是数数，是确认每个人还在。",
        soundCue: "soft",
      },
    ],
  },
  registerHandoff: {
    id: "registerHandoff",
    duration: 4.8,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.5,
        camera: { anchorX: 320, viewDistance: 10.4, lift: 1.68, lookLift: 0.82, targetZ: -0.55 },
        actors: { player: "pass", mother: "pass" },
        caption: "周禾合上点名簿，没有说“找回来”，只说：“见到一个，就应一个名字。”",
        soundCue: "paper",
      },
      {
        from: 2.5,
        to: 4.8,
        camera: { anchorX: 430, viewDistance: 13.8, lift: 2.12, lookLift: 0.96, targetZ: -0.85 },
        actors: { player: "shield", mother: "listen" },
        caption: "阿苇把簿子塞进衣襟。那时，上面还只有六行。",
        soundCue: "cloth",
      },
    ],
  },
  miziHandoff: {
    id: "miziHandoff",
    duration: 3.7,
    skippableAfter: 0.8,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.8,
        camera: { anchorX: 610, viewDistance: 9.8, lift: 1.58, lookLift: 0.76, targetZ: -0.32 },
        actors: { player: "lift", followers: "peek" },
        caption: "麦子缩在倒下的课桌后面，鞋丢了一只。",
        soundCue: "soft",
      },
      {
        from: 1.8,
        to: 3.7,
        camera: { anchorX: 660, viewDistance: 11.2, lift: 1.72, lookLift: 0.82, targetZ: -0.4 },
        actors: { player: "pass", followers: "listen", followerStagger: 0.08 },
        caption: "她没有哭，只攥住阿苇的袖口，说：“老师让我等名字来找我。”",
        soundCue: "cloth",
      },
    ],
  },
  blindDrop: {
    id: "blindDrop",
    duration: 3.4,
    skippableAfter: 0.75,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.65,
        camera: { anchorX: 820, viewDistance: 10.8, lift: 1.8, lookLift: 0.82, targetZ: -0.22 },
        actors: { player: "pull", followers: "shield" },
        effects: { blindDrop: [0, 1] },
        caption: "阿苇扯断草绳，旧苇帘带着一冬的灰落下来。",
        soundCue: "rope",
      },
      {
        from: 1.65,
        to: 3.4,
        camera: { anchorX: 930, viewDistance: 13.4, lift: 2.08, lookLift: 0.9, targetZ: -0.7 },
        actors: { player: "shield", followers: "peek" },
        effects: { blindDrop: 1 },
        caption: "灯光被挡住一瞬。她们用这一瞬，离开教室。",
        soundCue: "wind",
      },
    ],
  },
  cartBrace: {
    id: "cartBrace",
    duration: 3.6,
    skippableAfter: 0.8,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.1,
        camera: { anchorX: 1515, viewDistance: 10.6, lift: 1.72, lookLift: 0.78, targetZ: -0.18 },
        actors: { player: "push", followers: "shield" },
        effects: { cartSettle: [0, 1] },
        caption: "车轮一次次滑回泥里。麦子用肩膀抵住车帮，没有出声。",
        soundCue: "wood",
      },
      {
        from: 2.1,
        to: 3.6,
        camera: { anchorX: 1600, viewDistance: 12.2, lift: 1.92, lookLift: 0.86, targetZ: -0.42 },
        actors: { player: "brace", followers: "peek" },
        effects: { cartSettle: 1 },
        caption: "两个人的重量，刚好让车轮不再动。",
        soundCue: "soft",
      },
    ],
  },
  drainPassage: {
    id: "drainPassage",
    duration: 4.2,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.15,
        camera: { anchorX: 2535, viewDistance: 9.9, lift: 1.5, lookLift: 0.68, targetZ: -0.12 },
        actors: { player: "lift", followers: "board" },
        effects: { drainOpen: [0, 1] },
        caption: "石板抬起一道缝。阿苇先把那只光脚送进黑暗。",
        soundCue: "stone",
      },
      {
        from: 2.15,
        to: 4.2,
        camera: { anchorX: 2640, viewDistance: 12.4, lift: 1.76, lookLift: 0.78, targetZ: -0.6 },
        actors: { player: "board", followers: "listen" },
        effects: { drainOpen: 1 },
        caption: "麦子在洞里回头。阿苇最后一个钻进去。",
        soundCue: "cloth",
      },
    ],
  },
  windReading: {
    id: "windReading",
    duration: 3.6,
    skippableAfter: 0.8,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.7,
        camera: { anchorX: 350, viewDistance: 12.1, lift: 2.02, lookLift: 0.9, targetZ: -0.75 },
        actors: { player: "listen", followers: "shield" },
        caption: "第一阵风只动苇花，第二阵才压低整片苇梢。",
        soundCue: "wind",
      },
      {
        from: 1.7,
        to: 3.6,
        camera: { anchorX: 470, viewDistance: 15.4, lift: 2.38, lookLift: 1.02, targetZ: -1.2 },
        actors: { player: "signal", followers: "listen", followerStagger: 0.09 },
        caption: "阿苇举起两根手指。麦子学会在第三阵风里迈步。",
        soundCue: "soft",
      },
    ],
  },
  emptyBoatDiversion: {
    id: "emptyBoatDiversion",
    duration: 4.7,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.1,
        camera: { anchorX: 1100, viewDistance: 10.8, lift: 1.84, lookLift: 0.82, targetZ: -0.3 },
        actors: { player: "pull", followers: "shield" },
        effects: { emptyBoatRelease: [0, 0.35] },
        caption: "缆绳松开。空船先不走，像是在等最后一只手放开。",
        soundCue: "rope",
      },
      {
        from: 2.1,
        to: 4.7,
        camera: { anchorX: 980, viewDistance: 18.8, lift: 2.9, lookLift: 1.12, targetZ: -2.25 },
        actors: { player: "shield", followers: "peek" },
        effects: { emptyBoatRelease: [0.35, 1], searchlightDiversion: [0, 1] },
        caption: "木船撞响远处的桩。巡逻灯追着那条没有人的水路转开。",
        soundCue: "water",
      },
    ],
  },
  sluiceRise: {
    id: "sluiceRise",
    duration: 5.0,
    skippableAfter: 0.95,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.6,
        camera: { anchorX: 1735, viewDistance: 10.6, lift: 1.72, lookLift: 0.78, targetZ: -0.28 },
        actors: { player: "brace", followers: "shield" },
        effects: { bridgeRaise: [0, 0.42] },
        caption: "长杆不肯下去。阿苇把整个人的重量挂在上面。",
        soundCue: "wood",
      },
      {
        from: 2.6,
        to: 5.0,
        camera: { anchorX: 2040, viewDistance: 16.4, lift: 2.62, lookLift: 1.0, targetZ: -1.3 },
        actors: { player: "listen", followers: "peek" },
        effects: { bridgeRaise: [0.42, 1] },
        caption: "水托起旧门板。不是桥，只是一条暂时没有沉下去的路。",
        soundCue: "water",
      },
    ],
  },
  reedRoute: {
    id: "reedRoute",
    duration: 3.2,
    skippableAfter: 0.75,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.7,
        camera: { anchorX: 2960, viewDistance: 10.9, lift: 1.78, lookLift: 0.82, targetZ: -0.35 },
        actors: { player: "count", followers: "listen" },
        effects: { routeMarked: [0, 1] },
        caption: "三根苇梢折向北。没有碑，也没有署名。",
        soundCue: "wind",
      },
      {
        from: 1.7,
        to: 3.2,
        camera: { anchorX: 2820, viewDistance: 16.2, lift: 2.54, lookLift: 1.0, targetZ: -1.45 },
        actors: { player: "listen", followers: "peek" },
        effects: { routeMarked: 1 },
        caption: "后面的人看见它，就会知道这里曾有人走通。",
        soundCue: "soft",
      },
    ],
  },
  wellVent: {
    id: "wellVent",
    duration: 4.8,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.35,
        camera: { anchorX: 590, viewDistance: 9.6, lift: 1.46, lookLift: 0.72, targetZ: -0.2, trackX: 14, dolly: -0.42 },
        actors: { player: "lift", followers: "shield" },
        effects: { ventOpening: [0, 1], smokeRetreat: [0, 0.24] },
        caption: "井板上的土一层层落下来。上面的夜，终于漏进一线。",
        soundCue: "stone",
      },
      {
        from: 2.35,
        to: 4.8,
        camera: { anchorX: 720, viewDistance: 12.9, lift: 2.06, lookLift: 0.94, targetZ: -1.25, trackX: 18, dolly: -0.36 },
        actors: { player: "listen", followers: "count", followerStagger: 0.1 },
        effects: { ventOpening: 1, smokeRetreat: [0.24, 0.48] },
        caption: "孩子们先听见风，再敢吸下一口气。",
        soundCue: "wind",
      },
    ],
  },
  sealCrack: {
    id: "sealCrack",
    duration: 4.2,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.2,
        camera: { anchorX: 1320, viewDistance: 9.9, lift: 1.42, lookLift: 0.7, targetZ: -0.18 },
        actors: { player: "push", followers: "shield" },
        effects: { crackSeal: [0, 1], smokeRetreat: [0.48, 0.78] },
        caption: "湿苇席贴上裂缝，烟转了方向，火星还在另一边发亮。",
        soundCue: "cloth",
      },
      {
        from: 2.2,
        to: 4.2,
        camera: { anchorX: 1480, viewDistance: 13.8, lift: 1.9, lookLift: 0.86, targetZ: -1.1 },
        actors: { player: "listen", followers: "peek" },
        effects: { crackSeal: 1, smokeRetreat: [0.78, 1] },
        caption: "黑暗里响起第一声咳嗽。有人还活着。",
        soundCue: "knock",
      },
    ],
  },
  shuanLift: {
    id: "shuanLift",
    duration: 4.1,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.25,
        camera: { anchorX: 1980, viewDistance: 9.8, lift: 1.42, lookLift: 0.7, targetZ: -0.15 },
        actors: { player: "lift", followers: "shield", followerStagger: 0.06 },
        effects: { shuanLift: [0, 1] },
        caption: "栓儿烧得说不出“到”，还是把手举过了额头。",
        soundCue: "soft",
      },
      {
        from: 2.25,
        to: 4.1,
        camera: { anchorX: 2040, viewDistance: 11.4, lift: 1.58, lookLift: 0.76, targetZ: -0.42 },
        actors: { player: "listen", followers: "count" },
        effects: { shuanLift: 1 },
        caption: "阿苇替他答了一声。其他孩子也跟着答。",
        soundCue: "knock",
      },
    ],
  },
  reedExit: {
    id: "reedExit",
    duration: 4.3,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.15,
        camera: { anchorX: 2740, viewDistance: 10.4, lift: 1.54, lookLift: 0.72, targetZ: -0.28 },
        actors: { player: "push", followers: "board", followerStagger: 0.1 },
        effects: { exitOpen: [0, 1] },
        caption: "苇根被推开。六个孩子一个接一个摸到夜风。",
        soundCue: "wind",
      },
      {
        from: 2.15,
        to: 4.3,
        camera: { anchorX: 2760, viewDistance: 17.2, lift: 2.52, lookLift: 1.0, targetZ: -1.7 },
        actors: { player: "count", followers: "count", followerStagger: 0.12 },
        effects: { exitOpen: 1 },
        caption: "阿苇没有数影子。她逐个叫名字，逐个等回应。",
        soundCue: "soft",
      },
    ],
  },
  ferryRollCall: {
    id: "ferryRollCall",
    duration: 4.5,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.4,
        camera: { anchorX: 360, viewDistance: 10.8, lift: 1.82, lookLift: 0.82, targetZ: -0.35 },
        actors: { player: "count", followers: "count", followerStagger: 0.12 },
        caption: "麦子。杏花。小锁。春妮。石头。栓儿。",
        soundCue: "soft",
      },
      {
        from: 2.4,
        to: 4.5,
        camera: { anchorX: 500, viewDistance: 14.8, lift: 2.32, lookLift: 0.96, targetZ: -1.1 },
        actors: { player: "listen", followers: "listen", followerStagger: 0.08 },
        caption: "六声“到”并不整齐。正因为不整齐，才知道不是回声。",
        soundCue: "wind",
      },
    ],
  },
  screenLift: {
    id: "screenLift",
    duration: 4.8,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.45,
        camera: { anchorX: 1040, viewDistance: 10.6, lift: 1.74, lookLift: 0.8, targetZ: -0.25 },
        actors: { player: "pull", followers: "shield" },
        effects: { screenRaise: [0, 0.72] },
        caption: "孩子们留在草垛后。灯下只有阿苇一个人的影子。",
        soundCue: "rope",
      },
      {
        from: 2.45,
        to: 4.8,
        camera: { anchorX: 1260, viewDistance: 16.6, lift: 2.62, lookLift: 1.02, targetZ: -1.55 },
        actors: { player: "brace", followers: "peek" },
        effects: { screenRaise: [0.72, 1] },
        caption: "苇障升到肩头时，六个小影子才重新动起来。",
        soundCue: "wind",
      },
    ],
  },
  tunnelRollCall: {
    id: "tunnelRollCall",
    duration: 8.8,
    skippableAfter: 1.0,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.4,
        camera: { anchorX: 1580, viewDistance: 12.8, lift: 1.76, lookLift: 0.9, targetZ: -0.48, trackX: 10, dolly: -0.34 },
        actors: { player: "tap", followers: "huddle", followerStagger: 0.08 },
        caption: "阿苇用指节敲了两下。不是暗号，是告诉黑暗里的人：我在等。",
        soundCue: "knock",
      },
      {
        from: 2.4,
        to: 4.7,
        camera: { anchorX: 1740, viewDistance: 11.6, lift: 1.62, lookLift: 0.88, targetZ: -0.4, trackX: 12, dolly: -0.28 },
        actors: { player: "listen", followers: "count", followerStagger: 0.17 },
        caption: "杏花。小锁。春妮。石头。四声“到”贴着土壁，一声比一声近。",
        soundCue: "soft",
      },
      {
        from: 4.7,
        to: 6.8,
        camera: { anchorX: 1970, viewDistance: 9.4, lift: 1.38, lookLift: 0.76, targetZ: -0.12, trackX: -8, dolly: -0.3 },
        actors: { player: "listen", followers: "huddle", followerFocusIndex: 5, followerFocusAction: "raiseHand" },
        caption: "“栓儿。”没有声音。最里面，一只发烫的小手慢慢举过了额头。",
        soundCue: "soft",
      },
      {
        from: 6.8,
        to: 8.8,
        camera: { anchorX: 1900, viewDistance: 11.2, lift: 1.58, lookLift: 0.84, targetZ: -0.3, trackX: 10, dolly: 0.18 },
        actors: { player: "answer", followers: "huddle", followerFocusIndex: 5, followerFocusAction: "raiseHand" },
        caption: "阿苇替他答：“到。”孩子把手放下以前，其他五只手已经挨了过去。",
        soundCue: "cloth",
      },
    ],
  },
  tunnelHandoff: {
    id: "tunnelHandoff",
    duration: 3.8,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.25,
        camera: { anchorX: 2290, viewDistance: 10.8, lift: 1.48, lookLift: 0.82, targetZ: -0.08 },
        actors: { player: "pass", followers: "pass", followerStagger: 0.08 },
        caption: "井口伸下一双手。没有人问这孩子是哪一家的。",
        soundCue: "cloth",
      },
      {
        from: 2.25,
        to: 3.8,
        camera: { anchorX: 2350, viewDistance: 12.7, lift: 1.78, lookLift: 0.94, targetZ: -0.35 },
        actors: { player: "listen", followers: "peek" },
        caption: "手接住了，阿苇才松开。",
      },
    ],
  },
  motherHandoff: {
    id: "motherHandoff",
    duration: 8.8,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.0,
        camera: { anchorX: 1885, viewDistance: 9.5, lift: 1.82, lookLift: 0.84, targetZ: 0.02, trackX: 8, dolly: -0.34 },
        actors: { player: "pass", followers: "peek", mother: "pass" },
        caption: "周禾翻过六行。每个名字后面，都有一声不一样的“到”。",
        soundCue: "paper",
      },
      {
        from: 2.0,
        to: 4.2,
        camera: { anchorX: 1888, viewDistance: 8.9, lift: 1.7, lookLift: 0.8, targetZ: 0.06, trackX: -6, dolly: -0.28 },
        actors: { player: "listen", followers: "count", mother: "write" },
        caption: "她在第七行写下“阿苇”，说：“你也还只是个孩子。”",
        soundCue: "paper",
      },
      {
        from: 4.2,
        to: 6.7,
        camera: { anchorX: 1882, viewDistance: 8.4, lift: 1.66, lookLift: 0.79, targetZ: 0.1, trackX: 5, dolly: -0.3 },
        actors: { player: "receiveComfort", followers: "listen", mother: "embrace" },
        blocking: { playerX: 18.66, playerFacing: 1, playerVelocity: 0, motherX: 18.98, motherFacing: -1, motherVelocity: 0 },
        caption: "周禾伸手时，阿苇先僵住了。她已经很久没有被谁当作一个孩子抱住。",
        soundCue: "soft",
      },
      {
        from: 6.7,
        to: 8.8,
        camera: { anchorX: 1900, viewDistance: 10.8, lift: 1.92, lookLift: 0.88, targetZ: -0.12, trackX: 16, dolly: 0.24 },
        actors: { player: "holdRegister", followers: "listen", mother: "goodbye" },
        blocking: { playerX: 18.66, playerFacing: 1, playerVelocity: 0, motherX: [18.98, 19.72], motherFacing: 1, motherVelocity: 0.3 },
        caption: "周禾松开手：“过河以后，把自己的名字也念出来。”",
        soundCue: "wind",
      },
    ],
  },
  motherSignal: {
    id: "motherSignal",
    duration: 4.7,
    skippableAfter: 0.95,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.0,
        camera: { anchorX: 2070, viewDistance: 11.9, lift: 2.24, lookLift: 0.98, targetZ: -0.25 },
        actors: { player: "shield", followers: "shield", mother: "signal" },
        effects: { signalWind: [0.2, 1] },
        caption: "白布先吃住了风，马灯才转向南汊。",
        soundCue: "bell",
      },
      {
        from: 2.0,
        to: 4.7,
        camera: { anchorX: 2350, viewDistance: 17.8, lift: 2.86, lookLift: 1.08, targetZ: -1.5 },
        actors: { player: "peek", followers: "peek", mother: "listen" },
        effects: { signalWind: [1, 0.65] },
        caption: "灯跟着她走远。渡口这边，六个孩子开始向前。",
        soundCue: "wind",
      },
    ],
  },
  endingDeparture: {
    id: "endingDeparture",
    duration: 21.6,
    skippableAfter: 2.4,
    lockInput: "all",
    blocksCompletion: true,
    blocksEnding: true,
    segments: [
      {
        from: 0,
        to: 3.0,
        camera: { anchorX: 3230, viewDistance: 11.6, lift: 2.04, lookLift: 0.88, targetZ: 0.1, trackX: 18, dolly: -0.38 },
        actors: { player: "pass", followers: "board", followerStagger: 0.18, mother: "listen" },
        blocking: { playerX: 32.42, playerFacing: 1, playerVelocity: 0 },
        effects: { boarding: [0, 0.7], playerBoarding: 0, ferryDeparture: 0, motherDeparture: 0 },
        caption: "麦子。杏花。小锁。春妮。石头。栓儿。",
        soundCue: "plank",
      },
      {
        from: 3.0,
        to: 5.4,
        camera: { anchorX: 3290, viewDistance: 10.7, lift: 1.94, lookLift: 0.83, targetZ: 0.15, trackX: 14, dolly: -0.3 },
        actors: { player: "count", followers: "board", followerStagger: 0.15, mother: "listen" },
        blocking: { playerX: 32.46, playerFacing: 1, playerVelocity: 0 },
        effects: { boarding: [0.7, 1], playerBoarding: 0, ferryDeparture: 0, motherDeparture: 0 },
        caption: "六声“到”，先过了船板。",
        soundCue: "soft",
      },
      {
        from: 5.4,
        to: 8.4,
        camera: { anchorX: 3250, viewDistance: 8.8, lift: 1.58, lookLift: 0.68, targetZ: 0.18, trackX: -12, dolly: -0.42 },
        actors: { player: "writeKneel", followers: "huddle", mother: "goodbye" },
        blocking: { playerX: [32.46, 32.62], playerFacing: -1, playerVelocity: -0.08, playerCrouch: false, motherX: [23.4, 22.45], motherFacing: -1, motherVelocity: -0.42 },
        effects: { boarding: 1, playerBoarding: 0, ferryDeparture: 0, motherDeparture: [0, 0.2] },
        caption: "阿苇蹲在船板边，在第八行写下“周禾”。墨还没干，老师的脚步已经向南。",
        soundCue: "paper",
      },
      {
        from: 8.4,
        to: 11.2,
        camera: { anchorX: 3310, viewDistance: 10.8, lift: 1.98, lookLift: 0.84, targetZ: 0.14, trackX: 22, dolly: -0.4 },
        actors: { player: "board", followers: "huddle", mother: "goodbye" },
        blocking: { playerX: 32.64, playerFacing: 1, playerVelocity: 0.44, motherX: [22.45, 20.6], motherFacing: -1, motherVelocity: -0.58 },
        effects: { boarding: 1, playerBoarding: [0, 1], ferryDeparture: [0, 0.08], motherDeparture: [0.2, 0.48] },
        caption: "她把点名簿贴回胸口，最后一个跨过船板。",
        soundCue: "rope",
      },
      {
        from: 11.2,
        to: 14.2,
        camera: { anchorX: 3380, viewDistance: 11.4, lift: 2.08, lookLift: 0.88, targetZ: 0.04, trackX: 24, dolly: -0.32 },
        actors: { player: "answer", followers: "count", followerStagger: 0.1, mother: "goodbye" },
        blocking: { playerFacing: -1, playerVelocity: 0, motherX: [20.6, 18.7], motherFacing: -1, motherVelocity: -0.58 },
        effects: { boarding: 1, playerBoarding: 1, ferryDeparture: [0.08, 0.25], motherDeparture: [0.48, 0.72] },
        caption: "麦子仰头叫：“阿苇姐。”阿苇停了一下，答：“到。”",
        soundCue: "soft",
      },
      {
        from: 14.2,
        to: 18.4,
        camera: { anchorX: 3460, viewDistance: 21.8, lift: 3.58, lookLift: 1.22, targetZ: -3.6, trackX: 56, dolly: 2.2, crane: 0.38, fov: 26.4 },
        actors: { player: "call", followers: "huddle", mother: "goodbye" },
        blocking: { playerFacing: -1, playerVelocity: 0, motherX: [18.7, 16.6], motherFacing: -1, motherVelocity: -0.48 },
        effects: { boarding: 1, playerBoarding: 1, ferryDeparture: [0.25, 1], motherDeparture: [0.72, 1] },
        caption: "“周禾老师——”河面没有回答。阿苇没有划掉第八行。船向北，灯向南。",
        soundCue: "water",
      },
      {
        from: 18.4,
        to: 21.6,
        camera: { anchorX: 3660, viewDistance: 29.5, lift: 4.72, lookLift: 1.4, targetZ: -5.8, trackX: 36, dolly: 1.1, crane: 0.28, fov: 27.2 },
        actors: { player: "holdRegister", followers: "huddle", mother: "goodbye" },
        blocking: { playerFacing: -1, playerVelocity: 0, motherX: [16.6, 15.8], motherFacing: -1, motherVelocity: -0.34 },
        effects: { boarding: 1, playerBoarding: 1, ferryDeparture: 1, motherDeparture: 1 },
        caption: "河面只剩桨声。第八行没有划掉。",
        soundCue: "water",
      },
    ],
  },
});

export const ChapterOpeningCinematics = DeepFreeze({
  school: "schoolOpening",
  blockade: "blockadeOpening",
  tunnel: "tunnelOpening",
  ferry: "ferryOpening",
});

export const ActionCinematics = DeepFreeze({
  takeRegister: "registerHandoff",
  findMizi: "miziHandoff",
  dropBlind: "blindDrop",
  cartPlaced: "cartBrace",
  openDrain: "drainPassage",
  readWind: "windReading",
  releaseBoat: "emptyBoatDiversion",
  raiseSluice: "sluiceRise",
  markRoute: "reedRoute",
  openWellVent: "wellVent",
  sealEastCrack: "sealCrack",
  findChildren: "tunnelRollCall",
  liftShuan: "shuanLift",
  handShuanUp: "tunnelHandoff",
  openReedExit: "reedExit",
  countChildren: "ferryRollCall",
  raiseScreen: "screenLift",
  meetMother: "motherHandoff",
  motherSignal: "motherSignal",
  boardFerry: "endingDeparture",
});

export function GetCinematicSequence(sequenceId) {
  return CinematicSequences[sequenceId] || null;
}

export function GetChapterOpeningCinematic(chapterId) {
  return ChapterOpeningCinematics[chapterId] || null;
}

export function GetActionCinematic(actionId) {
  return ActionCinematics[actionId] || null;
}
