function DeepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) DeepFreeze(child);
  return value;
}

// These sequences never alter historical outcomes or gameplay rewards. They
// only reframe state that the rules layer has already produced, keeping the
// story in the same continuous 3D space as play.
export const CinematicSequences = DeepFreeze({
  schoolOpening: {
    id: "schoolOpening",
    duration: 12.4,
    skippableAfter: 0.9,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 3.6,
        camera: { anchorX: [560, 455], viewDistance: [35, 23], lift: [5.6, 3.45], lookLift: [3.95, 2.8], targetZ: [-7.2, -3.7], fov: [26.4, 24.8] },
        actors: { player: { action: "listen", fear: 0.13, lookOffset: -0.04 }, mother: { action: "listen", fear: 0.08, lookOffset: 0.04 } },
        blocking: { playerX: [4.35, 3.55], playerFacing: -1, playerVelocity: -0.32, motherX: [1.65, 2.2], motherFacing: 1, motherVelocity: 0.24 },
        caption: "封锁线外，村子还在。教室里没有铃声。",
        soundCue: "wind",
      },
      {
        from: 3.6,
        to: 6.3,
        camera: { anchorX: [455, 365], viewDistance: [23, 10.4], lift: [3.45, 1.42], lookLift: [1.28, 0.64], targetZ: [-3.7, -0.88], fov: [24.8, 24.2], cut: false },
        actors: { player: { action: "listen", fear: 0.12 }, mother: { action: "arrangeShoes", window: [0.05, 0.92], fear: 0.06, lookOffset: 0.1 } },
        blocking: { playerX: 3.42, playerFacing: -1, playerVelocity: 0, motherX: 2.42, motherFacing: 1, motherVelocity: 0 },
        effects: { shoeOrder: [0, 1] },
        caption: "周禾把六双鞋尖一一摆正。",
        soundCue: "cloth",
      },
      {
        from: 6.3,
        to: 9.2,
        camera: { anchorX: [365, 315], viewDistance: [10.4, 8.8], lift: [1.42, 1.28], lookLift: [0.64, 0.56], targetZ: [-0.88, -0.3], fov: [24.2, 24], cut: false },
        actors: { player: { action: "listen", fear: 0.1, lookOffset: -0.08 }, mother: { action: "write", window: [0.08, 0.92], fear: 0.04 } },
        blocking: { playerX: [3.48, 3.22], playerFacing: -1, playerVelocity: -0.12, motherX: 2.38, motherFacing: 1, motherVelocity: 0 },
        effects: { shoeOrder: 1 },
        caption: "点名簿上先有六行。每一行都在等一声“到”。",
        soundCue: "paper",
      },
      {
        from: 9.2,
        to: 12.4,
        camera: { anchorX: [315, 540], viewDistance: [8.8, 19.5], lift: [1.28, 3.05], lookLift: [0.56, 1.16], targetZ: [-0.3, -2.8], fov: [24, 25.2], cut: false },
        actors: { player: { action: "listen", fear: 0.16, lookOffset: -0.05 }, mother: { action: "holdRegister", window: [0.1, 0.9], fear: 0.08 } },
        blocking: { playerX: 3.18, playerFacing: -1, playerVelocity: 0, motherX: 2.36, motherFacing: 1, motherVelocity: 0 },
        effects: { shoeOrder: 1 },
        caption: "天亮以前，簿子还会多出两行。",
        soundCue: "soft",
      },
    ],
  },
  blockadeOpening: {
    id: "blockadeOpening",
    duration: 7.2,
    skippableAfter: 0.8,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 3.0,
        camera: { anchorX: [1510, 700], viewDistance: [37, 24], lift: [6.1, 3.7], lookLift: [4.35, 3.1], targetZ: [-8.2, -3.8], fov: [26.6, 24.9] },
        actors: { player: { action: "listen", fear: 0.44, lookOffset: 0.08 }, followers: { action: "peek", fear: 0.58 } },
        caption: "封锁沟从岗楼脚下一直切到看不见的村口。人在里面，只剩一粒会动的黑点。",
        soundCue: "water",
      },
      {
        from: 3.0,
        to: 5.1,
        camera: { anchorX: [700, 260], viewDistance: [24, 12.8], lift: [3.7, 1.92], lookLift: [1.3, 0.9], targetZ: [-3.8, -0.72], fov: [24.9, 24.1], cut: false },
        actors: { player: { action: "peek", fear: 0.56, lookOffset: -0.1 }, followers: { action: "shield", fear: 0.7 }, followerStagger: 0.08 },
        caption: "灯扫过去，水面先亮；灯回来以前，旧船必须先替他们发出声音。",
        soundCue: "water",
      },
      {
        from: 5.1,
        to: 7.2,
        camera: { anchorX: [260, 175], viewDistance: [12.8, 10.8], lift: [1.92, 1.58], lookLift: [0.9, 0.76], targetZ: [-0.72, -0.2], fov: [24.1, 24], cut: false },
        actors: { player: { action: "listen", fear: 0.5, lookOffset: 0.08 }, followers: { action: "shield", fear: 0.66 } },
        caption: "阿苇不看灯，只看苇梢什么时候一起低头。",
        soundCue: "wind",
      },
    ],
  },
  tunnelOpening: {
    id: "tunnelOpening",
    duration: 7.4,
    skippableAfter: 0.8,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 3.2,
        camera: { anchorX: [1510, 600], viewDistance: [31, 21], lift: [5.0, 3.2], lookLift: [3.65, 2.55], targetZ: [-7.2, -3.3], fov: [26.3, 24.8] },
        actors: { player: { action: "listen", fear: 0.42, lookOffset: 0.08 }, followers: { action: "peek", fear: 0.56 } },
        caption: "头顶是整座村庄的重量。井口只漏下一线天，烟却认得每条裂缝。",
        soundCue: "smoke",
      },
      {
        from: 3.2,
        to: 5.3,
        camera: { anchorX: [600, 250], viewDistance: [21, 13.4], lift: [3.2, 1.78], lookLift: [1.18, 0.86], targetZ: [-3.3, -0.92], fov: [24.8, 24.1], cut: false },
        actors: { player: { action: "listen", fear: 0.48 }, followers: { action: "shield", fear: 0.7 }, followerStagger: 0.07, followerFocusIndex: 0, followerFocusAction: { action: "suppressCough", window: [0.08, 0.94], fear: 0.82, lookOffset: -0.12 } },
        caption: "麦子把咳嗽压回掌心。阿苇先看见了。",
        soundCue: "smoke",
      },
      {
        from: 5.3,
        to: 7.4,
        camera: { anchorX: [250, 155], viewDistance: [13.4, 10.8], lift: [1.78, 1.48], lookLift: [0.86, 0.72], targetZ: [-0.92, -0.26], fov: [24.1, 24], cut: false },
        actors: { player: { action: "steadyChild", window: [0.04, 0.88], fear: 0.4, crouching: false }, followers: { action: "shield", fear: 0.64 }, followerFocusIndex: 0, followerFocusAction: { action: "suppressCough", window: [0.18, 0.82], fear: 0.76 } },
        caption: "她压低身子，等孩子把这口气熬过去。",
      },
    ],
  },
  ferryOpening: {
    id: "ferryOpening",
    duration: 8.2,
    skippableAfter: 0.9,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 3.4,
        camera: { anchorX: [2380, 900], viewDistance: [44, 27], lift: [7.0, 4.2], lookLift: [5.25, 3.2], targetZ: [-10.5, -4.8], fov: [27, 25] },
        actors: { player: { action: "count", fear: 0.3 }, followers: { action: "count", fear: 0.4 }, mother: "listen" },
        caption: "北汊的船只有一叶，南汊的灯却铺满半条河。六个孩子在堤上，小得像六颗苇籽。",
        soundCue: "water",
      },
      {
        from: 3.4,
        to: 5.9,
        camera: { anchorX: [900, 300], viewDistance: [27, 14.6], lift: [4.2, 2.12], lookLift: [1.4, 0.94], targetZ: [-4.8, -0.82], fov: [25, 24.2], cut: false },
        actors: { player: { action: "count", fear: 0.32, lookOffset: -0.08 }, followers: { action: "huddle", fear: 0.44 }, mother: "listen" },
        caption: "阿苇先看远岸，再回头看每张脸。少一个，船就不能开。",
        soundCue: "wind",
      },
      {
        from: 5.9,
        to: 8.2,
        camera: { anchorX: [300, 170], viewDistance: [14.6, 11.8], lift: [2.12, 1.68], lookLift: [0.94, 0.8], targetZ: [-0.82, -0.28], fov: [24.2, 24], cut: false },
        actors: { player: { action: "count", fear: 0.28, lookOffset: 0.08 }, followers: { action: "peek", fear: 0.4 }, mother: "listen" },
        caption: "点名不是数数，是确认每个人还在。",
        soundCue: "soft",
      },
    ],
  },
  registerHandoff: {
    id: "registerHandoff",
    duration: 4.8,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.5,
        camera: { anchorX: 320, viewDistance: 10.4, lift: 1.68, lookLift: 0.82, targetZ: -0.55 },
        actors: { player: "pass", mother: "pass" },
        caption: "周禾合上点名簿，没有说“找回来”，只说：“见到一个，就应一个名字。”",
        soundCue: "paper",
      },
      {
        from: 2.5,
        to: 4.8,
        camera: { anchorX: 430, viewDistance: 13.8, lift: 2.12, lookLift: 0.96, targetZ: -0.85 },
        actors: { player: "shield", mother: "listen" },
        caption: "阿苇把簿子塞进衣襟。那时，上面还只有六行。",
        soundCue: "cloth",
      },
    ],
  },
  miziHandoff: {
    id: "miziHandoff",
    duration: 6.6,
    skippableAfter: 0.8,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.0,
        camera: { anchorX: [670, 615], viewDistance: [12.8, 9.4], lift: [1.92, 1.42], lookLift: [0.9, 0.68], targetZ: [-0.9, -0.2], fov: [24.5, 24.1] },
        actors: { player: { action: "kneelListen", window: [0.05, 0.9], fear: 0.28 }, followers: { action: "huddle", fear: 0.6 }, followerFocusIndex: 0, followerFocusAction: { action: "huddle", fear: 0.72, lookOffset: -0.12 }, followerFocusFacing: 1, followerFocusX: 5.7, followerFocusZ: 0.52 },
        blocking: { playerX: 6.24, playerFacing: -1, playerVelocity: 0 },
        caption: "麦子缩在倒下的课桌后面，鞋丢了一只。",
        soundCue: "soft",
      },
      {
        from: 2.0,
        to: 4.6,
        camera: { anchorX: [615, 605], viewDistance: [9.4, 8.2], lift: [1.42, 1.22], lookLift: [0.68, 0.56], targetZ: [-0.2, 0.08], fov: [24.1, 24], cut: false },
        actors: { player: { action: "kneelListen", fear: 0.24, lookOffset: -0.08 }, followers: "huddle", followerFocusIndex: 0, followerFocusAction: { action: "gripSleeve", window: [0.08, 0.92], fear: 0.68, lookOffset: 0.1 }, followerFocusFacing: 1, followerFocusX: 5.7, followerFocusZ: 0.52 },
        blocking: { playerX: 6.24, playerFacing: -1, playerVelocity: 0 },
        caption: "她没有哭，只攥住阿苇的袖口，说：“老师让我等名字来找我。”",
        soundCue: "cloth",
      },
      {
        from: 4.6,
        to: 6.6,
        camera: { anchorX: [605, 660], viewDistance: [8.2, 10.8], lift: [1.22, 1.72], lookLift: [0.56, 0.8], targetZ: [0.08, -0.38], fov: [24, 24.3], cut: false },
        actors: { player: { action: "steadyChild", window: [0.04, 0.86], fear: 0.16 }, followers: "listen", followerFocusIndex: 0, followerFocusAction: { action: "breatheRelief", window: [0.18, 0.94], fear: 0.34, lookOffset: 0.08 }, followerFocusFacing: 1, followerFocusX: 5.78, followerFocusZ: 0.46 },
        blocking: { playerX: 6.24, playerFacing: -1, playerVelocity: 0 },
        caption: "阿苇没有催。麦子松开袖口，改抓住她的手。",
        soundCue: "soft",
      },
    ],
  },
  blindDrop: {
    id: "blindDrop",
    duration: 3.4,
    skippableAfter: 0.75,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.65,
        camera: { anchorX: 820, viewDistance: 10.8, lift: 1.8, lookLift: 0.82, targetZ: -0.22 },
        actors: { player: "pull", followers: "shield" },
        effects: { blindDrop: [0, 1] },
        caption: "阿苇扯断草绳，旧苇帘带着一冬的灰落下来。",
        soundCue: "rope",
      },
      {
        from: 1.65,
        to: 3.4,
        camera: { anchorX: 930, viewDistance: 13.4, lift: 2.08, lookLift: 0.9, targetZ: -0.7 },
        actors: { player: "shield", followers: "peek" },
        effects: { blindDrop: 1 },
        caption: "灯光被挡住一瞬。她们用这一瞬，离开教室。",
        soundCue: "wind",
      },
    ],
  },
  cartBrace: {
    id: "cartBrace",
    duration: 5.8,
    skippableAfter: 0.8,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.2,
        camera: { anchorX: 1560, viewDistance: 9.45, lift: 1.42, lookLift: 0.64, targetZ: 0.08, trackX: 3, dolly: -0.24 },
        actors: { player: "push", followers: "shield", followerFocusIndex: 0, followerFocusAction: "shoulderBrace", followerFocusFacing: 1, followerFocusX: 14.78, followerFocusZ: 0.58 },
        blocking: { playerX: 16.24, playerFacing: -1, playerVelocity: 0 },
        effects: { cartSettle: [0, 0.42] },
        caption: "车轮一次次滑回泥里。麦子用肩膀抵住车帮，没有出声。",
        soundCue: "wood",
      },
      {
        from: 2.2,
        to: 4.1,
        camera: { anchorX: 1570, viewDistance: 9.7, lift: 1.46, lookLift: 0.66, targetZ: 0.06, trackX: 4, dolly: -0.18 },
        actors: { player: "brace", followers: "shield", followerFocusIndex: 0, followerFocusAction: "shoulderBrace", followerFocusFacing: 1, followerFocusX: 14.8, followerFocusZ: 0.58 },
        blocking: { playerX: 16.24, playerFacing: -1, playerVelocity: 0 },
        effects: { cartSettle: [0.42, 1] },
        caption: "阿苇没有回头，只把长柄再压低一点。麦子学着把呼吸留到车轮停住以后。",
        soundCue: "wood",
      },
      {
        from: 4.1,
        to: 5.8,
        camera: { anchorX: 1600, viewDistance: 12.2, lift: 1.92, lookLift: 0.86, targetZ: -0.42, trackX: 12, dolly: 0.18 },
        actors: { player: "breatheRelief", followers: "listen", followerFocusIndex: 0, followerFocusAction: "breatheRelief", followerFocusFacing: 1, followerFocusX: 14.86, followerFocusZ: 0.5 },
        blocking: { playerX: 16.16, playerFacing: -1, playerVelocity: 0 },
        effects: { cartSettle: 1 },
        caption: "两个人的重量，刚好让车轮不再动。",
        soundCue: "soft",
      },
    ],
  },
  drainPassage: {
    id: "drainPassage",
    duration: 4.2,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.15,
        camera: { anchorX: 2535, viewDistance: 9.9, lift: 1.5, lookLift: 0.68, targetZ: -0.12 },
        actors: { player: "lift", followers: "board" },
        effects: { drainOpen: [0, 1] },
        caption: "石板抬起一道缝。阿苇先把那只光脚送进黑暗。",
        soundCue: "stone",
      },
      {
        from: 2.15,
        to: 4.2,
        camera: { anchorX: 2640, viewDistance: 12.4, lift: 1.76, lookLift: 0.78, targetZ: -0.6 },
        actors: { player: "board", followers: "listen", followerFocusIndex: 0, followerFocusAction: "lookBack", followerFocusFacing: 1 },
        effects: { drainOpen: 1 },
        caption: "麦子在洞里回头。阿苇最后一个钻进去。",
        soundCue: "cloth",
      },
    ],
  },
  windReading: {
    id: "windReading",
    duration: 3.6,
    skippableAfter: 0.8,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.7,
        camera: { anchorX: 350, viewDistance: 12.1, lift: 2.02, lookLift: 0.9, targetZ: -0.75 },
        actors: { player: "listen", followers: "shield" },
        caption: "第一阵风只动苇花，第二阵才压低整片苇梢。",
        soundCue: "wind",
      },
      {
        from: 1.7,
        to: 3.6,
        camera: { anchorX: 470, viewDistance: 15.4, lift: 2.38, lookLift: 1.02, targetZ: -1.2 },
        actors: { player: "signal", followers: "listen", followerStagger: 0.09 },
        caption: "阿苇举起两根手指。麦子学会在第三阵风里迈步。",
        soundCue: "soft",
      },
    ],
  },
  emptyBoatDiversion: {
    id: "emptyBoatDiversion",
    duration: 4.7,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.1,
        camera: { anchorX: 1100, viewDistance: 10.8, lift: 1.84, lookLift: 0.82, targetZ: -0.3 },
        actors: { player: "pull", followers: "shield" },
        effects: { emptyBoatRelease: [0, 0.35] },
        caption: "缆绳松开。空船先不走，像是在等最后一只手放开。",
        soundCue: "rope",
      },
      {
        from: 2.1,
        to: 4.7,
        camera: { anchorX: 980, viewDistance: 18.8, lift: 2.9, lookLift: 1.12, targetZ: -2.25 },
        actors: { player: "shield", followers: "peek" },
        effects: { emptyBoatRelease: [0.35, 1], searchlightDiversion: [0, 1] },
        caption: "木船撞响远处的桩。巡逻灯追着那条没有人的水路转开。",
        soundCue: "water",
      },
    ],
  },
  sluiceRise: {
    id: "sluiceRise",
    duration: 5.0,
    skippableAfter: 0.95,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.6,
        camera: { anchorX: 1735, viewDistance: 10.6, lift: 1.72, lookLift: 0.78, targetZ: -0.28 },
        actors: { player: "brace", followers: "shield" },
        effects: { bridgeRaise: [0, 0.42] },
        caption: "长杆不肯下去。阿苇把整个人的重量挂在上面。",
        soundCue: "wood",
      },
      {
        from: 2.6,
        to: 5.0,
        camera: { anchorX: 2040, viewDistance: 16.4, lift: 2.62, lookLift: 1.0, targetZ: -1.3 },
        actors: { player: "listen", followers: "peek" },
        effects: { bridgeRaise: [0.42, 1] },
        caption: "水托起旧门板。不是桥，只是一条暂时没有沉下去的路。",
        soundCue: "water",
      },
    ],
  },
  reedRoute: {
    id: "reedRoute",
    duration: 3.2,
    skippableAfter: 0.75,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.7,
        camera: { anchorX: 2960, viewDistance: 10.9, lift: 1.78, lookLift: 0.82, targetZ: -0.35 },
        actors: { player: "count", followers: "listen" },
        effects: { routeMarked: [0, 1] },
        caption: "三根苇梢折向北。没有碑，也没有署名。",
        soundCue: "wind",
      },
      {
        from: 1.7,
        to: 3.2,
        camera: { anchorX: 2820, viewDistance: 16.2, lift: 2.54, lookLift: 1.0, targetZ: -1.45 },
        actors: { player: "listen", followers: "peek" },
        effects: { routeMarked: 1 },
        caption: "后面的人看见它，就会知道这里曾有人走通。",
        soundCue: "soft",
      },
    ],
  },
  wellVent: {
    id: "wellVent",
    duration: 6.7,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.25,
        camera: { anchorX: [520, 625], viewDistance: [13.8, 9.5], lift: [2.02, 1.42], lookLift: [0.94, 0.7], targetZ: [-1.25, -0.18], fov: [24.6, 24.1] },
        actors: { player: { action: "lift", fear: 0.5 }, followers: { action: "shield", fear: 0.74 } },
        effects: { ventOpening: [0, 1], smokeRetreat: [0, 0.24] },
        caption: "井板上的土一层层落下来。上面的夜，终于漏进一线。",
        soundCue: "stone",
      },
      {
        from: 2.25,
        to: 4.25,
        camera: { anchorX: [625, 690], viewDistance: [9.5, 8.7], lift: [1.42, 1.28], lookLift: [0.7, 0.62], targetZ: [-0.18, 0.08], fov: [24.1, 24], cut: false },
        actors: { player: { action: "steadyChild", window: [0.08, 0.92], fear: 0.36 }, followers: "breatheRelief", followerFocusIndex: 0, followerFocusAction: { action: "suppressCough", window: [0.04, 0.76], fear: 0.7, lookOffset: -0.1 }, followerFocusFacing: -1, followerFocusX: 6.72 },
        blocking: { playerX: 6.08, playerFacing: 1, playerVelocity: 0 },
        effects: { ventOpening: 1, smokeRetreat: [0.24, 0.4] },
        caption: "风落下来。阿苇的手还按在麦子肩上。",
        soundCue: "wind",
      },
      {
        from: 4.25,
        to: 6.7,
        camera: { anchorX: [690, 1590], viewDistance: [8.7, 15.2], lift: [1.28, 2.18], lookLift: [0.62, 0.92], targetZ: [0.08, -1.7], fov: [24, 24.6], cut: false },
        actors: {
          player: { action: "listen", fear: 0.28, lookOffset: 0.08 },
          followers: { action: "breatheRelief", fear: 0.46 },
          followerStagger: 0.08,
          followerStandIns: [
            { index: 1, x: 1525, y: 0, z: 0.12, facing: 1 },
            { index: 2, x: 1570, y: 0, z: -0.12, facing: -1 },
            { index: 3, x: 1620, y: 0, z: -0.38, facing: 1 },
            { index: 4, x: 1670, y: 0, z: -0.64, facing: -1 },
          ],
        },
        effects: { ventOpening: 1, smokeRetreat: [0.4, 0.58] },
        caption: "更深处，四个还没有被找到的孩子，也在同一阵风里抬起头。",
        soundCue: "soft",
      },
    ],
  },
  sealCrack: {
    id: "sealCrack",
    duration: 4.2,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.2,
        camera: { anchorX: 1320, viewDistance: 9.9, lift: 1.42, lookLift: 0.7, targetZ: -0.18 },
        actors: { player: "push", followers: "shield" },
        effects: { crackSeal: [0, 1], smokeRetreat: [0.48, 0.78] },
        caption: "湿苇席贴上裂缝，烟转了方向，火星还在另一边发亮。",
        soundCue: "cloth",
      },
      {
        from: 2.2,
        to: 4.2,
        camera: { anchorX: 1480, viewDistance: 13.8, lift: 1.9, lookLift: 0.86, targetZ: -1.1 },
        actors: { player: "listen", followers: "peek" },
        effects: { crackSeal: 1, smokeRetreat: [0.78, 1] },
        caption: "黑暗里响起第一声咳嗽。有人还活着。",
        soundCue: "knock",
      },
    ],
  },
  shuanLift: {
    id: "shuanLift",
    duration: 4.1,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.25,
        camera: { anchorX: 1980, viewDistance: 9.8, lift: 1.42, lookLift: 0.7, targetZ: -0.15 },
        actors: { player: "lift", followers: "shield", followerStagger: 0.06 },
        effects: { shuanLift: [0, 1] },
        caption: "栓儿烧得说不出“到”，还是把手举过了额头。",
        soundCue: "soft",
      },
      {
        from: 2.25,
        to: 4.1,
        camera: { anchorX: 2040, viewDistance: 11.4, lift: 1.58, lookLift: 0.76, targetZ: -0.42 },
        actors: { player: "listen", followers: "count" },
        effects: { shuanLift: 1 },
        caption: "阿苇替他答了一声。其他孩子也跟着答。",
        soundCue: "knock",
      },
    ],
  },
  reedExit: {
    id: "reedExit",
    duration: 4.3,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.15,
        camera: { anchorX: 2740, viewDistance: 10.4, lift: 1.54, lookLift: 0.72, targetZ: -0.28 },
        actors: { player: "push", followers: "board", followerStagger: 0.1 },
        effects: { exitOpen: [0, 1] },
        caption: "苇根被推开。六个孩子一个接一个摸到夜风。",
        soundCue: "wind",
      },
      {
        from: 2.15,
        to: 4.3,
        camera: { anchorX: 2760, viewDistance: 17.2, lift: 2.52, lookLift: 1.0, targetZ: -1.7 },
        actors: { player: "count", followers: "count", followerStagger: 0.12 },
        effects: { exitOpen: 1 },
        caption: "阿苇没有数影子。她逐个叫名字，逐个等回应。",
        soundCue: "soft",
      },
    ],
  },
  ferryRollCall: {
    id: "ferryRollCall",
    duration: 4.5,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.4,
        camera: { anchorX: 360, viewDistance: 10.8, lift: 1.82, lookLift: 0.82, targetZ: -0.35 },
        actors: { player: "count", followers: "count", followerStagger: 0.12 },
        caption: "麦子。杏花。小锁。春妮。石头。栓儿。",
        soundCue: "soft",
      },
      {
        from: 2.4,
        to: 4.5,
        camera: { anchorX: 500, viewDistance: 14.8, lift: 2.32, lookLift: 0.96, targetZ: -1.1 },
        actors: { player: "listen", followers: "listen", followerStagger: 0.08 },
        caption: "六声“到”并不整齐。正因为不整齐，才知道不是回声。",
        soundCue: "wind",
      },
    ],
  },
  screenLift: {
    id: "screenLift",
    duration: 4.8,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.45,
        camera: { anchorX: 1040, viewDistance: 10.6, lift: 1.74, lookLift: 0.8, targetZ: -0.25 },
        actors: { player: "pull", followers: "shield" },
        effects: { screenRaise: [0, 0.72] },
        caption: "孩子们留在草垛后。灯下只有阿苇一个人的影子。",
        soundCue: "rope",
      },
      {
        from: 2.45,
        to: 4.8,
        camera: { anchorX: 1260, viewDistance: 16.6, lift: 2.62, lookLift: 1.02, targetZ: -1.55 },
        actors: { player: "brace", followers: "peek" },
        effects: { screenRaise: [0.72, 1] },
        caption: "苇障升到肩头时，六个小影子才重新动起来。",
        soundCue: "wind",
      },
    ],
  },
  tunnelRollCall: {
    id: "tunnelRollCall",
    duration: 8.8,
    skippableAfter: 1.0,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.4,
        camera: { anchorX: [1510, 1620], viewDistance: [17.6, 11.8], lift: [2.62, 1.7], lookLift: [1.06, 0.86], targetZ: [-2.2, -0.42], fov: [24.8, 24.1] },
        actors: { player: { action: "tap", window: [0.05, 0.88], fear: 0.42 }, followers: { action: "huddle", fear: 0.62 }, followerStagger: 0.08 },
        caption: "阿苇用指节敲了两下。不是暗号，是告诉黑暗里的人：我在等。",
        soundCue: "knock",
      },
      {
        from: 2.4,
        to: 4.7,
        camera: { anchorX: [1620, 1755], viewDistance: [11.8, 10.6], lift: [1.7, 1.52], lookLift: [0.86, 0.82], targetZ: [-0.42, -0.2], fov: [24.1, 24], cut: false },
        actors: { player: { action: "listen", fear: 0.38, lookOffset: 0.1 }, followers: { action: "count", fear: 0.5 }, followerStagger: 0.17 },
        caption: "杏花。小锁。春妮。石头。四声“到”贴着土壁，一声比一声近。",
        soundCue: "soft",
      },
      {
        from: 4.7,
        to: 6.8,
        camera: { anchorX: [1755, 1970], viewDistance: [10.6, 8.9], lift: [1.52, 1.32], lookLift: [0.82, 0.72], targetZ: [-0.2, 0.04], fov: [24, 23.9], cut: false },
        actors: { player: { action: "listen", fear: 0.44 }, followers: { action: "huddle", fear: 0.7 }, followerFocusIndex: 5, followerFocusAction: { action: "raiseHand", window: [0.08, 0.94], fear: 0.82, lookOffset: -0.14 } },
        caption: "“栓儿。”没有声音。最里面，一只发烫的小手慢慢举过了额头。",
        soundCue: "soft",
      },
      {
        from: 6.8,
        to: 8.8,
        camera: { anchorX: [1970, 1905], viewDistance: [8.9, 10.8], lift: [1.32, 1.56], lookLift: [0.72, 0.82], targetZ: [0.04, -0.28], fov: [23.9, 24.2], cut: false },
        actors: { player: { action: "steadyChild", window: [0.02, 0.9], fear: 0.34 }, followers: { action: "huddle", fear: 0.56 }, followerFocusIndex: 5, followerFocusAction: { action: "raiseHand", window: [0, 0.64], fear: 0.72 } },
        caption: "阿苇替他答：“到。”她扶住他，其他五只手也挨了过来。",
        soundCue: "cloth",
      },
    ],
  },
  tunnelHandoff: {
    id: "tunnelHandoff",
    duration: 3.8,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.25,
        camera: { anchorX: 2290, viewDistance: 10.8, lift: 1.48, lookLift: 0.82, targetZ: -0.08 },
        actors: { player: "pass", followers: "pass", followerStagger: 0.08 },
        caption: "井口伸下一双手。没有人问这孩子是哪一家的。",
        soundCue: "cloth",
      },
      {
        from: 2.25,
        to: 3.8,
        camera: { anchorX: 2350, viewDistance: 12.7, lift: 1.78, lookLift: 0.94, targetZ: -0.35 },
        actors: { player: "listen", followers: "peek" },
        caption: "手接住了，阿苇才松开。",
      },
    ],
  },
  motherHandoff: {
    id: "motherHandoff",
    duration: 8.8,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.0,
        camera: { anchorX: [1770, 1885], viewDistance: [14.8, 9.7], lift: [2.46, 1.8], lookLift: [1.02, 0.82], targetZ: [-1.35, 0.02], fov: [24.8, 24.1] },
        actors: { player: { action: "pass", fear: 0.18 }, followers: { action: "peek", fear: 0.28 }, mother: { action: "pass", fear: 0.16 } },
        caption: "周禾翻过六行。每个名字后面，都有一声不一样的“到”。",
        soundCue: "paper",
      },
      {
        from: 2.0,
        to: 4.2,
        camera: { anchorX: [1885, 1888], viewDistance: [9.7, 8.35], lift: [1.8, 1.58], lookLift: [0.82, 0.74], targetZ: [0.02, 0.12], fov: [24.1, 23.9], cut: false },
        actors: { player: { action: "touchName", window: [0.14, 0.9], fear: 0.2, lookOffset: -0.12 }, followers: "count", mother: { action: "write", window: [0.02, 0.64], fear: 0.12 } },
        caption: "周禾写下第七行：“阿苇。”阿苇的手指停在自己的名字上。",
        soundCue: "paper",
      },
      {
        from: 4.2,
        to: 6.7,
        camera: { anchorX: [1888, 1882], viewDistance: [8.35, 8.05], lift: [1.58, 1.54], lookLift: [0.74, 0.72], targetZ: [0.12, 0.08], fov: [23.9, 24], cut: false },
        actors: { player: { action: "receiveComfort", window: [0.04, 0.94], fear: 0.16 }, followers: "listen", mother: { action: "embrace", window: [0.02, 0.92], fear: 0.1 } },
        blocking: { playerX: 18.66, playerFacing: 1, playerVelocity: 0, motherX: 18.98, motherFacing: -1, motherVelocity: 0 },
        caption: "周禾抱住她。阿苇先僵住，才慢慢还回一只手。",
        soundCue: "soft",
      },
      {
        from: 6.7,
        to: 8.8,
        camera: { anchorX: [1882, 1935], viewDistance: [8.05, 11.6], lift: [1.54, 2.02], lookLift: [0.72, 0.9], targetZ: [0.08, -0.45], fov: [24, 24.4], cut: false },
        actors: { player: { action: "holdRegister", window: [0.06, 0.88], fear: 0.2, lookOffset: 0.1 }, followers: "listen", mother: { action: "goodbye", fear: 0.18, lookOffset: -0.08 } },
        blocking: { playerX: 18.66, playerFacing: 1, playerVelocity: 0, motherX: [18.98, 19.72], motherFacing: 1, motherVelocity: 0.3 },
        caption: "周禾松开手：“过河以后，把自己的名字也念出来。”",
        soundCue: "wind",
      },
    ],
  },
  motherSignal: {
    id: "motherSignal",
    duration: 4.7,
    skippableAfter: 0.95,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.0,
        camera: { anchorX: 2070, viewDistance: 11.9, lift: 2.24, lookLift: 0.98, targetZ: -0.25 },
        actors: { player: "shield", followers: "shield", mother: "signal" },
        effects: { signalWind: [0.2, 1] },
        caption: "白布先吃住了风，马灯才转向南汊。",
        soundCue: "bell",
      },
      {
        from: 2.0,
        to: 4.7,
        camera: { anchorX: 2350, viewDistance: 17.8, lift: 2.86, lookLift: 1.08, targetZ: -1.5 },
        actors: { player: "peek", followers: "peek", mother: "listen" },
        effects: { signalWind: [1, 0.65] },
        caption: "灯跟着她走远。渡口这边，六个孩子开始向前。",
        soundCue: "wind",
      },
    ],
  },
  endingDeparture: {
    id: "endingDeparture",
    duration: 21.6,
    skippableAfter: 2.4,
    lockInput: "all",
    blocksCompletion: true,
    blocksEnding: true,
    segments: [
      {
        from: 0,
        to: 3.0,
        camera: { anchorX: [3140, 3235], viewDistance: [16.4, 11.3], lift: [2.72, 1.98], lookLift: [1.08, 0.86], targetZ: [-1.5, 0.08], fov: [24.8, 24.1] },
        actors: { player: { action: "pass", fear: 0.3 }, followers: { action: "board", fear: 0.36 }, followerStagger: 0.18, mother: "listen" },
        blocking: { playerX: 32.42, playerFacing: 1, playerVelocity: 0 },
        effects: { boarding: [0, 0.7], playerBoarding: 0, ferryDeparture: 0, motherDeparture: 0 },
        caption: "麦子。杏花。小锁。春妮。石头。栓儿。",
        soundCue: "plank",
      },
      {
        from: 3.0,
        to: 5.4,
        camera: { anchorX: [3235, 3290], viewDistance: [11.3, 9.9], lift: [1.98, 1.78], lookLift: [0.86, 0.78], targetZ: [0.08, 0.16], fov: [24.1, 24], cut: false },
        actors: { player: { action: "reachGoodbye", window: [0.06, 0.96], fear: 0.32, lookOffset: -0.12 }, followers: { action: "board", fear: 0.3 }, followerStagger: 0.15, mother: "goodbye" },
        blocking: { playerX: 32.46, playerFacing: 1, playerVelocity: 0 },
        effects: { boarding: [0.7, 1], playerBoarding: 0, ferryDeparture: 0, motherDeparture: 0 },
        caption: "阿苇抬起手。周禾没有回头；那只手停在半空。",
        soundCue: "soft",
      },
      {
        from: 5.4,
        to: 8.4,
        camera: { anchorX: [3290, 3250], viewDistance: [9.9, 8.4], lift: [1.78, 1.5], lookLift: [0.78, 0.66], targetZ: [0.16, 0.2], fov: [24, 23.8], cut: false },
        actors: { player: { action: "writeKneel", window: [0.04, 0.94], fear: 0.24 }, followers: "huddle", mother: "goodbye" },
        blocking: { playerX: [32.46, 32.62], playerFacing: -1, playerVelocity: -0.08, playerCrouch: false, motherX: [23.4, 22.45], motherFacing: -1, motherVelocity: -0.42 },
        effects: { boarding: 1, playerBoarding: 0, ferryDeparture: 0, motherDeparture: [0, 0.2] },
        caption: "她收回手，在第八行写下“周禾”。",
        soundCue: "paper",
      },
      {
        from: 8.4,
        to: 11.2,
        camera: { anchorX: [3250, 3330], viewDistance: [8.4, 11], lift: [1.5, 1.94], lookLift: [0.66, 0.84], targetZ: [0.2, 0.04], fov: [23.8, 24.2], cut: false },
        actors: { player: { action: "board", fear: 0.22 }, followers: "huddle", mother: "goodbye" },
        blocking: { playerX: 32.64, playerFacing: 1, playerVelocity: 0.44, motherX: [22.45, 20.6], motherFacing: -1, motherVelocity: -0.58 },
        effects: { boarding: 1, playerBoarding: [0, 1], ferryDeparture: [0, 0.08], motherDeparture: [0.2, 0.48] },
        caption: "她把点名簿贴回胸口，最后一个跨过船板。",
        soundCue: "rope",
      },
      {
        from: 11.2,
        to: 14.2,
        camera: { anchorX: [3330, 3400], viewDistance: [11, 12.2], lift: [1.94, 2.16], lookLift: [0.84, 0.9], targetZ: [0.04, -0.3], fov: [24.2, 24.4], cut: false },
        actors: { player: { action: "answer", fear: 0.2, lookOffset: 0.08 }, followers: "count", followerStagger: 0.1, mother: "goodbye" },
        blocking: { playerFacing: -1, playerVelocity: 0, motherX: [20.6, 18.7], motherFacing: -1, motherVelocity: -0.58 },
        effects: { boarding: 1, playerBoarding: 1, ferryDeparture: [0.08, 0.25], motherDeparture: [0.48, 0.72] },
        caption: "麦子仰头叫：“阿苇姐。”阿苇停了一下，答：“到。”",
        soundCue: "soft",
      },
      {
        from: 14.2,
        to: 18.4,
        camera: { anchorX: [3400, 3600], viewDistance: [12.2, 23.5], lift: [2.16, 3.82], lookLift: [0.9, 1.24], targetZ: [-0.3, -3.9], fov: [24.4, 26], cut: false },
        actors: { player: { action: "holdRegister", window: [0.04, 0.9], fear: 0.18, lookOffset: -0.1 }, followers: "huddle", mother: "goodbye" },
        blocking: { playerFacing: -1, playerVelocity: 0, motherX: [18.7, 16.6], motherFacing: -1, motherVelocity: -0.48 },
        effects: { boarding: 1, playerBoarding: 1, ferryDeparture: [0.25, 1], motherDeparture: [0.72, 1] },
        caption: "船向北，灯向南。阿苇把第八行贴在胸口。",
        soundCue: "water",
      },
      {
        from: 18.4,
        to: 21.6,
        camera: { anchorX: [3600, 3810], viewDistance: [23.5, 31], lift: [3.82, 4.9], lookLift: [1.24, 1.42], targetZ: [-3.9, -6.2], fov: [26, 27], cut: false },
        actors: { player: { action: "holdRegister", fear: 0.14, lookOffset: -0.06 }, followers: "huddle", mother: "goodbye" },
        blocking: { playerFacing: -1, playerVelocity: 0, motherX: [16.6, 15.8], motherFacing: -1, motherVelocity: -0.34 },
        effects: { boarding: 1, playerBoarding: 1, ferryDeparture: 1, motherDeparture: 1 },
        caption: "河面只剩桨声。第八行没有划掉。",
        soundCue: "water",
      },
    ],
  },
});

export const ChapterOpeningCinematics = DeepFreeze({
  school: "schoolOpening",
  blockade: "blockadeOpening",
  tunnel: "tunnelOpening",
  ferry: "ferryOpening",
});

export const ActionCinematics = DeepFreeze({
  takeRegister: "registerHandoff",
  findMizi: "miziHandoff",
  dropBlind: "blindDrop",
  cartPlaced: "cartBrace",
  openDrain: "drainPassage",
  readWind: "windReading",
  releaseBoat: "emptyBoatDiversion",
  raiseSluice: "sluiceRise",
  markRoute: "reedRoute",
  openWellVent: "wellVent",
  sealEastCrack: "sealCrack",
  findChildren: "tunnelRollCall",
  liftShuan: "shuanLift",
  handShuanUp: "tunnelHandoff",
  openReedExit: "reedExit",
  countChildren: "ferryRollCall",
  raiseScreen: "screenLift",
  meetMother: "motherHandoff",
  motherSignal: "motherSignal",
  boardFerry: "endingDeparture",
});

export function GetCinematicSequence(sequenceId) {
  return CinematicSequences[sequenceId] || null;
}

export function GetChapterOpeningCinematic(chapterId) {
  return ChapterOpeningCinematics[chapterId] || null;
}

export function GetActionCinematic(actionId) {
  return ActionCinematics[actionId] || null;
}
