function DeepFreeze(value) {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  Object.freeze(value);
  for (const child of Object.values(value)) DeepFreeze(child);
  return value;
}

// These sequences never alter historical outcomes or gameplay rewards. They
// only reframe state that the rules layer has already produced, keeping the
// story in the same continuous 3D space as play.
export const CinematicSequences = DeepFreeze({
  schoolOpening: {
    id: "schoolOpening",
    duration: 7.4,
    skippableAfter: 0.9,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 2.1,
        camera: { anchorX: 330, viewDistance: 11.7, lift: 1.76, lookLift: 0.78, targetZ: -1.2 },
        actors: { player: "listen", mother: "write" },
        caption: "周禾在空教室里写下六个名字。每一笔，都对应一双没有坐在这里的鞋。",
        soundCue: "paper",
      },
      {
        from: 2.1,
        to: 4.8,
        camera: { anchorX: 470, viewDistance: 24.5, lift: 3.68, lookLift: 1.42, targetZ: -2.2, fov: 25.8 },
        actors: { player: "listen", mother: "count" },
        caption: "封锁线留下以后，村子还在，读书声先没有了。",
        soundCue: "wind",
      },
      {
        from: 4.8,
        to: 7.4,
        camera: { anchorX: 680, viewDistance: 15.2, lift: 2.42, lookLift: 1.02, targetZ: -0.72 },
        actors: { player: "shield", mother: "listen" },
        caption: "阿苇还不知道，天亮以前，这册簿子会多出两个名字。",
        soundCue: "soft",
      },
    ],
  },
  blockadeOpening: {
    id: "blockadeOpening",
    duration: 4.8,
    skippableAfter: 0.8,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 2.15,
        camera: { anchorX: 1450, viewDistance: 27.8, lift: 4.3, lookLift: 1.54, targetZ: -3.15, fov: 26.2 },
        actors: { player: "listen", followers: "peek" },
        caption: "沟、堤、岗楼，把村与村切成了几段。",
        soundCue: "water",
      },
      {
        from: 2.15,
        to: 4.8,
        camera: { anchorX: 360, viewDistance: 14.0, lift: 2.38, lookLift: 0.98, targetZ: -0.65 },
        actors: { player: "listen", followers: "shield" },
        caption: "阿苇不看灯，只看苇梢什么时候一起低头。",
        soundCue: "wind",
      },
    ],
  },
  tunnelOpening: {
    id: "tunnelOpening",
    duration: 4.7,
    skippableAfter: 0.8,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 2.1,
        camera: { anchorX: 1520, viewDistance: 19.4, lift: 2.92, lookLift: 1.3, targetZ: -2.75, fov: 25.4 },
        actors: { player: "listen", followers: "peek" },
        caption: "土层很薄，烟却会顺着每条裂缝往下找人。",
        soundCue: "smoke",
      },
      {
        from: 2.1,
        to: 4.7,
        camera: { anchorX: 590, viewDistance: 11.9, lift: 1.68, lookLift: 0.92, targetZ: -0.35 },
        actors: { player: "lift", followers: "shield" },
        caption: "先给烟一条向上的路，再去找黑暗里的回声。",
      },
    ],
  },
  ferryOpening: {
    id: "ferryOpening",
    duration: 5.2,
    skippableAfter: 0.9,
    lockInput: "all",
    segments: [
      {
        from: 0,
        to: 2.35,
        camera: { anchorX: 2300, viewDistance: 29.0, lift: 4.42, lookLift: 1.6, targetZ: -3.9, fov: 26.2 },
        actors: { player: "count", followers: "count", mother: "listen" },
        caption: "远岸有船，南汊有灯，中间是六个名字。",
        soundCue: "water",
      },
      {
        from: 2.35,
        to: 5.2,
        camera: { anchorX: 520, viewDistance: 14.4, lift: 2.4, lookLift: 1.0, targetZ: -0.7 },
        actors: { player: "count", followers: "peek", mother: "listen" },
        caption: "点名不是数数，是确认每个人还在。",
        soundCue: "soft",
      },
    ],
  },
  registerHandoff: {
    id: "registerHandoff",
    duration: 4.8,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.5,
        camera: { anchorX: 320, viewDistance: 10.4, lift: 1.68, lookLift: 0.82, targetZ: -0.55 },
        actors: { player: "pass", mother: "pass" },
        caption: "周禾合上点名簿，没有说“找回来”，只说：“见到一个，就应一个名字。”",
        soundCue: "paper",
      },
      {
        from: 2.5,
        to: 4.8,
        camera: { anchorX: 430, viewDistance: 13.8, lift: 2.12, lookLift: 0.96, targetZ: -0.85 },
        actors: { player: "shield", mother: "listen" },
        caption: "阿苇把簿子塞进衣襟。那时，上面还只有六行。",
        soundCue: "cloth",
      },
    ],
  },
  miziHandoff: {
    id: "miziHandoff",
    duration: 3.7,
    skippableAfter: 0.8,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.8,
        camera: { anchorX: 610, viewDistance: 9.8, lift: 1.58, lookLift: 0.76, targetZ: -0.32 },
        actors: { player: "lift", followers: "peek" },
        caption: "麦子缩在倒下的课桌后面，鞋丢了一只。",
        soundCue: "soft",
      },
      {
        from: 1.8,
        to: 3.7,
        camera: { anchorX: 660, viewDistance: 11.2, lift: 1.72, lookLift: 0.82, targetZ: -0.4 },
        actors: { player: "pass", followers: "listen", followerStagger: 0.08 },
        caption: "她没有哭，只攥住阿苇的袖口，说：“老师让我等名字来找我。”",
        soundCue: "cloth",
      },
    ],
  },
  blindDrop: {
    id: "blindDrop",
    duration: 3.4,
    skippableAfter: 0.75,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.65,
        camera: { anchorX: 820, viewDistance: 10.8, lift: 1.8, lookLift: 0.82, targetZ: -0.22 },
        actors: { player: "pull", followers: "shield" },
        effects: { blindDrop: [0, 1] },
        caption: "阿苇扯断草绳，旧苇帘带着一冬的灰落下来。",
        soundCue: "rope",
      },
      {
        from: 1.65,
        to: 3.4,
        camera: { anchorX: 930, viewDistance: 13.4, lift: 2.08, lookLift: 0.9, targetZ: -0.7 },
        actors: { player: "shield", followers: "peek" },
        effects: { blindDrop: 1 },
        caption: "灯光被挡住一瞬。她们用这一瞬，离开教室。",
        soundCue: "wind",
      },
    ],
  },
  cartBrace: {
    id: "cartBrace",
    duration: 3.6,
    skippableAfter: 0.8,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.1,
        camera: { anchorX: 1515, viewDistance: 10.6, lift: 1.72, lookLift: 0.78, targetZ: -0.18 },
        actors: { player: "push", followers: "shield" },
        effects: { cartSettle: [0, 1] },
        caption: "车轮一次次滑回泥里。麦子用肩膀抵住车帮，没有出声。",
        soundCue: "wood",
      },
      {
        from: 2.1,
        to: 3.6,
        camera: { anchorX: 1600, viewDistance: 12.2, lift: 1.92, lookLift: 0.86, targetZ: -0.42 },
        actors: { player: "brace", followers: "peek" },
        effects: { cartSettle: 1 },
        caption: "两个人的重量，刚好让车轮不再动。",
        soundCue: "soft",
      },
    ],
  },
  drainPassage: {
    id: "drainPassage",
    duration: 4.2,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.15,
        camera: { anchorX: 2535, viewDistance: 9.9, lift: 1.5, lookLift: 0.68, targetZ: -0.12 },
        actors: { player: "lift", followers: "board" },
        effects: { drainOpen: [0, 1] },
        caption: "石板抬起一道缝。阿苇先把那只光脚送进黑暗。",
        soundCue: "stone",
      },
      {
        from: 2.15,
        to: 4.2,
        camera: { anchorX: 2640, viewDistance: 12.4, lift: 1.76, lookLift: 0.78, targetZ: -0.6 },
        actors: { player: "board", followers: "listen" },
        effects: { drainOpen: 1 },
        caption: "麦子在洞里回头。阿苇最后一个钻进去。",
        soundCue: "cloth",
      },
    ],
  },
  windReading: {
    id: "windReading",
    duration: 3.6,
    skippableAfter: 0.8,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.7,
        camera: { anchorX: 350, viewDistance: 12.1, lift: 2.02, lookLift: 0.9, targetZ: -0.75 },
        actors: { player: "listen", followers: "shield" },
        caption: "第一阵风只动苇花，第二阵才压低整片苇梢。",
        soundCue: "wind",
      },
      {
        from: 1.7,
        to: 3.6,
        camera: { anchorX: 470, viewDistance: 15.4, lift: 2.38, lookLift: 1.02, targetZ: -1.2 },
        actors: { player: "signal", followers: "listen", followerStagger: 0.09 },
        caption: "阿苇举起两根手指。麦子学会在第三阵风里迈步。",
        soundCue: "soft",
      },
    ],
  },
  emptyBoatDiversion: {
    id: "emptyBoatDiversion",
    duration: 4.7,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.1,
        camera: { anchorX: 1100, viewDistance: 10.8, lift: 1.84, lookLift: 0.82, targetZ: -0.3 },
        actors: { player: "pull", followers: "shield" },
        effects: { emptyBoatRelease: [0, 0.35] },
        caption: "缆绳松开。空船先不走，像是在等最后一只手放开。",
        soundCue: "rope",
      },
      {
        from: 2.1,
        to: 4.7,
        camera: { anchorX: 980, viewDistance: 18.8, lift: 2.9, lookLift: 1.12, targetZ: -2.25 },
        actors: { player: "shield", followers: "peek" },
        effects: { emptyBoatRelease: [0.35, 1], searchlightDiversion: [0, 1] },
        caption: "木船撞响远处的桩。巡逻灯追着那条没有人的水路转开。",
        soundCue: "water",
      },
    ],
  },
  sluiceRise: {
    id: "sluiceRise",
    duration: 5.0,
    skippableAfter: 0.95,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.6,
        camera: { anchorX: 1735, viewDistance: 10.6, lift: 1.72, lookLift: 0.78, targetZ: -0.28 },
        actors: { player: "brace", followers: "shield" },
        effects: { bridgeRaise: [0, 0.42] },
        caption: "长杆不肯下去。阿苇把整个人的重量挂在上面。",
        soundCue: "wood",
      },
      {
        from: 2.6,
        to: 5.0,
        camera: { anchorX: 2040, viewDistance: 16.4, lift: 2.62, lookLift: 1.0, targetZ: -1.3 },
        actors: { player: "listen", followers: "peek" },
        effects: { bridgeRaise: [0.42, 1] },
        caption: "水托起旧门板。不是桥，只是一条暂时没有沉下去的路。",
        soundCue: "water",
      },
    ],
  },
  reedRoute: {
    id: "reedRoute",
    duration: 3.2,
    skippableAfter: 0.75,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.7,
        camera: { anchorX: 2960, viewDistance: 10.9, lift: 1.78, lookLift: 0.82, targetZ: -0.35 },
        actors: { player: "count", followers: "listen" },
        effects: { routeMarked: [0, 1] },
        caption: "三根苇梢折向北。没有碑，也没有署名。",
        soundCue: "wind",
      },
      {
        from: 1.7,
        to: 3.2,
        camera: { anchorX: 2820, viewDistance: 16.2, lift: 2.54, lookLift: 1.0, targetZ: -1.45 },
        actors: { player: "listen", followers: "peek" },
        effects: { routeMarked: 1 },
        caption: "后面的人看见它，就会知道这里曾有人走通。",
        soundCue: "soft",
      },
    ],
  },
  wellVent: {
    id: "wellVent",
    duration: 4.8,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.35,
        camera: { anchorX: 590, viewDistance: 9.8, lift: 1.46, lookLift: 0.72, targetZ: -0.2 },
        actors: { player: "lift", followers: "shield" },
        effects: { ventOpening: [0, 1], smokeRetreat: [0, 0.24] },
        caption: "井板上的土一层层落下来。上面的夜，终于漏进一线。",
        soundCue: "stone",
      },
      {
        from: 2.35,
        to: 4.8,
        camera: { anchorX: 760, viewDistance: 15.4, lift: 2.34, lookLift: 1.02, targetZ: -2.15 },
        actors: { player: "listen", followers: "count", followerStagger: 0.1 },
        effects: { ventOpening: 1, smokeRetreat: [0.24, 0.48] },
        caption: "孩子们先听见风，再敢吸下一口气。",
        soundCue: "wind",
      },
    ],
  },
  sealCrack: {
    id: "sealCrack",
    duration: 4.2,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.2,
        camera: { anchorX: 1320, viewDistance: 9.9, lift: 1.42, lookLift: 0.7, targetZ: -0.18 },
        actors: { player: "push", followers: "shield" },
        effects: { crackSeal: [0, 1], smokeRetreat: [0.48, 0.78] },
        caption: "湿苇席贴上裂缝，烟转了方向，火星还在另一边发亮。",
        soundCue: "cloth",
      },
      {
        from: 2.2,
        to: 4.2,
        camera: { anchorX: 1480, viewDistance: 13.8, lift: 1.9, lookLift: 0.86, targetZ: -1.1 },
        actors: { player: "listen", followers: "peek" },
        effects: { crackSeal: 1, smokeRetreat: [0.78, 1] },
        caption: "黑暗里响起第一声咳嗽。有人还活着。",
        soundCue: "knock",
      },
    ],
  },
  shuanLift: {
    id: "shuanLift",
    duration: 4.1,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.25,
        camera: { anchorX: 1980, viewDistance: 9.8, lift: 1.42, lookLift: 0.7, targetZ: -0.15 },
        actors: { player: "lift", followers: "shield", followerStagger: 0.06 },
        effects: { shuanLift: [0, 1] },
        caption: "栓儿烧得说不出“到”，还是把手举过了额头。",
        soundCue: "soft",
      },
      {
        from: 2.25,
        to: 4.1,
        camera: { anchorX: 2040, viewDistance: 11.4, lift: 1.58, lookLift: 0.76, targetZ: -0.42 },
        actors: { player: "listen", followers: "count" },
        effects: { shuanLift: 1 },
        caption: "阿苇替他答了一声。其他孩子也跟着答。",
        soundCue: "knock",
      },
    ],
  },
  reedExit: {
    id: "reedExit",
    duration: 4.3,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.15,
        camera: { anchorX: 2740, viewDistance: 10.4, lift: 1.54, lookLift: 0.72, targetZ: -0.28 },
        actors: { player: "push", followers: "board", followerStagger: 0.1 },
        effects: { exitOpen: [0, 1] },
        caption: "苇根被推开。六个孩子一个接一个摸到夜风。",
        soundCue: "wind",
      },
      {
        from: 2.15,
        to: 4.3,
        camera: { anchorX: 2760, viewDistance: 17.2, lift: 2.52, lookLift: 1.0, targetZ: -1.7 },
        actors: { player: "count", followers: "count", followerStagger: 0.12 },
        effects: { exitOpen: 1 },
        caption: "阿苇没有数影子。她逐个叫名字，逐个等回应。",
        soundCue: "soft",
      },
    ],
  },
  ferryRollCall: {
    id: "ferryRollCall",
    duration: 4.5,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.4,
        camera: { anchorX: 360, viewDistance: 10.8, lift: 1.82, lookLift: 0.82, targetZ: -0.35 },
        actors: { player: "count", followers: "count", followerStagger: 0.12 },
        caption: "麦子。杏花。小锁。春妮。石头。栓儿。",
        soundCue: "soft",
      },
      {
        from: 2.4,
        to: 4.5,
        camera: { anchorX: 500, viewDistance: 14.8, lift: 2.32, lookLift: 0.96, targetZ: -1.1 },
        actors: { player: "listen", followers: "listen", followerStagger: 0.08 },
        caption: "六声“到”并不整齐。正因为不整齐，才知道不是回声。",
        soundCue: "wind",
      },
    ],
  },
  screenLift: {
    id: "screenLift",
    duration: 4.8,
    skippableAfter: 0.9,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.45,
        camera: { anchorX: 1040, viewDistance: 10.6, lift: 1.74, lookLift: 0.8, targetZ: -0.25 },
        actors: { player: "pull", followers: "shield" },
        effects: { screenRaise: [0, 0.72] },
        caption: "孩子们留在草垛后。灯下只有阿苇一个人的影子。",
        soundCue: "rope",
      },
      {
        from: 2.45,
        to: 4.8,
        camera: { anchorX: 1260, viewDistance: 16.6, lift: 2.62, lookLift: 1.02, targetZ: -1.55 },
        actors: { player: "brace", followers: "peek" },
        effects: { screenRaise: [0.72, 1] },
        caption: "苇障升到肩头时，六个小影子才重新动起来。",
        soundCue: "wind",
      },
    ],
  },
  tunnelRollCall: {
    id: "tunnelRollCall",
    duration: 4.9,
    skippableAfter: 1.0,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.6,
        camera: { anchorX: 1620, viewDistance: 10.9, lift: 1.54, lookLift: 0.84, targetZ: -0.2 },
        actors: { player: "count", followers: "peek", followerStagger: 0.13 },
        caption: "杏花。小锁。春妮。石头。",
        soundCue: "soft",
      },
      {
        from: 1.6,
        to: 3.55,
        camera: { anchorX: 1760, viewDistance: 12.0, lift: 1.68, lookLift: 0.9, targetZ: -0.55 },
        actors: { player: "listen", followers: "count", followerStagger: 0.17 },
        caption: "黑暗里，四声轻轻的“到”。",
        soundCue: "knock",
      },
      {
        from: 3.55,
        to: 4.9,
        camera: { anchorX: 1980, viewDistance: 11.1, lift: 1.56, lookLift: 0.84, targetZ: -0.25 },
        actors: { player: "lift", followers: "shield" },
        caption: "第六个孩子没出声，只把手举了起来。",
      },
    ],
  },
  tunnelHandoff: {
    id: "tunnelHandoff",
    duration: 3.8,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.25,
        camera: { anchorX: 2290, viewDistance: 10.8, lift: 1.48, lookLift: 0.82, targetZ: -0.08 },
        actors: { player: "pass", followers: "pass", followerStagger: 0.08 },
        caption: "井口伸下一双手。没有人问这孩子是哪一家的。",
        soundCue: "cloth",
      },
      {
        from: 2.25,
        to: 3.8,
        camera: { anchorX: 2350, viewDistance: 12.7, lift: 1.78, lookLift: 0.94, targetZ: -0.35 },
        actors: { player: "listen", followers: "peek" },
        caption: "手接住了，阿苇才松开。",
      },
    ],
  },
  motherHandoff: {
    id: "motherHandoff",
    duration: 5.6,
    skippableAfter: 0.85,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 1.8,
        camera: { anchorX: 1900, viewDistance: 11.6, lift: 2.06, lookLift: 0.9, targetZ: -0.1 },
        actors: { player: "pass", followers: "peek", mother: "pass" },
        caption: "周禾翻过六行。每个名字后面，都有一声不一样的“到”。",
        soundCue: "paper",
      },
      {
        from: 1.8,
        to: 3.85,
        camera: { anchorX: 2040, viewDistance: 12.8, lift: 2.18, lookLift: 0.94, targetZ: -0.3 },
        actors: { player: "listen", followers: "count", mother: "write" },
        caption: "她在第七行写下“阿苇”，说：“你也还只是个孩子。”",
        soundCue: "paper",
      },
      {
        from: 3.85,
        to: 5.6,
        camera: { anchorX: 1980, viewDistance: 10.9, lift: 1.96, lookLift: 0.88, targetZ: -0.18 },
        actors: { player: "pass", followers: "listen", mother: "pass" },
        caption: "“过河以后，把自己的名字也念出来。”",
        soundCue: "soft",
      },
    ],
  },
  motherSignal: {
    id: "motherSignal",
    duration: 4.7,
    skippableAfter: 0.95,
    lockInput: "all",
    blocksCompletion: true,
    segments: [
      {
        from: 0,
        to: 2.0,
        camera: { anchorX: 2070, viewDistance: 11.9, lift: 2.24, lookLift: 0.98, targetZ: -0.25 },
        actors: { player: "shield", followers: "shield", mother: "signal" },
        effects: { signalWind: [0.2, 1] },
        caption: "白布先吃住了风，马灯才转向南汊。",
        soundCue: "bell",
      },
      {
        from: 2.0,
        to: 4.7,
        camera: { anchorX: 2350, viewDistance: 17.8, lift: 2.86, lookLift: 1.08, targetZ: -1.5 },
        actors: { player: "peek", followers: "peek", mother: "listen" },
        effects: { signalWind: [1, 0.65] },
        caption: "灯跟着她走远。渡口这边，六个孩子开始向前。",
        soundCue: "wind",
      },
    ],
  },
  endingDeparture: {
    id: "endingDeparture",
    duration: 13.4,
    skippableAfter: 2.4,
    lockInput: "all",
    blocksCompletion: true,
    blocksEnding: true,
    segments: [
      {
        from: 0,
        to: 2.55,
        camera: { anchorX: 3230, viewDistance: 12.8, lift: 2.18, lookLift: 0.92, targetZ: 0.05 },
        actors: { player: "pass", followers: "board", followerStagger: 0.18, mother: "listen" },
        effects: { boarding: [0, 0.55], playerBoarding: 0, ferryDeparture: 0 },
        caption: "麦子。杏花。小锁。春妮。石头。栓儿。",
        soundCue: "plank",
      },
      {
        from: 2.55,
        to: 4.9,
        camera: { anchorX: 3290, viewDistance: 11.8, lift: 2.05, lookLift: 0.86, targetZ: 0.12 },
        actors: { player: "count", followers: "board", followerStagger: 0.15, mother: "listen" },
        effects: { boarding: [0.55, 1], playerBoarding: 0, ferryDeparture: 0 },
        caption: "六声“到”，先过了船板。",
        soundCue: "soft",
      },
      {
        from: 4.9,
        to: 7.2,
        camera: { anchorX: 3310, viewDistance: 12.6, lift: 2.18, lookLift: 0.9, targetZ: 0.08 },
        actors: { player: "board", followers: "count", followerStagger: 0.11, mother: "signal" },
        effects: { boarding: 1, playerBoarding: [0, 1], ferryDeparture: [0, 0.08] },
        caption: "阿苇最后上船，把第七行贴在离心口最近的地方。",
        soundCue: "rope",
      },
      {
        from: 7.2,
        to: 9.55,
        camera: { anchorX: 3370, viewDistance: 12.2, lift: 2.16, lookLift: 0.9, targetZ: -0.08 },
        actors: { player: "count", followers: "count", followerStagger: 0.1, mother: "listen" },
        effects: { boarding: 1, playerBoarding: 1, ferryDeparture: [0.08, 0.24] },
        caption: "麦子仰头叫：“阿苇姐。”阿苇停了一下，答：“到。”",
        soundCue: "soft",
      },
      {
        from: 9.55,
        to: 13.4,
        camera: { anchorX: 3460, viewDistance: 21.5, lift: 3.52, lookLift: 1.24, targetZ: -2.55 },
        actors: { player: "listen", followers: "huddle", mother: "listen" },
        effects: { boarding: 1, playerBoarding: 1, ferryDeparture: [0.24, 1] },
        caption: "最后一行没有回应。阿苇没有划掉它。船向北，灯向南。",
        soundCue: "water",
      },
    ],
  },
});

export const ChapterOpeningCinematics = DeepFreeze({
  school: "schoolOpening",
  blockade: "blockadeOpening",
  tunnel: "tunnelOpening",
  ferry: "ferryOpening",
});

export const ActionCinematics = DeepFreeze({
  takeRegister: "registerHandoff",
  findMizi: "miziHandoff",
  dropBlind: "blindDrop",
  cartPlaced: "cartBrace",
  openDrain: "drainPassage",
  readWind: "windReading",
  releaseBoat: "emptyBoatDiversion",
  raiseSluice: "sluiceRise",
  markRoute: "reedRoute",
  openWellVent: "wellVent",
  sealEastCrack: "sealCrack",
  findChildren: "tunnelRollCall",
  liftShuan: "shuanLift",
  handShuanUp: "tunnelHandoff",
  openReedExit: "reedExit",
  countChildren: "ferryRollCall",
  raiseScreen: "screenLift",
  meetMother: "motherHandoff",
  motherSignal: "motherSignal",
  boardFerry: "endingDeparture",
});

export function GetCinematicSequence(sequenceId) {
  return CinematicSequences[sequenceId] || null;
}

export function GetChapterOpeningCinematic(chapterId) {
  return ChapterOpeningCinematics[chapterId] || null;
}

export function GetActionCinematic(actionId) {
  return ActionCinematics[actionId] || null;
}
