export const storyMetadata = {
  storyId: 'ashenRoute1942',
  title: '余烬交通线',
  englishTitle: 'Ashen Route 1942',
  chapterTitle: '天亮以前',
  dateLabel: '1942年9月下旬',
  placeLabel: '华北太行山东麓，虚构的槐树沟一带',
  targetPlaytimeSeconds: 930,
  playtimeRangeSeconds: [720, 1080],
  logline: '两名成年交通员必须在封锁合拢前，悄无声息地帮助一支村民转移队穿过旧灌渠，并决定秘密交通线是否还能继续使用。',
  pointOfView: 'thirdPersonLimited',
  tone: ['克制', '潮冷', '紧迫', '互相信任', '没有轻易的胜利'],
  originalityBoundary: '人物、地点、任务与对话均为原创；核心关系是两名有独立职责的成年基层工作者协作，不采用成人护送儿童的叙事结构。',
};

export const cast = [
  {
    characterId: 'zhaoTongcen',
    displayName: '赵同岑',
    age: 34,
    role: '玩家角色，县交通队线路员',
    background: '战前在正太铁路沿线做过道班修理工，熟悉涵洞、路基和简易机械。入队时间不长，懂路，却还不熟悉槐树沟每一户人。',
    dramaticNeed: '学会把“保住一条线”理解为保住线上的人和信任，而不是保住地图上的一笔。',
    speech: '句子短，先报观察再作判断；不用现代战术黑话，也不把沉默误作冷酷。',
    equipment: ['旧汉阳造步枪', '四发随身枪弹', '钢丝钳', '一卷麻绳', '个人用棉布急救包'],
  },
  {
    characterId: 'duXiangyun',
    displayName: '杜湘云',
    age: 39,
    role: '成人同伴，槐树沟交通站负责人兼乡村接生员',
    background: '靠接生和替人写信走熟周边村落。她掌握住户情况、夜间联络规矩与临时安置点位置，是本次转移的实际组织者。',
    dramaticNeed: '在照看眼前每个人与维持长期交通之间作出没有标准答案的判断。',
    agency: '主动带队、给出路线判断、完成分流与灯号，不作为等待玩家救援或发号施令的附属角色。',
    speech: '具体、平静，常用生活经验解释决定；紧张时反而说得更慢。',
    equipment: ['遮光油灯', '住户名册的记忆', '一把短柄镰刀', '两卷干净棉布'],
  },
  {
    characterId: 'miaoHuaisheng',
    displayName: '苗槐生',
    age: 62,
    role: '旧磨坊主人，第一批转移人员的带路者',
    background: '右耳听力很差，因此总先看人的嘴再回答。磨坊停转后，他把石槽当成交通线的无字信箱。',
    speech: '不煽情，不说大道理；只说天气、脚印、牲口和路。',
  },
  {
    characterId: 'heQin',
    displayName: '何芹',
    age: 28,
    role: '村中识字班教员，负责转移队尾部清点与照看伤员',
    background: '她把住户分成几个彼此认识的小组，避免夜路失散；不参加正面交火。',
    speech: '报人时用称呼不用数字，提醒玩家那些不是任务图标。',
  },
];

export const objectives = [
  {
    objectiveId: 'reachOldMill',
    text: '沿干河沟抵达旧磨坊',
    shortText: '抵达旧磨坊',
    compassTargetId: 'oldMill',
  },
  {
    objectiveId: 'readStoneSignal',
    text: '检查磨盘下的三颗石子，不要惊动村口',
    shortText: '核对交通线暗号',
    compassTargetId: 'millStoneSignal',
  },
  {
    objectiveId: 'meetStationKeeper',
    text: '跟随杜湘云进入槐树沟交通站',
    shortText: '进入交通站',
    compassTargetId: 'stationCellarDoor',
  },
  {
    objectiveId: 'prepareQuietPassage',
    text: '与杜湘云垫紧伤员车的车轴',
    shortText: '垫紧车轴',
    compassTargetId: 'handcartAxle',
  },
  {
    objectiveId: 'openEastGate',
    text: '用布裹住东侧小门的门闩，再放转移队出发',
    shortText: '打开东侧小门',
    compassTargetId: 'eastGateLatch',
  },
  {
    objectiveId: 'reachIrrigationDitch',
    text: '先于转移队抵达旧灌渠，观察封锁哨',
    shortText: '侦察旧灌渠',
    compassTargetId: 'ditchObservationPoint',
  },
  {
    objectiveId: 'disableWarningLine',
    text: '绕到封锁哨后方，剪断通往铜铃的警戒线',
    shortText: '切断警戒铃线',
    compassTargetId: 'warningLine',
  },
  {
    objectiveId: 'crossDrainageCulvert',
    text: '穿过排水洞，在北口等杜湘云的遮光灯号',
    shortText: '穿过排水洞',
    compassTargetId: 'drainageCulvert',
  },
  {
    objectiveId: 'holdKilnMouth',
    text: '守住废石灰窑入口，只争取转移所需的时间',
    shortText: '守住窑口',
    compassTargetId: 'limeKiln',
  },
  {
    objectiveId: 'waitForClearSignal',
    text: '等待“亮一下、灭两下”的全员通过灯号',
    shortText: '等待通过灯号',
    compassTargetId: 'limeKiln',
  },
  {
    objectiveId: 'decideRouteFate',
    text: '决定封住水洞，还是冒险重布假迹保留交通线',
    shortText: '决定交通线去留',
    compassTargetId: 'culvertDecisionPoint',
  },
  {
    objectiveId: 'reachSafeRidge',
    text: '与杜湘云沿北坡撤离',
    shortText: '沿北坡撤离',
    compassTargetId: 'northSlopeExit',
  },
];

export const companionHints = [
  {
    hintId: 'hintMillMark',
    speakerId: 'duXiangyun',
    text: '别只看石子。摸摸灶灰，今夜有没有人来过。',
    delaySeconds: 16,
    repeatAfterSeconds: 22,
  },
  {
    hintId: 'hintQuietPreparation',
    speakerId: 'duXiangyun',
    text: '我去分人。你把车轴和东门办妥，别替他们收拾家当。',
    delaySeconds: 18,
    repeatAfterSeconds: 28,
  },
  {
    hintId: 'hintCutWire',
    speakerId: 'duXiangyun',
    text: '铃线贴着矮墙走。你从高粱秆后面绕，我盯住巡沟的人。',
    delaySeconds: 20,
    repeatAfterSeconds: 30,
  },
  {
    hintId: 'hintRetreatKiln',
    speakerId: 'duXiangyun',
    text: '别追出去。窑壁能挡住路口，我们只守这几步。',
    delaySeconds: 8,
    repeatAfterSeconds: 18,
  },
  {
    hintId: 'hintRouteDecision',
    speakerId: 'duXiangyun',
    text: '先看人走远，再看这条路。没有哪一个选项替我们省掉代价。',
    delaySeconds: 22,
    repeatAfterSeconds: 30,
  },
];

export const narrativeEvents = [
  {
    id: 'eventApproachWhisper',
    title: '干河沟',
    objective: '沿干河沟抵达旧磨坊',
    subtitle: { speaker: '杜湘云', text: '灯别举过肩。东坡炮楼昨夜换了岗。', duration: 3.6 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '灯别举过肩。东坡炮楼昨夜换了岗。', duration: 3.6, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '磨盘下三颗石子。少一颗，我们就回头。', duration: 3.8, delay: 4.2 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '石头没少，也先别放心。人比暗号要紧。', duration: 3.7, delay: 8.5 },
    ],
    ambience: 'cueDistantBlockhouseShutter',
    urgency: 'low',
  },
  {
    id: 'eventMillSignalFound',
    title: '三颗石子',
    objective: '跟随杜湘云进入槐树沟',
    subtitle: { speaker: '赵同岑', text: '三颗都在，尖面朝北。灶灰还是温的。', duration: 4.1 },
    subtitles: [
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '三颗都在，尖面朝北。灶灰还是温的。', duration: 4.1, delay: 0 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '槐生昨晚来过。走，脚下别碰磨杆。', duration: 3.5, delay: 4.7 },
    ],
    ambience: 'cueMillWoodSettle',
    urgency: 'low',
    setFlags: ['millSignalRead'],
  },
  {
    id: 'eventVillageSeen',
    title: '没有鸡叫的村子',
    objective: '进入交通站',
    subtitle: { speaker: '赵同岑', text: '鸡笼开着，钟也包住了。村里已经在等。', duration: 4.0 },
    subtitles: [
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '鸡笼开着，钟也包住了。村里已经在等。', duration: 4.0, delay: 0 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '不是等我们，是等一个能走的时辰。', duration: 3.8, delay: 4.6 },
    ],
    ambience: 'cueWrappedAnimalBell',
    urgency: 'medium',
  },
  {
    id: 'eventStationKeeperFound',
    title: '交通站',
    objective: '听杜湘云说明转移办法',
    subtitle: { speaker: '苗槐生', text: '南岗先有车声，后来只剩鞋底蹭石头。至少两拨人。', duration: 4.8 },
    subtitles: [
      { speakerId: 'miaoHuaisheng', speaker: '苗槐生', text: '南岗先有车声，后来只剩鞋底蹭石头。至少两拨人。', duration: 4.8, delay: 0 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '卡车留在路上，巡逻已经下沟。我们提前半个时辰走。', duration: 4.8, delay: 5.4 },
      { speakerId: 'heQin', speaker: '何芹', text: '秀禾扶着她娘，槐生叔跟伤员，最后是我。不会把谁落成一个数。', duration: 5.2, delay: 10.8 },
    ],
    ambience: 'cueCellarBreathingRoom',
    urgency: 'medium',
    setFlags: ['stationReached'],
  },
  {
    id: 'eventEvacuationBrief',
    title: '分路',
    objective: '垫紧车轴并打开东侧小门',
    subtitle: { speaker: '杜湘云', text: '不抬箱柜，不赶牲口。每户只带被褥、炒面和自己的药。', duration: 5.0 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '不抬箱柜，不赶牲口。每户只带被褥、炒面和自己的药。', duration: 5.0, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '我从旧灌渠先走，剪铃线。你带人到水洞南口。', duration: 4.5, delay: 5.6 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '我亮一下、灭两下，才是全过去了。别把别的光当成我。', duration: 4.9, delay: 10.7 },
    ],
    ambience: 'cueClothBundlesLifted',
    urgency: 'medium',
    setFlags: ['evacuationBriefed'],
  },
  {
    id: 'eventCartMuffled',
    title: '车轮不叫',
    objective: '打开东侧小门',
    subtitle: { speaker: '杜湘云', text: '毡条塞紧，轴上只抹这一勺油。够它安静到北坡。', duration: 4.7 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '毡条塞紧，轴上只抹这一勺油。够它安静到北坡。', duration: 4.7, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '过了北坡就得换轴套。', duration: 2.6, delay: 5.2 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '过了北坡再修。先让它过北坡。', duration: 3.2, delay: 8.3 },
    ],
    ambience: 'cueCartAxleMuted',
    urgency: 'medium',
    setFlags: ['cartMuffled'],
  },
  {
    id: 'eventEastGateOpened',
    title: '小门',
    objective: '先于转移队抵达旧灌渠',
    subtitle: { speaker: '何芹', text: '门外没有说话声。我们按住户分开走，不拉成长队。', duration: 4.8 },
    subtitles: [
      { speakerId: 'heQin', speaker: '何芹', text: '门外没有说话声。我们按住户分开走，不拉成长队。', duration: 4.8, delay: 0 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '同岑，前面交给你。后面交给我。', duration: 3.2, delay: 5.4 },
    ],
    ambience: 'cueWoodLatchWrapped',
    urgency: 'medium',
    setFlags: ['eastGateOpen', 'convoyMoving'],
  },
  {
    id: 'eventPatrolCounted',
    title: '封锁哨',
    objective: '绕到封锁哨后方，剪断警戒铃线',
    subtitle: { speaker: '赵同岑', text: '两个沿沟走，一个守棚。铃线贴着矮墙。', duration: 4.1 },
    subtitles: [
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '两个沿沟走，一个守棚。铃线贴着矮墙。', duration: 4.1, delay: 0 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '不跟他们耗。剪断它，给后面留一条黑路。', duration: 4.0, delay: 4.7 },
    ],
    ambience: 'cuePatrolBootsOnGravel',
    urgency: 'high',
    setFlags: ['blockadeObserved'],
  },
  {
    id: 'eventWarningLineCut',
    title: '铃不再响',
    objective: '穿过排水洞，在北口等待灯号',
    subtitle: { speaker: '赵同岑', text: '铃线断了。南口还有一盏遮着的灯。', duration: 3.8 },
    subtitles: [
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '铃线断了。南口还有一盏遮着的灯。', duration: 3.8, delay: 0 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '那是我。你先过，我们隔着人群说话。', duration: 3.7, delay: 4.4 },
    ],
    ambience: 'cueWireTensionRelease',
    urgency: 'high',
    setFlags: ['warningLineCut'],
  },
  {
    id: 'eventBlockadeSpotted',
    title: '枪声会留下路',
    objective: '脱离视线，退向废石灰窑',
    subtitle: { speaker: '杜湘云', text: '枪声一响，他们就会往路上找。别恋战，退到窑壁！', duration: 4.6 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '枪声一响，他们就会往路上找。别恋战，退到窑壁！', duration: 4.6, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '只打挡路的人，不追。', duration: 2.9, delay: 5.1 },
    ],
    ambience: 'cueBlockadeAlarmMuffled',
    urgency: 'critical',
    incrementCounters: { alertLevel: 1 },
  },
  {
    id: 'eventCulvertSignal',
    title: '水洞北口',
    objective: '守住废石灰窑入口',
    subtitle: { speaker: '杜湘云', text: '第一拨过去了。还有伤员的车，别让巡沟的人靠近洞口。', duration: 4.8 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '第一拨过去了。还有伤员的车，别让巡沟的人靠近洞口。', duration: 4.8, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '我守窑口。你不用回来接我。', duration: 3.2, delay: 5.4 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '我不回来接你。我回来把这件事做完。', duration: 3.8, delay: 9.1 },
    ],
    ambience: 'cueCulvertWaterAndCart',
    urgency: 'high',
    setFlags: ['firstGroupClear'],
  },
  {
    id: 'eventKilnRearGuard',
    title: '只守几步',
    objective: '争取灯号出现前的时间',
    subtitle: { speaker: '杜湘云', text: '窑壁能挡住路口。别往前，我们只守这几步。', duration: 4.2 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '窑壁能挡住路口。别往前，我们只守这几步。', duration: 4.2, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '等灯，不数枪。', duration: 2.4, delay: 4.8 },
    ],
    ambience: 'cueKilnDustFall',
    urgency: 'critical',
  },
  {
    id: 'eventCombatRestraint',
    title: '不追',
    objective: '等待通过灯号',
    subtitle: { speaker: '杜湘云', text: '别追。听后面——车轮还在动，人还没过完。', duration: 4.2 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '别追。听后面——车轮还在动，人还没过完。', duration: 4.2, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '明白。守沟口，不往前。', duration: 3.0, delay: 4.8 },
    ],
    ambience: 'cueDistantCartWheel',
    urgency: 'high',
  },
  {
    id: 'eventCiviliansClear',
    title: '亮一下，灭两下',
    objective: '决定交通线去留',
    subtitle: { speaker: '杜湘云', text: '人都过了。现在才轮到这条路。', duration: 3.5 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '人都过了。现在才轮到这条路。', duration: 3.5, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '天亮还剩多久？', duration: 2.2, delay: 4.1 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '够封洞。也只够做一次假迹。', duration: 3.2, delay: 6.8 },
    ],
    ambience: 'cueShutteredLampSignal',
    urgency: 'medium',
    setFlags: ['allCiviliansClear'],
  },
  {
    id: 'eventRouteDecision',
    title: '留下什么',
    objective: '封住水洞，或重布假迹',
    subtitle: { speaker: '杜湘云', text: '封上，今晚稳妥，东线从此断；不封，我们得再走回亮处一次。', duration: 5.6 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '封上，今晚稳妥，东线从此断；不封，我们得再走回亮处一次。', duration: 5.6, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '人已经安全。这个险，只算在我们两个人身上。', duration: 4.2, delay: 6.2 },
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '我想留它，药还要从这里过。真压不住就封——你看过岗哨，你说还能不能骗。', duration: 5.2, delay: 11.0 },
    ],
    ambience: 'cueDawnWindInReeds',
    urgency: 'decision',
    setFlags: ['routeDecisionReady'],
  },
  {
    id: 'eventEndingSeal',
    title: '结局：路可以重接',
    objective: '前往北坡临时安置点',
    subtitle: { speaker: '杜湘云', text: '路断了，人还在。等风头过去，我们从别处再接。', duration: 4.6 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '路断了，人还在。等风头过去，我们从别处再接。', duration: 4.6, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '记下北坡第三棵枣树。下一条线，从那里量。', duration: 4.3, delay: 5.2 },
    ],
    ambience: 'cueCulvertStoneCollapse',
    urgency: 'resolved',
    setFlags: ['culvertSealed', 'endingRouteBroken'],
    endCard: '苗槐生把伤员车停在北坡第三棵枣树下。何芹等秀禾扶母亲走上坡，又回身摸了摸伤员身上的被角。东线就此停用；此后数周，交通员从两道山梁外重新接路。',
  },
  {
    id: 'eventEndingPreserve',
    title: '结局：灰往东，脚印往西',
    objective: '沿北坡撤离',
    subtitle: { speaker: '杜湘云', text: '灰往东飘，脚印往西。只够骗他们一回。', duration: 4.2 },
    subtitles: [
      { speakerId: 'duXiangyun', speaker: '杜湘云', text: '灰往东飘，脚印往西。只够骗他们一回。', duration: 4.2, delay: 0 },
      { speakerId: 'zhaoTongcen', speaker: '赵同岑', text: '一回够把下一批药送过来。以后每回都得先走空路。', duration: 4.8, delay: 4.8 },
    ],
    ambience: 'cueFalseTrailRake',
    urgency: 'resolved',
    setFlags: ['falseTrailLaid', 'endingRoutePreserved'],
    endCard: '何芹在北坡等到最后一户走出沟口，苗槐生俯身给伤员车补上轴油。巡逻追向废石窑，东线仍可使用；从此，每次过线都必须有人先走一遍空路。',
  },
];

export const runtimeStageDialogueEvents = [
  {
    id: 'stageDialogueReachOldMill',
    stageId: 'reachOldMill',
    dialogue: [
      { speaker: '杜湘云', text: '灯别举过肩。东坡炮楼昨夜换了岗。', durationSeconds: 3.6 },
      { speaker: '赵同岑', text: '先到磨坊。暗号对，也要看有没有人来过。', durationSeconds: 4.0 },
    ],
  },
  {
    id: 'stageDialogueReadStoneSignal',
    stageId: 'readStoneSignal',
    dialogue: [
      { speaker: '赵同岑', text: '三颗石子，尖面朝北。', durationSeconds: 2.8 },
      { speaker: '杜湘云', text: '再摸灶灰。人比暗号要紧。', durationSeconds: 3.2 },
    ],
  },
  {
    id: 'stageDialogueMeetStationKeeper',
    stageId: 'meetStationKeeper',
    dialogue: [
      { speaker: '杜湘云', text: '鸡笼开着，铃也包住了。村里已经开始走。', durationSeconds: 4.2 },
      { speaker: '赵同岑', text: '我去交通站听清路，你去看每一户。', durationSeconds: 3.6 },
    ],
  },
  {
    id: 'stageDialoguePrepareQuietPassage',
    stageId: 'prepareQuietPassage',
    dialogue: [
      { speaker: '杜湘云', text: '毡条先垫车轴。别替他们收拾家当。', durationSeconds: 4.2 },
      { speaker: '赵同岑', text: '只让车轮安静，不碰他们留下的东西。', durationSeconds: 3.8 },
    ],
  },
  {
    id: 'stageDialogueOpenEastGate',
    stageId: 'openEastGate',
    dialogue: [
      { speaker: '杜湘云', text: '再去东门。门闩也裹住，何芹才会带后队出院。', durationSeconds: 4.8 },
      { speaker: '赵同岑', text: '我开门，你按住车。门外安静再走。', durationSeconds: 3.7 },
    ],
  },
  {
    id: 'stageDialogueReachIrrigationDitch',
    stageId: 'reachIrrigationDitch',
    dialogue: [
      { speaker: '赵同岑', text: '两个沿沟走，一个守棚。先等他们错开。', durationSeconds: 4.0 },
      { speaker: '杜湘云', text: '我看南口。你只管铃线，别把巡逻往人群带。', durationSeconds: 4.3 },
    ],
  },
  {
    id: 'stageDialogueDisableWarningLine',
    stageId: 'disableWarningLine',
    dialogue: [
      { speaker: '杜湘云', text: '铃线贴着矮墙走。等守棚的人转身。', durationSeconds: 3.6 },
      { speaker: '赵同岑', text: '剪断就退，不在哨口停。', durationSeconds: 2.8 },
    ],
  },
  {
    id: 'stageDialogueCrossDrainageCulvert',
    stageId: 'crossDrainageCulvert',
    dialogue: [
      { speaker: '杜湘云', text: '第一拨已经到南口。水响的时候走，水停就停。', durationSeconds: 4.7 },
      { speaker: '赵同岑', text: '我在北口等你的灯。', durationSeconds: 2.6 },
    ],
  },
  {
    id: 'stageDialogueHoldKilnMouth',
    stageId: 'holdKilnMouth',
    dialogue: [
      { speaker: '杜湘云', text: '窑壁能挡住路口。别往前，我们只守这几步。', durationSeconds: 4.2 },
      { speaker: '赵同岑', text: '等灯，不数枪。', durationSeconds: 2.4 },
    ],
  },
  {
    id: 'stageDialogueWaitForClearSignal',
    stageId: 'waitForClearSignal',
    dialogue: [
      { speaker: '杜湘云', text: '听后面。车轮还在动，人还没过完。', durationSeconds: 3.7 },
      { speaker: '赵同岑', text: '我不追。守到亮一下、灭两下。', durationSeconds: 3.5 },
    ],
  },
  {
    id: 'stageDialogueDecideRouteFate',
    stageId: 'decideRouteFate',
    dialogue: [
      { speaker: '杜湘云', text: '人都过了。封洞，今晚稳妥；留线，我们还得再走回亮处一次。', durationSeconds: 5.6 },
      { speaker: '赵同岑', text: '人已经安全。这个险，只算在我们两个人身上。', durationSeconds: 4.2 },
    ],
  },
  {
    id: 'stageDialogueReachSafeRidge',
    stageId: 'reachSafeRidge',
    dialogue: [
      { speaker: '杜湘云', text: '天快亮了。北坡还有一段。', durationSeconds: 3.0 },
      { speaker: '赵同岑', text: '前面的人不会等我们报数。走吧。', durationSeconds: 3.5 },
    ],
  },
];

export const storyEvents = [...narrativeEvents, ...runtimeStageDialogueEvents];

export const narrativeActs = [
  {
    stageId: 'readTheRoute',
    title: '石磨下的三颗石子',
    objectiveId: 'reachOldMill',
    entryTriggerId: 'triggerLevelStart',
    exitTriggerId: 'triggerVillageThreshold',
    checkpointId: 'checkpointRavine',
    targetSeconds: 105,
    aiZoneIds: [],
    beats: [
      { beatId: 'beatApproachWhisper', eventId: 'eventApproachWhisper', kind: 'walkAndTalk', targetSeconds: 34, intensity: 0.12, allowCombat: false, resourcePressure: 0, companionHintId: 'hintMillMark' },
      { beatId: 'beatReadMillSignal', eventId: 'eventMillSignalFound', kind: 'inspect', targetSeconds: 48, intensity: 0.2, allowCombat: false, resourcePressure: 0, companionHintId: 'hintMillMark' },
    ],
    failureAndCosts: ['Leaving the ravine raises distant suspicion but does not fail the mission.', 'No combat is permitted in this stage.'],
  },
  {
    stageId: 'wakeTheVillage',
    title: '没有鸡叫的村子',
    objectiveId: 'meetStationKeeper',
    entryTriggerId: 'triggerVillageThreshold',
    exitTriggerId: 'triggerEvacuationBriefComplete',
    checkpointId: 'checkpointVillageLane',
    targetSeconds: 150,
    aiZoneIds: ['villageEdgePatrolZone'],
    beats: [
      { beatId: 'beatReadVillageSilence', eventId: 'eventVillageSeen', kind: 'environmentalRead', targetSeconds: 42, intensity: 0.28, allowCombat: false, resourcePressure: 0, companionHintId: null },
      { beatId: 'beatMeetTheStation', eventId: 'eventStationKeeperFound', kind: 'dialogue', targetSeconds: 45, intensity: 0.36, allowCombat: false, resourcePressure: 0, companionHintId: null },
      { beatId: 'beatPlanTheEvacuation', eventId: 'eventEvacuationBrief', kind: 'briefingInMotion', targetSeconds: 48, intensity: 0.42, allowCombat: false, resourcePressure: 0.08, companionHintId: 'hintQuietPreparation' },
    ],
    failureAndCosts: ['Entering an occupied house is blocked; domestic property is not a loot space.', 'A patrol glimpse adds alert without depicting harm to villagers.'],
  },
  {
    stageId: 'prepareThePassage',
    title: '让车轮安静',
    objectiveId: 'prepareQuietPassage',
    entryTriggerId: 'triggerEvacuationBriefComplete',
    exitTriggerId: 'triggerEastGateOpened',
    checkpointId: 'checkpointStationYard',
    targetSeconds: 155,
    aiZoneIds: ['villageEdgePatrolZone'],
    beats: [
      { beatId: 'beatMuffleCart', eventId: 'eventCartMuffled', kind: 'companionInteraction', targetSeconds: 55, intensity: 0.4, allowCombat: false, resourcePressure: 0.1, companionHintId: 'hintQuietPreparation' },
      { beatId: 'beatOpenEastGate', eventId: 'eventEastGateOpened', kind: 'traversalPreparation', targetSeconds: 62, intensity: 0.48, allowCombat: false, resourcePressure: 0.12, companionHintId: 'hintQuietPreparation' },
    ],
    failureAndCosts: ['Forcing the gate makes noise and raises alertLevel by one; it never creates a civilian casualty counter.', 'The convoy waits off camera until the passage is ready.'],
  },
  {
    stageId: 'crossTheBlockade',
    title: '铃线以北',
    objectiveId: 'reachIrrigationDitch',
    entryTriggerId: 'triggerEastGateOpened',
    exitTriggerId: 'triggerCulvertNorthMouth',
    checkpointId: 'checkpointDryDitch',
    targetSeconds: 265,
    aiZoneIds: ['villageEdgePatrolZone', 'blockadePostZone'],
    beats: [
      { beatId: 'beatCountPatrol', eventId: 'eventPatrolCounted', kind: 'stealthObservation', targetSeconds: 55, intensity: 0.62, allowCombat: false, resourcePressure: 0.22, companionHintId: 'hintCutWire' },
      { beatId: 'beatDisableAlarm', eventId: 'eventWarningLineCut', kind: 'stealthInfiltration', targetSeconds: 105, intensity: 0.76, allowCombat: true, resourcePressure: 0.5, companionHintId: 'hintCutWire' },
      { beatId: 'beatCrossCulvert', eventId: 'eventCulvertSignal', kind: 'crouchTraversal', targetSeconds: 62, intensity: 0.66, allowCombat: false, resourcePressure: 0.32, companionHintId: null },
    ],
    failureAndCosts: ['Detection is recoverable through disengagement; gunfire raises alertLevel and changes the final encounter.', 'The warning line can be bypassed, but doing so forces the routeSealed ending.'],
  },
  {
    stageId: 'buyTheMinutes',
    title: '只守这几步',
    objectiveId: 'holdKilnMouth',
    entryTriggerId: 'triggerCulvertNorthMouth',
    exitTriggerId: 'triggerAllCiviliansClear',
    checkpointId: 'checkpointLimeKiln',
    targetSeconds: 165,
    aiZoneIds: ['blockadePostZone', 'kilnPursuitZone'],
    beats: [
      { beatId: 'beatTakeKilnPosition', eventId: 'eventKilnRearGuard', kind: 'defensiveReposition', targetSeconds: 38, intensity: 0.82, allowCombat: true, resourcePressure: 0.64, companionHintId: 'hintRetreatKiln' },
      { beatId: 'beatLimitedRearGuard', eventId: 'eventCombatRestraint', kind: 'limitedCombatOrEvasion', targetSeconds: 82, intensity: 0.92, allowCombat: true, resourcePressure: 0.82, companionHintId: 'hintRetreatKiln' },
      { beatId: 'beatWatchTheSignal', eventId: 'eventCiviliansClear', kind: 'release', targetSeconds: 30, intensity: 0.35, allowCombat: false, resourcePressure: 0.2, companionHintId: null },
    ],
    failureAndCosts: ['There are no endless waves and no reward for pursuing retreating enemies.', 'If an enemy reaches the protected corridor, the scene resets before any civilian violence is shown or counted.'],
  },
  {
    stageId: 'chooseWhatRemains',
    title: '留下什么',
    objectiveId: 'decideRouteFate',
    entryTriggerId: 'triggerAllCiviliansClear',
    exitTriggerId: 'triggerEndingExit',
    checkpointId: 'checkpointRouteDecision',
    targetSeconds: 90,
    aiZoneIds: [],
    beats: [
      { beatId: 'beatRouteDecision', eventId: 'eventRouteDecision', kind: 'branchChoice', targetSeconds: 40, intensity: 0.3, allowCombat: false, resourcePressure: 0, companionHintId: 'hintRouteDecision' },
      { beatId: 'beatEndingWalk', eventId: 'eventEndingSeal', alternateEventIds: ['eventEndingPreserve'], kind: 'consequenceWalk', targetSeconds: 40, intensity: 0.16, allowCombat: false, resourcePressure: 0, companionHintId: null },
    ],
    failureAndCosts: ['Both endings keep the evacuees safe; the choice concerns immediate concealment versus future route capacity.', 'Neither ending is labeled good, bad, heroic, or cowardly.'],
  },
];

export const missionStages = [
  {
    stageId: 'reachOldMill',
    macroActId: 'readTheRoute',
    title: '无灯的磨坊',
    objectiveId: 'reachOldMill',
    targetId: 'oldMill',
    mode: 'reach',
    radius: 7,
    entryTriggerId: 'triggerLevelStart',
    exitTriggerId: 'triggerOldMillApproach',
    checkpointId: 'checkpointRavine',
    targetSeconds: 85,
    aiZoneIds: [],
    beats: [
      { beatId: 'beatApproachWhisperRuntime', eventId: 'eventApproachWhisper', kind: 'walkAndTalk', targetSeconds: 60, intensity: 0.12, allowCombat: false, resourcePressure: 0, companionHintId: 'hintMillMark' },
    ],
  },
  {
    stageId: 'readStoneSignal',
    macroActId: 'readTheRoute',
    title: '三颗石子',
    objectiveId: 'readStoneSignal',
    targetId: 'millStoneSignal',
    mode: 'interact',
    radius: 3.2,
    entryTriggerId: 'triggerOldMillApproach',
    exitTriggerId: 'triggerMillSignalRead',
    checkpointId: 'checkpointRavine',
    targetSeconds: 45,
    aiZoneIds: [],
    beats: [
      { beatId: 'beatReadMillSignalRuntime', eventId: 'eventMillSignalFound', kind: 'inspect', targetSeconds: 35, intensity: 0.2, allowCombat: false, resourcePressure: 0, companionHintId: 'hintMillMark' },
    ],
  },
  {
    stageId: 'meetStationKeeper',
    macroActId: 'wakeTheVillage',
    title: '没有鸡叫的村子',
    objectiveId: 'meetStationKeeper',
    targetId: 'stationCellarDoor',
    mode: 'interact',
    radius: 3.2,
    entryTriggerId: 'triggerVillageThreshold',
    exitTriggerId: 'triggerStationDoor',
    checkpointId: 'checkpointVillageLane',
    targetSeconds: 115,
    aiZoneIds: ['villageEdgePatrolZone'],
    beats: [
      { beatId: 'beatReadVillageSilenceRuntime', eventId: 'eventVillageSeen', kind: 'environmentalRead', targetSeconds: 42, intensity: 0.28, allowCombat: false, resourcePressure: 0, companionHintId: null },
      { beatId: 'beatMeetTheStationRuntime', eventId: 'eventStationKeeperFound', kind: 'dialogue', targetSeconds: 45, intensity: 0.36, allowCombat: false, resourcePressure: 0, companionHintId: null },
    ],
  },
  {
    stageId: 'prepareQuietPassage',
    macroActId: 'prepareThePassage',
    title: '垫住车轴',
    objectiveId: 'prepareQuietPassage',
    targetId: 'handcartAxle',
    mode: 'interact',
    radius: 3.4,
    entryTriggerId: 'triggerEvacuationBriefComplete',
    exitTriggerId: 'triggerCartMuffled',
    checkpointId: 'checkpointStationYard',
    targetSeconds: 105,
    aiZoneIds: ['villageEdgePatrolZone'],
    beats: [
      { beatId: 'beatPlanEvacuationRuntime', eventId: 'eventEvacuationBrief', kind: 'briefingInMotion', targetSeconds: 38, intensity: 0.4, allowCombat: false, resourcePressure: 0.08, companionHintId: 'hintQuietPreparation' },
      { beatId: 'beatMuffleCartRuntime', eventId: 'eventCartMuffled', kind: 'companionInteraction', targetSeconds: 46, intensity: 0.45, allowCombat: false, resourcePressure: 0.1, companionHintId: 'hintQuietPreparation' },
    ],
  },
  {
    stageId: 'openEastGate',
    macroActId: 'prepareThePassage',
    title: '东侧小门',
    objectiveId: 'openEastGate',
    targetId: 'eastGateLatch',
    mode: 'interact',
    radius: 3.2,
    entryTriggerId: 'triggerCartMuffled',
    exitTriggerId: 'triggerEastGateOpened',
    checkpointId: 'checkpointStationYard',
    targetSeconds: 50,
    aiZoneIds: ['villageEdgePatrolZone'],
    beats: [
      { beatId: 'beatOpenEastGateRuntime', eventId: 'eventEastGateOpened', kind: 'traversalPreparation', targetSeconds: 38, intensity: 0.48, allowCombat: false, resourcePressure: 0.12, companionHintId: 'hintQuietPreparation' },
    ],
  },
  {
    stageId: 'reachIrrigationDitch',
    macroActId: 'crossTheBlockade',
    title: '先听再走',
    objectiveId: 'reachIrrigationDitch',
    targetId: 'ditchObservationPoint',
    mode: 'interact',
    radius: 3.4,
    entryTriggerId: 'triggerEastGateOpened',
    exitTriggerId: 'triggerDitchObservation',
    checkpointId: 'checkpointDryDitch',
    targetSeconds: 85,
    aiZoneIds: ['villageEdgePatrolZone', 'ditchStealthZone'],
    beats: [
      { beatId: 'beatCountPatrolRuntime', eventId: 'eventPatrolCounted', kind: 'stealthObservation', targetSeconds: 62, intensity: 0.62, allowCombat: false, resourcePressure: 0.22, companionHintId: 'hintCutWire' },
    ],
  },
  {
    stageId: 'disableWarningLine',
    macroActId: 'crossTheBlockade',
    title: '哑掉的铜铃',
    objectiveId: 'disableWarningLine',
    targetId: 'warningLine',
    mode: 'interact',
    radius: 3.4,
    entryTriggerId: 'triggerDitchObservation',
    exitTriggerId: 'triggerWarningLineCut',
    checkpointId: 'checkpointDryDitch',
    targetSeconds: 100,
    aiZoneIds: ['ditchStealthZone', 'blockadePostZone'],
    beats: [
      { beatId: 'beatDisableAlarmRuntime', eventId: 'eventWarningLineCut', kind: 'stealthInfiltration', targetSeconds: 82, intensity: 0.76, allowCombat: true, resourcePressure: 0.5, companionHintId: 'hintCutWire' },
    ],
    failureAndCosts: ['Detection is recoverable by breaking sightlines.', 'Leaving the warning line intact forces the seal ending.'],
  },
  {
    stageId: 'crossDrainageCulvert',
    macroActId: 'crossTheBlockade',
    title: '水声盖住脚步',
    objectiveId: 'crossDrainageCulvert',
    targetId: 'culvertNorthMouth',
    mode: 'reach',
    radius: 6,
    entryTriggerId: 'triggerWarningLineCut',
    exitTriggerId: 'triggerCulvertNorthMouth',
    checkpointId: 'checkpointDryDitch',
    targetSeconds: 70,
    aiZoneIds: ['blockadePostZone'],
    beats: [
      { beatId: 'beatCrossCulvertRuntime', eventId: 'eventCulvertSignal', kind: 'forcedCrouchTraversal', targetSeconds: 52, intensity: 0.68, allowCombat: false, resourcePressure: 0.32, companionHintId: null },
    ],
  },
  {
    stageId: 'holdKilnMouth',
    macroActId: 'buyTheMinutes',
    title: '只守这几步',
    objectiveId: 'holdKilnMouth',
    targetId: 'limeKiln',
    mode: 'hold',
    radius: 12,
    holdSeconds: 24,
    entryTriggerId: 'triggerCulvertNorthMouth',
    exitTriggerId: 'triggerCombatRestraint',
    checkpointId: 'checkpointLimeKiln',
    targetSeconds: 135,
    aiZoneIds: ['blockadePostZone', 'kilnPursuitZone'],
    beats: [
      { beatId: 'beatTakeKilnPositionRuntime', eventId: 'eventKilnRearGuard', kind: 'defensiveReposition', targetSeconds: 35, intensity: 0.82, allowCombat: true, resourcePressure: 0.64, companionHintId: 'hintRetreatKiln' },
      { beatId: 'beatLimitedRearGuardRuntime', eventId: 'eventCombatRestraint', kind: 'limitedCombatOrEvasion', targetSeconds: 75, intensity: 0.92, allowCombat: true, resourcePressure: 0.82, companionHintId: 'hintRetreatKiln' },
    ],
    failureAndCosts: ['No endless waves and no reward for pursuing retreating enemies.', 'A protected-corridor breach rewinds before contact with civilians.'],
  },
  {
    stageId: 'waitForClearSignal',
    macroActId: 'buyTheMinutes',
    title: '亮一下，灭两下',
    objectiveId: 'waitForClearSignal',
    targetId: 'limeKiln',
    mode: 'wait',
    radius: 12,
    holdSeconds: 6,
    entryTriggerId: 'triggerCombatRestraint',
    exitTriggerId: 'triggerAllCiviliansClear',
    checkpointId: 'checkpointLimeKiln',
    targetSeconds: 55,
    aiZoneIds: ['kilnPursuitZone'],
    beats: [
      { beatId: 'beatWatchSignalRuntime', eventId: 'eventCiviliansClear', kind: 'release', targetSeconds: 36, intensity: 0.35, allowCombat: false, resourcePressure: 0.2, companionHintId: null },
    ],
  },
  {
    stageId: 'decideRouteFate',
    macroActId: 'chooseWhatRemains',
    title: '留下什么',
    objectiveId: 'decideRouteFate',
    targetId: 'culvertDecisionPoint',
    mode: 'choice',
    radius: 5,
    entryTriggerId: 'triggerRouteDecision',
    exitTriggerId: 'triggerRouteChoiceResolved',
    checkpointId: 'checkpointRouteDecision',
    targetSeconds: 80,
    aiZoneIds: [],
    beats: [
      { beatId: 'beatRouteDecisionRuntime', eventId: 'eventRouteDecision', kind: 'branchChoice', targetSeconds: 45, intensity: 0.3, allowCombat: false, resourcePressure: 0, companionHintId: 'hintRouteDecision' },
    ],
    failureAndCosts: ['Both endings keep the evacuees safe.', 'Neither option receives a good, bad or morality label.'],
  },
  {
    stageId: 'reachSafeRidge',
    macroActId: 'chooseWhatRemains',
    title: '天亮以前',
    objectiveId: 'reachSafeRidge',
    targetId: 'northSlopeExit',
    mode: 'reach',
    radius: 5,
    entryTriggerId: 'triggerRouteChoiceResolved',
    exitTriggerId: 'triggerEndingExit',
    checkpointId: 'checkpointRouteDecision',
    targetSeconds: 55,
    aiZoneIds: [],
    beats: [
      { beatId: 'beatEndingWalkRuntime', eventId: 'eventEndingSeal', alternateEventIds: ['eventEndingPreserve'], kind: 'consequenceWalk', targetSeconds: 40, intensity: 0.16, allowCombat: false, resourcePressure: 0, companionHintId: null },
    ],
  },
];

export const storyStages = missionStages;

export const routeChoice = {
  choiceId: 'routeFateChoice',
  eyebrow: '人已经过去，路还留在身后',
  title: '怎样处理这条交通线',
  body: '这不是一道善恶题。两个选择都保住今晚的转移，也都会把代价留给之后。',
  prompt: '转移队已经通过。怎样处理旧灌渠？',
  options: [
    {
      choiceId: 'seal',
      optionId: 'sealTheCulvert',
      title: '封住水洞',
      label: '封住水洞',
      description: '确保今晚的足迹止于此处；东线停用，日后另找接路。',
      consequence: '眼前的隐蔽更稳妥；熟路停用，交通员要在更远处重新接线。',
      interactableId: 'culvertCollapsePoint',
      eventId: 'eventEndingSeal',
      alwaysAvailable: true,
      setFlags: ['culvertSealed', 'endingRouteBroken'],
    },
    {
      choiceId: 'falseTrail',
      optionId: 'preserveTheRoute',
      title: '重布假迹',
      label: '重布假迹',
      description: '回到较亮的窑场制造向西的脚印；保留东线，但把风险留给以后每一次过线。',
      consequence: '保留未来的近路；此后每次通行都需要有人先走空路确认。',
      interactableId: 'falseTrailTools',
      eventId: 'eventEndingPreserve',
      availableWhen: {
        allFlags: ['warningLineCut', 'allCiviliansClear'],
        countersAtMost: { alertLevel: 1 },
      },
      unavailableReason: '警戒铃线未断或封锁哨已经全面警觉，假迹无法再骗过巡逻。',
      setFlags: ['falseTrailLaid', 'endingRoutePreserved'],
    },
  ],
};

export const environmentalNarratives = [
  {
    narrativeId: 'environmentWarmMillAsh',
    landmarkId: 'oldMill',
    inspectableId: 'warmMillAsh',
    position: { x: -31.2, y: 1.25, z: 49.8 },
    radius: 2.1,
    interactionLabel: '查看磨坊灶灰',
    title: '温灰',
    text: '灰心还有一点温。有人在一个时辰内来过，只烧了够照亮磨盘的一把秸秆。',
    companionLine: '槐生叔不肯多烧柴。烟会替人报信。',
    historicalPurpose: '用燃料紧张和隐蔽需求表现封锁下的日常选择，不展示苦难奇观。',
  },
  {
    narrativeId: 'environmentWrappedBell',
    landmarkId: 'villageSouthLane',
    inspectableId: 'wrappedMuleBell',
    position: { x: -16.5, y: 3.35, z: 27.2 },
    radius: 2.0,
    interactionLabel: '查看包住的铜铃',
    title: '包住的铃',
    text: '旧毡布一层层缠住铜铃，打结的方式方便在安全后快速拆开。',
    companionLine: '牲口留在村里。铃先闭嘴，人才能走远。',
    historicalPurpose: '以具体生活物件表现无声转移，而非用尸体或废墟制造冲击。',
  },
  {
    narrativeId: 'environmentHalfWovenCloth',
    landmarkId: 'stationHouse',
    inspectableId: 'halfWovenCloth',
    position: { x: 9.4, y: 3.25, z: 7.2 },
    radius: 2.0,
    interactionLabel: '查看停下的织机',
    title: '停在梭口的布',
    text: '织机上的布停在一条没有收尾的纬线上。旁边压着写给外村亲属的两封信，均未署名。',
    companionLine: '不用替她收。她知道自己为什么把梭子留在这儿。',
    historicalPurpose: '让住户保有决定和尊严，玩家不能把家庭空间当作资源箱。',
  },
  {
    narrativeId: 'environmentMudCoveredDoorPlate',
    landmarkId: 'villageCenter',
    inspectableId: 'mudCoveredDoorPlate',
    position: { x: -1.8, y: 4.25, z: 14.5 },
    radius: 2.0,
    interactionLabel: '查看泥封门牌',
    title: '泥封门牌',
    text: '几块写有户名的门牌被湿泥抹住，泥面尚未干透。',
    companionLine: '名字留下，就能顺着名字找人。今晚先让门替他们沉默。',
    historicalPurpose: '提示占领区的户籍与保甲控制，但不照搬某一真实村庄的具体遭遇。',
  },
  {
    narrativeId: 'environmentHiddenGrainJar',
    landmarkId: 'stationYard',
    inspectableId: 'sealedGrainJar',
    position: { x: 14.1, y: 2.5, z: 0.8 },
    radius: 1.9,
    interactionLabel: '查看封好的粮瓮',
    title: '封好的粮瓮',
    text: '粮瓮埋在夯土地面下，封泥完好，瓮口压着一小片写有归还月份的麻纸。',
    companionLine: '那是留给回村的人，不是给我们路上吃的。',
    historicalPurpose: '明确平民口粮不进入玩家资源循环。',
  },
  {
    narrativeId: 'environmentCulvertScratches',
    landmarkId: 'drainageCulvert',
    inspectableId: 'culvertHeightMarks',
    position: { x: -3.8, y: 0.65, z: -59.5 },
    radius: 1.8,
    interactionLabel: '查看洞壁水痕',
    title: '水痕与肩印',
    text: '洞壁有旧水痕，也有扁担长期擦过的浅印。交通线借用了本来就属于生活的道路。',
    companionLine: '这不是我们修的秘密路。它先是挑水、送粮、走亲戚的路。',
    historicalPurpose: '避免把基层交通网络描绘成脱离村民生活的英雄机关。',
  },
];

export const failureStates = [
  {
    failureId: 'playerIncapacitated',
    condition: 'playerHealthAtOrBelowZero',
    response: 'restartCurrentCheckpoint',
    message: '赵同岑没能继续前进。回到最近的隐蔽点。',
    presentationRule: 'No execution close-up, score penalty, or slow-motion spectacle.',
  },
  {
    failureId: 'companionUnableToProceed',
    condition: 'companionDownForMoreThanTwentySeconds',
    response: 'restartCurrentCheckpoint',
    message: '杜湘云无法继续带队。回到最近的协作节点。',
    presentationRule: 'Companion is never treated as expendable or converted into a resource loss.',
  },
  {
    failureId: 'protectedCorridorBreached',
    condition: 'hostileInsideProtectedCorridorBeforeAllCiviliansClear',
    response: 'rewindToLimeKilnCheckpoint',
    message: '巡逻逼近转移通路。回到窑口重新争取时间。',
    presentationRule: 'Fade before contact. Do not show, count, or rank civilian casualties.',
  },
  {
    failureId: 'routeWindowMissed',
    condition: 'alertLevelAtOrAboveTwoOrWarningLineIntact',
    response: 'continueWithForcedSealChoice',
    message: '封锁哨已经警觉。假迹不再可信，只能封住水洞。',
    presentationRule: 'This is a consequence, not a mission failure or moral score.',
  },
];

export const narrativeStateDefaults = {
  flags: {
    millSignalRead: false,
    stationReached: false,
    evacuationBriefed: false,
    cartMuffled: false,
    eastGateOpen: false,
    convoyMoving: false,
    blockadeObserved: false,
    warningLineCut: false,
    firstGroupClear: false,
    allCiviliansClear: false,
    routeDecisionReady: false,
    culvertSealed: false,
    falseTrailLaid: false,
    endingRouteBroken: false,
    endingRoutePreserved: false,
    emergencyCacheOpened: false,
  },
  counters: {
    alertLevel: 0,
    shotsFired: 0,
    kilnHoldSeconds: 0,
    fieldDressings: 1,
    rifleRounds: 4,
  },
};

export const historicalContext = {
  scope: 'A fictional composite of resistance base-area edges and occupied plains in North China during 1942. No fictional atrocity is assigned to a named real village or real individual.',
  groundedElements: [
    'Blockhouses, road ditches, warning wires, patrols, household registration pressure, grain requisition and repeated sweeps shaped movement in occupied North China.',
    'Secret traffic work often depended on ordinary homes, mills, field paths, drainage works, remembered relationships and signals that left little written evidence.',
    'Millet and sorghum, rammed-earth walls, stone field terraces, cotton clothing, puttees, handcarts and shaded oil lamps fit the selected season and region.',
    'Weapons are scarce and mechanically ordinary: a worn Hanyang rifle and a small number of cartridges. No suppressors, assault rifles, portable radios or instant-heal medicine appear.',
  ],
  languageRules: [
    'Use concrete period vocabulary such as 炮楼、交通站、灌渠、保甲门牌、转移 and 封锁哨.',
    'Avoid modern phrases such as 小队撤离点、火力压制套餐、刷资源、击杀数 and 任务评分.',
    'Do not make every character speak in slogans; operational language and domestic detail carry the period atmosphere.',
    'Occupation troops and collaborationist security personnel are dangerous human adversaries, not supernatural monsters or collectible targets.',
  ],
  civilianRepresentationRules: [
    'Civilians have names, relationships and decisions, but are never score, currency, loot, bait or a kill counter.',
    'Domestic food, medicine and keepsakes cannot be taken by the player unless a named owner explicitly gives a personal-use item.',
    'Violence against civilians is not staged for spectacle. A breached protected corridor rewinds before contact.',
    'The ending reports consequences in prose and does not grade the number of survivors.',
  ],
  productionNotes: [
    'Enemy signage should remain generic and fictional; avoid reproducing a real victim list or sensational decree as scenery.',
    'Uniform silhouettes should distinguish Japanese occupation troops from mixed local collaborationist security units without inventing elite fantasy armor.',
    'The village should look deliberately quiet and recently inhabited, not like a picturesque ruin that exists only for combat.',
  ],
};

export const storyData = {
  metadata: storyMetadata,
  cast,
  objectives,
  companionHints,
  events: storyEvents,
  narrativeActs,
  missionStages,
  routeChoice,
  environmentalNarratives,
  failureStates,
  stateDefaults: narrativeStateDefaults,
  historicalContext,
};

export default storyData;
