export const levelMetadata = {
  levelId: 'ashenRouteVerticalSlice',
  title: '天亮以前',
  coordinateSystem: {
    units: 'meters',
    upAxis: 'y',
    forwardDescription: 'Mission progression moves primarily from z +70 at the southern ravine to z -110 at the northern slope.',
  },
  worldBounds: {
    min: { x: -60, y: -4, z: -115 },
    max: { x: 60, y: 18, z: 75 },
  },
  playerSpawn: { x: -37, y: 1.2, z: 69 },
  companionSpawn: { x: -34.5, y: 1.2, z: 67.5 },
  extractionPoint: { x: -43, y: 2.4, z: -109 },
  targetPlaytimeSeconds: 930,
  expectedMovementSpeedMetersPerSecond: 2.2,
  weather: 'A cold, damp predawn after light rain; low cloud, no dramatic thunderstorm.',
  timeOfDay: '04:37 to 05:04 local dramatic time',
};

export const landmarks = [
  {
    landmarkId: 'southernRavine',
    displayName: '干河沟',
    center: { x: -35, y: 1, z: 64 },
    halfExtents: { x: 17, y: 4, z: 12 },
    narrativePurpose: 'A sheltered onboarding path that teaches crouch, listening and companion spacing without an enemy encounter.',
  },
  {
    landmarkId: 'oldMill',
    displayName: '旧磨坊',
    center: { x: -29, y: 2.1, z: 52 },
    halfExtents: { x: 8, y: 5, z: 7 },
    narrativePurpose: 'The line signal is embedded in an ordinary workplace rather than a spy-gadget set piece.',
  },
  {
    landmarkId: 'villageSouthLane',
    displayName: '槐树沟南巷',
    center: { x: -15, y: 3.1, z: 29 },
    halfExtents: { x: 17, y: 6, z: 14 },
    narrativePurpose: 'Recently inhabited domestic space made tense by intentional silence, not picturesque destruction.',
  },
  {
    landmarkId: 'villageCenter',
    displayName: '槐树沟场院',
    center: { x: 2, y: 3.3, z: 13 },
    halfExtents: { x: 21, y: 7, z: 14 },
    narrativePurpose: 'A compact hub where the player reads preparations and sees named adults organizing themselves.',
  },
  {
    landmarkId: 'stationHouse',
    displayName: '交通站院',
    center: { x: 12, y: 3.2, z: 4 },
    halfExtents: { x: 10, y: 6, z: 9 },
    narrativePurpose: 'Briefing and companion cooperation; homes are not loot dungeons.',
  },
  {
    landmarkId: 'eastFieldGate',
    displayName: '东侧小门',
    center: { x: 24, y: 2.7, z: -8 },
    halfExtents: { x: 7, y: 4, z: 5 },
    narrativePurpose: 'A quiet transition from collective preparation to exposed movement.',
  },
  {
    landmarkId: 'oldIrrigationDitch',
    displayName: '旧灌渠',
    center: { x: 24, y: 0.8, z: -25 },
    halfExtents: { x: 23, y: 4, z: 13 },
    narrativePurpose: 'A low route with reeds, broken retaining walls and two stealth approaches.',
  },
  {
    landmarkId: 'blockadePost',
    displayName: '封锁哨',
    center: { x: 8, y: 4.1, z: -42 },
    halfExtents: { x: 18, y: 8, z: 13 },
    narrativePurpose: 'A small practical control point, not a fortified combat arena.',
  },
  {
    landmarkId: 'drainageCulvert',
    displayName: '排水洞',
    center: { x: -4, y: 0.2, z: -58 },
    halfExtents: { x: 10, y: 3, z: 12 },
    narrativePurpose: 'A constricted crossing whose ordinary water marks show that the secret line grew from daily life.',
  },
  {
    landmarkId: 'culvertNorthMouth',
    displayName: '排水洞北口',
    center: { x: -9, y: 0.8, z: -67 },
    halfExtents: { x: 4, y: 3, z: 4 },
    narrativePurpose: 'The player waits here for the companion signal before moving to the kiln.',
  },
  {
    landmarkId: 'limeKiln',
    displayName: '废石灰窑',
    center: { x: -27, y: 5.1, z: -79 },
    halfExtents: { x: 16, y: 8, z: 14 },
    narrativePurpose: 'Limited rear-guard space with strong retreat geometry and no incentive to advance on enemies.',
  },
  {
    landmarkId: 'culvertDecisionPoint',
    displayName: '北坡水口',
    center: { x: -35, y: 2.2, z: -96 },
    halfExtents: { x: 12, y: 5, z: 8 },
    narrativePurpose: 'A quiet consequence space after the civilians have already cleared the route.',
  },
  {
    landmarkId: 'northSlopeExit',
    displayName: '北坡',
    center: { x: -43, y: 2.4, z: -108 },
    halfExtents: { x: 13, y: 5, z: 7 },
    narrativePurpose: 'No victory podium; the characters walk toward work that continues beyond the slice.',
  },
];

export const levelZones = [
  {
    zoneId: 'ravineApproachZone',
    category: 'narrativeTraversal',
    type: 'shadowCover',
    center: { x: -34, y: 1, z: 61 },
    radius: 14,
    halfExtents: { x: 18, y: 5, z: 14 },
    aiEnabled: false,
    patrolPoints: [],
    searchAnchors: [],
    coverPoints: [
      { x: -43, y: 1.1, z: 61 },
      { x: -31, y: 1.0, z: 56 },
    ],
    hearingMultiplier: 0.82,
    visibilityMultiplier: 0.7,
    ambienceId: 'ambienceRavinePredawn',
  },
  {
    zoneId: 'oldMillNarrativeZone',
    category: 'narrativeSafe',
    type: 'shadowCover',
    center: { x: -29, y: 2.1, z: 51 },
    radius: 7,
    halfExtents: { x: 9, y: 6, z: 8 },
    aiEnabled: false,
    patrolPoints: [],
    searchAnchors: [
      { x: -30, y: 2.0, z: 53 },
      { x: -24, y: 2.0, z: 49 },
    ],
    coverPoints: [
      { x: -34, y: 2.0, z: 50 },
    ],
    hearingMultiplier: 0.95,
    visibilityMultiplier: 0.58,
    ambienceId: 'ambienceOldMill',
  },
  {
    zoneId: 'villageHushZone',
    category: 'civilianNarrative',
    type: 'villageShadowCover',
    center: { x: 0, y: 3, z: 15 },
    radius: 22,
    halfExtents: { x: 29, y: 8, z: 25 },
    aiEnabled: false,
    protectedFromCombat: true,
    patrolPoints: [],
    searchAnchors: [
      { x: -15, y: 3.0, z: 28 },
      { x: 5, y: 3.1, z: 12 },
      { x: 14, y: 3.0, z: 3 },
    ],
    coverPoints: [
      { x: -11, y: 3.0, z: 20 },
      { x: 7, y: 3.0, z: 15 },
      { x: 17, y: 3.0, z: 1 },
    ],
    hearingMultiplier: 1.18,
    visibilityMultiplier: 0.68,
    ambienceId: 'ambienceMutedVillage',
  },
  {
    zoneId: 'villageEdgePatrolZone',
    category: 'aiStealthBoundary',
    type: 'fieldCover',
    center: { x: 34, y: 2.5, z: 9 },
    radius: 22,
    halfExtents: { x: 14, y: 7, z: 28 },
    aiEnabled: true,
    preferredResolution: 'avoid',
    maxActiveEnemies: 2,
    patrolPoints: [
      { x: 38, y: 2.5, z: 27 },
      { x: 34, y: 2.3, z: 14 },
      { x: 39, y: 2.0, z: -2 },
      { x: 31, y: 1.8, z: -14 },
    ],
    searchAnchors: [
      { x: 28, y: 2.6, z: 21 },
      { x: 26, y: 2.3, z: 5 },
      { x: 27, y: 2.0, z: -10 },
    ],
    coverPoints: [
      { x: 22, y: 2.6, z: 22 },
      { x: 27, y: 2.2, z: 8 },
      { x: 25, y: 1.9, z: -9 },
    ],
    hearingMultiplier: 1.08,
    visibilityMultiplier: 0.78,
    ambienceId: 'ambienceFieldEdgePatrol',
  },
  {
    zoneId: 'stationPreparationZone',
    category: 'companionInteraction',
    center: { x: 14, y: 3.0, z: 2 },
    halfExtents: { x: 13, y: 7, z: 12 },
    aiEnabled: false,
    protectedFromCombat: true,
    patrolPoints: [],
    searchAnchors: [],
    coverPoints: [],
    hearingMultiplier: 1.15,
    visibilityMultiplier: 0.6,
    ambienceId: 'ambienceStationPreparation',
  },
  {
    zoneId: 'ditchStealthZone',
    category: 'stealthTraversal',
    type: 'reedCover',
    center: { x: 22, y: 0.8, z: -25 },
    radius: 22,
    halfExtents: { x: 25, y: 6, z: 14 },
    aiEnabled: true,
    preferredResolution: 'observeAndBypass',
    maxActiveEnemies: 2,
    patrolPoints: [
      { x: 31, y: 1.1, z: -18 },
      { x: 22, y: 0.7, z: -25 },
      { x: 14, y: 1.0, z: -31 },
    ],
    searchAnchors: [
      { x: 29, y: 0.9, z: -25 },
      { x: 19, y: 0.8, z: -29 },
      { x: 7, y: 1.2, z: -33 },
    ],
    coverPoints: [
      { x: 34, y: 1.1, z: -24 },
      { x: 26, y: 0.8, z: -29 },
      { x: 18, y: 0.8, z: -21 },
      { x: 9, y: 1.1, z: -32 },
    ],
    hearingMultiplier: 0.74,
    visibilityMultiplier: 0.56,
    ambienceId: 'ambienceWetReeds',
  },
  {
    zoneId: 'blockadePostZone',
    category: 'aiControlPoint',
    center: { x: 8, y: 3.7, z: -42 },
    halfExtents: { x: 19, y: 9, z: 14 },
    aiEnabled: true,
    preferredResolution: 'disableAlarmAndSlipPast',
    maxActiveEnemies: 4,
    reinforcementLimit: 0,
    patrolPoints: [
      { x: 19, y: 3.0, z: -35 },
      { x: 12, y: 3.5, z: -41 },
      { x: 3, y: 3.2, z: -48 },
      { x: -3, y: 2.1, z: -42 },
    ],
    searchAnchors: [
      { x: 22, y: 2.8, z: -33 },
      { x: 9, y: 3.3, z: -37 },
      { x: 1, y: 2.6, z: -47 },
      { x: -7, y: 1.7, z: -52 },
    ],
    coverPoints: [
      { x: 17, y: 2.7, z: -39 },
      { x: 8, y: 3.0, z: -46 },
      { x: -1, y: 2.0, z: -45 },
      { x: -9, y: 1.3, z: -51 },
    ],
    hearingMultiplier: 1.0,
    visibilityMultiplier: 0.84,
    ambienceId: 'ambienceBlockadePost',
  },
  {
    zoneId: 'culvertProtectedCorridor',
    category: 'protectedTransfer',
    type: 'shadowCover',
    center: { x: -7.5, y: 0.4, z: -59.5 },
    radius: 7,
    halfExtents: { x: 7, y: 5, z: 6 },
    aiEnabled: false,
    protectedFromCombat: true,
    patrolPoints: [],
    searchAnchors: [],
    coverPoints: [
      { x: -16, y: 1.0, z: -68 },
    ],
    hearingMultiplier: 0.7,
    visibilityMultiplier: 0.34,
    ambienceId: 'ambienceCulvert',
  },
  {
    zoneId: 'kilnPursuitZone',
    category: 'limitedRearGuard',
    type: 'stoneCover',
    center: { x: -25, y: 4.8, z: -78 },
    radius: 15,
    halfExtents: { x: 20, y: 9, z: 15 },
    aiEnabled: true,
    preferredResolution: 'holdThenDisengage',
    maxActiveEnemies: 4,
    reinforcementLimit: 2,
    patrolPoints: [
      { x: -8, y: 2.0, z: -66 },
      { x: -15, y: 3.2, z: -72 },
      { x: -22, y: 4.3, z: -76 },
    ],
    searchAnchors: [
      { x: -10, y: 2.4, z: -67 },
      { x: -19, y: 3.9, z: -73 },
      { x: -29, y: 4.9, z: -82 },
    ],
    coverPoints: [
      { x: -17, y: 3.6, z: -73 },
      { x: -25, y: 4.7, z: -77 },
      { x: -32, y: 5.0, z: -82 },
      { x: -37, y: 4.2, z: -88 },
    ],
    hearingMultiplier: 1.08,
    visibilityMultiplier: 0.76,
    ambienceId: 'ambienceLimeKiln',
  },
  {
    zoneId: 'routeDecisionZone',
    category: 'branchAndRelease',
    center: { x: -35, y: 2.2, z: -96 },
    halfExtents: { x: 14, y: 6, z: 10 },
    aiEnabled: false,
    patrolPoints: [],
    searchAnchors: [],
    coverPoints: [],
    hearingMultiplier: 0.82,
    visibilityMultiplier: 0.66,
    ambienceId: 'ambienceDawnSlope',
  },
  {
    zoneId: 'northSlopeExitZone',
    category: 'endingWalk',
    center: { x: -43, y: 2.4, z: -107 },
    halfExtents: { x: 15, y: 7, z: 8 },
    aiEnabled: false,
    patrolPoints: [],
    searchAnchors: [],
    coverPoints: [],
    hearingMultiplier: 0.76,
    visibilityMultiplier: 0.7,
    ambienceId: 'ambienceNorthSlope',
  },
];

export const patrolRoutes = [
  {
    routeId: 'routeVillageOuterPair',
    zoneId: 'villageEdgePatrolZone',
    factionId: 'collaborationistSecurity',
    enemyCount: 2,
    activation: { stageId: 'meetStationKeeper', alertLevelAtLeast: 0 },
    loop: true,
    direction: 'pingPong',
    walkingSpeed: 1.05,
    investigationSpeed: 1.65,
    pauses: [
      { pointIndex: 1, seconds: 4.5, facingYawDegrees: 252 },
      { pointIndex: 3, seconds: 5.5, facingYawDegrees: 190 },
    ],
    points: [
      { x: 38, y: 2.5, z: 27 },
      { x: 34, y: 2.3, z: 14 },
      { x: 39, y: 2.0, z: -2 },
      { x: 31, y: 1.8, z: -14 },
    ],
    behaviorNotes: 'They remain outside the inhabited center unless alert reaches two. The player is taught avoidance, not silent takedown farming.',
  },
  {
    routeId: 'routeDitchPatrolPair',
    zoneId: 'ditchStealthZone',
    factionId: 'collaborationistSecurity',
    enemyCount: 2,
    activation: { stageId: 'reachIrrigationDitch', alertLevelAtLeast: 0 },
    loop: true,
    direction: 'forward',
    walkingSpeed: 0.95,
    investigationSpeed: 1.7,
    pauses: [
      { pointIndex: 0, seconds: 3.0, facingYawDegrees: 210 },
      { pointIndex: 2, seconds: 6.0, facingYawDegrees: 315 },
    ],
    points: [
      { x: 31, y: 1.1, z: -18 },
      { x: 22, y: 0.7, z: -25 },
      { x: 14, y: 1.0, z: -31 },
      { x: 25, y: 0.8, z: -29 },
    ],
    behaviorNotes: 'The pair talk briefly at the east bend, creating a readable crossing window. They do not randomly reverse without an audio cue.',
  },
  {
    routeId: 'routeBlockadeSentry',
    zoneId: 'blockadePostZone',
    factionId: 'occupationPatrol',
    enemyCount: 1,
    activation: { stageId: 'reachIrrigationDitch', alertLevelAtLeast: 0 },
    loop: true,
    direction: 'fixedCircuit',
    walkingSpeed: 0.72,
    investigationSpeed: 1.55,
    pauses: [
      { pointIndex: 0, seconds: 7.0, facingYawDegrees: 145 },
      { pointIndex: 2, seconds: 5.0, facingYawDegrees: 270 },
    ],
    points: [
      { x: 12, y: 3.5, z: -41 },
      { x: 8, y: 3.3, z: -47 },
      { x: 3, y: 3.2, z: -48 },
      { x: 6, y: 3.5, z: -42 },
    ],
    behaviorNotes: 'A regular sentry with a rifle and lantern shutter, not an armored elite or boss.',
  },
  {
    routeId: 'routeKilnResponse',
    zoneId: 'kilnPursuitZone',
    factionId: 'mixedSearchGroup',
    enemyCount: 2,
    activation: { stageId: 'holdKilnMouth', alertLevelAtLeast: 0 },
    loop: false,
    direction: 'approachThenHold',
    walkingSpeed: 1.15,
    investigationSpeed: 1.8,
    points: [
      { x: -8, y: 2.0, z: -67 },
      { x: -13, y: 2.8, z: -69 },
      { x: -19, y: 3.7, z: -74 },
      { x: -23, y: 4.2, z: -76 },
    ],
    stopDistanceFromProtectedCorridor: 9,
    behaviorNotes: 'They probe the kiln mouth and withdraw after the clear signal. They never spawn behind the player and never enter the civilian route on screen.',
  },
];

export const interactables = [
  {
    interactableId: 'millStoneSignal',
    type: 'missionInspect',
    position: { x: -28.8, y: 1.55, z: 51.6 },
    radius: 1.6,
    prompt: '检查磨盘下的石子',
    holdSeconds: 1.5,
    eventId: 'eventMillSignalFound',
    requires: { stageId: 'reachOldMill' },
    setsFlags: ['millSignalRead'],
    noiseRadius: 0,
  },
  {
    interactableId: 'warmMillAsh',
    type: 'environmentInspect',
    position: { x: -31.2, y: 1.25, z: 49.8 },
    radius: 1.35,
    prompt: '摸一摸灶灰',
    holdSeconds: 0.7,
    narrativeId: 'environmentWarmMillAsh',
    noiseRadius: 0,
  },
  {
    interactableId: 'wrappedMuleBell',
    type: 'environmentInspect',
    position: { x: -16.5, y: 3.35, z: 27.2 },
    radius: 1.2,
    prompt: '查看包住的铜铃',
    holdSeconds: 0.6,
    narrativeId: 'environmentWrappedBell',
    noiseRadius: 0,
  },
  {
    interactableId: 'halfWovenCloth',
    type: 'environmentInspect',
    position: { x: 9.4, y: 3.25, z: 7.2 },
    radius: 1.25,
    prompt: '查看停下的织机',
    holdSeconds: 0.6,
    narrativeId: 'environmentHalfWovenCloth',
    noiseRadius: 0,
  },
  {
    interactableId: 'mudCoveredDoorPlate',
    type: 'environmentInspect',
    position: { x: -1.8, y: 4.25, z: 14.5 },
    radius: 1.2,
    prompt: '查看门牌上的湿泥',
    holdSeconds: 0.6,
    narrativeId: 'environmentMudCoveredDoorPlate',
    noiseRadius: 0,
  },
  {
    interactableId: 'sealedGrainJar',
    type: 'environmentInspectProtected',
    position: { x: 14.1, y: 2.5, z: 0.8 },
    radius: 1.25,
    prompt: '查看封泥',
    holdSeconds: 0.5,
    narrativeId: 'environmentHiddenGrainJar',
    grantsResources: {},
    canLoot: false,
    noiseRadius: 0,
  },
  {
    interactableId: 'stationCellarDoor',
    type: 'missionDoor',
    position: { x: 10.8, y: 3.0, z: 5.1 },
    radius: 1.7,
    prompt: '轻敲两下，再停一下',
    holdSeconds: 1.0,
    eventId: 'eventStationKeeperFound',
    requires: { allFlags: ['millSignalRead'] },
    setsFlags: ['stationReached'],
    noiseRadius: 2.2,
  },
  {
    interactableId: 'emergencyCartridgeTin',
    type: 'consentedResource',
    position: { x: 13.3, y: 3.4, z: 4.3 },
    radius: 1.15,
    prompt: '收下杜湘云分出的两发备用弹',
    holdSeconds: 0.8,
    requires: { allFlags: ['evacuationBriefed'] },
    grantsResources: { rifleRounds: 2 },
    contents: { ammo: 2 },
    label: '收下两发备用弹',
    pickupText: '杜湘云分出两发交通站备用弹。',
    setsFlags: ['emergencyCacheOpened'],
    companionLine: '给你两发。不是让你留在这儿打，是让你能退回来。',
    canRepeat: false,
    noiseRadius: 0,
  },
  {
    interactableId: 'handcartAxle',
    type: 'companionCooperation',
    position: { x: 16.8, y: 2.72, z: -0.8 },
    radius: 1.65,
    prompt: '与杜湘云一起垫紧车轴',
    holdSeconds: 2.8,
    eventId: 'eventCartMuffled',
    requires: { allFlags: ['evacuationBriefed'] },
    companionAnchor: { x: 18.0, y: 2.72, z: -0.1 },
    setsFlags: ['cartMuffled'],
    noiseRadius: 1.5,
  },
  {
    interactableId: 'eastGateLatch',
    type: 'missionLatch',
    position: { x: 23.8, y: 3.05, z: -7.7 },
    radius: 1.45,
    prompt: '用布裹住门闩再打开',
    holdSeconds: 2.0,
    eventId: 'eventEastGateOpened',
    requires: { allFlags: ['cartMuffled'] },
    setsFlags: ['eastGateOpen', 'convoyMoving'],
    noiseRadius: 1.2,
    forcedInteractionNoiseRadius: 12,
  },
  {
    interactableId: 'looseStonePile',
    type: 'worldResource',
    position: { x: 29.2, y: 0.55, z: -22.8 },
    radius: 1.4,
    prompt: '拾取三块碎石',
    holdSeconds: 0.45,
    grantsResources: { distractionStones: 3 },
    contents: { stone: 3 },
    label: '拾取三块碎石',
    pickupText: '拾起三块可用来引开巡逻的碎石。',
    maximumCarry: 3,
    ownership: 'naturallyLooseGroundMaterial',
    canRepeat: false,
    noiseRadius: 0.6,
  },
  {
    interactableId: 'ditchObservationPoint',
    type: 'missionObserve',
    position: { x: 26.5, y: 1.05, z: -27.0 },
    radius: 1.8,
    prompt: '观察封锁哨的巡逻',
    holdSeconds: 1.2,
    eventId: 'eventPatrolCounted',
    requires: { allFlags: ['convoyMoving'] },
    setsFlags: ['blockadeObserved'],
    noiseRadius: 0,
  },
  {
    interactableId: 'warningLine',
    type: 'missionSabotage',
    position: { x: 1.4, y: 1.95, z: -45.8 },
    radius: 1.3,
    prompt: '用钢丝钳剪断铃线',
    holdSeconds: 2.2,
    eventId: 'eventWarningLineCut',
    requires: { allFlags: ['blockadeObserved'], equippedTool: 'wireCutters' },
    setsFlags: ['warningLineCut'],
    noiseRadius: 1.0,
  },
  {
    interactableId: 'culvertHeightMarks',
    type: 'environmentInspect',
    position: { x: -3.8, y: 0.65, z: -59.5 },
    radius: 1.1,
    prompt: '查看洞壁上的擦痕',
    holdSeconds: 0.5,
    narrativeId: 'environmentCulvertScratches',
    noiseRadius: 0,
  },
  {
    interactableId: 'culvertCollapsePoint',
    type: 'endingChoice',
    position: { x: -36.8, y: 2.0, z: -95.4 },
    radius: 1.8,
    prompt: '封住水洞',
    holdSeconds: 3.2,
    eventId: 'eventEndingSeal',
    choiceId: 'routeFateChoice',
    optionId: 'sealTheCulvert',
    requires: { allFlags: ['routeDecisionReady', 'allCiviliansClear'] },
    setsFlags: ['culvertSealed', 'endingRouteBroken'],
    noiseRadius: 8,
  },
  {
    interactableId: 'falseTrailTools',
    type: 'endingChoice',
    position: { x: -31.7, y: 2.25, z: -97.2 },
    radius: 1.8,
    prompt: '带上枝帚，重布假迹',
    holdSeconds: 2.0,
    eventId: 'eventEndingPreserve',
    choiceId: 'routeFateChoice',
    optionId: 'preserveTheRoute',
    requires: {
      allFlags: ['routeDecisionReady', 'allCiviliansClear', 'warningLineCut'],
      countersAtMost: { alertLevel: 1 },
    },
    setsFlags: ['falseTrailLaid', 'endingRoutePreserved'],
    noiseRadius: 3,
  },
];

export const storyTriggers = [
  {
    triggerId: 'triggerLevelStart',
    eventId: 'eventApproachWhisper',
    center: { x: -37, y: 1.2, z: 69 },
    radius: 5,
    activation: 'automaticOnSpawn',
    once: true,
    requires: { stageId: 'reachOldMill' },
  },
  {
    triggerId: 'triggerOldMillApproach',
    eventId: null,
    center: { x: -29, y: 2.1, z: 52 },
    radius: 7,
    activation: 'enterRadius',
    once: true,
    requires: { stageId: 'reachOldMill' },
  },
  {
    triggerId: 'triggerMillSignalRead',
    eventId: 'eventMillSignalFound',
    center: { x: -28.8, y: 1.55, z: 51.6 },
    radius: 1.6,
    activation: 'interact',
    interactableId: 'millStoneSignal',
    once: true,
    requires: { stageId: 'readStoneSignal' },
  },
  {
    triggerId: 'triggerVillageThreshold',
    eventId: 'eventVillageSeen',
    center: { x: -18.2, y: 3.0, z: 32.0 },
    radius: 5.5,
    activation: 'enterRadius',
    once: true,
    requires: { allFlags: ['millSignalRead'] },
  },
  {
    triggerId: 'triggerStationDoor',
    eventId: 'eventStationKeeperFound',
    center: { x: 10.8, y: 3.0, z: 5.1 },
    radius: 1.7,
    activation: 'interact',
    interactableId: 'stationCellarDoor',
    once: true,
    requires: { allFlags: ['millSignalRead'] },
  },
  {
    triggerId: 'triggerEvacuationBriefComplete',
    eventId: 'eventEvacuationBrief',
    center: { x: 13.0, y: 3.0, z: 2.2 },
    radius: 5.2,
    activation: 'lingerInRadius',
    lingerSeconds: 3.0,
    once: true,
    requires: { allFlags: ['stationReached'] },
  },
  {
    triggerId: 'triggerCartMuffled',
    eventId: 'eventCartMuffled',
    center: { x: 16.8, y: 2.72, z: -0.8 },
    radius: 1.65,
    activation: 'interact',
    interactableId: 'handcartAxle',
    once: true,
    requires: { allFlags: ['evacuationBriefed'] },
  },
  {
    triggerId: 'triggerEastGateOpened',
    eventId: 'eventEastGateOpened',
    center: { x: 23.8, y: 3.05, z: -7.7 },
    radius: 1.45,
    activation: 'interact',
    interactableId: 'eastGateLatch',
    once: true,
    requires: { allFlags: ['cartMuffled'] },
  },
  {
    triggerId: 'triggerDitchObservation',
    eventId: 'eventPatrolCounted',
    center: { x: 26.5, y: 1.05, z: -27.0 },
    radius: 1.8,
    activation: 'interact',
    interactableId: 'ditchObservationPoint',
    once: true,
    requires: { allFlags: ['convoyMoving'] },
  },
  {
    triggerId: 'triggerWarningLineCut',
    eventId: 'eventWarningLineCut',
    center: { x: 1.4, y: 1.95, z: -45.8 },
    radius: 1.3,
    activation: 'interact',
    interactableId: 'warningLine',
    once: true,
    requires: { allFlags: ['blockadeObserved'] },
  },
  {
    triggerId: 'triggerBlockadeDetection',
    eventId: 'eventBlockadeSpotted',
    center: { x: 8, y: 3.7, z: -42 },
    radius: 22,
    activation: 'systemCondition',
    systemCondition: 'playerDetectedInBlockadePostZone',
    once: true,
    requires: { anyStageIds: ['reachIrrigationDitch', 'disableWarningLine', 'crossDrainageCulvert'] },
  },
  {
    triggerId: 'triggerCulvertNorthMouth',
    eventId: 'eventCulvertSignal',
    center: { x: -9.0, y: 0.8, z: -67.0 },
    radius: 4.0,
    activation: 'enterRadius',
    once: true,
    requires: { allFlags: ['convoyMoving'] },
  },
  {
    triggerId: 'triggerLimeKiln',
    eventId: 'eventKilnRearGuard',
    center: { x: -24.0, y: 4.4, z: -75.0 },
    radius: 5.0,
    activation: 'enterRadius',
    once: true,
    requires: { stageId: 'holdKilnMouth' },
  },
  {
    triggerId: 'triggerCombatRestraint',
    eventId: 'eventCombatRestraint',
    center: { x: -27, y: 5.1, z: -79 },
    radius: 12,
    activation: 'systemCondition',
    systemCondition: 'firstKilnThreatBrokenOrEvaded',
    once: true,
    requires: { stageId: 'holdKilnMouth' },
  },
  {
    triggerId: 'triggerAllCiviliansClear',
    eventId: 'eventCiviliansClear',
    center: { x: -31.5, y: 4.2, z: -87.5 },
    radius: 7.0,
    activation: 'systemCondition',
    systemCondition: 'kilnHoldSecondsAtLeastThirtySixOrThreatsDisengaged',
    once: true,
    requires: { allFlags: ['firstGroupClear'] },
  },
  {
    triggerId: 'triggerRouteDecision',
    eventId: 'eventRouteDecision',
    center: { x: -35.0, y: 2.2, z: -96.0 },
    radius: 5.0,
    activation: 'enterRadius',
    once: true,
    requires: { allFlags: ['allCiviliansClear'] },
  },
  {
    triggerId: 'triggerEndingSeal',
    eventId: 'eventEndingSeal',
    center: { x: -36.8, y: 2.0, z: -95.4 },
    radius: 1.8,
    activation: 'interact',
    interactableId: 'culvertCollapsePoint',
    once: true,
    requires: { allFlags: ['routeDecisionReady'] },
  },
  {
    triggerId: 'triggerEndingPreserve',
    eventId: 'eventEndingPreserve',
    center: { x: -31.7, y: 2.25, z: -97.2 },
    radius: 1.8,
    activation: 'interact',
    interactableId: 'falseTrailTools',
    once: true,
    requires: {
      allFlags: ['routeDecisionReady', 'warningLineCut'],
      countersAtMost: { alertLevel: 1 },
    },
  },
  {
    triggerId: 'triggerRouteChoiceResolved',
    eventId: null,
    center: { x: -35.0, y: 2.2, z: -96.0 },
    radius: 5.0,
    activation: 'systemCondition',
    systemCondition: 'routeChoiceResolved',
    once: true,
    requires: { anyFlags: ['endingRouteBroken', 'endingRoutePreserved'] },
  },
  {
    triggerId: 'triggerEndingExit',
    eventId: null,
    center: { x: -43, y: 2.4, z: -109 },
    radius: 5,
    activation: 'enterRadius',
    once: true,
    requires: { anyFlags: ['endingRouteBroken', 'endingRoutePreserved'] },
  },
];

export const levelTriggers = storyTriggers;

export const navigationRoutes = [
  {
    routeId: 'routePrimaryMissionFlow',
    use: 'playerCriticalPath',
    expectedTraversalSeconds: 310,
    waypoints: [
      { x: -37, y: 1.2, z: 69, landmarkId: 'southernRavine' },
      { x: -32, y: 1.4, z: 59 },
      { x: -29, y: 2.1, z: 52, landmarkId: 'oldMill' },
      { x: -22, y: 2.7, z: 40 },
      { x: -16, y: 3.0, z: 30, landmarkId: 'villageSouthLane' },
      { x: -5, y: 3.2, z: 18, landmarkId: 'villageCenter' },
      { x: 12, y: 3.2, z: 4, landmarkId: 'stationHouse' },
      { x: 24, y: 2.7, z: -8, landmarkId: 'eastFieldGate' },
      { x: 27, y: 1.0, z: -25, landmarkId: 'oldIrrigationDitch' },
      { x: 2, y: 2.0, z: -46, landmarkId: 'blockadePost' },
      { x: -4, y: 0.2, z: -58, landmarkId: 'drainageCulvert' },
      { x: -27, y: 5.1, z: -79, landmarkId: 'limeKiln' },
      { x: -35, y: 2.2, z: -96, landmarkId: 'culvertDecisionPoint' },
      { x: -43, y: 2.4, z: -109, landmarkId: 'northSlopeExit' },
    ],
  },
  {
    routeId: 'routeEastDitchStealth',
    use: 'lowVisibilityBypass',
    expectedTraversalSeconds: 92,
    tradeoff: 'More crouch movement and wet noise, but fewer direct sightlines.',
    waypoints: [
      { x: 24, y: 2.7, z: -8 },
      { x: 34, y: 1.4, z: -16 },
      { x: 32, y: 0.7, z: -27 },
      { x: 23, y: 0.6, z: -34 },
      { x: 11, y: 1.0, z: -38 },
      { x: 2, y: 1.8, z: -46 },
    ],
  },
  {
    routeId: 'routeWestTerraceRisk',
    use: 'shortExposedBypass',
    expectedTraversalSeconds: 64,
    tradeoff: 'Shorter and drier, but exposed to the fixed blockade sentry for longer.',
    waypoints: [
      { x: 24, y: 2.7, z: -8 },
      { x: 12, y: 3.2, z: -18 },
      { x: 4, y: 4.0, z: -28 },
      { x: -3, y: 3.4, z: -38 },
      { x: 1, y: 2.0, z: -46 },
    ],
  },
  {
    routeId: 'routeCivilianTransfer',
    use: 'protectedOffCameraConvoy',
    visibleSegments: ['stationYardDeparture', 'culvertSilhouettes', 'northSlopeLampSignal'],
    waypoints: [
      { x: 13, y: 3.0, z: 2 },
      { x: 24, y: 2.7, z: -8 },
      { x: 36, y: 1.6, z: -19 },
      { x: 31, y: 0.8, z: -33 },
      { x: 18, y: 0.8, z: -47 },
      { x: 2, y: 0.5, z: -54 },
      { x: -8, y: 0.4, z: -63 },
      { x: -19, y: 2.1, z: -74 },
      { x: -36, y: 2.3, z: -97 },
      { x: -44, y: 2.4, z: -109 },
    ],
    simulationRule: 'Civilians travel as authored distant silhouettes and audio cues, never as combat targets or escort-health bars.',
  },
];

export const traversalLinks = [
  {
    linkId: 'millBrokenWallStep',
    type: 'stepUp',
    from: { x: -34.0, y: 1.4, z: 54.0 },
    to: { x: -32.6, y: 2.1, z: 52.8 },
    durationSeconds: 0.7,
    companionMode: 'followsIndependently',
  },
  {
    linkId: 'eastGateCartAssist',
    type: 'cooperativePush',
    from: { x: 21.8, y: 2.8, z: -5.8 },
    to: { x: 24.8, y: 2.7, z: -9.2 },
    durationSeconds: 2.4,
    companionMode: 'duXiangyunLeadsPlayerMatches',
    requires: { allFlags: ['cartMuffled', 'eastGateOpen'] },
  },
  {
    linkId: 'ditchLowWallVault',
    type: 'lowVault',
    from: { x: 22.4, y: 0.8, z: -30.0 },
    to: { x: 20.8, y: 1.2, z: -31.6 },
    durationSeconds: 0.9,
    noiseRadius: 2.2,
    companionMode: 'holdsCoverThenFollows',
  },
  {
    linkId: 'culvertCrouchPassage',
    type: 'forcedCrouch',
    from: { x: -1.5, y: 0.5, z: -52.5 },
    to: { x: -8.8, y: 0.6, z: -67.0 },
    durationSeconds: 7.5,
    noiseRadius: 1.2,
    companionMode: 'separateConvoyRoute',
  },
  {
    linkId: 'kilnLedgeAssist',
    type: 'companionBoost',
    from: { x: -24.0, y: 4.4, z: -75.8 },
    to: { x: -27.2, y: 5.2, z: -78.4 },
    durationSeconds: 1.8,
    companionMode: 'playerBoostsDuThenDuPullsPlayer',
    tacticalPurpose: 'Creates a retreat route and visibly reciprocal adult cooperation.',
  },
];

export const ambientVolumes = [
  {
    ambienceId: 'ambienceRavinePredawn',
    center: { x: -34, y: 2, z: 61 },
    radius: 25,
    bedCueId: 'ambRavineWindLow',
    detailCueIds: ['detailSingleNightInsect', 'detailDistantWoodShutter'],
    musicCueId: null,
    mixNote: 'Let footsteps and wet cloth dominate; music enters only after the village threshold.',
  },
  {
    ambienceId: 'ambienceMutedVillage',
    center: { x: 0, y: 3, z: 15 },
    radius: 35,
    bedCueId: 'ambVillageAirStill',
    detailCueIds: ['detailWrappedBellDull', 'detailLoomWoodSettle', 'detailSuppressedCough'],
    musicCueId: 'musicLowBowedStringPulse',
    mixNote: 'No generic crying crowd. Individual close sounds reveal occupied homes and preparation.',
  },
  {
    ambienceId: 'ambienceWetReeds',
    center: { x: 22, y: 1, z: -25 },
    radius: 29,
    bedCueId: 'ambReedsWetWind',
    detailCueIds: ['detailDitchWater', 'detailPatrolGravel'],
    musicCueId: 'musicMutedSkinDrumPulse',
    mixNote: 'Patrol boots must be directionally legible before they are visible.',
  },
  {
    ambienceId: 'ambienceBlockadePost',
    center: { x: 8, y: 4, z: -42 },
    radius: 27,
    bedCueId: 'ambBlockadeLampAndWire',
    detailCueIds: ['detailWireCreak', 'detailRifleSling', 'detailLowConversation'],
    musicCueId: 'musicHeldBreathDrone',
    mixNote: 'No action-movie percussion on detection; the alarming sound is the warning apparatus and shouted direction.',
  },
  {
    ambienceId: 'ambienceLimeKiln',
    center: { x: -27, y: 5, z: -79 },
    radius: 30,
    bedCueId: 'ambKilnWindHollow',
    detailCueIds: ['detailLimeDustFall', 'detailDistantCartWheel', 'detailShutteredLampClick'],
    musicCueId: 'musicRestrainedRearGuard',
    mixNote: 'The cart wheel and lamp cue outrank gunfire in the narrative mix.',
  },
  {
    ambienceId: 'ambienceDawnSlope',
    center: { x: -38, y: 3, z: -101 },
    radius: 25,
    bedCueId: 'ambDawnWindInDryGrass',
    detailCueIds: ['detailFarRoosterUncertain', 'detailStoneSettle'],
    musicCueId: 'musicTwoNoteAftermath',
    mixNote: 'Use a thin ending, not triumph. The first distant rooster marks time, not safety.',
  },
];

export const historicalDressing = [
  {
    dressingId: 'dressingRammedEarthPatchwork',
    landmarkId: 'villageSouthLane',
    positions: [
      { x: -19, y: 3.0, z: 31 },
      { x: -11, y: 3.1, z: 25 },
      { x: -4, y: 3.0, z: 18 },
    ],
    visual: 'Rammed-earth walls repaired with visibly different soil batches, stone footings, sparse grey tile caps.',
    materialRule: 'Matte earth with damp lower edges; no uniformly cracked post-apocalypse texture pass.',
  },
  {
    dressingId: 'dressingAutumnFieldWork',
    landmarkId: 'eastFieldGate',
    positions: [
      { x: 29, y: 2.0, z: -11 },
      { x: 34, y: 1.4, z: -18 },
      { x: 26, y: 1.0, z: -24 },
    ],
    visual: 'Cut sorghum stalks bundled low, millet chaff caught in wet ruts, one handcart with a repaired wooden hub.',
    materialRule: 'No bright harvest-gold grading; predawn moisture desaturates the stalks.',
  },
  {
    dressingId: 'dressingBlockadePracticality',
    landmarkId: 'blockadePost',
    positions: [
      { x: 8, y: 3.7, z: -42 },
      { x: 1.4, y: 1.95, z: -45.8 },
      { x: 13, y: 3.4, z: -38 },
    ],
    visual: 'A timber shelter, shallow road cut, sand-filled grain sacks, hooded kerosene lantern, wire linked to a plain copper bell.',
    materialRule: 'Small, repaired and muddy. Avoid concrete megabunkers, searchlights and fantasy fortification density.',
  },
  {
    dressingId: 'dressingClothingSilhouettes',
    landmarkId: 'stationHouse',
    positions: [
      { x: 13, y: 3.0, z: 2 },
      { x: 18, y: 2.8, z: -2 },
    ],
    visual: 'Layered cotton jackets, tied trouser cuffs, cloth shoes, reused headscarves and shoulder poles; wear differs by person and task.',
    materialRule: 'No uniform peasant costume, no glossy leather arsenal, no modern backpacks or zippers.',
  },
  {
    dressingId: 'dressingCulvertUseHistory',
    landmarkId: 'drainageCulvert',
    positions: [
      { x: -3.8, y: 0.65, z: -59.5 },
      { x: -6, y: 0.4, z: -63 },
    ],
    visual: 'Stone-lined irrigation drain with mineral water lines, shoulder-pole abrasion and fresh mud only at the edges.',
    materialRule: 'Readable dampness and use history; no sewer slime, bones or horror dressing.',
  },
];

export const encounterRules = {
  maximumSimultaneousEnemies: 4,
  maximumAuthoredEnemiesInSlice: 8,
  endlessReinforcements: false,
  enemyBodyLootEnabled: false,
  civilianEscortHealthBars: false,
  civilianCasualtyCounter: false,
  civilianCombatTargeting: false,
  combatGoal: 'Break sightlines or hold the kiln mouth until the shuttered-lamp signal, then disengage.',
  stealthGoal: 'Read patrol rhythm, use reeds and retaining walls, disable the bell wire, cross the culvert.',
  resourceRules: {
    startingRifleRounds: 4,
    optionalConsentedRifleRounds: 2,
    startingFieldDressings: 1,
    maximumDistractionStones: 3,
    instantHealing: false,
    domesticLoot: false,
  },
  protectedCorridorRule: 'If a hostile crosses into culvertProtectedCorridor before allCiviliansClear, fade and restart at checkpointLimeKiln before contact.',
  scoringRule: 'No kill count, survivor count, loot percentage or morality score. Only authored consequence flags alter dialogue and ending availability.',
};

export const checkpoints = [
  { checkpointId: 'checkpointRavine', position: { x: -37, y: 1.2, z: 69 }, facingYawDegrees: 198, stageId: 'reachOldMill' },
  { checkpointId: 'checkpointVillageLane', position: { x: -18, y: 3.0, z: 32 }, facingYawDegrees: 188, stageId: 'meetStationKeeper' },
  { checkpointId: 'checkpointStationYard', position: { x: 13, y: 3.0, z: 2 }, facingYawDegrees: 170, stageId: 'prepareQuietPassage' },
  { checkpointId: 'checkpointDryDitch', position: { x: 28, y: 1.0, z: -24 }, facingYawDegrees: 235, stageId: 'reachIrrigationDitch' },
  { checkpointId: 'checkpointLimeKiln', position: { x: -27, y: 5.1, z: -79 }, facingYawDegrees: 26, stageId: 'holdKilnMouth' },
  { checkpointId: 'checkpointRouteDecision', position: { x: -35, y: 2.2, z: -96 }, facingYawDegrees: 187, stageId: 'decideRouteFate' },
];

export const levelValidation = {
  requiredExports: ['levelZones', 'patrolRoutes', 'interactables', 'storyTriggers'],
  expectedStageOrder: ['reachOldMill', 'readStoneSignal', 'meetStationKeeper', 'prepareQuietPassage', 'openEastGate', 'reachIrrigationDitch', 'disableWarningLine', 'crossDrainageCulvert', 'holdKilnMouth', 'waitForClearSignal', 'decideRouteFate', 'reachSafeRidge'],
  coordinateAssertions: [
    'playerSpawn.z must be between 65 and 70',
    'extractionPoint.z must be between -110 and -105',
    'critical-path waypoint z values must trend from positive to negative except for local stealth loops',
  ],
  runtimeAssertions: [
    'Every eventId used by storyTriggers exists in Data_Story.storyEvents unless it is null.',
    'Every interactable referenced by a trigger exists and is within 0.25 meters of its trigger center.',
    'The eastGateLatch is a required interaction after handcartAxle and sets eastGateOpen plus convoyMoving before the ditch objective begins.',
    'Both endings are reachable from checkpointRouteDecision in a clean-alert run.',
    'The seal ending remains reachable at every alert level.',
    'No enemy spawn, search anchor or patrol point lies inside culvertProtectedCorridor.',
    'A full desktop keyboard-and-mouse run completes in 12 to 18 minutes.',
    'Visual review must include actual screenshots from the ravine, village lane, blockade sightline, kiln hold and both ending states.',
    'Gameplay review must complete one no-shot run, one detected recovery run and one high-alert forced-seal run.',
  ],
};

export const levelData = {
  metadata: levelMetadata,
  landmarks,
  levelZones,
  patrolRoutes,
  interactables,
  storyTriggers,
  navigationRoutes,
  traversalLinks,
  ambientVolumes,
  historicalDressing,
  encounterRules,
  checkpoints,
  validation: levelValidation,
};

export default levelData;
