import type { AssetManifest } from '../types/assets.types';

export const assetManifest: AssetManifest = {
  images: {
    shopCounter: './assets/art/realistic-shop-counter.png',
    phoneOverlays: './assets/art/phone_overlay.png',
    icon_chat: './assets/art/icon_chat.png',
    icon_mail: './assets/art/icon_mail.png',
    icon_social: './assets/art/icon_social.png',
    icon_news: './assets/art/icon_news.png',
    icon_shop: './assets/art/icon_shop.png',
    icon_game: './assets/art/icon_game.png',
    icon_video: './assets/art/icon_video.png',
    icon_music: './assets/art/icon_music.png',
    icon_photo: './assets/art/icon_photo.png',
    icon_map: './assets/art/icon_map.png',
    icon_weather: './assets/art/icon_weather.png',
    icon_calendar: './assets/art/icon_calendar.png',
    wallpaper_1: './assets/art/wallpaper_1.png',
    wallpaper_2: './assets/art/wallpaper_2.png',
    wallpaper_3: './assets/art/wallpaper_3.png',
    wallpaper_4: './assets/art/wallpaper_4.png',
    wallpaper_5: './assets/art/wallpaper_5.png',
    wallpaper_6: './assets/art/wallpaper_6.png',
    wallpaper_7: './assets/art/wallpaper_7.png',
    wallpaper_8: './assets/art/wallpaper_8.png',
    cust_a_neutral: './assets/art/cust_a_neutral.png',
    cust_b_neutral: './assets/art/cust_b_neutral.png',
    cust_c_neutral: './assets/art/cust_c_neutral.png',
    cust_d_neutral: './assets/art/cust_d_neutral.png',
    cust_e_neutral: './assets/art/cust_e_neutral.png',
    cust_f_neutral: './assets/art/cust_f_neutral.png',
    ad_redpacket: './assets/art/ad_redpacket.png',
    ad_offer: './assets/art/ad_offer.png',
    scam_warning: './assets/art/scam_warning.png',
  },
  audio: {},
};
