import type { SkillDef } from '../types/content.types';

export const skills: SkillDef[] = [
  {
    id: 'skill_clearphone',
    name: '整机秒清',
    desc: '立刻清空当前手机。',
    artId: 'skill_clearphone',
    unlockLevel: 5,
    cooldownMs: 25_000,
    effect: { kind: 'clearActivePhone' },
  },
  {
    id: 'skill_freeze',
    name: '信号冻结',
    desc: '12 秒内不再涌入新角标。',
    artId: 'skill_freeze',
    unlockLevel: 8,
    cooldownMs: 60_000,
    effect: { kind: 'freezeIncoming', durationMs: 12_000 },
  },
  {
    id: 'skill_soothe',
    name: '柜台安抚',
    desc: '回满整条队伍的耐心。',
    artId: 'skill_soothe',
    unlockLevel: 10,
    cooldownMs: 45_000,
    effect: { kind: 'sootheQueue' },
  },
  {
    id: 'skill_hands',
    name: '多几双手',
    desc: '临时增加自动清理帮手。',
    artId: 'skill_hands',
    unlockLevel: 12,
    cooldownMs: 90_000,
    effect: { kind: 'extraHands', hands: 2, durationMs: 15_000 },
  },
  {
    id: 'skill_tip',
    name: '小费冲刺',
    desc: '短时间内报酬和经验翻倍。',
    artId: 'skill_tip',
    unlockLevel: 15,
    cooldownMs: 120_000,
    effect: { kind: 'tipBoost', mult: 2, durationMs: 20_000 },
  },
  {
    id: 'skill_magnet',
    name: '角标磁吸',
    desc: '点击会吸附附近角标。',
    artId: 'skill_magnet',
    unlockLevel: 18,
    cooldownMs: 60_000,
    effect: { kind: 'magnet', durationMs: 10_000 },
  },
];
