import type { SkillDef } from '../types/content.types';

// 重设技能：移除作用不明的"磁吸"；新增针对弹窗的"一键净化"并前置；
// "安抚"改为回满全场（含在岗顾客）；"砸机"解锁等级前移到 20。
export const skills: SkillDef[] = [
  {
    id: 'skill_clearphone',
    name: '整机秒清',
    desc: '立刻清空当前手机的所有角标。',
    artId: 'skill_clearphone',
    icon: '🧼',
    unlockLevel: 3,
    cooldownMs: 25_000,
    effect: { kind: 'clearActivePhone' },
  },
  {
    id: 'skill_closeall',
    name: '一键净化',
    desc: '关闭所有手机上的全部弹窗（含诈骗弹窗）。',
    artId: 'skill_closeall',
    icon: '🛡️',
    unlockLevel: 6,
    cooldownMs: 28_000,
    effect: { kind: 'closeAllPopups' },
  },
  {
    id: 'skill_freeze',
    name: '信号冻结',
    desc: '10 秒内不再涌入新角标与新弹窗。',
    artId: 'skill_freeze',
    icon: '❄️',
    unlockLevel: 8,
    cooldownMs: 48_000,
    effect: { kind: 'freezeIncoming', durationMs: 10_000 },
  },
  {
    id: 'skill_soothe',
    name: '柜台安抚',
    desc: '回满全场顾客（含在修）的耐心。',
    artId: 'skill_soothe',
    icon: '☕',
    unlockLevel: 10,
    cooldownMs: 40_000,
    effect: { kind: 'sootheQueue' },
  },
  {
    id: 'skill_hands',
    name: '多几双手',
    desc: '12 秒内临时增加 2 名自动清理帮手。',
    artId: 'skill_hands',
    icon: '🙌',
    unlockLevel: 13,
    cooldownMs: 70_000,
    effect: { kind: 'extraHands', hands: 2, durationMs: 12_000 },
  },
  {
    id: 'skill_tip',
    name: '小费冲刺',
    desc: '18 秒内报酬与经验翻倍。',
    artId: 'skill_tip',
    icon: '💰',
    unlockLevel: 16,
    cooldownMs: 100_000,
    effect: { kind: 'tipBoost', mult: 2, durationMs: 18_000 },
  },
  {
    id: 'skill_smash',
    name: '砸机收割',
    desc: '砸碎当前手机，所有角标一次飞出并结算。',
    artId: 'skill_smash',
    icon: '🔨',
    unlockLevel: 20,
    cooldownMs: 110_000,
    effect: { kind: 'smashActivePhone' },
  },
];
