import type { UpgradeDef } from '../types/content.types';

export const upgrades: UpgradeDef[] = [
  {
    id: 'up_clear',
    name: '厚手指',
    desc: '每次点击多清 1 个角标。',
    category: 'clear',
    artId: 'up_clear',
    baseCost: 25,
    costGrowth: 1.15,
    maxLevel: 0,
    effect: (level) => level,
  },
  {
    id: 'up_swipe',
    name: '顺滑手势',
    desc: '解锁按住滑动，拖过红色角标即可连清。',
    category: 'swipe',
    artId: 'up_swipe',
    baseCost: 100,
    costGrowth: 1.15,
    maxLevel: 1,
    effect: (level) => (level > 0 ? 1 : 0),
  },
  {
    id: 'up_value',
    name: '经验账本',
    desc: '每个角标获得更多经验。',
    category: 'value',
    artId: 'up_value',
    baseCost: 40,
    costGrowth: 1.15,
    maxLevel: 0,
    effect: (level) => Math.pow(1.15, level),
  },
  {
    id: 'up_slot',
    name: '加装工位',
    desc: '桌面上多摆一台手机，同时处理更多订单。',
    category: 'slot',
    artId: 'up_slot',
    baseCost: 500,
    costGrowth: 1.25,
    maxLevel: 5,
    effect: (level) => level,
  },
  {
    id: 'up_queue',
    name: '候客架',
    desc: '候客区多容纳一位顾客。',
    category: 'queue',
    artId: 'up_queue',
    baseCost: 120,
    costGrowth: 1.18,
    maxLevel: 6,
    effect: (level) => level,
  },
  {
    id: 'up_patience',
    name: '软座椅',
    desc: '顾客多等十秒。',
    category: 'patience',
    artId: 'up_patience',
    baseCost: 90,
    costGrowth: 1.18,
    maxLevel: 6,
    effect: (level) => level * 10_000,
  },
  {
    id: 'up_botcount',
    name: '招学徒',
    desc: '学徒会自动帮忙清角标。',
    category: 'auto',
    artId: 'up_botcount',
    baseCost: 200,
    costGrowth: 1.22,
    maxLevel: 0,
    effect: (level) => level,
  },
  {
    id: 'up_botspeed',
    name: '学徒训练',
    desc: '学徒清理速度更快。',
    category: 'auto',
    artId: 'up_botspeed',
    baseCost: 150,
    costGrowth: 1.18,
    maxLevel: 0,
    effect: (level) => Math.pow(1.2, level),
  },
  {
    id: 'up_payout',
    name: '金牌服务',
    desc: '归还手机时获得更多报酬。',
    category: 'payout',
    artId: 'up_payout',
    baseCost: 300,
    costGrowth: 1.2,
    maxLevel: 0,
    effect: (level) => Math.pow(1.2, level),
  },
];
