import type { UpgradeDef } from '../types/content.types';

export const upgrades: UpgradeDef[] = [
  {
    id: 'up_clear',
    name: 'Heavy Thumb',
    desc: 'Clear one more badge per hit.',
    category: 'clear',
    artId: 'up_clear',
    baseCost: 25,
    costGrowth: 1.15,
    maxLevel: 0,
    effect: (level) => level,
  },
  {
    id: 'up_swipe',
    name: 'Swipe Polish',
    desc: 'Drag across apps to clear a path.',
    category: 'swipe',
    artId: 'up_swipe',
    baseCost: 100,
    costGrowth: 1.15,
    maxLevel: 1,
    effect: (level) => (level > 0 ? 1 : 0),
  },
  {
    id: 'up_value',
    name: 'Receipt Ledger',
    desc: 'Earn more XP per badge.',
    category: 'value',
    artId: 'up_value',
    baseCost: 40,
    costGrowth: 1.15,
    maxLevel: 0,
    effect: (level) => Math.pow(1.15, level),
  },
  {
    id: 'up_slot',
    name: 'Extra Bench',
    desc: 'Run another phone station.',
    category: 'slot',
    artId: 'up_slot',
    baseCost: 500,
    costGrowth: 1.25,
    maxLevel: 3,
    effect: (level) => level,
  },
  {
    id: 'up_queue',
    name: 'Waiting Shelf',
    desc: 'Fit another queued customer.',
    category: 'queue',
    artId: 'up_queue',
    baseCost: 120,
    costGrowth: 1.18,
    maxLevel: 6,
    effect: (level) => level,
  },
  {
    id: 'up_patience',
    name: 'Soft Chairs',
    desc: 'Customers wait ten seconds longer.',
    category: 'patience',
    artId: 'up_patience',
    baseCost: 90,
    costGrowth: 1.18,
    maxLevel: 6,
    effect: (level) => level * 10_000,
  },
  {
    id: 'up_botcount',
    name: 'Hire Apprentice',
    desc: 'Apprentices clear badges automatically.',
    category: 'auto',
    artId: 'up_botcount',
    baseCost: 200,
    costGrowth: 1.22,
    maxLevel: 0,
    effect: (level) => level,
  },
  {
    id: 'up_botspeed',
    name: 'Practice Drills',
    desc: 'Apprentices work faster.',
    category: 'auto',
    artId: 'up_botspeed',
    baseCost: 150,
    costGrowth: 1.18,
    maxLevel: 0,
    effect: (level) => Math.pow(1.2, level),
  },
  {
    id: 'up_payout',
    name: 'Gold Service',
    desc: 'Increase payout from returned phones.',
    category: 'payout',
    artId: 'up_payout',
    baseCost: 300,
    costGrowth: 1.2,
    maxLevel: 0,
    effect: (level) => Math.pow(1.2, level),
  },
];
