import type { UpgradeDef } from '../types/content.types';

// 重新平衡：高频核心升级设上限，避免无限叠加碾压玩法；新增两项"弹窗对抗"升级。
export const upgrades: UpgradeDef[] = [
  {
    id: 'up_clear',
    name: '厚手指',
    desc: '每次点击多清 1 个角标（最高 +8）。',
    category: 'clear',
    artId: 'up_clear',
    baseCost: 30,
    costGrowth: 1.18,
    maxLevel: 8,
    effect: (level) => level,
  },
  {
    id: 'up_swipe',
    name: '顺滑手势',
    desc: '解锁按住滑动，拖过红色角标即可连清。',
    category: 'swipe',
    artId: 'up_swipe',
    baseCost: 130,
    costGrowth: 1,
    maxLevel: 1,
    effect: (level) => (level > 0 ? 1 : 0),
  },
  {
    id: 'up_value',
    name: '经验账本',
    desc: '每个角标的经验 ×1.12 累乘。',
    category: 'value',
    artId: 'up_value',
    baseCost: 55,
    costGrowth: 1.16,
    maxLevel: 0,
    effect: (level) => Math.pow(1.12, level),
  },
  {
    id: 'up_payout',
    name: '金牌服务',
    desc: '归还手机的报酬 ×1.18 累乘。',
    category: 'payout',
    artId: 'up_payout',
    baseCost: 240,
    costGrowth: 1.2,
    maxLevel: 0,
    effect: (level) => Math.pow(1.18, level),
  },
  {
    id: 'up_slot',
    name: '加装工位',
    desc: '同时多修一台手机（最多 +4）。',
    category: 'slot',
    artId: 'up_slot',
    baseCost: 650,
    costGrowth: 1.32,
    maxLevel: 4,
    effect: (level) => level,
  },
  {
    id: 'up_queue',
    name: '候客架',
    desc: '候客区多容纳一位顾客（最多 +6）。',
    category: 'queue',
    artId: 'up_queue',
    baseCost: 150,
    costGrowth: 1.2,
    maxLevel: 6,
    effect: (level) => level,
  },
  {
    id: 'up_patience',
    name: '软座椅',
    desc: '所有顾客多等 8 秒（最多 +8 级）。',
    category: 'patience',
    artId: 'up_patience',
    baseCost: 110,
    costGrowth: 1.2,
    maxLevel: 8,
    effect: (level) => level * 8_000,
  },
  {
    id: 'up_botcount',
    name: '招学徒',
    desc: '学徒自动帮忙清角标（最多 6 名）。',
    category: 'auto',
    artId: 'up_botcount',
    baseCost: 280,
    costGrowth: 1.26,
    maxLevel: 6,
    effect: (level) => level,
  },
  {
    id: 'up_botspeed',
    name: '学徒训练',
    desc: '学徒清理速度 ×1.18 累乘（最多 8 级）。',
    category: 'auto',
    artId: 'up_botspeed',
    baseCost: 200,
    costGrowth: 1.2,
    maxLevel: 8,
    effect: (level) => Math.pow(1.18, level),
  },
  {
    id: 'up_adblock',
    name: '防弹窗插件',
    desc: '降低广告弹窗出现频率（最多 6 级）。',
    category: 'defense',
    artId: 'up_adblock',
    baseCost: 220,
    costGrowth: 1.22,
    maxLevel: 6,
    effect: (level) => level,
  },
  {
    id: 'up_antivirus',
    name: '安全卫士',
    desc: '诈骗弹窗更少、留给你更久的拆除时间、扣费更低（最多 5 级）。',
    category: 'defense',
    artId: 'up_antivirus',
    baseCost: 360,
    costGrowth: 1.25,
    maxLevel: 5,
    effect: (level) => level,
  },
];
