// Measure the shipped skeletons, never infer gait speed from an AI speed setting.
// Node-only, deterministic; no source GLB is modified.
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { LoadGlb, PoseScene } from './Script_LugouGlbPose.mjs';
import { CHARACTER_INFANTRY_SOURCE_BY_MODEL } from '../Data_CharacterSelection.mjs';

const project = path.resolve(import.meta.dirname, '..');
const catalog = JSON.parse(fs.readFileSync(path.join(project, 'Model/Character/Data_LugouCharacterManifest.json')));
const profiles = {};
const Round = v => +v.toFixed(6);
const Median = values => values.sort((a,b) => a-b)[Math.floor(values.length/2)];

function Measure(file, id) {
  const bytes = fs.readFileSync(path.join(project, file)), scene = new PoseScene(LoadGlb(bytes));
  const index = scene.AnimationIndex(id), duration = scene.animations[index].duration;
  const count = Math.ceil(duration * 120), step = duration/count, frames = [];
  const nodes = ['L','R'].map(side => scene.FindNode(new RegExp(` ${side} Toe0$`)));
  for(let i=0;i<=count;i++) {
    scene.Apply(index,i*step);
    frames.push(nodes.map(node => Array.from(scene.world[node].slice(12,15))));
  }
  const contacts = {}, speeds = [];
  for(const [sideIndex,side] of ['L','R'].entries()) {
    const floor = Math.min(...frames.map(frame => frame[sideIndex][1]));
    const stance = frames.map((frame,i) => {
      const lo=Math.max(0,i-1), hi=Math.min(count,i+1);
      const velocity = -(frames[hi][sideIndex][2]-frames[lo][sideIndex][2])/((hi-lo)*step);
      const grounded = frame[sideIndex][1] < floor+.035 && velocity>.12;
      if(grounded)speeds.push(velocity);
      return grounded;
    });
    contacts[side]=[];
    for(let start=0;start<count;start++) {
      if(!stance[start])continue;
      let end=start+1;while(end<count&&stance[end])end++;
      if((end-start)*step>.075)contacts[side].push([Round(start/count),Round(end/count)]);
      start=end;
    }
  }
  if(!speeds.length || !contacts.L.length || !contacts.R.length)throw new Error(`No measured stance: ${file}/${id}`);
  return {duration:Round(duration),referenceMps:Round(Median(speeds)),contacts,
    source:file,sha256:crypto.createHash('sha256').update(bytes).digest('hex')};
}

for(const record of catalog.models) {
  const entries={RifleRun:Measure(`Model/Character/Model_${record.id}.glb`,'RifleRun')};
  // The crouch source already has independently verified sole-contact correction.
  // Keep its measured linear travel speed; ankle roll is not root travel.
  const infantrySource=CHARACTER_INFANTRY_SOURCE_BY_MODEL[record.id]||record.id;
  if(!infantrySource.endsWith('05')) {
    const infantry = JSON.parse(fs.readFileSync(path.join(project,'Model/Character/Data_InfantryAnimations.json')));
    const source=infantry.models.find(model=>model.id===infantrySource);
    const clip=source.clips.find(clip=>clip.id==='RifleCrouchAdvance');
    entries.RifleCrouchAdvance={referenceMps:clip.referenceSpeedMps};
  }
  profiles[record.id]=entries;
}
const back=Measure('Animation/BackRifleRun/Animation_LugouNraBackRifleRun.glb','BackRifleRun');
for(const [id,entries] of Object.entries(profiles))if(id.startsWith('LugouNra'))entries.BackRifleRun=back;
const text='// Generated by _import/Script_LocomotionProfileBake.mjs from shipped GLBs at 120 Hz.\n'
  +'export const ACTOR_LOCOMOTION_PROFILES = '+JSON.stringify(profiles,null,2)+';\n';
const target=path.join(project,'Data_ActorLocomotion.mjs');
if(process.argv.includes('--verify')) {
  if(fs.readFileSync(target,'utf8').replace(/\r\n/g,'\n')!==text)throw new Error('Locomotion profiles are stale; rebake them');
}else fs.writeFileSync(target,text);
console.log(JSON.stringify(Object.fromEntries(Object.entries(profiles).map(([id,p])=>[id,Object.fromEntries(Object.entries(p).map(([clip,v])=>[clip,v.referenceMps]))]))));
