// ===========================================================================
// Script_ExportRailBridgeTerrain.mjs —— 给 Script_BuildRailBridge.py 喂地形
//
// 北沙河铁路桥的模型与坍塌动画在 Blender 里建（docs/Data_RailBridge.md）。
// 坍塌时桥身、碎块要落在**游戏里真实的河槽与岸坡**上，Blender 读不到 JS 地形，
// 所以这里把桥附近一片高度场按桥的局部坐标采出来（原点 = MISSION_RAIL_BRIDGE 的
// (x, 0, z)，x 东、y 上、z 南，与游戏同轴），连同水面、爆破手撤出点一起写成 JSON。
//
//   node Taierzhuang1938/_blender/Script_ExportRailBridgeTerrain.mjs
//
// 地形或桥位改了就重跑它，再重烘模型（Blender 脚本只认这份 JSON）。
// ===========================================================================
import fs from "node:fs";
import { SampleMissionTerrain } from "../Data_FirstLevelMissionTerrain.mjs";
import { MISSION_RAIL_BRIDGE, MISSION_NORTH_RIVER, MISSION_STAGE_ANCHORS, RiverProfileAt } from "../Data_FirstLevelMissionTopology.mjs";
import { END_TUNING as E } from "../Data_Tuning_FirstLevelEnd.mjs";

const B = MISSION_RAIL_BRIDGE;
const GRID = { x0: -26, x1: 26, z0: -32, z1: 56, step: 1 };
const heights = [];
for (let z = GRID.z0; z <= GRID.z1; z += GRID.step) {
  const row = [];
  for (let x = GRID.x0; x <= GRID.x1; x += GRID.step) row.push(Number(SampleMissionTerrain(B.x + x, B.z + z).toFixed(3)));
  heights.push(row);
}
// 与 Data_FirstLevelMissionLayout 的 NorthRiverWater* 同一口径：槽底以上 1.2 m，
// 水面半宽 min(7.5, floorHalfW - 3.5)，体块厚 0.14（这里给的是水面顶）。
const profile = RiverProfileAt(B.x, MISSION_NORTH_RIVER);
const waterHalfW = Math.min(7.5, profile.floorHalfW - 3.5);
const waterTop = SampleMissionTerrain(B.x - 1, MISSION_NORTH_RIVER.z) + 1.2 + 0.07;
const Local = (p) => ({ x: Number((p.x - B.x).toFixed(3)), z: Number((p.z - B.z).toFixed(3)) });
const out = {
  note: "Generated by Script_ExportRailBridgeTerrain.mjs; bridge-local metres (x east, y up, z south).",
  origin: { x: B.x, y: 0, z: B.z },
  grid: GRID, heights,
  water: { top: Number(waterTop.toFixed(3)), halfW: waterHalfW, riverZ: MISSION_NORTH_RIVER.z - B.z },
  deck: { topY: B.deckTopY, halfD: B.deckHalfD, w: B.deckW, trussOffsetX: B.trussOffsetX, railGaugeHalf: B.railGaugeHalf,
    gapZ: B.gapZ.map((z) => z - B.z) },
  blastSafe: Local(MISSION_STAGE_ANCHORS.blastSafe),
  exploder: Local(E.exploderAt),
};
const target = new URL("./Data_RailBridgeTerrain.json", import.meta.url);
fs.writeFileSync(target, JSON.stringify(out) + "\n");
console.log(`wrote ${target.pathname} (${heights.length}x${heights[0].length}, water top ${out.water.top}, exploder ${JSON.stringify(out.exploder)})`);
