// ===========================================================================
// Script_ExportRailBridgeTerrain.mjs —— 给 Script_BuildRailBridge.py 喂地形与桥位
//
// 北沙河铁路桥的模型与坍塌动画在 Blender 里建（docs/Data_RailBridge.md）。
// 坍塌时桥身、碎块要落在**游戏里真实的河槽与岸坡**上，Blender 读不到 JS 地形，
// 所以这里把桥附近一片高度场按桥的局部坐标采出来（原点 = MISSION_RAIL_BRIDGE 的
// (x, 0, z)，x 东、y 上、z 南，与游戏同轴），连同水面、桥位布局（三孔、三墩、两端桥台）、
// 爆破手落位、爆破手撤出点一起写成 JSON。
//
//   node Taierzhuang1938/_blender/Script_ExportRailBridgeTerrain.mjs
//
// 2026-09-30 三孔：原点是被炸那一孔（SpanSouth）的中心，z 80…175 的世界范围对应局部 −68…+27，
// 高度场覆盖局部 z −80…+40、x ±40（河宽约 66 m，碎件与水花要落得下）。
// 地形、桥位、爆破手落位改了就重跑它，再重烘模型（Blender 脚本只认这份 JSON）。
// ===========================================================================
import fs from "node:fs";
import { SampleMissionTerrain, SampleMissionNaturalHeight } from "../Data_FirstLevelMissionTerrain.mjs";
import { MISSION_RAIL_BRIDGE, MISSION_NORTH_RIVER, MISSION_STAGE_ANCHORS, RiverWaterAt } from "../Data_FirstLevelMissionTopology.mjs";
import { MISSION_PLACEMENT } from "../Data_FirstLevelMissionLayout.mjs";
import { END_TUNING as E } from "../Data_Tuning_FirstLevelEnd.mjs";

const B = MISSION_RAIL_BRIDGE;
const GRID = { x0: -40, x1: 40, z0: -80, z1: 40, step: 1 };
const heights = [];
for (let z = GRID.z0; z <= GRID.z1; z += GRID.step) {
  const row = [];
  for (let x = GRID.x0; x <= GRID.x1; x += GRID.step) row.push(Number(SampleMissionTerrain(B.x + x, B.z + z).toFixed(3)));
  heights.push(row);
}
// 与 Data_FirstLevelMissionLayout 的 NorthRiverWater* 同一口径（RiverWaterAt）：拓宽河段水面在南岸自然地面下
// 1.25 m，水线取断面上正好没水的位置；这里给的是水面顶与南北水线（局部 z）。
const water = RiverWaterAt(B.x, MISSION_NORTH_RIVER);
const waterTop = SampleMissionNaturalHeight(B.x, MISSION_NORTH_RIVER.z) + water.level;
const Local = (p) => ({ x: Number((p.x - B.x).toFixed(3)), z: Number((p.z - B.z).toFixed(3)) });
const Lz = (z) => Number((z - B.z).toFixed(3));
const crew = MISSION_PLACEMENT.bridge.demolition.map((post) => ({ ...Local(post), yaw: post.yaw }));
const out = {
  note: "Generated by Script_ExportRailBridgeTerrain.mjs; bridge-local metres (x east, y up, z south).",
  origin: { x: B.x, y: 0, z: B.z },
  grid: GRID, heights,
  water: { top: Number(waterTop.toFixed(3)), z0: Lz(water.z0), z1: Lz(water.z1),
    riverZ: Number(((water.z0 + water.z1) / 2 - B.z).toFixed(3)), halfW: Number(((water.z1 - water.z0) / 2).toFixed(3)) },
  deck: { topY: B.deckTopY, halfD: B.deckHalfD, w: B.deckW, trussOffsetX: B.trussOffsetX, railGaugeHalf: B.railGaugeHalf,
    gapZ: B.gapZ.map(Lz) },
  // 三孔布局（局部 z）：spans 的 z0 是南端、z1 是北端；piers 是墩心；abutmentZ 是 [北, 南] 桥台碰撞盒中心。
  layout: {
    spans: B.spans.map((s) => ({ id: s.id, z0: Lz(s.z0), z1: Lz(s.z1), blasted: !!s.blasted })),
    piers: B.piers.map((p) => ({ id: p.id, z: Lz(p.z) })), pierW: B.pierW, pierD: B.pierD,
    abutmentZ: B.abutmentZ.map(Lz), approachSouth: { z0: Lz(B.approachSouth.z0), z1: Lz(B.approachSouth.z1) },
  },
  crew,
  blastSafe: Local(MISSION_STAGE_ANCHORS.blastSafe),
  exploder: Local(E.exploderAt),
};
const target = new URL("./Data_RailBridgeTerrain.json", import.meta.url);
fs.writeFileSync(target, JSON.stringify(out) + "\n");
console.log(`wrote ${target.pathname} (${heights.length}x${heights[0].length}, water top ${out.water.top} z ${out.water.z0}..${out.water.z1}, `
  + `exploder ${JSON.stringify(out.exploder)}, crew ${JSON.stringify(crew)})`);
