/**
 * Static layout data for the Studio Survival side-scrolling office.
 *
 * Coordinates use a small 2D convention that is convenient for both Canvas
 * and a future 2.5D renderer: x grows from left to right, y grows upwards,
 * and a character's x/y position is the centre of its feet. Rectangles use
 * x as their left edge and y as their top edge unless noted otherwise.
 */

const FreezeList = (items) => Object.freeze(items.map((item) => Object.freeze({ ...item })));

export const WorldConfig = Object.freeze({
  width: 40,
  height: 12,
  groundY: 0,
  cameraViewportWidth: 12,
  cameraFollowOffset: 6,
  playerWidth: 0.72,
  playerHeight: 1.55,
  moveSpeed: 6,
  jumpSpeed: 10.5,
  gravity: -25,
  interactionRange: 2.15,
  collectibleRadius: 0.45,
  hazardDamageCooldown: 0.9,
  maxHealth: 100,
  hazardDamage: 18,
  spawn: Object.freeze({ x: 1.8, y: 0 }),
});

export const WorldBounds = Object.freeze({
  minX: 0,
  maxX: WorldConfig.width,
  minY: -8,
  maxY: WorldConfig.height,
});

export const Ground = Object.freeze({
  id: "ground",
  x: 0,
  y: WorldConfig.groundY,
  width: WorldConfig.width,
  height: 0.5,
  top: WorldConfig.groundY,
  solid: true,
});

export const Platforms = FreezeList([
  {
    id: "platformCoffee",
    x: 5.0,
    y: 1.8,
    width: 4.4,
    height: 0.32,
    top: 1.8,
    solid: true,
  },
  {
    id: "platformArchive",
    x: 12.8,
    y: 3.65,
    width: 4.7,
    height: 0.32,
    top: 3.65,
    solid: true,
  },
  {
    id: "platformServer",
    x: 20.4,
    y: 2.2,
    width: 4.2,
    height: 0.32,
    top: 2.2,
    solid: true,
  },
  {
    id: "platformRoof",
    x: 28.1,
    y: 4.05,
    width: 4.8,
    height: 0.32,
    top: 4.05,
    solid: true,
  },
  {
    id: "platformLaunch",
    x: 34.1,
    y: 2.75,
    width: 3.8,
    height: 0.32,
    top: 2.75,
    solid: true,
  },
]);

export const InteractionPoints = FreezeList([
  {
    id: "fridge",
    kind: "fridge",
    label: "冰箱",
    x: 3.7,
    y: 0,
    radius: 2.0,
    action: "food",
  },
  {
    id: "bank",
    kind: "bank",
    label: "银行",
    x: 7.6,
    y: 0,
    radius: 1.8,
    action: "finance",
  },
  {
    id: "lotteryMachine",
    kind: "lotteryMachine",
    label: "彩票机",
    x: 10.8,
    y: 0,
    radius: 1.65,
    action: "lottery",
  },
  {
    id: "talentMachine",
    kind: "talentMachine",
    label: "人才机",
    x: 14.2,
    y: 0,
    radius: 1.65,
    action: "talent",
  },
  {
    id: "workstationArt",
    kind: "workstation",
    moduleKey: "art",
    label: "美术工位",
    x: 17.9,
    y: 0,
    radius: 1.55,
    action: "module",
  },
  {
    id: "workstationDesign",
    kind: "workstation",
    moduleKey: "design",
    label: "策划工位",
    x: 19.8,
    y: 0,
    radius: 1.55,
    action: "module",
  },
  {
    id: "workstationClient",
    kind: "workstation",
    moduleKey: "client",
    label: "客户端工位",
    x: 21.7,
    y: 0,
    radius: 1.55,
    action: "module",
  },
  {
    id: "workstationPerformance",
    kind: "workstation",
    moduleKey: "performance",
    label: "性能工位",
    x: 23.6,
    y: 0,
    radius: 1.55,
    action: "module",
  },
  {
    id: "whiteboard",
    kind: "whiteboard",
    label: "白板",
    x: 27.1,
    y: 0,
    radius: 1.8,
    action: "directive",
  },
  {
    id: "promoSign",
    kind: "promoSign",
    label: "宣发牌",
    x: 30.1,
    y: 0,
    radius: 1.8,
    action: "marketing",
  },
  {
    id: "releaseDoor",
    kind: "releaseDoor",
    label: "发布门",
    x: 33.3,
    y: 0,
    radius: 1.85,
    action: "release",
  },
  {
    id: "monthCalendar",
    kind: "monthCalendar",
    label: "月历",
    x: 35.9,
    y: 0,
    radius: 1.65,
    action: "nextMonth",
  },
  {
    id: "offWorkDoor",
    kind: "offWorkDoor",
    label: "下班门",
    x: 37.7,
    y: 0,
    radius: 1.65,
    action: "nextMonth",
  },
  {
    id: "aiTerminal",
    kind: "aiTerminal",
    label: "AI终端",
    x: 39.25,
    y: 0,
    radius: 1.55,
    action: "ai",
  },
]);

export const Collectibles = FreezeList([
  {
    id: "questFragmentBrief",
    kind: "questFragment",
    moduleKey: "art",
    label: "需求碎片·简报",
    x: 6.2,
    y: 2.4,
    radius: 0.32,
    value: 1,
  },
  {
    id: "questFragmentMoodboard",
    kind: "questFragment",
    moduleKey: "design",
    label: "需求碎片·情绪板",
    x: 14.8,
    y: 4.2,
    radius: 0.32,
    value: 1,
  },
  {
    id: "questFragmentScope",
    kind: "questFragment",
    moduleKey: "client",
    label: "需求碎片·范围",
    x: 22.2,
    y: 2.75,
    radius: 0.32,
    value: 1,
  },
  {
    id: "questFragmentPitch",
    kind: "questFragment",
    moduleKey: "performance",
    label: "需求碎片·提案",
    x: 29.2,
    y: 4.6,
    radius: 0.32,
    value: 1,
  },
  {
    id: "questFragmentMetrics",
    kind: "questFragment",
    moduleKey: "art",
    label: "需求碎片·指标",
    x: 35.3,
    y: 3.3,
    radius: 0.32,
    value: 1,
  },
  {
    id: "questFragmentCredit",
    kind: "questFragment",
    moduleKey: "design",
    label: "需求碎片·署名",
    x: 38.45,
    y: 1.1,
    radius: 0.32,
    value: 1,
  },
]);

export const MovingHazards = FreezeList([
  {
    id: "printerCart",
    kind: "movingHazard",
    label: "失控打印车",
    x: 9.1,
    y: 0,
    width: 0.95,
    height: 0.8,
    axis: "x",
    amplitude: 1.8,
    speed: 1.2,
    phase: 0,
    damage: 18,
  },
  {
    id: "serverDrone",
    kind: "movingHazard",
    label: "服务器无人机",
    x: 22.1,
    y: 3.0,
    width: 0.9,
    height: 0.62,
    axis: "x",
    amplitude: 1.6,
    speed: 1.55,
    phase: 1.2,
    damage: 22,
  },
  {
    id: "coffeeRobot",
    kind: "movingHazard",
    label: "咖啡机器人",
    x: 31.9,
    y: 0,
    width: 0.78,
    height: 1.0,
    axis: "y",
    amplitude: 1.1,
    speed: 1.35,
    phase: 2.1,
    damage: 16,
  },
  {
    id: "launchConveyor",
    kind: "movingHazard",
    label: "发布传送带",
    x: 36.2,
    y: 2.75,
    width: 1.15,
    height: 0.72,
    axis: "x",
    amplitude: 1.0,
    speed: 1.8,
    phase: 2.8,
    damage: 20,
  },
]);

// Friendly aliases make the intent of the static data obvious to callers
// without duplicating arrays or creating a second source of truth.
export const QuestFragments = Collectibles;

export const WorldData = Object.freeze({
  config: WorldConfig,
  bounds: WorldBounds,
  ground: Ground,
  platforms: Platforms,
  interactions: InteractionPoints,
  collectibles: Collectibles,
  hazards: MovingHazards,
});
