import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const ReadLocal = (name) => readFileSync(new URL(name, import.meta.url), "utf8");

const html = ReadLocal("./index.html");
const css = ReadLocal("./Style_Play.css");
const script = ReadLocal("./Script_Play.mjs");
const setupChoiceScript = script.match(/function RenderSetupChoices\(\) \{[^]*?dom\.continueButton[^]*?\n\}/)?.[0] || "";
const contractDecisionPage = html.match(/<article class="contractPage contractDecisionPage active"[^]*?<\/article>/)?.[0] || "";
const sealKeyupSource = script.match(/dom\.sealButton\.addEventListener\("keyup"[^]*?\n  \}\);/)?.[0] || "";
const homeComputerSource = script.slice(
  script.indexOf("function OpenHomeComputerSheet"),
  script.indexOf("function OpenWorkstationSheet"),
);

assert.match(html, /viewport-fit=cover/, "the page must preserve phone safe-area insets");
assert.match(html, /id="mobileControls"/, "the touch-control region needs a stable DOM hook");
assert.match(html, /class="actionControls"/, "jump and interaction controls must share a right-thumb group");
assert.match(html, /id="moveLeftButton"[^>]+aria-pressed="false"/, "left movement needs an accessible held state");
assert.match(html, /id="moveRightButton"[^>]+aria-pressed="false"/, "right movement needs an accessible held state");
assert.match(html, /id="jumpButton"[^>]+aria-pressed="false"/, "jump needs visible press feedback");
assert.match(html, /id="interactButton"[^>]+disabled/, "interaction should begin disabled until a target is nearby");
assert.match(html, /Style_Play\.css\?v=20260815ag/, "UI changes must bypass the Pages cache");
assert.match(html, /Script_Play\.mjs\?v=20260815ag/, "gameplay changes must bypass the Pages cache");
assert.doesNotMatch(html, /Style_Play\.css\?v=20260815(?!ag)/, "the stylesheet cache-bust must stay unified");
assert.doesNotMatch(html, /Script_Play\.mjs\?v=20260815(?!ag)/, "the gameplay cache-bust must stay unified");
assert.match(html, /id="goalReveal"[^>]+role="dialog"[^>]+aria-modal="true"[^>]+aria-labelledby="goalRevealTitle"/, "the opening must contain an accessible creator-goal reveal");
assert.match(html, /id="goalRevealCounter">0<\/span><b>亿元<\/b>/, "the reveal must animate toward the explicit 100-yuan-billion target");
assert.match(html, /贷款 · 彩票 · 炒股/, "the reveal must say which cash sources do not count toward the creator goal");
assert.match(html, /你将成为成功的游戏制作人/, "the 100-yuan-billion goal must describe the creator milestone rather than victory");
assert.doesNotMatch(html, /胜利|通关/, "the active page must not frame 100-yuan-billion revenue as winning the game");
assert.match(html, /id="settlementButton"[^>]*aria-label="下一回合[^>]*>[\s\S]*?id="settlementMonthValue"/, "the bottom-right next-turn button needs a stable accessible DOM contract");
assert.doesNotMatch(html, /id="phoneButton"/, "the removed phone must not return as a HUD shortcut");
assert.match(html, /id="foundingNamePanel"[\s\S]*01 \/ 04/, "the founding book must begin with the first of four pages");
assert.match(html, /id="founderProfilePanel"[\s\S]*02 \/ 04/, "the founder profile must remain the second book page");
assert.match(html, /id="contractPageCounter">03 \/ 04/, "the project contract must continue the four-page book");
assert.equal([...html.matchAll(/data-contract-page=/g)].length, 2, "selection and signature must be the only contract pages");
assert.match(contractDecisionPage, /id="projectChoices"/, "theme choices must appear on the combined decision page");
assert.match(contractDecisionPage, /id="typeChoices"/, "release choices must appear beside the theme choices");
assert.doesNotMatch(html, /gameNameInput|游戏正式名称|填写游戏名/, "project setup must not ask the player to name the game");
assert.match(html, /签署发行合同/, "the final action must be presented as signing the publishing contract");

assert.match(css, /--controlSize:\s*clamp\(58px,\s*15\.5vh,\s*70px\)/, "primary controls must scale with short landscape screens");
assert.match(css, /\.interactButton\.available/, "the contextual action needs a high-confidence ready state");
assert.match(css, /min-height:\s*44px/, "sheet actions must retain a minimum touch target");
assert.match(css, /calc\(var\(--safeBottom\)/, "controls must sit above the phone home indicator");
assert.match(css, /\.mobileControls\.suppressed/, "world controls must disappear behind modal interactions");
assert.match(css, /\.settlementButton\s*\{[\s\S]*?position:\s*fixed;[\s\S]*?right:\s*var\(--safeRight\);[\s\S]*?bottom:\s*var\(--safeBottom\);/, "next turn must be pinned to the desktop bottom-right safe area");
assert.match(css, /\.settlementButton\s*\{[\s\S]*?bottom:\s*calc\(var\(--safeBottom\) \+ var\(--controlSize\) \+ 10px\);/, "touch layouts must keep next turn above the right-thumb controls");
assert.match(css, /\.modalLayer\.monthCloseMode \.worldPanel/, "monthly confirmation needs its own compact ritual surface");
assert.match(css, /\.modalLayer\.travelMapMode \.worldPanel/, "the destination map needs its own physical surface");
assert.match(css, /\.travelMapPaper\s*\{[^}]*aspect-ratio:/s, "the folded map must preserve its landscape layout");
assert.match(css, /\.travelMapPlace\s*\{[^}]*min-height:\s*52px/s, "desktop map places must read as substantial physical markers");
assert.match(css, /@media \(hover:none\), \(pointer:coarse\), \(max-width:920px\)[\s\S]*?\.travelMapPlace\s*\{[^}]*min-height:\s*44px/s, "phone map places must retain full touch targets");
assert.match(css, /\.projectCalendarLive\s*\{[^}]*grid-template-columns:/s, "post-launch store status needs a compact calendar layout");
assert.match(css, /\.projectCalendarReminder\s*\{/, "random events need a visible calendar reminder row");
assert.match(css, /\.resultLayer\.monthResultMode \.resultCard/, "monthly results need a distinct ceremonial reveal");
assert.match(css, /\.monthResultMode \.stockReturnGrid\s*\{\s*display:\s*none;/, "stock settlement must stay compact inside the monthly reveal");
assert.match(css, /\.cashStat\s*\{\s*display:\s*grid;/, "the smallest supported landscape must keep cash visible");
assert.match(css, /\.roundButton\s*\{[^}]*min-width:\s*44px;[^}]*min-height:\s*44px;/s, "utility controls must remain full touch targets");
assert.match(css, /\.goalReveal\.active \.goalRevealNumber/, "the 100-yuan-billion target needs a dedicated entrance animation");
assert.match(css, /\.goalRevealCard\s*\{\s*gap:5px;/, "the target reveal must compact itself on short landscape phones");
assert.match(css, /\.goalRevealButton\s*\{[^}]*min-height:44px;/, "the target acknowledgement must remain a full touch target");
assert.match(css, /\.contractDecisionGrid\s*\{[^}]*grid-template-columns:/s, "theme and release choices need a shared responsive contract grid");
assert.match(css, /\.contractDecisionPage\.active\s*\{[^}]*overflow-y:auto;/s, "short landscape screens must be able to scroll every contract choice into view");
assert.match(css, /\.contractReviewPage\.active\s*\{[^}]*height:100%;[^}]*overflow-y:auto;/s, "the signing page must scroll inside the book instead of hiding the seal behind navigation");
assert.match(css, /@media \(max-height: 410px\) and \(orientation: landscape\)[\s\S]*?\.projectContract \.contractReview\s*\{[^}]*grid-template-columns:repeat\(4,minmax\(0,1fr\)\);/s, "very short landscape phones must keep the contract summary on one row so the signing seal stays visible");
assert.doesNotMatch(css, /\.contractChoiceGroup \.compactRail\s*\{[^}]*grid-template-columns:\s*1fr/s, "three release modes must not stack into a clipped short-screen column");
assert.match(css, /\.stockPickGrid\s*\{/, "the bank stock picker needs a responsive two-choice layout");
assert.match(css, /\.stockMonthReport\s*\{/, "the next-turn result needs a dedicated stock chart report");
assert.match(css, /\.stockQuickAmounts button,[\s\S]*min-height:\s*44px/, "stock amount shortcuts must remain full touch targets");
assert.match(css, /\.founderSkillControls button\s*\{[^}]*min-height:\s*44px;/s, "founder skill steppers must remain full touch targets");
assert.doesNotMatch(css, /\.founderSkillPresets/, "founder setup must stay focused on the three editable abilities");
assert.match(css, /\.computerReleaseCallout button\s*\{[^}]*min-height:\s*44px;/s, "the release action must remain a full touch target");
assert.match(css, /\.endingActions button\s*\{[^}]*min-height:\s*48px;/s, "restart choices must remain full touch targets");
assert.match(css, /\.endingActions \{ grid-template-columns:minmax\(0,1\.45fr\) minmax\(150px,\.55fr\); \}/, "short landscape endings must keep both restart choices above the fold");
assert.doesNotMatch(css, /\.documentButton,\.bookBackButton\s*\{[^}]*min-height:\s*(?:3\d|4[0-3])px;/s, "book navigation must not shrink below a 44px touch target");
assert.doesNotMatch(css, /\.sealButton\s*\{[^}]*height:\s*(?:3\d|4[0-3])px;/s, "the signing seal must not shrink below a 44px touch target");
assert.match(css, /\.modalLayer\.computerMode \.worldPanel\s*\{/, "the home computer needs its own physical monitor shell");
assert.match(css, /\.computerMonitorShell\s*\{/, "the home computer must retain its monitor frame");
assert.match(css, /\.energyModuleGrid\s*\{/, "the computer must expose its four development work areas");
assert.match(css, /@media \(orientation: landscape\)\s*\{\s*\.modalLayer\.computerMode \.sheetBody\s*\{\s*overflow:hidden;/s, "the landscape computer must fit without an outer scrollbar");
assert.match(css, /@media \(max-height: 820px\) and \(min-height: 651px\) and \(orientation: landscape\)[\s\S]*?\.computerDeskScene\s*\{[^}]*padding:0 132px 82px 0;/, "medium-height screens must compact the physical computer before it overflows");
assert.match(css, /@media \(max-height: 500px\) and \(orientation: landscape\)[\s\S]*?\.computerObjective p,\.workCostNote,\.computerLocationHint\s*\{\s*display:none;/, "short screens must drop redundant monitor copy before hiding the keyboard");
assert.match(css, /\.modalLayer\.whiteboardMode \.worldPanel\s*\{/, "the project board needs its own enamel-board frame");
assert.match(css, /\.whiteboardMarkerSet\s*\{/, "the project board must retain its marker tray props");
assert.match(css, /\.whiteboardMode \.worldChoice::before/, "direction notes must stay physically pinned to the board");
assert.match(css, /\.whiteboardFocus\s*\{/, "the project board needs a visually dominant current-focus strip");
assert.match(css, /\.whiteboardAction\s*\{/, "selectable notes need a persistent touch-visible action cue");
assert.match(css, /\.whiteboardMode button\.worldChoice:focus-visible,[\s\S]*?outline:4px solid/, "whiteboard notes need an unmistakable keyboard focus state");
assert.match(css, /\.whiteboardMode button\.worldChoice:active:not\(:disabled\)/, "whiteboard notes need physical press feedback on touch screens");

assert.match(script, /SetTouchButtonPressed/, "held controls need deterministic visual state updates");
assert.match(script, /classList\.toggle\("available", interactionAvailable\)/, "interaction readiness must track the nearest target");
assert.match(script, /toggleAttribute\("inert", suppressed\)/, "hidden controls must leave the accessibility and touch order");
assert.match(script, /dom\.settlementButton\.addEventListener\("click"[\s\S]*?OpenMonthSheet\(\)/, "the permanent next-turn button must open project calendar confirmation");
assert.doesNotMatch(script, /event\.code === "KeyN"/, "monthly close must not gain an undocumented keyboard shortcut");
assert.doesNotMatch(script, /event\.code === "KeyM"|marketingPhone|OpenMarketPhoneSheet|OpenMarketingSheet|dom\.phoneButton/, "the phone surface and its controls must be gone");
assert.match(script, /function TurnContractPage\(/, "the contract must support explicit page turns");
assert.match(script, /function BeginSealHold\(/, "the contract must retain its deliberate signing gesture");
assert.doesNotMatch(script, /确认开局/, "the signing action must never fall back to generic start-game copy");
assert.doesNotMatch(sealKeyupSource, /CompleteContractSigning/, "releasing a keyboard key early must cancel instead of bypassing the one-second signature hold");
assert.match(script, /selectedProjectId = button\.dataset\.projectId;[\s\S]*?RenderSetupChoices\(\);[\s\S]*?data-project-id=[^\n]+\.focus\(/, "rebuilding theme cards must restore keyboard focus to the selected choice");
assert.match(script, /selectedGameTypeId = button\.dataset\.typeId;[\s\S]*?RenderSetupChoices\(\);[\s\S]*?data-type-id=[^\n]+\.focus\(/, "rebuilding release cards must restore keyboard focus to the selected choice");
assert.match(script, /addEventListener\("pointerleave", CancelSealHold\)/, "leaving the seal while pressed must cancel the signature timer");
assert.match(script, /data-computer-release|function OpenReleaseSheet\(/, "publishing must remain reachable from the development computer");
assert.match(script, /matches\?\.\("button, a, \[role='button'\]"\)[^\n]+\["Space", "Enter"\]/, "focused physical controls must retain native keyboard activation");
assert.match(script, /navigator\.vibrate\?\./, "coarse-pointer actions should provide optional tactile confirmation");
assert.match(script, /dom\.sheetBody\.scrollTop = 0/, "each interaction sheet must open at its own beginning");
assert.match(script, /ShowGoalReveal\(result\.state\)/, "fresh contracts must show the target before entering the playable world");
assert.match(script, /dom\.goalRevealButton\.addEventListener\("click", CompleteGoalReveal\)/, "the player must acknowledge the creator goal before play begins");
assert.match(script, /candidate\.status === "ended"[\s\S]*candidate\.outcome\?\.kind === "worldMaker"[\s\S]*你成为了成功的游戏制作人！/, "completed legacy saves must receive the current successful-creator ending copy");
assert.match(script, /AddPhysicalLabel\(sceneGroup, location\.name, ""/, "scene signs must render the place name without an explanatory subtitle");
assert.match(script, /OpenPanel\("地图", "去哪？"[\s\S]*\{ mode: "travelMap" \}/, "the exit interaction must open the compact map presentation");
assert.doesNotMatch(setupChoiceScript, /project\.pitch|project\.trend|gameType\.description|gameType\.warning/, "project choices must stay label-only");
assert.match(script, /function OpenBankSheet[\s\S]*?data-open-stock/, "stock trading must enter through the physical bank interaction");
assert.doesNotMatch(script, /function OpenHomeComputerSheet[\s\S]*?data-open-stock[\s\S]*?function OpenWorkstationSheet/, "the development computer must not expose stock trading");
assert.match(script, /function OpenScratchSheet\(/, "the supermarket counter must have its own scratch-card screen");
assert.match(script, /function StockSettlementReport\(/, "the next turn must render the monthly stock trend and return");
assert.doesNotMatch(script, /LOTTERY \/ STOCKS/, "stocks and scratch cards must not share the old combined entry");
assert.match(script, /classList\.toggle\("computerMode", panelOptions\.mode === "computer"\)/, "computer sheets need an isolated presentation mode");
assert.match(homeComputerSource, /class="computerDeskScene"/, "the home computer must render a desk scene inside the monitor");
assert.match(homeComputerSource, /class="computerMonitorShell"/, "the home computer must retain its physical monitor shell");
assert.match(homeComputerSource, /class="computerGlassFrame"/, "the CRT must have a separate curved-glass surround");
assert.match(homeComputerSource, /class="computerTopVent"/, "the CRT casing must retain visible ventilation");
assert.match(homeComputerSource, /class="computerTowerVisual"/, "the home computer must include a separate desktop tower");
assert.match(homeComputerSource, /class="computerKeyboardVisual"/, "the home computer must include its physical keyboard");
assert.match(homeComputerSource, /class="computerMouseVisual"/, "the home computer must include its physical mouse");
assert.match(homeComputerSource, /\{ mode: "computer" \}/, "the home computer must open in the physical monitor mode");
assert.doesNotMatch(homeComputerSource, /data-computer-action|OpenDirectiveSheet|OpenStockSheet|OpenTalentSheet|OpenMonthSheet/, "the development computer must not expose unrelated systems");

console.log("StudioSurvival mobile UI contract test passed");
