/*
 * 《纸上有家》互动叙事数据
 *
 * 所有人物、槐树沟村与石门河滩均为虚构。故事只让玩家影响一夜之间
 * 普通人的选择与保存下来的物件，不改变 1942 年太行敌后战场的真实进程。
 */

export const StoryMeta = {
  id: "paperHasAHome",
  title: "纸上有家",
  subtitle: "一封没有寄出的信",
  dateLabel: "1942年5月24日傍晚—25日清晨",
  placeLabel: "山西辽县·槐树沟村（虚构）",
  estimatedMinutes: [15, 25],
  startSceneId: "schoolAfterBell",
  endingMarker: "__ending__",
  saveKey: "TaihangLetters1942_Save_V1",
  premise: "侵华日军对太行根据地的五月“扫荡”压力逼近。十六岁的赵杏枝与四十一岁的乡村教师沈兰贞，在村民分散转移后，带着十九人的学生名册、一套钢板铁笔油印包和一束没有寄出的家信，走向河东的临时教学点。",
  historyBoundary: "槐树沟、石门河滩及全部角色都是虚构的复合创作。辽县名称、1942年5月太行敌后反“扫荡”的处境、群众与学校分散转移等宏观背景保持固定；玩家不能改变真实战局，也不会与真实人物相遇。",
  roleBoundary: "赵杏枝是学生与转移中的普通村民。她不持武器、不侦察敌情，也不承担战斗或诱敌任务；游戏中的勇气体现为照料、记忆、隐蔽和求助。",
  toneNote: "创伤以失散、道路中断、物资匮乏和相互照料克制呈现。任何结局都不靠角色必死催泪，也不以伤亡、击杀或牺牲换取分数。",
  initialStats: {
    time: 0,
    sound: 0,
    bond: 1,
    health: 4,
    paper: 4,
    compassion: 0,
  },
  initialItems: ["mimeographKit", "studentRoster", "letterBundle"],
  initialWords: [],
};

export const SupplyChoices = [
  {
    id: "packMedicine",
    label: "带上药布包",
    hint: "一小包外伤药与干净布条，能照料伤脚或沿途的病人。",
    itemId: "medicine",
    effects: {
      compassion: 1,
      itemsAdd: ["medicine"],
    },
  },
  {
    id: "packClothShoes",
    label: "带上旧布鞋和包袱带",
    hint: "鞋底厚实，另有一条捆油印包的长粗布带。",
    itemId: "clothShoes",
    effects: {
      health: 1,
      itemsAdd: ["clothShoes"],
    },
  },
  {
    id: "packLantern",
    label: "带上罩灯",
    hint: "只剩一点灯油；遮严以后，可以贴地照亮几步。",
    itemId: "hoodedLantern",
    effects: {
      itemsAdd: ["hoodedLantern"],
    },
  },
];

export const ItemDefinitions = [
  {
    id: "mimeographKit",
    label: "油印包",
    note: "分装的钢板、铁笔、蜡纸、简易油印框、少量油墨与小滚筒，用来制作识字页和寻人便笺。",
    glyph: "印",
  },
  {
    id: "studentRoster",
    label: "学生名册",
    note: "十九名学生的姓名、年龄与最后可靠去向；赵石头一栏暂记“待寻”。",
    glyph: "册",
  },
  {
    id: "letterBundle",
    label: "未寄出的信束",
    note: "孩子与沈兰贞写给失散亲人的家信，地址有的完整，有的仍留着空白。",
    glyph: "信",
  },
  {
    id: "medicine",
    label: "药布包",
    note: "一小包外伤药与干净布条，只够认真照料一次。",
    glyph: "药",
  },
  {
    id: "clothShoes",
    label: "旧布鞋和包袱带",
    note: "一双厚底旧鞋，另带一条可固定伤脚、捆扎油印包的长粗布带。",
    glyph: "鞋",
  },
  {
    id: "hoodedLantern",
    label: "罩灯",
    note: "带遮光罩的小油灯，只余少量灯油，能贴近地面照亮几步。",
    glyph: "灯",
  },
  {
    id: "shitouSlate",
    label: "练字板",
    note: "赵石头写过名字的小黑板；背面的“东井”是成年人留下的转移方向。",
    glyph: "石",
  },
];

export const StudentRoster = [
  { id: "zhaoXingzhi", name: "赵杏枝", age: 16, status: "转移中", note: "随沈兰贞老师携带名册" },
  { id: "zhaoShitou", name: "赵石头", age: 10, status: "待寻", note: "最后与东井方向的转移村民同行" },
  { id: "gaoYuee", name: "高月娥", age: 13, status: "随家转移", note: "西坡组" },
  { id: "sunXiaosuo", name: "孙小锁", age: 11, status: "随家转移", note: "北沟组" },
  { id: "liBaoan", name: "李保安", age: 14, status: "随家转移", note: "东梁组" },
  { id: "wangLaishun", name: "王来顺", age: 10, status: "随家转移", note: "东井组" },
  { id: "guoXinger", name: "郭杏儿", age: 12, status: "随家转移", note: "西坡组" },
  { id: "tianMancang", name: "田满仓", age: 15, status: "随家转移", note: "南沟组" },
  { id: "fengGaihua", name: "冯改花", age: 13, status: "随家转移", note: "北坡组" },
  { id: "yangXiaoni", name: "杨小妮", age: 8, status: "随家转移", note: "东井组" },
  { id: "zhangShuanzhu", name: "张栓柱", age: 12, status: "随家转移", note: "北沟组" },
  { id: "chenYulan", name: "陈玉兰", age: 14, status: "随家转移", note: "东梁组" },
  { id: "liuErxi", name: "刘二喜", age: 9, status: "随家转移", note: "西坡组" },
  { id: "maChunsheng", name: "马春生", age: 15, status: "随家转移", note: "南沟组" },
  { id: "heXiuzhen", name: "贺秀珍", age: 11, status: "随家转移", note: "北坡组" },
  { id: "weiXiaoman", name: "魏小满", age: 10, status: "随家转移", note: "东井组" },
  { id: "dongGuixiang", name: "董桂香", age: 16, status: "随家转移", note: "南沟组" },
  { id: "shenSuocheng", name: "申锁成", age: 13, status: "随家转移", note: "北沟组" },
  { id: "qiaoGenlai", name: "乔根来", age: 14, status: "随家转移", note: "东梁组" },
];

export const MemoryObjects = [
  {
    id: "person",
    glyph: "人",
    label: "人",
    title: "人先于纸",
    copy: "名单、信和油印工具都为活着的人服务。物件可以藏起、重抄或重制，人必须先过河。",
  },
  {
    id: "name",
    glyph: "名",
    label: "名",
    title: "名字不是数字",
    copy: "十九行字各自通向一个孩子。去向不明时，诚实写下“待寻”，比替命运落笔更重要。",
  },
  {
    id: "road",
    glyph: "路",
    label: "路",
    title: "路会断，也会再接上",
    copy: "敌后交通并不可靠，却由许多普通人用记忆、口信与互助一段段续起来。",
  },
  {
    id: "home",
    glyph: "家",
    label: "家",
    title: "家也可以暂时写在纸上",
    copy: "房屋可能空下，亲人可能失散；一封信记住称呼、方向和约定，让寻找仍有起点。",
  },
];

export const StoryScenes = [
  {
    id: "schoolAfterBell",
    chapter: 1,
    chapterLabel: "第一章 · 钟停以后",
    title: "最后一次点名",
    timeLabel: "1942年5月24日 · 日暮",
    place: "槐树沟临时小学",
    mood: "dusk",
    copy: [
      "傍晚的钟没有敲。来报信的村民只说，公路方向的搜索正在收紧，各家按预先约定分成小组离村，不要聚成一队。半间教室很快空了，只剩窗纸被风一下一下顶起。",
      "讲台上放着一册薄名册、一束孩子们写给失散亲人的信，还有一套分装的油印工具：钢板、铁笔、几张蜡纸、简易油印框、一小罐油墨与滚筒。它们不是什么军用文件，只用来印识字页、点名表和寻人便笺。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "杏枝，北沟的临时教学点天亮前收人。我们只走群众转移路，不跟任何队伍同行。" },
      { speaker: "赵杏枝", text: "石头还没回来。名册上写着“待寻”，像是你早知道会少一个。" },
      { speaker: "沈兰贞", text: "我只知道不能替他写结局。待寻，就是还要找。" },
    ],
    historyId: "CreativeBoundary",
    choices: [
      {
        id: "countNamesFirst",
        label: "先点一遍十九个名字",
        hint: "把每一行和熟悉的脸重新对上。",
        next: "packing",
        effects: {
          bond: 1,
          wordsAdd: ["name"],
          flagsSet: ["countedRoster"],
        },
      },
      {
        id: "closeSchoolFirst",
        label: "先替教室收好最后一张凳子",
        hint: "让空屋看起来只是普通的空屋。",
        next: "packing",
        effects: {
          time: 1,
          compassion: 1,
          wordsAdd: ["home"],
          flagsSet: ["schoolSecured"],
        },
      },
    ],
  },
  {
    id: "packing",
    chapter: 1,
    chapterLabel: "第一章 · 钟停以后",
    title: "书包只剩一角",
    timeLabel: "1942年5月24日 · 日暮后",
    place: "临时小学后屋",
    mood: "dusk",
    copy: [
      "名册贴身放，信束用油纸裹两层，钢板、铁笔、蜡纸、可拆油印框、油墨和滚筒分装，由两个人轮换背。三样东西已经占满大半行李。沈兰贞把剩下的一角让给杏枝：只能再选一件。",
      "窗外有人轻敲两下墙，这是各家开始分散的约定。杏枝第一次意识到，选择带什么，也等于选择暂时留下什么。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "都带不行吗？" },
      { speaker: "沈兰贞", text: "背不动的时候，什么都到不了。选一样，记住另两样藏在哪儿，回来还可以找。" },
    ],
    historyId: "CivilianEvacuation",
    choices: [
      {
        id: "packMedicine",
        label: "带上药布包",
        hint: "一小包外伤药与干净布条，能照料伤脚或沿途的病人。",
        next: "pendingName",
        effects: {
          compassion: 1,
          itemsAdd: ["medicine"],
        },
      },
      {
        id: "packClothShoes",
        label: "带上旧布鞋",
        hint: "鞋底厚实，鞋带也能拆作结实的长布条。",
        next: "pendingName",
        effects: {
          health: 1,
          itemsAdd: ["clothShoes"],
        },
      },
      {
        id: "packLantern",
        label: "带上罩灯",
        hint: "只剩一点灯油；遮严以后，可以贴地照亮几步。",
        next: "pendingName",
        effects: {
          itemsAdd: ["hoodedLantern"],
        },
      },
    ],
  },
  {
    id: "pendingName",
    chapter: 1,
    chapterLabel: "第一章 · 钟停以后",
    title: "“待寻”两个字",
    timeLabel: "1942年5月24日 · 初更",
    place: "学校门槛",
    mood: "intimate",
    copy: [
      "赵石头十岁，是杏枝的弟弟。下午分组时，他牵着耳背的杨奶奶去找东井组；第二次清点，组里没有他。没人看见争执，也没人听见呼救，只有道路突然被来往的人切成许多段。",
      "杏枝的指甲压在“待寻”上。她想过把两个字涂掉，仿佛不看就能少怕一点；也想过写成“已到”，骗自己走得快些。沈兰贞把笔放在她手边，没有替她决定。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "你写“待寻”，是不是也可能一直寻不到？" },
      { speaker: "沈兰贞", text: "可能。可不知道就是不知道。我们不能用一个好听的字，把一个人盖住。" },
    ],
    historyId: "NamesAndRecords",
    choices: [
      {
        id: "keepPendingTruth",
        label: "让“待寻”留在原处",
        hint: "承认未知，也保留继续寻找的责任。",
        next: "villageLane",
        effects: {
          bond: 1,
          compassion: 1,
          wordsAdd: ["person", "name"],
          flagsSet: ["keptPendingTruth"],
        },
      },
      {
        id: "writeLastSeen",
        label: "在旁边补写“东井方向”",
        hint: "留下最后可靠的去向，不把猜测写成事实。",
        next: "villageLane",
        effects: {
          time: 1,
          paper: -1,
          wordsAdd: ["road", "name"],
          flagsSet: ["recordedLastSeen"],
        },
      },
      {
        id: "foldNameInward",
        label: "把这一页向内折好",
        hint: "名字仍在，只是不让路上偶然看见的人读到。",
        next: "villageLane",
        effects: {
          sound: -1,
          bond: 1,
          wordsAdd: ["name"],
          flagsSet: ["concealedRoster"],
        },
      },
    ],
  },
  {
    id: "villageLane",
    chapter: 1,
    chapterLabel: "第一章 · 钟停以后",
    title: "一扇没有合严的门",
    timeLabel: "1942年5月24日 · 初更",
    place: "槐树沟西巷",
    mood: "tense",
    copy: [
      "村里没有奔跑的人。鸡笼盖着布，灶灰已经拨冷，留在门槛上的鞋印朝不同方向散开。分散不是离弃：每一小组都有去处，也有人在后面复查行动不便的住户。",
      "顾婶家的门却没有合严。她腿脚慢，按约定应由邻家带往北坡。杏枝听见屋里木杖碰地，不确定接应的人是否已经到过。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "喊一声，她就知道有人没忘她。可这巷子太静。" },
      { speaker: "沈兰贞", text: "不要大喊。你决定怎么留话，我在巷口听着。" },
    ],
    historyId: "LocalGuide",
    choices: [
      {
        id: "warnAuntGu",
        label: "贴门低声确认接应",
        hint: "多停几分钟，也会在静巷里多留一点动静。",
        next: "dryWellFork",
        effects: {
          time: 1,
          sound: 1,
          compassion: 2,
          wordsAdd: ["person", "home"],
          flagsSet: ["warnedAuntGu"],
        },
      },
      {
        id: "leaveMutualAidMark",
        label: "在门脚画下北坡互助记号",
        hint: "复查的人会看懂，屋里的人不必冒险出声。",
        next: "dryWellFork",
        effects: {
          time: 1,
          compassion: 1,
          wordsAdd: ["road", "home"],
          flagsSet: ["leftMutualAidMark"],
        },
      },
      {
        id: "reportHouseLater",
        label: "记住西巷第三院的门脚记号",
        hint: "到北沟立即报给接应人；现在更快，但顾婶要多等一段时间。",
        next: "dryWellFork",
        effects: {
          compassion: 1,
          wordsAdd: ["home"],
          flagsSet: ["carriedHouseReport"],
        },
      },
    ],
  },
  {
    id: "dryWellFork",
    chapter: 2,
    chapterLabel: "第二章 · 路是人记住的",
    title: "枯井旁的三条路",
    timeLabel: "1942年5月24日 · 初更",
    place: "村北梯田",
    mood: "night",
    copy: [
      "离村后，纸上的简图很快失去用处。梯田边沿被新土盖住，老杏树只剩半截，三条羊肠路都像通向同一片黑。真正的路藏在旧井、风口和石壁回声之间。",
      "沈兰贞没有考杏枝。她只是问：白天带孩子们认路时，谁说过哪条路下雨不积泥？杏枝想起石头总嫌那一段绕远。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "简图会错，认路的办法不能只在一个人脑子里。" },
      { speaker: "赵杏枝", text: "井口朝南，背风那边有碎白石。榆树梁绕远，可脚下硬。" },
    ],
    historyId: "MountainRoute",
    choices: [
      {
        id: "takeElmRidge",
        label: "走榆树梁的硬路",
        hint: "更陡，方向清楚，也不容易在泥地留下成串脚印。",
        next: "slateOnSlope",
        effects: {
          health: -1,
          sound: -1,
          wordsAdd: ["road"],
          flagsSet: ["tookElmRidge"],
        },
      },
      {
        id: "takeLowerTerrace",
        label: "沿下层田埂慢慢绕",
        hint: "省脚力，但要多花时间辨认每一道岔口。",
        next: "slateOnSlope",
        effects: {
          time: 2,
          health: 1,
          wordsAdd: ["road"],
          flagsSet: ["tookLowerTerrace"],
        },
      },
      {
        id: "rebuildRouteTogether",
        label: "和沈老师逐个复述地标",
        hint: "两个人都记住路线，以后谁都不必独自带路。",
        next: "slateOnSlope",
        effects: {
          time: 1,
          bond: 2,
          wordsAdd: ["road"],
          flagsSet: ["sharedRouteMemory"],
        },
      },
    ],
  },
  {
    id: "slateOnSlope",
    chapter: 2,
    chapterLabel: "第二章 · 路是人记住的",
    title: "石坡上的小黑板",
    timeLabel: "1942年5月24日 · 初更将尽",
    place: "榆树梁北坡",
    mood: "memory",
    copy: [
      "一块巴掌大的练字板卡在刺丛里。正面反复写着歪斜的“赵石头”，背面有成年人用白土写下“东井”两字，旁边按着半个手印。它证明那一组走过这里，却不能证明后来去了哪儿。",
      "杏枝把板子拿起又放下。她既想循着每个痕迹追下去，也知道夜里脱离约定路线，会让沈兰贞和名册一起失去去向。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "这是他的。他总把“石”的一撇写得太长。" },
      { speaker: "沈兰贞", text: "收好它。板子只能说明他来过，后头的路，见着人再问。" },
    ],
    historyId: "NamesAndRecords",
    choices: [
      {
        id: "takeShitouSlate",
        label: "收起练字板，记下发现地点",
        hint: "多一件可核对身份的东西，也多花一点时间。",
        next: "kilnShelter",
        effects: {
          time: 1,
          bond: 1,
          wordsAdd: ["person", "name"],
          itemsAdd: ["shitouSlate"],
          flagsSet: ["foundShitouTrail"],
        },
      },
      {
        id: "copySlateClue",
        label: "只把“东井”抄到名册页角",
        hint: "不增加负重，但会用掉一点纸面。",
        next: "kilnShelter",
        effects: {
          paper: -1,
          wordsAdd: ["name", "road"],
          flagsSet: ["foundShitouTrail", "copiedSlateClue"],
        },
      },
      {
        id: "markSlateLocation",
        label: "把板子藏高，垒三块石作记号",
        hint: "留给按原路复查的人，自己继续按约定前进。",
        next: "kilnShelter",
        effects: {
          time: 1,
          compassion: 1,
          wordsAdd: ["person", "road"],
          flagsSet: ["markedShitouClue"],
        },
      },
    ],
  },
  {
    id: "kilnShelter",
    chapter: 2,
    chapterLabel: "第二章 · 路是人记住的",
    title: "窑洞里的一碗凉水",
    timeLabel: "1942年5月24日 · 二更",
    place: "废石灰窑",
    mood: "shelter",
    copy: [
      "废窑里藏着杨小妮和祖母，同行的人去前方确认岔路，还没有折返。孩子额头有些热，脚背又被碎石划开一道口子。老人仍把半碗凉水推给杏枝，仿佛她们才是需要招待的客人。",
      "几组人分开行动，是为了避免一次搜索牵连所有人。杏枝和沈兰贞不能把祖孙带进自己的路线，却能留下物品、写清去向，或把消息带到下一个接应点。",
    ],
    dialogue: [
      { speaker: "杨奶奶", text: "石头先前扶我过了乱石。他看见东井组的人，就跑去问路。我一转身，人群散了。" },
      { speaker: "赵杏枝", text: "他不是去逞能，他只是怕你听不清。" },
      { speaker: "沈兰贞", text: "这句话也记住。以后问到他，先说清他为什么离开。" },
    ],
    historyId: "LocalGuide",
    choices: [
      {
        id: "useMedicineForXiaoni",
        label: "留下药布包和用法",
        hint: "先清理包扎脚伤，并请下一处接应人继续留意孩子发热。",
        next: "fourWrittenWords",
        effects: {
          compassion: 3,
          bond: 1,
          itemsRemove: ["medicine"],
          wordsAdd: ["person"],
          flagsSet: ["aidedXiaoni"],
        },
        requires: {
          items: ["medicine"],
        },
      },
      {
        id: "leaveKilnNote",
        label: "写一张不带姓名的接应便条",
        hint: "说明窑里有两位村民与下一处去向，避免暴露完整名册。",
        next: "fourWrittenWords",
        effects: {
          time: 1,
          paper: -1,
          compassion: 2,
          wordsAdd: ["road", "home"],
          flagsSet: ["leftKilnNote"],
        },
      },
      {
        id: "carryKilnReport",
        label: "背熟祖孙特征与窑洞位置",
        hint: "不用纸，抵达北沟后把接应责任当面交清。",
        next: "fourWrittenWords",
        effects: {
          time: 1,
          compassion: 2,
          bond: 1,
          wordsAdd: ["person", "home"],
          flagsSet: ["memorizedKilnReport"],
        },
      },
      {
        id: "leaveLanternWithKiln",
        label: "把罩灯留给祖孙",
        hint: "她们等到接应时有一小点光；你们过河只能靠别的办法。",
        next: "fourWrittenWords",
        effects: {
          compassion: 3,
          itemsRemove: ["hoodedLantern"],
          wordsAdd: ["home"],
          flagsSet: ["leftLanternAtKiln"],
        },
        requires: {
          items: ["hoodedLantern"],
        },
      },
    ],
  },
  {
    id: "fourWrittenWords",
    chapter: 2,
    chapterLabel: "第二章 · 路是人记住的",
    title: "纸角上的四个字",
    timeLabel: "1942年5月24日 · 二更",
    place: "窑洞外的背风坡",
    mood: "intimate",
    copy: [
      "重新上路前，包住钢板的旧识字样张被颠散。沈兰贞蹲下，把四张沾墨的纸角依次铺好：人、名、路；最后一个“家”，来自孩子信封上反复描过的字。它们都是今晚一路遇见的东西。",
      "杏枝问，为什么偏要背这一套沉工具。沈兰贞说，钢板、铁笔和滚筒丢了还能设法再找；但道路断掉的时候，只要还能刻出几个人人都认得的字，一句口信就能留得比脚印久。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "挑一个放在最上面。天亮后先印哪个，由你。" },
      { speaker: "赵杏枝", text: "只挑一个？" },
      { speaker: "沈兰贞", text: "不是丢掉另外三个。是看你今晚最怕忘了什么。" },
    ],
    historyId: "Mimeograph",
    choices: [
      {
        id: "choosePersonWord",
        label: "把“人”字放在最上面",
        hint: "先记得一切物件为了谁。",
        next: "ditchWaiting",
        effects: {
          bond: 1,
          compassion: 1,
          wordsAdd: ["person"],
        },
      },
      {
        id: "chooseNameWord",
        label: "把“名”字放在最上面",
        hint: "每一行都必须能回到一个人。",
        next: "ditchWaiting",
        effects: {
          bond: 1,
          wordsAdd: ["name"],
        },
      },
      {
        id: "chooseRoadWord",
        label: "把“路”字放在最上面",
        hint: "路断了，还要有人记得怎样接。",
        next: "ditchWaiting",
        effects: {
          time: -1,
          wordsAdd: ["road"],
        },
      },
      {
        id: "chooseHomeWord",
        label: "把“家”字放在最上面",
        hint: "有时家只剩称呼、方向和一句约定。",
        next: "ditchWaiting",
        effects: {
          compassion: 1,
          wordsAdd: ["home"],
        },
      },
    ],
  },
  {
    id: "ditchWaiting",
    chapter: 3,
    chapterLabel: "第三章 · 没有地址的信",
    title: "沟渠上方的灯影",
    timeLabel: "1942年5月24日 · 二更将尽",
    place: "旧驮道下方",
    mood: "tense",
    copy: [
      "公路方向传来断续的发动机声，随后有灯光在高处土路上扫过。看不清是谁，也没有必要靠近确认。两个人伏在废灌渠下，等光从石缝上移开。",
      "油印包里的钢板轻轻碰了一下滚筒木柄。杏枝用掌心压住包角，才发现沈兰贞的手也在发抖。老师并不比学生更不害怕，只是把呼吸放得更慢。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "你也怕？" },
      { speaker: "沈兰贞", text: "怕。先别动。车声远了，我捏一下你的手，咱们再起身。" },
    ],
    historyId: "TaihangSweep",
    choices: [
      {
        id: "waitForRoadSilence",
        label: "一起数呼吸，等灯影远去",
        hint: "花时间换取安静，也让彼此的步子重新一致。",
        next: "unsentLetter",
        effects: {
          time: 2,
          sound: -2,
          bond: 2,
          flagsSet: ["waitedForSilence"],
        },
      },
      {
        id: "moveThroughColdDitch",
        label: "沿冰凉的废渠低身绕过",
        hint: "更快离开高路，但湿鞋会耗掉体力。",
        next: "unsentLetter",
        effects: {
          time: 1,
          sound: -1,
          health: -1,
          flagsSet: ["usedColdDitch"],
        },
      },
      {
        id: "trustTeacherTiming",
        label: "把起身时机交给沈老师",
        hint: "让她听道路，自己护住三个包裹。",
        next: "unsentLetter",
        effects: {
          time: 1,
          bond: 2,
          sound: -1,
          flagsSet: ["trustedTeacherTiming"],
        },
      },
    ],
  },
  {
    id: "unsentLetter",
    chapter: 3,
    chapterLabel: "第三章 · 没有地址的信",
    title: "沈老师的那一封",
    timeLabel: "1942年5月24日 · 三更前",
    place: "废羊圈背墙",
    mood: "memory",
    copy: [
      "等道路彻底安静，两人在废羊圈背风处歇脚。信束最下面还有一封字迹密密的信，收信人只写“小禾”，地址一栏空着。沈兰贞的妹妹在两年前随亲戚离开，后来交通屡次中断，最后一次口信只说她平安到了东边。",
      "沈兰贞每隔一阵仍会续写一页：村里谁学会了自己的名字，杏树哪天开花，她在旧课本里给妹妹留了哪一道题。信没有寄出，不等于收信人已经不在；没有回音，也不等于写信的人该停止生活。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "你一直教我别把不知道写成坏消息。你自己做得到吗？" },
      { speaker: "沈兰贞", text: "有些晚上做不到。第二天再把那一页重写。" },
      { speaker: "赵杏枝", text: "那石头那一行，我也等到第二天再看。" },
    ],
    historyId: "MountainRoute",
    choices: [
      {
        id: "promiseSharedSearch",
        label: "约定天亮后一起补地址",
        hint: "寻找石头与寻找小禾，都不必由一个人独自承担。",
        next: "brokenMarkers",
        effects: {
          bond: 3,
          compassion: 1,
          wordsAdd: ["person", "home"],
          flagsSet: ["sharedSearchPromise"],
        },
      },
      {
        id: "admitRosterFear",
        label: "承认自己想过涂掉“待寻”",
        hint: "把最难说出口的念头交给可信的人。",
        next: "brokenMarkers",
        effects: {
          bond: 3,
          wordsAdd: ["name"],
          flagsSet: ["admittedRosterFear"],
        },
      },
      {
        id: "askToReadLetter",
        label: "请她念一段写给小禾的话",
        hint: "不是告别，只是让这封信第一次有一个听众。",
        next: "letterReadAloud",
        effects: {
          time: 1,
          bond: 2,
          compassion: 2,
          wordsAdd: ["home"],
          flagsSet: ["heardUnsentLetter"],
        },
      },
    ],
  },
  {
    id: "letterReadAloud",
    chapter: 3,
    chapterLabel: "第三章 · 没有地址的信",
    title: "第一次有了听众",
    timeLabel: "1942年5月24日 · 三更前",
    place: "废羊圈背墙",
    mood: "intimate",
    copy: [
      "沈兰贞只念了中间一小段：“小禾，槐树沟的杏花今年又落了。孩子们先学会写自己的名字，再学会写去处。你若收到这封信，不要赶夜路回来，托可靠的人捎一句‘已到’，我就接着教书。”",
      "纸上没有一句“想你”。杏枝却听见沈兰贞在“不要赶夜路”那里停了一下，等嗓子里的气稳住才继续。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "你怎么不写想她？" },
      { speaker: "沈兰贞", text: "怕她看了就往回赶。等路稳了，我当面说。" },
    ],
    historyId: "NamesAndRecords",
    choices: [
      {
        id: "foldLetterTogether",
        label: "把地址栏留空，收好这封信",
        hint: "没有可靠去向时，不替收信人写结局。",
        next: "brokenMarkers",
        effects: {
          bond: 1,
          compassion: 1,
          wordsAdd: ["home"],
          flagsSet: ["letterReadAloud"],
        },
      },
    ],
  },
  {
    id: "brokenMarkers",
    chapter: 3,
    chapterLabel: "第三章 · 没有地址的信",
    title: "被风翻过的路标",
    timeLabel: "1942年5月25日 · 三更",
    place: "石门沟西口",
    mood: "night",
    copy: [
      "午夜后，山风把岔口原有的草结吹散了。她们仍能凭石壁缺口找到河滩，但身后还有窑洞里的祖孙和分散的村民。留下太显眼的路标可能被陌生人看见；什么也不留，后面的人又要在黑暗里重走一次犹豫。",
      "沈兰贞说，路标只需要让知道约定的人看懂。杏枝摸到信束外面几张空白识字纸，也看见地上到处是拳头大的白石。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "纸一撕，就少一张能写名字的。" },
      { speaker: "沈兰贞", text: "所以不要替我选。想清楚这张纸现在能帮到谁。" },
    ],
    historyId: "MountainRoute",
    choices: [
      {
        id: "leaveNarrowPaperMarker",
        label: "裁一条窄纸，夹进约定的石缝",
        hint: "只有熟悉记号的人会留意；少一张可用纸。",
        next: "westBank",
        effects: {
          time: 1,
          paper: -1,
          compassion: 2,
          wordsAdd: ["road"],
          flagsSet: ["leftPaperMarker"],
        },
        requires: {
          min: {
            paper: 1,
          },
        },
      },
      {
        id: "buildWhiteStoneMarker",
        label: "按约定垒出三块白石",
        hint: "不用纸，也不留文字；搬石会多耽搁一会儿。",
        next: "westBank",
        effects: {
          time: 2,
          health: -1,
          compassion: 1,
          wordsAdd: ["road"],
          flagsSet: ["leftStoneMarker"],
        },
      },
      {
        id: "memorizeHandoffOnly",
        label: "不留路标，把岔口特征背给接应人",
        hint: "痕迹最少，但帮助要等口信传回西岸。",
        next: "westBank",
        effects: {
          sound: -1,
          bond: 1,
          flagsSet: ["memorizedRiverHandoff"],
        },
      },
    ],
  },
  {
    id: "westBank",
    chapter: 4,
    chapterLabel: "第四章 · 纸做的桥",
    title: "看不见的踏脚石",
    timeLabel: "1942年5月25日 · 四更",
    place: "石门河滩西岸",
    mood: "river",
    copy: [
      "石门河不宽，这里也是村民熟悉的浅滩，可云遮住月亮以后，二十几步水面像一整片没有边的黑。平日过河的踏脚石只露出偶尔一线白沫。两户分散转移的村民等在柳丛里，其中有老人和年幼的孩子。",
      "原定来领路的人没有出现。所有人都知道大致方向，却没人愿意用别人的脚去试错。杏枝手里的纸、罩灯、练字板和关于地标的记忆，此刻各有一种用法，也各有代价。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "我们不是带他们冒险。能把路说明白就走，说明白不了就等。" },
      { speaker: "赵杏枝", text: "我记得第三块石头旁有柳根。请熟悉水性的成年人用木杆核对，再把短柳枝插进石缝，我在枝头系纸。纸不能搭桥，可它能让人看见哪一步核过了。" },
    ],
    historyId: "MountainRoute",
    choices: [
      {
        id: "makePaperBridge",
        label: "请成年人持杆探路，再插柳枝系纸标",
        hint: "成年人确认一块便插一根短柳枝，杏枝留在岸边系空白纸；不动家信，用后收走。",
        next: "midstream",
        effects: {
          time: 1,
          sound: 1,
          paper: -2,
          compassion: 3,
          bond: 1,
          wordsAdd: ["road", "home"],
          flagsSet: ["paperBridge", "guidedCrossing"],
        },
        requires: {
          min: {
            paper: 2,
          },
        },
      },
      {
        id: "useShieldedLantern",
        label: "把罩灯贴近水面，一次只照一步",
        hint: "光被人墙遮住，但有限的灯油会用完，也会增加被远处察觉的风险。",
        next: "midstream",
        effects: {
          time: 1,
          sound: 2,
          compassion: 2,
          itemsRemove: ["hoodedLantern"],
          wordsAdd: ["road"],
          flagsSet: ["lanternFord", "guidedCrossing"],
        },
        requires: {
          items: ["hoodedLantern"],
        },
      },
      {
        id: "leadWithSlate",
        label: "请熟悉浅滩的成年人探路，在练字板上画次序",
        hint: "杏枝留在岸边记录已确认的踏脚石，练字板随后留作过河次序牌。",
        next: "midstream",
        effects: {
          time: 1,
          compassion: 2,
          bond: 1,
          itemsRemove: ["shitouSlate"],
          wordsAdd: ["person", "road"],
          flagsSet: ["slateFord", "guidedCrossing"],
        },
        requires: {
          items: ["shitouSlate"],
          flags: ["foundShitouTrail"],
        },
      },
      {
        id: "waitForCloudBreak",
        label: "陪大家等到云隙透出一点月光",
        hint: "最少依赖物件，也最耗时间；所有人留在柳丛中分散休息。",
        next: "midstream",
        effects: {
          time: 3,
          sound: -1,
          health: 1,
          compassion: 2,
          bond: 1,
          flagsSet: ["waitedForCloudBreak", "guidedCrossing"],
        },
      },
    ],
  },
  {
    id: "midstream",
    chapter: 4,
    chapterLabel: "第四章 · 纸做的桥",
    title: "人、名册、信、油印包",
    timeLabel: "1942年5月25日 · 四更",
    place: "石门河滩中央",
    mood: "climax",
    copy: [
      "最后一趟过河时，沈兰贞的旧鞋在石缝里一绊，脚踝猛地歪向水中。杏枝扶住她，背后的油印包却滑到肘弯；钢板、名册和信束同时挤在两双手之间。水不致命，但足以把纸泡散，也足以让扭伤的人站不起来。",
      "沈兰贞没有喊“护住工具”。她只按课堂点名的次序说了四样：人，名册，信，油印包。排在最后的东西可以重配，蜡纸也能重刻；必要时先藏在有记号的石边，天亮以后再想办法。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "我不想再丢一样东西。" },
      { speaker: "沈兰贞", text: "那就别先丢人。别把舍不得，误当成全都抱得住。" },
    ],
    historyId: "LocalGuide",
    choices: [
      {
        id: "makeClothHarness",
        label: "用包袱带扎紧油印包，腾出双手扶人",
        hint: "旧布鞋给沈老师换上，长粗布带把工具固定在背后。",
        next: "farBank",
        effects: {
          time: 1,
          bond: 2,
          health: 1,
          itemsRemove: ["clothShoes"],
          flagsSet: ["teacherAcross", "keptMimeographKit", "clothHarness"],
        },
        requires: {
          items: ["clothShoes", "mimeographKit", "studentRoster", "letterBundle"],
        },
      },
      {
        id: "askCrossersForHands",
        label: "把名册和信交给岸边村民，开口求助",
        hint: "信任刚刚一同过河的人；两个人扶老师，一人接油印包。",
        next: "farBank",
        effects: {
          time: 1,
          sound: 1,
          bond: 2,
          compassion: 2,
          flagsSet: ["teacherAcross", "keptMimeographKit", "acceptedHelp"],
        },
        requires: {
          min: {
            bond: 4,
          },
          items: ["mimeographKit", "studentRoster", "letterBundle"],
          flags: ["guidedCrossing"],
        },
      },
      {
        id: "cacheMimeographByBoulder",
        label: "把油印包压在有缺口的巨石内侧",
        hint: "不是任它冲走：油纸包牢、石块压住并记下浅水位置，先腾出双手扶人。",
        next: "farBank",
        effects: {
          bond: 2,
          compassion: 1,
          health: 1,
          itemsRemove: ["mimeographKit"],
          wordsAdd: ["person"],
          flagsSet: ["teacherAcross", "lostMimeographKit", "markedRiverCache"],
        },
        requires: {
          items: ["mimeographKit"],
        },
      },
      {
        id: "putPersonBeforeTools",
        label: "放下油印包，用双手扶稳沈老师",
        hint: "油纸包落在浅水石窝里；人、名册和信先到对岸。",
        next: "farBank",
        effects: {
          bond: 3,
          compassion: 2,
          health: 1,
          itemsRemove: ["mimeographKit"],
          wordsAdd: ["person"],
          flagsSet: ["teacherAcross", "lostMimeographKit", "markedRiverCache", "personBeforeTools"],
        },
      },
    ],
  },
  {
    id: "farBank",
    chapter: 4,
    chapterLabel: "第四章 · 纸做的桥",
    title: "湿透的纸边",
    timeLabel: "1942年5月25日 · 四更将尽",
    place: "石门河滩东岸",
    mood: "afterstorm",
    copy: [
      "沈兰贞的脚踝能落地，只是每走一步都疼。名册和信束的边角进了水，墨迹还没有散。刚过河的人围成背风的半圈，没有问她们属于哪支队伍，只把干衣角和一块平石让出来。",
      "杏枝一页页分开湿纸。她看见孩子们写得最多的并非大话，而是“娘的咳嗽好些没有”“门后的谷种别受潮”“我还记得回家的岔口”。那些句子很小，却比钢板和滚筒更沉。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "先看墨线，别揉纸。慢一点，信不会因为晚一刻就失去家。" },
      { speaker: "赵杏枝", text: "以前我嫌他们每封都写这些。现在我怕的就是这些没人记得。" },
    ],
    historyId: "Mimeograph",
    choices: [
      {
        id: "treatAnkleAndWrapLetters",
        label: "用药布固定脚踝，再用外层干布包信",
        hint: "药与布都在这一夜用完，人和纸都得到照料。",
        next: "shitouNews",
        effects: {
          time: 1,
          health: 2,
          bond: 1,
          itemsRemove: ["medicine"],
          flagsSet: ["treatedTeacher", "lettersProtected"],
        },
        requires: {
          items: ["medicine"],
        },
      },
      {
        id: "separatePagesByBodyHeat",
        label: "把湿页夹在两层干布之间贴身温着",
        hint: "避免墨迹相蹭，不消耗纸张，但寒意会跟着走一段路。",
        next: "shitouNews",
        effects: {
          time: 1,
          health: -1,
          bond: 1,
          flagsSet: ["lettersProtected"],
        },
      },
      {
        id: "restAndAirPages",
        label: "在背风处多等一会儿，逐页晾开",
        hint: "用时间换取稳妥，也让沈老师的脚缓过来。",
        next: "shitouNews",
        effects: {
          time: 2,
          health: 1,
          paper: 1,
          flagsSet: ["lettersProtected", "paperRecovered"],
        },
      },
    ],
  },
  {
    id: "shitouNews",
    chapter: 5,
    chapterLabel: "第五章 · 天亮还要点名",
    title: "不是结局的消息",
    timeLabel: "1942年5月25日 · 五更",
    place: "河东柳林",
    mood: "quiet",
    copy: [
      "准备离开河滩时，一名东井组的妇女听见“赵石头”，记起有个十岁男孩在岔路口反复说姐姐叫杏枝。他跟着熟识的王家人去了东梁洞，临走前还问，老师会不会在新地方点名。",
      "这是一条可信的口信，却仍要到接应点核对。杏枝没有立刻笑。她先问男孩左眉是否有一道浅疤，又问他右膝补的是不是一块深蓝粗布、当时喊的是“杏子”还是“姐”。女人都答得上来。",
    ],
    dialogue: [
      { speaker: "东井组妇女", text: "他没一个人乱跑，是跟着认识的大人走的。我们分组以后，路上才又错开。" },
      { speaker: "赵杏枝", text: "我想现在就去东梁洞。" },
      { speaker: "沈兰贞", text: "可以去，也可以先把消息交到北沟，让两边都有人找。别再让一个人变成一条断路。" },
    ],
    historyId: "CivilianEvacuation",
    choices: [
      {
        id: "verifyWithSlateDetails",
        label: "用发现地点、补丁与称呼核对口信",
        hint: "地点与妇女记住的特征彼此吻合，可以把去向写得更确定。",
        next: "dawnRoster",
        effects: {
          bond: 2,
          compassion: 1,
          wordsAdd: ["person", "name", "road"],
          flagsSet: ["shitouReportedSafe", "verifiedShitouNews"],
        },
        requires: {
          flags: ["foundShitouTrail"],
        },
      },
      {
        id: "detourToEastRidgeHandoff",
        label: "绕到东梁岔口，把寻找责任当面交清",
        hint: "不追着孩子的脚印乱走；多花时间确认哪位成人继续接应。",
        next: "dawnRoster",
        effects: {
          time: 2,
          health: -1,
          compassion: 2,
          bond: 1,
          wordsAdd: ["person", "road"],
          flagsSet: ["shitouReportedSafe", "eastRidgeHandoff"],
        },
      },
      {
        id: "keepPendingAndHandoff",
        label: "仍写“待寻”，把新口信交给北沟复核",
        hint: "好消息也先注明来源；寻找会由两处接应人同时继续。",
        next: "dawnRoster",
        effects: {
          compassion: 2,
          bond: 1,
          wordsAdd: ["person", "name"],
          flagsSet: ["searchHandoff", "keptPendingTruth"],
        },
      },
    ],
  },
  {
    id: "dawnRoster",
    chapter: 5,
    chapterLabel: "第五章 · 天亮还要点名",
    title: "第十九行",
    timeLabel: "1942年5月25日 · 破晓前",
    place: "北沟临时教学点",
    mood: "predawn",
    copy: [
      "北沟的教学点只是炭窑旁两间空屋。没有旗，也没有欢迎的人群。接应人核对完几句约定口信，便去安排河西的祖孙和顾婶；先到的村民烧水、铺草，把各组去向一条条拼起来。",
      "沈兰贞让杏枝先核对受潮的第十九行。有干纸便重抄，没有纸便当着两位接应人逐句复述。写“已到东梁洞”需要注明是谁看见、在哪里看见；继续写“待寻”也不是拒绝好消息，而是让下一位寻找的人知道，哪一步还没有核实。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "我现在明白了。名字后面不是句号，是下一段路。" },
      { speaker: "沈兰贞", text: "写吧。今天点不齐，明天还点。学校先从记得谁没到开始。" },
    ],
    historyId: "WartimeSchool",
    choices: [
      {
        id: "updateShitouDestination",
        label: "写“随东井组转往东梁洞，待当面核对”",
        hint: "保存好消息，也保留它仍需核实的边界。",
        next: "letterPostscript",
        effects: {
          time: 1,
          paper: -1,
          bond: 2,
          compassion: 1,
          wordsAdd: ["name", "road"],
          flagsSet: ["rosterComplete", "rosterProtected", "shitouDestinationAdded"],
        },
        requires: {
          min: {
            paper: 1,
          },
          flags: ["shitouReportedSafe"],
        },
      },
      {
        id: "preservePendingWithSource",
        label: "保留“待寻”，补上口信来源与最后去向",
        hint: "不替未知落笔，让搜索从可靠的地方继续。",
        next: "letterPostscript",
        effects: {
          time: 1,
          paper: -1,
          compassion: 2,
          bond: 1,
          wordsAdd: ["person", "name", "road"],
          flagsSet: ["rosterComplete", "rosterProtected", "pendingWithSource"],
        },
        requires: {
          min: {
            paper: 1,
          },
        },
      },
      {
        id: "splitRosterSafely",
        label: "重抄两份分开的去向表",
        hint: "一份只列名字，一份只列家庭记号；由不同接应人保管。",
        next: "letterPostscript",
        effects: {
          time: 2,
          paper: -2,
          compassion: 2,
          wordsAdd: ["name", "home"],
          flagsSet: ["rosterComplete", "rosterProtected", "splitRoster"],
        },
        requires: {
          min: {
            paper: 2,
          },
        },
      },
      {
        id: "oralRosterHandoff",
        label: "不添新纸，当着两位接应人逐行复述",
        hint: "原名册仍由沈老师贴身保管；两位成年人分别复述一遍姓名、来源与待核去向。",
        next: "letterPostscript",
        effects: {
          time: 2,
          bond: 1,
          compassion: 1,
          wordsAdd: ["person", "name"],
          flagsSet: ["rosterComplete", "rosterProtected", "oralRosterHandoff"],
        },
      },
    ],
  },
  {
    id: "letterPostscript",
    chapter: 5,
    chapterLabel: "第五章 · 天亮还要点名",
    title: "纸上有家",
    timeLabel: "1942年5月25日 · 东方发白",
    place: "北沟临时教学点",
    mood: "dawn",
    copy: [
      "东方发白时，远处道路仍不安静。真实的战争没有因为她们过了一条河就转向，槐树沟的屋门也不会立刻重新打开。可十九个名字有了去向或待寻的起点，河西有人会去接，沿途不得不留下的物件也都有记号可循。",
      "沈兰贞把写给小禾的信重新铺平。杏枝没有问这封信什么时候一定能寄到。她只把空着的地址栏留好，又翻到背面：若纸面还能落笔，那里容得下一行；天也正好亮到能看清笔尖。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "路通的时候，信会需要地址。路没通的时候，人先记住人。" },
      { speaker: "赵杏枝", text: "那就别写告别。写下一次从哪里找。" },
    ],
    historyId: "LiaoCounty",
    choices: [
      {
        id: "printFourMemoryWords",
        label: "刻下“人、名、路、家”，推一次油印滚筒",
        hint: "在蜡纸上刻字，再印到名单背面；四个字是这一夜学会的次序。",
        next: "__ending__",
        effects: {
          paper: -1,
          bond: 2,
          compassion: 1,
          flagsSet: ["completedLetter", "memoryComplete"],
        },
        requires: {
          min: {
            paper: 1,
          },
          items: ["mimeographKit", "studentRoster", "letterBundle"],
          flags: ["teacherAcross", "rosterComplete"],
          words: ["person", "name", "road", "home"],
        },
      },
      {
        id: "writeSearchPostscript",
        label: "添一句“我们从北沟继续找”",
        hint: "这不是保证找到的日期，而是一个不会独自承担的约定。",
        next: "__ending__",
        effects: {
          paper: -1,
          bond: 1,
          compassion: 2,
          wordsAdd: ["home"],
          flagsSet: ["completedLetter", "sharedSearchPromise"],
        },
        requires: {
          min: {
            paper: 1,
          },
          items: ["studentRoster", "letterBundle"],
          flags: ["teacherAcross", "rosterComplete"],
        },
      },
      {
        id: "leaveAddressOpen",
        label: "收好信，把地址栏留给下一段路",
        hint: "没有虚构团圆，也没有把未知写成永别。",
        next: "__ending__",
        effects: {
          bond: 1,
          compassion: 1,
          wordsAdd: ["home"],
          flagsSet: ["addressLeftOpen"],
        },
      },
    ],
  },
];

export const EndingDefinitions = [
  {
    id: "paperHasAHome",
    priority: 400,
    requires: {
      min: {
        bond: 5,
        compassion: 6,
      },
      max: {
        sound: 4,
        time: 12,
      },
      items: ["mimeographKit", "studentRoster", "letterBundle"],
      flags: ["paperBridge", "teacherAcross", "rosterComplete", "memoryComplete"],
      words: ["person", "name", "road", "home"],
    },
    title: "纸上有家",
    kicker: "结局一 · 四个字都在",
    copy: [
      "第一张新识字页没有印胜利，也没有印仇恨。铁笔只在蜡纸上刻了“人、名、路、家”，下面留出十九行，让后来抵达的人补写去向。河滩上的纸条用后被一一收回，没有把路线留给陌生的眼睛。",
      "杏枝和沈兰贞都没有得到一个圆满的保证。她们得到的是更具体的东西：石头最后随谁同行，小禾的信该从哪里续寄，河西还有谁等待接应，钢板铁笔明天还能刻出新的名单。",
      "多年以后，杏枝记得最清楚的不是水有多冷，而是有人在对岸伸手接过名册。原来所谓把家保在纸上，并不是抱紧一张纸，而是让纸重新回到人手里。",
    ],
    finalLine: "人先过河，名字才有地方抵达。",
  },
  {
    id: "nineteenNames",
    priority: 300,
    requires: {
      min: {
        compassion: 3,
      },
      items: ["studentRoster", "letterBundle"],
      flags: ["teacherAcross", "rosterComplete", "completedLetter"],
      words: ["name", "home"],
    },
    title: "十九个名字",
    kicker: "结局二 · 明天继续点名",
    copy: [
      "北沟的第一堂课没有齐人。有人在西坡，有人在东梁，有人尚待核对。沈兰贞仍从第一行念到第十九行；答“到”的人替不在场的同学说出最后去向，答不出的便在旁边留白。",
      "赵石头那一行没有被涂掉。好消息写着来源，未知写着下一处接应点。杏枝终于明白，一册诚实的名册并不能消除失散，却能阻止一个孩子在混乱中变成“少了一个”。",
      "写给小禾的信依然没有完整地址，但信束有了北沟这个新起点。只要交通重新接上一段，它们就再往前走一段。",
    ],
    finalLine: "今天点不齐，明天还点；名字在，寻找就没有停。",
  },
  {
    id: "stencilCanBeRecut",
    priority: 200,
    requires: {
      items: ["studentRoster", "letterBundle"],
      flags: ["teacherAcross", "lostMimeographKit", "rosterComplete"],
      words: ["person"],
    },
    title: "字会重刻",
    kicker: "结局三 · 留在浅水里的油印包",
    copy: [
      "油印包没有随她们到北沟。杏枝在简图背面画下缺口巨石、柳根和第三块踏脚石，等水更浅、道路更稳时，再由熟悉河滩的成年人去找。钢板可能生锈，蜡纸可能泡坏，但没有一个人为了捞工具留在夜水里。",
      "沈兰贞用木炭在旧木片上写出新的识字牌。笔画不齐，印不了许多份，却足够让十九个名字被重新抄下。她告诉杏枝，老师守的从来不是某一块钢板，而是让人有能力另取蜡纸，把毁掉的那一版重新刻出来。",
      "杏枝仍舍不得那套工具。舍不得并不等于选择错了；它只是提醒她，战争夺走的每件日常物品都值得日后认真找回。",
    ],
    finalLine: "工具可以找，蜡纸可以重刻；那一刻，两双手先扶住了人。",
  },
  {
    id: "beforeDaybreak",
    priority: 100,
    requires: {
      flags: ["teacherAcross"],
    },
    title: "天亮以前",
    kicker: "结局四 · 路还没有走完",
    copy: [
      "到达北沟时，有些纸受了潮，有些去向还只能写“待寻”，这一夜也留下了没来得及照料的人和需要复查的路。接应人把每一件未完成的事分别交给下一组成年人，没有让杏枝独自背回去。",
      "沈兰贞的信仍然没有地址。她把它收进信束，不把沉默解释成永别。杏枝也没有在天亮时得到弟弟站在门口的奇迹；她得到一条可信口信，以及愿意从两边继续核对的人。",
      "真实的1942年仍将十分艰难。一个夜晚不能改写战局，但可以决定普通人在风声最紧的时候，是否仍把彼此当作有姓名、有来路、也该有归处的人。",
    ],
    finalLine: "天亮不是故事结束，只是终于能看清下一段路。",
  },
];
