/*
 * 《名册》互动叙事数据
 *
 * 所有人物、槐树沟村与石门河滩均为虚构。故事只让玩家影响一夜之间
 * 普通人的选择与保存下来的物件，不改变 1942 年太行敌后战场的真实进程。
 */

export const StoryMeta = {
  id: "paperHasAHome",
  title: "名册",
  subtitle: "1942年，辽县的一夜",
  dateLabel: "1942年5月24日傍晚—25日清晨",
  placeLabel: "山西辽县·槐树沟村（虚构）",
  estimatedMinutes: [15, 25],
  startSceneId: "schoolAfterBell",
  endingMarker: "__ending__",
  saveKey: "TaihangLetters1942_Save_V1",
  premise: "1942年5月24日傍晚，侵华日军正在加紧对太行根据地的“扫荡”。十六岁的村学生赵杏枝给四十一岁的教员沈兰贞带路。她们要带着学生名册、几封家信和一套小型油印工具，赶到石门河东岸的北沟接应处。",
  historyBoundary: "槐树沟、石门河滩和全部角色都是虚构的。辽县县名、1942年5月太行反“扫荡”以及群众和学校分散转移的背景依据公开资料；玩家不会参与或改变真实战事。",
  roleBoundary: "赵杏枝是普通村学生，只负责认路和照应同行的人。她不带武器，也不承担侦察、战斗或诱敌任务。",
  toneNote: "故事会写亲人失散、转移和受伤，但不写血腥场面，也不靠强行安排人物死亡煽情。",
  initialStats: {
    time: 0,
    sound: 0,
    bond: 1,
    health: 4,
    paper: 4,
    compassion: 0,
  },
  initialItems: ["mimeographKit", "studentRoster", "letterBundle"],
  initialWords: [],
};

export const SupplyChoices = [
  {
    id: "packMedicine",
    label: "带上药布包",
    hint: "一小包外伤药与干净布条，能照料伤脚或沿途的病人。",
    itemId: "medicine",
    effects: {
      compassion: 1,
      itemsAdd: ["medicine"],
    },
  },
  {
    id: "packClothShoes",
    label: "带上旧布鞋和包袱带",
    hint: "鞋底厚实，另有一条捆油印包的长粗布带。",
    itemId: "clothShoes",
    effects: {
      health: 1,
      itemsAdd: ["clothShoes"],
    },
  },
  {
    id: "packLantern",
    label: "带上罩灯",
    hint: "只剩一点灯油；遮严以后，可以贴地照亮几步。",
    itemId: "hoodedLantern",
    effects: {
      itemsAdd: ["hoodedLantern"],
    },
  },
];

export const ItemDefinitions = [
  {
    id: "mimeographKit",
    label: "油印包",
    note: "分装的钢板、铁笔、蜡纸、简易油印框、少量油墨与小滚筒，用来制作识字页和寻人便笺。",
    glyph: "印",
  },
  {
    id: "studentRoster",
    label: "学生名册",
    note: "十九名学生的姓名、年龄与最后可靠去向；赵石头一栏临时记作“待寻”。",
    glyph: "册",
  },
  {
    id: "letterBundle",
    label: "未寄出的信束",
    note: "孩子与沈兰贞写给失散亲人的家信，地址有的完整，有的仍留着空白。",
    glyph: "信",
  },
  {
    id: "medicine",
    label: "药布包",
    note: "一小包外伤药和干净布条，分量只够处理一次较重的伤处。",
    glyph: "药",
  },
  {
    id: "clothShoes",
    label: "旧布鞋和包袱带",
    note: "一双厚底旧鞋，另带一条可固定伤脚、捆扎油印包的长粗布带。",
    glyph: "鞋",
  },
  {
    id: "hoodedLantern",
    label: "罩灯",
    note: "带遮光罩的小油灯，只余少量灯油，能贴近地面照亮几步。",
    glyph: "灯",
  },
  {
    id: "shitouSlate",
    label: "练字板",
    note: "赵石头写过名字的小黑板；背面的“东井”是成年人留下的转移方向。",
    glyph: "石",
  },
];

export const StudentRoster = [
  { id: "zhaoXingzhi", name: "赵杏枝", age: 16, status: "转移中", note: "随沈兰贞老师转移，携带名册" },
  { id: "zhaoShitou", name: "赵石头", age: 10, status: "待寻", note: "最后被看见时正往东井组方向跑" },
  { id: "gaoYuee", name: "高月娥", age: 13, status: "随家转移", note: "西坡组" },
  { id: "sunXiaosuo", name: "孙小锁", age: 11, status: "随家转移", note: "北沟组" },
  { id: "liBaoan", name: "李保安", age: 14, status: "随家转移", note: "东梁组" },
  { id: "wangLaishun", name: "王来顺", age: 10, status: "随家转移", note: "东井组" },
  { id: "guoXinger", name: "郭杏儿", age: 12, status: "随家转移", note: "西坡组" },
  { id: "tianMancang", name: "田满仓", age: 15, status: "随家转移", note: "南沟组" },
  { id: "fengGaihua", name: "冯改花", age: 13, status: "随家转移", note: "北坡组" },
  { id: "yangXiaoni", name: "杨小妮", age: 8, status: "随家转移", note: "东井组" },
  { id: "zhangShuanzhu", name: "张栓柱", age: 12, status: "随家转移", note: "北沟组" },
  { id: "chenYulan", name: "陈玉兰", age: 14, status: "随家转移", note: "东梁组" },
  { id: "liuErxi", name: "刘二喜", age: 9, status: "随家转移", note: "西坡组" },
  { id: "maChunsheng", name: "马春生", age: 15, status: "随家转移", note: "南沟组" },
  { id: "heXiuzhen", name: "贺秀珍", age: 11, status: "随家转移", note: "北坡组" },
  { id: "weiXiaoman", name: "魏小满", age: 10, status: "随家转移", note: "东井组" },
  { id: "dongGuixiang", name: "董桂香", age: 16, status: "随家转移", note: "南沟组" },
  { id: "shenSuocheng", name: "申锁成", age: 13, status: "随家转移", note: "北沟组" },
  { id: "qiaoGenlai", name: "乔根来", age: 14, status: "随家转移", note: "东梁组" },
];

export const MemoryObjects = [
  {
    id: "person",
    glyph: "伤",
    label: "伤员",
    title: "伤员情况",
    copy: "过河和转移时先照顾伤员与行动不便的人。名册丢失后可以重抄，油印工具也可以重新配齐。",
  },
  {
    id: "name",
    glyph: "册",
    label: "名册",
    title: "学生名册",
    copy: "名册记着十九名学生最后一次被看见的地点。没有可靠消息的人只写“待寻”，不能拿猜测当事实。",
  },
  {
    id: "road",
    glyph: "标",
    label: "路标",
    title: "接应路标",
    copy: "岔路、浅滩和临时藏身处都要记清。前一拨人留下记号，后一拨人才知道往哪里走。",
  },
  {
    id: "home",
    glyph: "址",
    label: "地址",
    title: "回信地址",
    copy: "信上要写清亲属姓名、原住村庄和约定的接信地点。即使暂时寄不出去，以后也有地方可查。",
  },
];

export const StoryScenes = [
  {
    id: "schoolAfterBell",
    chapter: 1,
    chapterLabel: "第一章 · 离开学校",
    title: "散学以后",
    timeLabel: "1942年5月24日 · 日暮",
    place: "槐树沟临时小学",
    mood: "dusk",
    copy: [
      "傍晚，村里来传话的人在窗下停住，只说日军搜索队正从公路往山里进，各家照早先分好的组散开走，别挤在一处。说完，他又赶去下一户。教室里的孩子陆续被家人领走，没人再去碰门外的钟绳。",
      "讲桌上摆着一册学生名册、一束没寄出的家信，还有拆开分装的油印工具。沈兰贞平时用钢板、铁笔、蜡纸、简易油印框、油墨和滚筒印识字页；哪家孩子走散了，也能印寻人条。杏枝把每一样都用布包好。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "杏枝，北沟那边天亮前有人接应。咱们按村里定好的路走，别让接应的人等空。路上不要临时跟人改道。" },
      { speaker: "赵杏枝", text: "石头还没回来。你怎么已经在他那一行写上“待寻”了？" },
      { speaker: "沈兰贞", text: "第二遍点人时没见着他，就得照实写。等有了准信，再改。" },
    ],
    historyId: "CreativeBoundary",
    choices: [
      {
        id: "countNamesFirst",
        label: "把十九个名字再念一遍",
        hint: "核对每个人跟哪一组走，也检查名册有没有缺页。",
        next: "packing",
        effects: {
          bond: 1,
          wordsAdd: ["name"],
          flagsSet: ["countedRoster"],
        },
      },
      {
        id: "closeSchoolFirst",
        label: "收起最后一张凳子，关好门窗",
        hint: "多停一会儿，别让人一眼看出学校刚刚撤走。",
        next: "packing",
        effects: {
          time: 1,
          compassion: 1,
          wordsAdd: ["home"],
          flagsSet: ["schoolSecured"],
        },
      },
    ],
  },
  {
    id: "packing",
    chapter: 1,
    chapterLabel: "第一章 · 离开学校",
    title: "只能再带一样",
    timeLabel: "1942年5月24日 · 日暮后",
    place: "临时小学后屋",
    mood: "dusk",
    copy: [
      "名册塞进杏枝贴身的布袋，信束裹上两层油纸，钢板、铁笔、蜡纸、油印框、油墨和滚筒装进一个大包袱，由两个人换着背。两人的水葫芦和两块杂粮饼已经装好。油印包沉得坠手，后屋剩下的药布包、旧布鞋和罩灯只能再拿一样。",
      "窗外传来两下轻轻的叩墙声，这是各家开始上路的信号。后屋有个现成的墙洞，选剩的两样用油纸一包，就能塞进去。杏枝蹲下来，把三样东西挨个掂了掂。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "我还能背，三样都带上不行吗？" },
      { speaker: "沈兰贞", text: "这个包已经够沉了，再加上就走不了多远。你挑一样，剩下的我包好藏起来。" },
    ],
    historyId: "CivilianEvacuation",
    choices: [
      {
        id: "packMedicine",
        label: "带上药布包",
        hint: "有外伤药和干净布条，只够给一个人仔细包扎一回。",
        next: "pendingName",
        effects: {
          compassion: 1,
          itemsAdd: ["medicine"],
        },
      },
      {
        id: "packClothShoes",
        label: "带上旧布鞋和包袱带",
        hint: "鞋底厚实，另有一条捆包袱的粗布带。",
        next: "pendingName",
        effects: {
          health: 1,
          itemsAdd: ["clothShoes"],
        },
      },
      {
        id: "packLantern",
        label: "带上罩灯",
        hint: "灯油不多，罩住光后只能照清脚前几步。",
        next: "pendingName",
        effects: {
          itemsAdd: ["hoodedLantern"],
        },
      },
    ],
  },
  {
    id: "pendingName",
    chapter: 1,
    chapterLabel: "第一章 · 离开学校",
    title: "石头那一行",
    timeLabel: "1942年5月24日 · 初更",
    place: "学校门槛",
    mood: "intimate",
    copy: [
      "赵石头十岁，是杏枝的弟弟。下午各家分组转移时，他扶着耳背的杨奶奶去找东井组。第二遍点人时，杨奶奶在东井组，石头却不在。有人最后看见他朝东井方向跑，后来拐了哪条岔路，谁也说不清。",
      "沈兰贞先在石头那一行临时记了“待寻”。杏枝拿着笔，想过把它改成“已到”，可接应点还要照着这本名册找人。真这么写，后来的人就不会再回头问石头去了哪儿。她在门槛上蹲了好一会儿。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "要是一直找不着呢？这两个字就一直留着？" },
      { speaker: "沈兰贞", text: "有准信就改。眼下没准信，只能这么写。旁边能补什么，咱们就补什么。" },
    ],
    historyId: "NamesAndRecords",
    choices: [
      {
        id: "keepPendingTruth",
        label: "先保留“待寻”",
        hint: "眼下没有到达的消息，到了接应点还得继续问。",
        next: "villageLane",
        effects: {
          bond: 1,
          compassion: 1,
          wordsAdd: ["person", "name"],
          flagsSet: ["keptPendingTruth"],
        },
      },
      {
        id: "writeLastSeen",
        label: "补上“最后往东井方向”",
        hint: "只记最后确认过的去向，不写他已经到达。",
        next: "villageLane",
        effects: {
          time: 1,
          paper: -1,
          wordsAdd: ["road", "name"],
          flagsSet: ["recordedLastSeen"],
        },
      },
      {
        id: "foldNameInward",
        label: "把这一页折到名册里面",
        hint: "字仍留着，路上不翻名册就看不到石头的名字和去向。",
        next: "villageLane",
        effects: {
          sound: -1,
          bond: 1,
          wordsAdd: ["name"],
          flagsSet: ["concealedRoster"],
        },
      },
    ],
  },
  {
    id: "villageLane",
    chapter: 1,
    chapterLabel: "第一章 · 离开学校",
    title: "顾婶还在屋里",
    timeLabel: "1942年5月24日 · 初更",
    place: "槐树沟西巷",
    mood: "tense",
    copy: [
      "西巷已经听不见人说话。鸡笼蒙着布，灶膛里的火也压灭了。各家按分好的组从不同路口出村，门前的脚印朝着好几个方向。走得快的先走，邻家会回来接腿脚慢的人。",
      "顾婶家的门还虚掩着。她腿脚不好，本来该由隔壁的人送去北坡。杏枝听见屋里有拐杖磕到门槛。接她的人是还没到，还是正从后巷绕过来，她也拿不准。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "她还在里头。我进去问一声？" },
      { speaker: "沈兰贞", text: "别在巷里喊。你贴着门问，我去看巷口。" },
    ],
    historyId: "LocalGuide",
    choices: [
      {
        id: "warnAuntGu",
        label: "贴着门问问顾婶",
        hint: "确认接她的人来过没有；要多停一会儿，两人低声说话也会让巷里多一点动静。",
        next: "dryWellFork",
        effects: {
          time: 1,
          sound: 1,
          compassion: 2,
          wordsAdd: ["person", "home"],
          flagsSet: ["warnedAuntGu"],
        },
      },
      {
        id: "leaveMutualAidMark",
        label: "在门脚画下北坡组的接应记号",
        hint: "回来查有没有落下人的村民能看懂；顾婶可以留在屋里等，不必出声。",
        next: "dryWellFork",
        effects: {
          time: 1,
          compassion: 1,
          wordsAdd: ["road", "home"],
          flagsSet: ["leftMutualAidMark"],
        },
      },
      {
        id: "reportHouseLater",
        label: "记下西巷第三院，到北沟报信",
        hint: "立刻赶路，到了接应点再请人回来；顾婶还要等一阵。",
        next: "dryWellFork",
        effects: {
          compassion: 1,
          wordsAdd: ["home"],
          flagsSet: ["carriedHouseReport"],
        },
      },
    ],
  },
  {
    id: "dryWellFork",
    chapter: 2,
    chapterLabel: "第二章 · 绕过村北",
    title: "枯井岔口",
    timeLabel: "1942年5月24日 · 初更",
    place: "村北梯田",
    mood: "night",
    copy: [
      "一出村，手里的简图就有些对不上了。梯田边刚翻过土，图上标的那棵老杏树也只剩半截。枯井旁分出三条羊肠路，天一黑，路面都看不清。",
      "沈兰贞在井边停下，问杏枝上回带学生认路时走的是哪一条：下过雨以后，哪条路不积泥？石头嫌哪一段最绕？杏枝摸到井口朝南的缺角，又在背风处找到几块碎白石。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "先别走。把你记得的地标说一遍。" },
      { speaker: "赵杏枝", text: "井口朝南有个缺角，碎白石在背风这边。榆树梁远一点，可脚下是硬路。" },
    ],
    historyId: "MountainRoute",
    choices: [
      {
        id: "takeElmRidge",
        label: "从榆树梁走",
        hint: "坡陡，费脚力；石面硬，不容易留下一串泥脚印。",
        next: "slateOnSlope",
        effects: {
          health: -1,
          sound: -1,
          wordsAdd: ["road"],
          flagsSet: ["tookElmRidge"],
        },
      },
      {
        id: "takeLowerTerrace",
        label: "沿下层田埂绕行",
        hint: "路平一些，但岔口多，要慢慢辨认。",
        next: "slateOnSlope",
        effects: {
          time: 2,
          health: 1,
          wordsAdd: ["road"],
          flagsSet: ["tookLowerTerrace"],
        },
      },
      {
        id: "rebuildRouteTogether",
        label: "停下来，把沿路地标对一遍",
        hint: "两个人都记下井口缺角、碎白石和榆树梁，再动身。",
        next: "slateOnSlope",
        effects: {
          time: 1,
          bond: 2,
          wordsAdd: ["road"],
          flagsSet: ["sharedRouteMemory"],
        },
      },
    ],
  },
  {
    id: "slateOnSlope",
    chapter: 2,
    chapterLabel: "第二章 · 绕过村北",
    title: "刺丛里的练字板",
    timeLabel: "1942年5月24日 · 初更将尽",
    place: "榆树梁北坡",
    mood: "memory",
    copy: [
      "榆树梁北坡的刺丛里卡着一块巴掌大的练字板。杏枝一眼认出正面的字：歪歪扭扭的“赵石头”写了好几遍，“石”的一撇总拖得很长。背面的字稳得多，是大人用白土写的“东井”，旁边还蹭着半个手印。",
      "这只能说明东井组走过北坡，不能说明石头现在在哪儿。杏枝捧着板子朝东井方向看；约定的路却通往北沟，她们要是临时改道，接应点就不知道名册和信走到了哪里。沈兰贞把包袱提稳，等她拿主意。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "是石头的。你看，他这个“石”字总写出格。" },
      { speaker: "沈兰贞", text: "我看见了。先记清是在北坡哪儿捡的。背面的字是谁写的，见着东井组的人再问。" },
    ],
    historyId: "NamesAndRecords",
    choices: [
      {
        id: "takeShitouSlate",
        label: "带上练字板，记下地点",
        hint: "到了接应点可以拿给东井组的人辨认；收拾时会多耽搁一会儿。",
        next: "kilnShelter",
        effects: {
          time: 1,
          bond: 1,
          wordsAdd: ["person", "name"],
          itemsAdd: ["shitouSlate"],
          flagsSet: ["foundShitouTrail"],
        },
      },
      {
        id: "copySlateClue",
        label: "把“东井”和地点抄到名册页角",
        hint: "线索跟名册放在一起，但要占一点纸面。",
        next: "kilnShelter",
        effects: {
          paper: -1,
          wordsAdd: ["name", "road"],
          flagsSet: ["foundShitouTrail", "copiedSlateClue"],
        },
      },
      {
        id: "markSlateLocation",
        label: "把板子藏高，垒三块石作记号",
        hint: "回来找人的村民能找到它；自己仍按约定去北沟。",
        next: "kilnShelter",
        effects: {
          time: 1,
          compassion: 1,
          wordsAdd: ["person", "road"],
          flagsSet: ["markedShitouClue"],
        },
      },
    ],
  },
  {
    id: "kilnShelter",
    chapter: 2,
    chapterLabel: "第二章 · 绕过村北",
    title: "废窑里的祖孙",
    timeLabel: "1942年5月24日 · 二更",
    place: "废石灰窑",
    mood: "shelter",
    copy: [
      "废石灰窑里，杨奶奶搂着小妮坐在草垫上。东井组的人去前头认路，到现在还没回来。小妮额头发烫，脚背又让碎石划开了一道口子。杨奶奶认出杏枝，忙把身边的半碗凉水递给她。",
      "东井组的人只是去前头认路，按说还会回来。小妮发着烧，杨奶奶也走不快，不能跟着杏枝她们连夜赶去河滩。她们又不能在窑口久留，眼下只能给小妮处理伤口、给接应人留话，或者把祖孙俩的情况带到北沟。",
    ],
    dialogue: [
      { speaker: "杨奶奶", text: "石头扶我过了乱石坡，又看见东井的人在前头，就跑去问他们走哪边。我只顾着小妮，回头就找不着他了。" },
      { speaker: "赵杏枝", text: "他不是贪玩。你耳朵不好，他怕人家说一遍你没听见。" },
      { speaker: "沈兰贞", text: "这话得记准。到了北沟打听石头，要说他是从这里往东井组那边走的。" },
    ],
    historyId: "LocalGuide",
    choices: [
      {
        id: "useMedicineForXiaoni",
        label: "给小妮包好伤口，再留下药和布",
        hint: "告诉杨奶奶怎么换药；到了北沟，再请人来看看孩子还烧不烧。",
        next: "fourWrittenWords",
        effects: {
          compassion: 3,
          bond: 1,
          itemsRemove: ["medicine"],
          wordsAdd: ["person"],
          flagsSet: ["aidedXiaoni"],
        },
        requires: {
          items: ["medicine"],
        },
      },
      {
        id: "leaveKilnNote",
        label: "写张便条，夹进窑外约定的石缝",
        hint: "回来找人的村民会查看这里。便条只写废窑有一老一小需要接应，不写姓名。",
        next: "fourWrittenWords",
        effects: {
          time: 1,
          paper: -1,
          compassion: 2,
          wordsAdd: ["road", "home"],
          flagsSet: ["leftKilnNote"],
        },
      },
      {
        id: "carryKilnReport",
        label: "记住两人的模样和废窑位置",
        hint: "不留纸；到了北沟，当面请接应人回来找她们。",
        next: "fourWrittenWords",
        effects: {
          time: 1,
          compassion: 2,
          bond: 1,
          wordsAdd: ["person", "home"],
          flagsSet: ["memorizedKilnReport"],
        },
      },
      {
        id: "leaveLanternWithKiln",
        label: "把罩灯留给杨奶奶",
        hint: "接应人来时，她们能照着收拾上路；你们过河时将没有灯可用。",
        next: "fourWrittenWords",
        effects: {
          compassion: 3,
          itemsRemove: ["hoodedLantern"],
          wordsAdd: ["home"],
          flagsSet: ["leftLanternAtKiln"],
        },
        requires: {
          items: ["hoodedLantern"],
        },
      },
    ],
  },
  {
    id: "fourWrittenWords",
    chapter: 2,
    chapterLabel: "第二章 · 绕过村北",
    title: "油印包还剩一张蜡纸",
    timeLabel: "1942年5月24日 · 二更",
    place: "窑洞外的背风坡",
    mood: "intimate",
    copy: [
      "出窑前，杏枝重新捆油印包。她们清点了一遍，发现只剩一张没刻过的蜡纸，油墨也只够印一小批。到了北沟，可以刻一版不带姓名和路线的空白登记表，分给出去接人的村民各自填写。",
      "河西需要接的人、十九名学生的去向、岔口和浅滩的记号、家信该送回话的地方，这些情况不能原样刻在同一张蜡纸上。她们眼下只能先理清一类，到了北沟再按河西、北沟和东梁分开手写。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "咱们先把哪一类理清？" },
      { speaker: "赵杏枝", text: "杨奶奶和小妮还在河西，石头也没准信。哪一类都缺。" },
      { speaker: "沈兰贞", text: "那就先理一类。剩下的路上继续问，到了北沟按地方分开写，别把姓名和路线印在一张纸上。" },
    ],
    historyId: "Mimeograph",
    choices: [
      {
        id: "choosePersonWord",
        label: "先整理伤员和落单人员的情况",
        hint: "记下杨奶奶、小妮和其他行动不便的人在哪里等、该由谁接。",
        next: "ditchWaiting",
        effects: {
          bond: 1,
          compassion: 1,
          wordsAdd: ["person"],
        },
      },
      {
        id: "chooseNameWord",
        label: "先整理十九名学生的去向",
        hint: "把姓名、同行的人和最后见到的地方重新核对一遍。",
        next: "ditchWaiting",
        effects: {
          bond: 1,
          wordsAdd: ["name"],
        },
      },
      {
        id: "chooseRoadWord",
        label: "先整理岔口和浅滩的记号",
        hint: "写清接应人认得的石缝、白石和柳枝记号。",
        next: "ditchWaiting",
        effects: {
          time: -1,
          wordsAdd: ["road"],
        },
      },
      {
        id: "chooseHomeWord",
        label: "先整理家信的回话地点",
        hint: "写清信送不到时该退回哪里，回话又该托给谁。",
        next: "ditchWaiting",
        effects: {
          compassion: 1,
          wordsAdd: ["home"],
        },
      },
    ],
  },
  {
    id: "ditchWaiting",
    chapter: 3,
    chapterLabel: "第三章 · 经过公路",
    title: "公路上的车灯",
    timeLabel: "1942年5月24日 · 二更将尽",
    place: "旧驮道下方",
    mood: "tense",
    copy: [
      "她们走到旧驮道下方时，公路那边传来发动机声。隔了一会儿，一束灯从高处的土路扫下来，照过灌木和沟沿。分不清是什么车，更不能上去看。两人贴着废灌渠伏下，把油印包和信束压在身边。",
      "杏枝挪动胳膊时，钢板碰了一下滚筒的木柄。她立刻按住油印包。旁边的沈兰贞手指也在抖，却还侧着头听车声。灯光第二次扫过来时，她轻轻往下拽了拽杏枝的袖口。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "沈老师，你的手在抖。" },
      { speaker: "沈兰贞", text: "嗯。别抬头。等听不见车声，我碰你一下，咱们再走。" },
    ],
    historyId: "TaihangSweep",
    choices: [
      {
        id: "waitForRoadSilence",
        label: "继续伏着，等车声完全远去",
        hint: "要多等一阵，免得刚起身，车灯又扫回来。",
        next: "unsentLetter",
        effects: {
          time: 2,
          sound: -2,
          bond: 2,
          flagsSet: ["waitedForSilence"],
        },
      },
      {
        id: "moveThroughColdDitch",
        label: "趁灯光转开，沿废渠低身绕走",
        hint: "能早些离开公路边；沟底有冷水，鞋袜会湿。",
        next: "unsentLetter",
        effects: {
          time: 1,
          sound: -1,
          health: -1,
          flagsSet: ["usedColdDitch"],
        },
      },
      {
        id: "trustTeacherTiming",
        label: "听沈老师的招呼再起身",
        hint: "她留意公路动静；杏枝把名册、信和油印包护好。",
        next: "unsentLetter",
        effects: {
          time: 1,
          bond: 2,
          sound: -1,
          flagsSet: ["trustedTeacherTiming"],
        },
      },
    ],
  },
  {
    id: "unsentLetter",
    chapter: 3,
    chapterLabel: "第三章 · 经过公路",
    title: "写给小禾的信",
    timeLabel: "1942年5月24日 · 三更前",
    place: "废羊圈背墙",
    mood: "memory",
    copy: [
      "车声听不见了，她们在废羊圈的背风墙下歇脚。杏枝整理信束时，摸到最底下一封厚信。信封上写着“小禾收”，住址却没填。小禾是沈兰贞的妹妹。两年前，她跟着亲戚往东边转移，后来山里的交通断了几回。她最后托人带回的口信，只说自己平安到了东边。再往后便没了消息。",
      "这封信不是一口气写完的。沈兰贞隔些日子就添一页。村里哪个孩子刚会写全自己的名字，杏花哪天开，她都记在信里。小禾留下的旧算术书还在她手上，里面有一道妹妹没做完的题。她不知道信什么时候能寄出，仍把每一页的日期写得清清楚楚。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "两年了，这些她一页也没看见？" },
      { speaker: "沈兰贞", text: "没有。先写着，等问到准地方，再一起寄。" },
      { speaker: "赵杏枝", text: "你就不怕白写？" },
      { speaker: "沈兰贞", text: "怕。可不写下来，真见着她，我怕这两年的事一句也想不全。" },
    ],
    historyId: "MountainRoute",
    choices: [
      {
        id: "promiseSharedSearch",
        label: "答应到了北沟一起打听两个人",
        hint: "石头最后往东井组去了；小禾最后在东边报过平安。先拿这两句话去问人。",
        next: "brokenMarkers",
        effects: {
          bond: 3,
          compassion: 1,
          wordsAdd: ["person", "home"],
          flagsSet: ["sharedSearchPromise"],
        },
      },
      {
        id: "admitRosterFear",
        label: "告诉她，自己想过把“待寻”涂掉",
        hint: "杏枝没有真改名册；她只是把那个念头说了出来。",
        next: "brokenMarkers",
        effects: {
          bond: 3,
          wordsAdd: ["name"],
          flagsSet: ["admittedRosterFear"],
        },
      },
      {
        id: "askToReadLetter",
        label: "请沈老师念一小段",
        hint: "杏枝想听听，沈老师这些年究竟写了些什么。",
        next: "letterReadAloud",
        effects: {
          time: 1,
          bond: 2,
          compassion: 2,
          wordsAdd: ["home"],
          flagsSet: ["heardUnsentLetter"],
        },
      },
    ],
  },
  {
    id: "letterReadAloud",
    chapter: 3,
    chapterLabel: "第三章 · 经过公路",
    title: "沈老师念了一页",
    timeLabel: "1942年5月24日 · 三更前",
    place: "废羊圈背墙",
    mood: "intimate",
    copy: [
      "沈兰贞展开最后一页，压低声音念道：“小禾，槐树沟的杏花已经落了。你那本算术书我还留着，你做到一半的那一页也还在。学校的孩子散在几处上课，有两个已经会写全名。你若收到信，别连夜往回赶。先托靠得住的人捎句话，写清你住在哪儿，我去接你。”",
      "念到“别连夜往回赶”，她停下来咽了口唾沫。信封里还装着前些日子写的几页，她没再念。杏枝看见每页右上角都写着日期；最早的一张，折痕已经磨白了。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "你信里怎么只写这些？你没说想她。" },
      { speaker: "沈兰贞", text: "不敢写。她性子急，看了说不准真会赶夜路。等问准她在哪儿，我当面说。" },
    ],
    historyId: "NamesAndRecords",
    choices: [
      {
        id: "foldLetterTogether",
        label: "照原来的折痕收好信，住址先空着",
        hint: "等打听到可靠的住处，再交给能走那条路的人。",
        next: "brokenMarkers",
        effects: {
          bond: 1,
          compassion: 1,
          wordsAdd: ["home"],
          flagsSet: ["letterReadAloud"],
        },
      },
    ],
  },
  {
    id: "brokenMarkers",
    chapter: 3,
    chapterLabel: "第三章 · 经过公路",
    title: "岔口的草结散了",
    timeLabel: "1942年5月25日 · 三更",
    place: "石门沟西口",
    mood: "night",
    copy: [
      "过了午夜，她们到了石门沟西口。原先系在灌木上的草结已经被风吹散，只剩两根枯草挂在石缝边。杏枝认得石壁上的缺口，知道再往下就是河滩；可从废窑赶来的祖孙和其他转移村民，未必能在黑地里找准这个岔口。",
      "她们不能留大字，也不能把记号摆在路中间。记号太显眼，陌生人也会顺着找到河滩。按原先的约定，接应人认得夹在石缝里的窄纸条，也认得三块白石。杏枝摸了摸包里剩下的空白纸，又看向坡脚散落的石块。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "用纸最快，可咱们只剩这几张了。" },
      { speaker: "沈兰贞", text: "你来定。要用纸就裁窄些；不用纸，我和你搬石头。实在不稳妥，到了河东再叫人回来接。" },
    ],
    historyId: "MountainRoute",
    choices: [
      {
        id: "leaveNarrowPaperMarker",
        label: "裁一条窄纸，夹进接应人认得的石缝",
        hint: "省时间，但会少一张空白纸；纸条不会露在路面上。",
        next: "westBank",
        effects: {
          time: 1,
          paper: -1,
          compassion: 2,
          wordsAdd: ["road"],
          flagsSet: ["leftPaperMarker"],
        },
        requires: {
          min: {
            paper: 1,
          },
        },
      },
      {
        id: "buildWhiteStoneMarker",
        label: "按原先的约定垒三块白石",
        hint: "不写字，也不用纸；弯腰搬石要多耽搁一阵。",
        next: "westBank",
        effects: {
          time: 2,
          health: -1,
          compassion: 1,
          wordsAdd: ["road"],
          flagsSet: ["leftStoneMarker"],
        },
      },
      {
        id: "memorizeHandoffOnly",
        label: "不留记号，到了河东再把岔口说清楚",
        hint: "不会留下痕迹；后边的人要等接应人回来领路。",
        next: "westBank",
        effects: {
          sound: -1,
          bond: 1,
          flagsSet: ["memorizedRiverHandoff"],
        },
      },
    ],
  },
  {
    id: "westBank",
    chapter: 4,
    chapterLabel: "第四章 · 过石门河",
    title: "先把浅滩探清",
    timeLabel: "1942年5月25日 · 四更",
    place: "石门河滩西岸",
    mood: "river",
    copy: [
      "石门河不宽，附近村民平日都从这处浅滩过河。今夜月亮被云遮住，水里的石头只有浪花翻起来时才露一点白。两户正在转移的村民躲在柳丛后面，队伍里有两个老人，还有几个年幼的孩子。",
      "约好领路的人一直没来。有人记得浅滩在什么方向，却说不准哪块石头松、哪处水深。沈兰贞不肯让人摸黑下水。杏枝翻了翻随身带的东西，想帮探路的人把已经试过的落脚处标出来。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "先别下水。找两个会水、又熟悉河滩的大人，拿长杆往前探。哪一步拿不准，大家就在岸上等。" },
      { speaker: "赵杏枝", text: "我记得第三块石头边有柳根。探过一块，就往石缝里插根短柳枝，我在枝上绑白纸。人都过去以后，再把纸收回来。" },
    ],
    historyId: "MountainRoute",
    choices: [
      {
        id: "makePaperBridge",
        label: "请两个熟悉河滩的大人持杆探水，沿路插柳枝系白纸",
        hint: "杏枝留在岸边，只给探过的石头做记号；不用家信，过河后把纸收走。",
        next: "midstream",
        effects: {
          time: 1,
          sound: 1,
          paper: -2,
          compassion: 3,
          bond: 1,
          wordsAdd: ["road", "home"],
          flagsSet: ["paperBridge", "guidedCrossing"],
        },
        requires: {
          min: {
            paper: 2,
          },
        },
      },
      {
        id: "useShieldedLantern",
        label: "由岸上的人挡光，用罩灯照探路人的脚下",
        hint: "每次只照近处一块石头。灯油不多，远处也可能看见亮光。",
        next: "midstream",
        effects: {
          time: 1,
          sound: 2,
          compassion: 2,
          itemsRemove: ["hoodedLantern"],
          wordsAdd: ["road"],
          flagsSet: ["lanternFord", "guidedCrossing"],
        },
        requires: {
          items: ["hoodedLantern"],
        },
      },
      {
        id: "leadWithSlate",
        label: "让熟悉浅滩的大人探水，杏枝在练字板上记石头次序",
        hint: "每确认一处落脚点便画一道，随后把练字板留在岸边，提醒大家依次过河。",
        next: "midstream",
        effects: {
          time: 1,
          compassion: 2,
          bond: 1,
          itemsRemove: ["shitouSlate"],
          wordsAdd: ["person", "road"],
          flagsSet: ["slateFord", "guidedCrossing"],
        },
        requires: {
          items: ["shitouSlate"],
          flags: ["foundShitouTrail"],
        },
      },
      {
        id: "waitForCloudBreak",
        label: "先躲进柳丛，等云散一些再过河",
        hint: "不用冒黑下水，但要在河边多等一阵。大家分散坐开，尽量不出声。",
        next: "midstream",
        effects: {
          time: 3,
          sound: -1,
          health: 1,
          compassion: 2,
          bond: 1,
          flagsSet: ["waitedForCloudBreak", "guidedCrossing"],
        },
      },
    ],
  },
  {
    id: "midstream",
    chapter: 4,
    chapterLabel: "第四章 · 过石门河",
    title: "沈老师扭了脚",
    timeLabel: "1942年5月25日 · 四更",
    place: "石门河滩中央",
    mood: "climax",
    copy: [
      "最后一趟过河时，沈兰贞的旧鞋卡进石缝，右脚踝猛地一歪。杏枝伸手扶她，肩上的油印包却顺着背带滑到了肘弯。水只到小腿，可脚下的石头很滑；沈老师疼得站不稳，名册和信束也险些泡进水里。",
      "沈兰贞忍着疼，让杏枝先把名册和信递给前面已经站稳的人，再找人回来搭手。油印包若实在带不过去，就用油纸裹严，压在有记号的石头后面，等天亮后请熟悉河滩的人来取。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "我扶你，包也不能掉。" },
      { speaker: "沈兰贞", text: "别硬撑。先把名册和信递出去，再叫人来扶我。工具带不了，就先压在石头后面。" },
    ],
    historyId: "LocalGuide",
    choices: [
      {
        id: "makeClothHarness",
        label: "先扶沈老师坐上平石，再用布鞋和包袱带固定脚踝",
        hint: "岸边的人接过名册和信，杏枝把油印包重新扎牢，再扶沈老师走完剩下几步。",
        next: "farBank",
        effects: {
          time: 1,
          bond: 2,
          health: 1,
          itemsRemove: ["clothShoes"],
          flagsSet: ["teacherAcross", "keptMimeographKit", "clothHarness"],
        },
        requires: {
          items: ["clothShoes", "mimeographKit", "studentRoster", "letterBundle"],
        },
      },
      {
        id: "askCrossersForHands",
        label: "请岸边村民接住东西，一起扶沈老师",
        hint: "一人接名册和信，一人背油印包，另外两人回来搭手。",
        next: "farBank",
        effects: {
          time: 1,
          sound: 1,
          bond: 2,
          compassion: 2,
          flagsSet: ["teacherAcross", "keptMimeographKit", "acceptedHelp"],
        },
        requires: {
          min: {
            bond: 4,
          },
          items: ["mimeographKit", "studentRoster", "letterBundle"],
          flags: ["guidedCrossing"],
        },
      },
      {
        id: "cacheMimeographByBoulder",
        label: "把油印包裹严，压在缺口巨石的内侧",
        hint: "记下柳根和踏脚石的位置，先空出双手扶沈老师上岸，天亮后再托人来取。",
        next: "farBank",
        effects: {
          bond: 2,
          compassion: 1,
          health: 1,
          itemsRemove: ["mimeographKit"],
          wordsAdd: ["person"],
          flagsSet: ["teacherAcross", "lostMimeographKit", "markedRiverCache"],
        },
        requires: {
          items: ["mimeographKit"],
        },
      },
      {
        id: "putPersonBeforeTools",
        label: "顾不上油印包了，先用双手扶住沈老师",
        hint: "包滑进浅水的石窝，杏枝记住位置，先把沈老师、名册和信送上岸。",
        next: "farBank",
        effects: {
          bond: 3,
          compassion: 2,
          health: 1,
          itemsRemove: ["mimeographKit"],
          wordsAdd: ["person"],
          flagsSet: ["teacherAcross", "lostMimeographKit", "markedRiverCache", "personBeforeTools"],
        },
      },
    ],
  },
  {
    id: "farBank",
    chapter: 4,
    chapterLabel: "第四章 · 过石门河",
    title: "上岸以后",
    timeLabel: "1942年5月25日 · 四更将尽",
    place: "石门河滩东岸",
    mood: "afterstorm",
    copy: [
      "沈兰贞坐到背风处，右脚一落地就疼。名册和信束的边角进了水，好在墨字还没有洇开。刚过河的村民腾出一块平石，又从包袱里找了两块干布，让杏枝先把纸上的水吸掉。",
      "杏枝把湿页慢慢揭开。信里写的都是家常话：“娘的咳嗽好些没有”“门后的谷种别受潮”“我还记得回家的岔口”。她从前嫌同学们总写这些，如今却怕漏掉任何一张。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "先看墨字散没散，别硬揭。粘住的先放着，等干一点再动。" },
      { speaker: "赵杏枝", text: "我以前还笑他们，封封都问咳嗽、问粮食。现在一张也不能少。" },
    ],
    historyId: "Mimeograph",
    choices: [
      {
        id: "treatAnkleAndWrapLetters",
        label: "用干净布条固定沈老师的脚踝，再用外层干布包信",
        hint: "布条和干布会一次用完；脚踝能固定住，信也不会继续受潮。",
        next: "shitouNews",
        effects: {
          time: 1,
          health: 2,
          bond: 1,
          itemsRemove: ["medicine"],
          flagsSet: ["treatedTeacher", "lettersProtected"],
        },
        requires: {
          items: ["medicine"],
        },
      },
      {
        id: "separatePagesByBodyHeat",
        label: "先用干布吸水，再把信束贴身收好",
        hint: "不能在河边久停，只能带着潮气继续走，杏枝也会冷上一阵。",
        next: "shitouNews",
        effects: {
          time: 1,
          health: -1,
          bond: 1,
          flagsSet: ["lettersProtected"],
        },
      },
      {
        id: "restAndAirPages",
        label: "在背风处多停一会儿，把湿页逐张晾开",
        hint: "纸干得慢，会耽搁行程；沈老师也能趁这会儿歇一歇脚。",
        next: "shitouNews",
        effects: {
          time: 2,
          health: 1,
          paper: 1,
          flagsSet: ["lettersProtected", "paperRecovered"],
        },
      },
    ],
  },
  {
    id: "shitouNews",
    chapter: 5,
    chapterLabel: "第五章 · 到北沟去",
    title: "有人见过石头",
    timeLabel: "1942年5月25日 · 五更",
    place: "河东柳林",
    mood: "quiet",
    copy: [
      "准备离开河滩时，杏枝挨个询问刚过河的东井组村民。一个妇女说，她在岔路口见过一个十岁左右的男孩。那孩子一直说姐姐叫杏枝，后来跟着他认识的王家人去了东梁洞。临走前，他托妇女带话，说自己没有落单。",
      "杏枝不敢只凭名字就认定是弟弟。她问那孩子左眉上有没有一道浅疤，右膝的补丁是不是深蓝粗布，又问他着急时喊的是“杏子”还是“姐”。妇女都答上了。眉疤、补丁和称呼全对得上，杏枝还是决定等东梁那边真见到人，再改名册。",
    ],
    dialogue: [
      { speaker: "东井组妇女", text: "他没落单，跟着王家两口子走的。后来过岔口时，各组又分开了，我就没再见着他们。" },
      { speaker: "赵杏枝", text: "东梁洞离这儿不算远，我现在就去找他。" },
      { speaker: "沈兰贞", text: "想去可以，但先把话留给北沟的接应人，也托东梁那边去找。万一路上又错开，两边都知道该问谁。" },
    ],
    historyId: "CivilianEvacuation",
    choices: [
      {
        id: "verifyWithSlateDetails",
        label: "把眉疤、补丁和称呼再核对一遍",
        hint: "妇女记得的几处特征都对得上，可以把她见到孩子的地点和时辰记下来。",
        next: "dawnRoster",
        effects: {
          bond: 2,
          compassion: 1,
          wordsAdd: ["person", "name", "road"],
          flagsSet: ["shitouReportedSafe", "verifiedShitouNews"],
        },
        requires: {
          flags: ["foundShitouTrail"],
        },
      },
      {
        id: "detourToEastRidgeHandoff",
        label: "绕到东梁岔口，把石头的事当面托给接应人",
        hint: "不沿着旧脚印乱追，先找到东梁那边的接应人，请他去找王家人。",
        next: "dawnRoster",
        effects: {
          time: 2,
          health: -1,
          compassion: 2,
          bond: 1,
          wordsAdd: ["person", "road"],
          flagsSet: ["shitouReportedSafe", "eastRidgeHandoff"],
        },
      },
      {
        id: "keepPendingAndHandoff",
        label: "先保留“待寻”，把妇女的话带到北沟",
        hint: "记清是谁、在哪里见过石头，再请北沟和东梁两处接应人继续核对。",
        next: "dawnRoster",
        effects: {
          compassion: 2,
          bond: 1,
          wordsAdd: ["person", "name"],
          flagsSet: ["searchHandoff", "keptPendingTruth"],
        },
      },
    ],
  },
  {
    id: "dawnRoster",
    chapter: 5,
    chapterLabel: "第五章 · 到北沟去",
    title: "核对石头那一行",
    timeLabel: "1942年5月25日 · 破晓前",
    place: "北沟临时校舍",
    mood: "predawn",
    copy: [
      "北沟的临时校舍设在炭窑旁的两间空屋里。接应人对过事先约好的口信，请两个熟路的大人先去河滩察看，路上安全再回河西接杨奶奶和小妮；顾婶住的院子也记了下来。先到的村民烧水、铺干草，挨个说自己这一路见过谁、又在哪里分开。",
      "沈兰贞让杏枝先看名册上石头那一行。有干纸就重抄，没有纸就当着两位接应人念清楚。名册上若添“去了东梁洞”，旁边得注明是谁、在哪儿见过他；没见到石头本人，“已到”两个字先不能写。",
    ],
    dialogue: [
      { speaker: "赵杏枝", text: "石头这一行怎么写？那位婶子见过他，可我还没见到。" },
      { speaker: "沈兰贞", text: "把那位婶子的姓名和见到他的地方都写上。没见到本人，就先别写‘已到’。北沟的人会照着姓名和地点，再往东梁问一遍。" },
    ],
    historyId: "WartimeSchool",
    choices: [
      {
        id: "updateShitouDestination",
        label: "写“随王家人往东梁洞，见到本人后再改”",
        hint: "同时记下东井组妇女的姓名和见面地点，接应人可以照着去问。",
        next: "letterPostscript",
        effects: {
          time: 1,
          paper: -1,
          bond: 2,
          compassion: 1,
          wordsAdd: ["name", "road"],
          flagsSet: ["rosterComplete", "rosterProtected", "shitouDestinationAdded"],
        },
        requires: {
          min: {
            paper: 1,
          },
          flags: ["shitouReportedSafe"],
        },
      },
      {
        id: "preservePendingWithSource",
        label: "保留“待寻”，补上妇女的口信和石头去向",
        hint: "不写“已到”，只把目前问到的情况记全，交给下一位接应人。",
        next: "letterPostscript",
        effects: {
          time: 1,
          paper: -1,
          compassion: 2,
          bond: 1,
          wordsAdd: ["person", "name", "road"],
          flagsSet: ["rosterComplete", "rosterProtected", "pendingWithSource"],
        },
        requires: {
          min: {
            paper: 1,
          },
        },
      },
      {
        id: "splitRosterSafely",
        label: "另抄两份表，分开交给两位接应人",
        hint: "一份只写学生姓名，一份只写家庭记号和去处；两人各收一份。",
        next: "letterPostscript",
        effects: {
          time: 2,
          paper: -2,
          compassion: 2,
          wordsAdd: ["name", "home"],
          flagsSet: ["rosterComplete", "rosterProtected", "splitRoster"],
        },
        requires: {
          min: {
            paper: 2,
          },
        },
      },
      {
        id: "oralRosterHandoff",
        label: "不添新纸，当着两位接应人把名册念一遍",
        hint: "沈老师继续贴身收好原册；两位接应人分别复述姓名、最后见到地点和还没问清的去处。",
        next: "letterPostscript",
        effects: {
          time: 2,
          bond: 1,
          compassion: 1,
          wordsAdd: ["person", "name"],
          flagsSet: ["rosterComplete", "rosterProtected", "oralRosterHandoff"],
        },
      },
    ],
  },
  {
    id: "letterPostscript",
    chapter: 5,
    chapterLabel: "第五章 · 到北沟去",
    title: "给小禾的信",
    timeLabel: "1942年5月25日 · 东方发白",
    place: "北沟临时校舍",
    mood: "dawn",
    copy: [
      "天刚蒙蒙亮，北沟外还不时有人赶路。接应人让屋里遮严窗缝，准备把聚在这里的人再分开安置。他已经请熟路的村民去察看回河西的路，也把顾婶的院子告诉了回头查人的村民；另有人往东梁打听赵石头。名册的边角虽然湿了，十九行字都还能看清。",
      "沈兰贞把写给妹妹小禾的信摊平。信封上只写了“小禾收”，村名仍空着：两年来，只知道小禾跟亲戚去了东边，不知道她如今住在哪个村。杏枝翻到信纸背面，那里还够补几句话。",
    ],
    dialogue: [
      { speaker: "沈兰贞", text: "住处没问准，地址不能乱填。这封信先交给北沟的交通员收着。" },
      { speaker: "赵杏枝", text: "背面还有空。把你现在在哪儿、回信该托给谁写清楚。她拿到信，就知道把回话捎到哪儿。" },
    ],
    historyId: "LiaoCounty",
    choices: [
      {
        id: "printFourMemoryWords",
        label: "刻一版空白接应登记表，滚印三份",
        hint: "蜡纸只刻栏目和约定代号，不刻姓名或路线；北沟、河西和东梁各自填写本地需要的内容。",
        next: "__ending__",
        effects: {
          paper: -1,
          bond: 2,
          compassion: 1,
          flagsSet: ["completedLetter", "memoryComplete"],
        },
        requires: {
          min: {
            paper: 1,
          },
          items: ["mimeographKit", "studentRoster", "letterBundle"],
          flags: ["teacherAcross", "rosterComplete"],
          words: ["person", "name", "road", "home"],
        },
      },
      {
        id: "writeSearchPostscript",
        label: "在信背面写“我在北沟，还在打听你的住处”",
        hint: "再写明回信可托给北沟接应人。不写什么时候一定能送到，只把转信的地方写清楚。",
        next: "__ending__",
        effects: {
          paper: -1,
          bond: 1,
          compassion: 2,
          wordsAdd: ["home"],
          flagsSet: ["completedLetter", "sharedSearchPromise"],
        },
        requires: {
          min: {
            paper: 1,
          },
          items: ["studentRoster", "letterBundle"],
          flags: ["teacherAcross", "rosterComplete"],
        },
      },
      {
        id: "leaveAddressOpen",
        label: "不补地址，先把信交给北沟交通员保管",
        hint: "等问到小禾的准住处再填，免得寄错；原信和其余家信一起收好。",
        next: "__ending__",
        effects: {
          bond: 1,
          compassion: 1,
          wordsAdd: ["home"],
          flagsSet: ["addressLeftOpen"],
        },
      },
    ],
  },
];

export const EndingDefinitions = [
  {
    id: "paperHasAHome",
    priority: 400,
    requires: {
      min: {
        bond: 5,
        compassion: 6,
      },
      max: {
        sound: 4,
        time: 12,
      },
      items: ["mimeographKit", "studentRoster", "letterBundle"],
      flags: ["paperBridge", "teacherAcross", "rosterComplete", "memoryComplete"],
      words: ["person", "name", "road", "home"],
    },
    title: "北沟的三张空白表",
    kicker: "结局一 · 油印包和名册都送到了",
    copy: [
      "天亮后，沈兰贞把蜡纸铺在钢板上，刻了一版空白接应表，滚印了三份。蜡纸上只有事项代号、报信人、最后地点和处理结果几个栏目，没有学生姓名、亲属去处或具体路线。昨夜绑在柳枝上的白纸也全部收了回来，河滩上没有留下过河的记号。",
      "北沟留下一张空表，另外两张分别交给回河西和去东梁的人，由各处只填写本地需要的内容。接应人安排一组去东梁洞找王家人，另一组等河滩的路安全后回去接杨奶奶和小妮。其余家信先由交通员收好，等问到确切住处再送。",
      "抄到赵石头那一行时，杏枝特意多留了半行空处。沈兰贞看了她一眼，没有催，只在旁边写下口信的日期和那位东井妇女的姓名。",
    ],
    finalLine: "“这一行先留宽些，”杏枝说，“找到石头以后，我自己补。”",
  },
  {
    id: "nineteenNames",
    priority: 300,
    requires: {
      min: {
        compassion: 3,
      },
      items: ["studentRoster", "letterBundle"],
      flags: ["teacherAcross", "rosterComplete", "completedLetter"],
      words: ["name", "home"],
    },
    title: "石头那一行没有划掉",
    kicker: "结局二 · 北沟核对名册",
    copy: [
      "两位北沟接应人坐在草铺边，听沈兰贞把十九个名字从头念了一遍。已经问清的，后面写上所在村组；还没问清的，便写最后见到的地方。两人听完，各自又复述一遍，免得只有沈老师一人记着。",
      "赵石头那一行仍是“待寻”。杏枝在旁边添上东井妇女的姓名、见面时辰和“随王家人往东梁洞”几个字，又请接应人把这句话带给去东梁的一组。",
      "写给小禾的信也没有乱填地址。交通员把它和其余家信包在一起，答应托往东边的人到几个接应点打听。沈兰贞在信封背面写下“暂存北沟”，好让捎信的人知道送不成时该退回哪里。",
    ],
    finalLine: "杏枝指着石头那一行说：“这行别划。等东梁回话。”",
  },
  {
    id: "stencilCanBeRecut",
    priority: 200,
    requires: {
      items: ["studentRoster", "letterBundle"],
      flags: ["teacherAcross", "lostMimeographKit", "rosterComplete"],
      words: ["person"],
    },
    title: "油印包还在河滩",
    kicker: "结局三 · 天亮后再托人去找",
    copy: [
      "油印包没能带到北沟。杏枝在简图背面画出缺口巨石、柳根和第三块踏脚石，又说明包压在巨石哪一面。接应人说，等天亮看清水势，再请两个熟悉浅滩的村民去找。包里的钢板和蜡纸是否还能用，现在谁也说不准。",
      "没有油印工具，沈兰贞便借来木炭和几块削平的木片。她逐行念名册，两位接应人把急着核对的姓名和地点抄下来。字写得慢，也不能一次印出许多份，但当天要去东梁和河西问谁，仍能安排下去。",
      "一路上，杏枝总忍不住去摸背后空下来的布带。沈兰贞看见了，只说先把脚养好；若工具泡坏，就去别的教学点借钢板和铁笔，重新刻一套。杏枝点点头，又把河滩简图检查了一遍。",
    ],
    finalLine: "天亮后，两个熟悉水路的村民接过简图，约好等水落一点就去找。",
  },
  {
    id: "beforeDaybreak",
    priority: 100,
    requires: {
      flags: ["teacherAcross"],
    },
    title: "北沟还在等口信",
    kicker: "结局四 · 还有几件事没办完",
    copy: [
      "到北沟时，有些纸受了潮，几个学生的去处仍只能写“待寻”。接应人把要办的事逐件记下：一组回河西接人，一组往东梁洞问王家人，另有人等后到的村民报平安。他们没有让杏枝一个人沿原路回去。",
      "沈兰贞写给小禾的信仍没有地址，只能先收进信束。杏枝也没有立刻见到弟弟。她记下那位妇女说的话，又记下两位接应人的姓名，请他们有消息就捎到北沟。",
      "天亮不久，北沟的人又开始分散转移。沈兰贞的脚踝肿了，只能靠墙歇着。杏枝坐在门槛内侧，和她再对一遍：去东梁要找王家人，回河西要接杨奶奶和小妮，北沟还得留人等消息。",
    ],
    finalLine: "“我不自己乱跑，”杏枝说，“先等东梁那边回话。”",
  },
];
