export const speakerDefinitions = Object.freeze({
  narrator: Object.freeze({ id: "narrator", name: "山中记事", shortName: "记" }),
  Liang: Object.freeze({ id: "Liang", name: "梁守田 · 风口梁", shortName: "梁" }),
  He: Object.freeze({ id: "He", name: "何青禾 · 槐树坪总机", shortName: "何" }),
  child: Object.freeze({ id: "child", name: "石小满 · 青石峪", shortName: "满" }),
});

export const evacueeNames = Object.freeze([
  ["梁春来", 62], ["赵素兰", 58], ["石有成", 47], ["何月琴", 44], ["郭来顺", 39],
  ["李桂英", 36], ["王根生", 35], ["刘秀珍", 33], ["孙满仓", 31], ["张兰芝", 30],
  ["冯万福", 29], ["田巧云", 28], ["梁保国", 26], ["赵秋生", 24], ["石秀兰", 23],
  ["何有德", 22], ["郭小凤", 21], ["李长胜", 19], ["王春妮", 18], ["刘小山", 17],
  ["孙月娥", 16], ["张存粮", 15], ["冯喜梅", 14], ["田来弟", 13], ["梁小锁", 12],
  ["赵杏儿", 12], ["石小满", 11], ["何长河", 11], ["郭麦生", 10], ["李小琴", 10],
  ["王二虎", 9], ["刘槐花", 9], ["孙小石", 8], ["张柳儿", 8], ["冯金锁", 7],
  ["田杏花", 7], ["梁小川", 6], ["赵来喜", 6], ["石豆儿", 6], ["何平安", 5],
  ["郭小兰", 5], ["李谷穗", 5], ["王栓柱", 4], ["刘春芽", 4], ["孙小青", 4],
  ["张满囤", 3], ["冯小麦", 3], ["田石榴", 3], ["梁月生", 2], ["赵冬儿", 2],
  ["石宁宁", 2], ["何小禾", 1], ["郭山娃", 1], ["李安安", 1], ["王盼生", 0],
  ["刘成义", 71], ["孙兰贞", 69], ["张德旺", 66], ["冯桂贞", 64], ["田茂林", 61],
  ["梁秋菊", 54], ["赵万山", 52], ["石桂芳", 49], ["何守仁", 46], ["郭玉枝", 43],
  ["李福生", 41], ["王杏枝", 38],
].map(([name, age], index) => Object.freeze({
  id: `Evacuee_${String(index + 1).padStart(2, "0")}`,
  number: index + 1,
  name,
  age,
})));

const palettes = Object.freeze({
  dusk: Object.freeze({
    skyTop: "#71818a",
    skyBottom: "#d5b27a",
    far: "#66726f",
    middle: "#465550",
    near: "#202d2a",
    ground: "#141c1b",
    haze: "#d9b882",
    accent: "#b34f3f",
  }),
  morning: Object.freeze({
    skyTop: "#778e99",
    skyBottom: "#d7c39c",
    far: "#75857e",
    middle: "#4d625b",
    near: "#263934",
    ground: "#172320",
    haze: "#d2c29f",
    accent: "#a44336",
  }),
  noon: Object.freeze({
    skyTop: "#82949a",
    skyBottom: "#c9c0a1",
    far: "#7a8177",
    middle: "#515e53",
    near: "#2b392f",
    ground: "#1b251f",
    haze: "#c7b58f",
    accent: "#9f3f33",
  }),
  night: Object.freeze({
    skyTop: "#18262b",
    skyBottom: "#35423f",
    far: "#263936",
    middle: "#1c2e2a",
    near: "#11211e",
    ground: "#0a1513",
    haze: "#68746a",
    accent: "#aa5144",
  }),
  smoke: Object.freeze({
    skyTop: "#555e5c",
    skyBottom: "#9c8f76",
    far: "#626761",
    middle: "#484f48",
    near: "#29342e",
    ground: "#151e1a",
    haze: "#aa9270",
    accent: "#b1483a",
  }),
  afterRain: Object.freeze({
    skyTop: "#596f78",
    skyBottom: "#bbc1ae",
    far: "#687c75",
    middle: "#40584f",
    near: "#233b34",
    ground: "#10241f",
    haze: "#c6c2a7",
    accent: "#a84a3d",
  }),
});

export const chapters = Object.freeze([
  Object.freeze({
    id: "Connect",
    order: 0,
    date: "1942年5月23日",
    time: "黄昏",
    title: "第一章 · 接通",
    location: "风口梁观察哨",
    weather: "西南风二级，能见度尚好",
    objective: "认清三个地标，再用手摇电话报告。",
    palette: palettes.dusk,
    viewLabel: "夕阳落在虚构的榆岭县山谷。近处是固定电话线，远处没有可供改写的真实战场。",
    intro: Object.freeze([
      ["narrator", "五月的太行山已经有了暑气。大路被封锁，县里把你派到风口梁：看山、守线、给正在转移的人留一双眼睛。"],
      ["narrator", "这不是一座能看见全世界的高塔。你只能看见三道沟，和一根随时会断的电话线。"],
    ]),
    clues: Object.freeze([
      Object.freeze({
        id: "WindGap",
        label: "风口梁",
        hint: "西侧最高的缺口",
        detail: "缺口上插着两根测风布条。西南风时，红布向东北抖动。",
        x: 0.18,
        y: 0.33,
        kind: "ridge",
      }),
      Object.freeze({
        id: "QingshiVillage",
        label: "青石峪",
        hint: "三缕炊烟下的村落",
        detail: "二十来户人家藏在沟底。撤离前只留少量炊烟，避免让远处看出住户多少。",
        x: 0.53,
        y: 0.61,
        kind: "village",
      }),
      Object.freeze({
        id: "StoneBridge",
        label: "石板桥",
        hint: "东南干河沟上的浅色横线",
        detail: "桥下春季多半无水，是翻过两道封锁线后通向山里的备用路。",
        x: 0.81,
        y: 0.67,
        kind: "bridge",
      }),
    ]),
    requiredClues: Object.freeze(["WindGap", "QingshiVillage", "StoneBridge"]),
    actionLabel: "摇通槐树坪总机",
    actionHint: "三个地标已校准。按住空格或点击电话柄，建立第一次通话。",
    dialogue: Object.freeze([
      ["Liang", "甲梁按约呼叫槐花。两短一长，收到请回。"],
      ["He", "槐花收到。你的呼号是“山雀”。行动期间，线路上只用呼号和图上代号。"],
      ["Liang", "本来还想叫“山石”。"],
      ["He", "省着点，满山都是石头。"],
      ["He", "试报地标。别说“东边”，东边有三条沟。"],
      ["Liang", "甲梁测风布向东北；乙村还有三缕烟；丙桥下无水。"],
      ["He", "清楚。以后你看见的每一件小事，都可能比枪声早半个时辰。"],
    ]),
    historyNote: "敌后观察、预警和通信来自多层网络。游戏把村哨、交通员与固定电话压缩到一个可操作岗位。",
  }),
  Object.freeze({
    id: "Dust",
    order: 1,
    date: "1942年5月24日",
    time: "清晨",
    title: "第二章 · 尘不跟风走",
    location: "风口梁观察哨",
    weather: "西南风转强，公路浮尘",
    objective: "分辨公路动向，为第一批群众找出转移空窗。",
    palette: palettes.morning,
    viewLabel: "清晨山谷中浮尘向两个方向移动；一处道路反光，一处村庄已熄火。",
    intro: Object.freeze([
      ["narrator", "天刚亮，公路上先有一线白光，随后才有声音。你没有望远镜，只能用风、尘和村里的动静互相印证。"],
      ["He", "山雀，别急着报人数。先告诉我：什么在逆着风走？"],
    ]),
    clues: Object.freeze([
      Object.freeze({
        id: "DustColumn",
        label: "逆风尘柱",
        hint: "公路北段的灰黄色长影",
        detail: "风向东北，尘柱却沿公路向西南延伸，说明有车辆或大队人马持续推进。",
        x: 0.73,
        y: 0.52,
        kind: "dust",
      }),
      Object.freeze({
        id: "RoadGlint",
        label: "断续反光",
        hint: "老槐坡下方的亮点",
        detail: "反光隔一阵出现一次，更像车辆玻璃或金属，不是河水。无法据此精确判断数量。",
        x: 0.64,
        y: 0.57,
        kind: "glint",
      }),
      Object.freeze({
        id: "ColdChimneys",
        label: "突然熄灭的炊烟",
        hint: "青石峪上方空下来的天空",
        detail: "村里按约熄火，表示第一批老人和孩子已经离开院落，等待你给出过沟时机。",
        x: 0.45,
        y: 0.64,
        kind: "village",
      }),
    ]),
    requiredClues: Object.freeze(["DustColumn", "RoadGlint", "ColdChimneys"]),
    actionLabel: "报告短暂空窗",
    actionHint: "线索已互相印证。接通电话，给出能负责的判断。",
    dialogue: Object.freeze([
      ["Liang", "公路北段尘柱逆风，老槐坡有断续反光。乙村已经熄火。"],
      ["He", "能不能数出几辆？"],
      ["Liang", "不能。山雾和坡脊挡着，我只能确认车队在向西南。"],
      ["He", "这样报就对。看不见的，不替它编出来。"],
      ["Liang", "丙桥东侧暂时没有尘。第一批可以沿一号沟过。"],
      ["He", "收到。让乙村老人和孩子先走，不追求把东西一次搬完。"],
    ]),
    historyNote: "史实记录中的敌情往往不完整。游戏不会让一次远眺得到精确兵力、番号或全知视野。",
  }),
  Object.freeze({
    id: "Names",
    order: 2,
    date: "1942年5月24日",
    time: "午后",
    title: "第三章 · 不是六十七个",
    location: "风口梁观察哨",
    weather: "闷热，远山积云",
    objective: "先接通一条支线，并承担看得见的物资代价。",
    palette: palettes.noon,
    viewLabel: "午后的两条电话支线分别通向卫生所和青石峪，线路负荷只允许先接通一处。",
    intro: Object.freeze([
      ["narrator", "记事簿把话密译成可读地名；线路上的原话只使用甲梁、乙村、丙桥等代号。"],
      ["He", "主线受潮漏电，两条支线并接后都摇不响。交换台今晚停线转移，只来得及临时接通一处。"],
      ["He", "村里和卫生员已经商量出两套先后，只等我们根据线路时限通知一边。人都能撤，但两样东西保不全。"],
      ["Liang", "乙村这次转移，一共多少？"],
      ["He", "六十七。"],
      ["Liang", "收到，群众六十七。"],
      ["He", "不。把名册上的称谓写下。"],
      ["Liang", "纸不够。"],
      ["He", "背面也能写。别让人只剩个数。"],
    ]),
    clues: Object.freeze([
      Object.freeze({
        id: "ClinicLine",
        label: "卫生所支线",
        hint: "北坡白墙下垂落的线",
        detail: "先接卫生所，能多带走药箱和绷带；村里来不及把一袋谷种送进山洞。",
        x: 0.32,
        y: 0.55,
        kind: "clinic",
      }),
      Object.freeze({
        id: "GranaryLine",
        label: "青石峪支线",
        hint: "沟口两根并行木杆",
        detail: "先接村口，能藏好来年的谷种；卫生所必须丢下一箱笨重器械。",
        x: 0.61,
        y: 0.62,
        kind: "granary",
      }),
    ]),
    requiredClues: Object.freeze(["ClinicLine", "GranaryLine"]),
    actionLabel: "决定先接哪条支线",
    actionHint: "两项代价已经说明。没有无损选项，也不会因选择造成人员死亡。",
    choice: Object.freeze({
      id: "SupplyChoice",
      prompt: "停线前只够先叫通一处",
      context: "人都能继续撤离。村里与卫生员已商量出两案，请你根据剩余通话窗口决定先通知哪一处。",
      options: Object.freeze([
        Object.freeze({
          id: "Medicine",
          title: "先接卫生所",
          cost: "药品与绷带保存；青石峪失去一袋谷种",
          detail: "伤病救护条件更好，返乡后的第一季播种会更难。",
        }),
        Object.freeze({
          id: "Seed",
          title: "先接青石峪",
          cost: "谷种保存；卫生所丢下一箱器械",
          detail: "返乡后能尽快播种，但伤员转移时可用器械更少。",
        }),
      ]),
    }),
    choiceDialogue: Object.freeze({
      Medicine: Object.freeze([
        ["Liang", "先接甲所。谷种的位置写清，等封锁松一点再想办法。"],
        ["He", "收到。药箱和绷带上路，种粮留在暗窖。它可能还在，也可能等不到我们。"],
      ]),
      Seed: Object.freeze([
        ["Liang", "先接乙村。来年要有人把地种起来。"],
        ["He", "收到。谷种进山洞，卫生员只带能背动的药和器械。"],
      ]),
    }),
    historyNote: "转移不等于无损。医疗器材、种粮、农具和房屋的损失会长期影响群众生活，本作不把它们换算成战果。",
  }),
  Object.freeze({
    id: "Repair",
    order: 3,
    date: "1942年5月24日",
    time: "深夜",
    title: "第四章 · 线断在半山",
    location: "半山接线盒",
    weather: "积云遮月，碎石坡有落石",
    objective: "摸黑确认断点，绞紧线条，重新固定瓷质绝缘子。",
    palette: palettes.night,
    viewLabel: "月光被积云遮住的碎石坡，只能看见接线盒、被扯落的线条与歪斜的瓷质绝缘子。",
    intro: Object.freeze([
      ["narrator", "夜里十一点，主线断了。你沿线下山，没有点灯。断处不是什么伏击：一块松石滚下来，惊了驮牲口，蹄子把线踩进泥里。"],
      ["narrator", "战争已经够可怕，不必把每块落石都编成敌人的阴谋。"],
    ]),
    clues: Object.freeze([
      Object.freeze({
        id: "DamagedSpan",
        label: "找到受损线段",
        hint: "沿电杆与瓷头确认扯落处",
        detail: "落石把线条扯离瓷头，惊起的牲口又把松垂段踩进泥里。你剪去受损的一小段。",
        x: 0.36,
        y: 0.67,
        kind: "wire",
      }),
      Object.freeze({
        id: "TwistJoint",
        label: "绞紧接头",
        hint: "两端交叠，再向相反方向缠紧",
        detail: "接头要能承受山风拉扯。你让线材两端交叠，用钢钳向相反方向缠紧。",
        x: 0.51,
        y: 0.59,
        kind: "repair",
      }),
      Object.freeze({
        id: "ResetInsulator",
        label: "重新固定瓷头",
        hint: "把接好的线架回瓷质绝缘子",
        detail: "线条重新离开泥地与湿木杆。你不用火花试线，只按约定摇铃，让交换台确认能否响铃。",
        x: 0.65,
        y: 0.69,
        kind: "repair",
      }),
    ]),
    requiredClues: Object.freeze(["DamagedSpan", "TwistJoint", "ResetInsulator"]),
    actionLabel: "试摇两短一长",
    actionHint: "断点已修好。用约定铃声确认线路，而不是大声呼叫站名。",
    dialogue: Object.freeze([
      ["He", "两短一长，听见了。你那边怎么断的？"],
      ["Liang", "落石惊了牲口。线已绞紧，重新架回瓷头。不是敌情。"],
      ["He", "那就这么写，别把偶然都写成战功。"],
      ["Liang", "你那边在收什么？听着像豆子。"],
      ["He", "五颗杏核。乙村一个孩子塞给我的，说回去以后要种在学校窗下。"],
      ["Liang", "所以孩子们叫你先生。"],
      ["He", "线路安静的时候，我教识字。最近它一直没安静过。"],
      ["Liang", "才五颗。"],
      ["He", "能回去一颗，就种一颗。"],
    ]),
    historyNote: "山地线路会因自然和日常事故中断。通信维护首先是重复、琐碎而危险的劳动，不等于不断发生战斗。",
  }),
  Object.freeze({
    id: "Encirclement",
    order: 4,
    date: "1942年5月25日",
    time: "下午",
    title: "第五章 · 合围",
    location: "风口梁观察哨",
    weather: "烟尘遮山，非写实远炮声",
    objective: "在视野不可靠时，为最后一批群众选择有代价的路线。",
    palette: palettes.smoke,
    viewLabel: "同一天下午，辽县麻田以东至十字岭一带正发生真实突围战斗；本章远炮声为非写实时间氛围，不代表虚构地点能听见或定位真实战场。",
    intro: Object.freeze([
      ["narrator", "同一天下午，辽县麻田以东至十字岭一带正发生真实突围战斗。本章远炮声只是非写实的时间氛围，不代表这座虚构山梁能听见或定位真实战场。"],
      ["He", "山雀，烟把公路吃掉了。只报你能确认的。最后一批在沟口等。"],
    ]),
    clues: Object.freeze([
      Object.freeze({
        id: "PatrolFigures",
        label: "石坡旧路的人影",
        hint: "烟幕后两次横向移动的黑点",
        detail: "旧路上可能有搜索人员经过。等待人影离开后再走，会错过下一次约定通话。",
        x: 0.69,
        y: 0.47,
        kind: "patrol",
      }),
      Object.freeze({
        id: "DryRiver",
        label: "干河沟的背阴面",
        hint: "桥下向西弯的深色沟槽",
        detail: "沟里更隐蔽，却陡到无法推车。被褥和一部分农具必须留在原地。",
        x: 0.43,
        y: 0.68,
        kind: "river",
      }),
      Object.freeze({
        id: "SmokeVeil",
        label: "不可穿透的烟幕",
        hint: "远山整片灰白",
        detail: "烟尘遮住了更远处。你不能据此判断任何真实部队位置，只能把它标为“未知”。",
        x: 0.82,
        y: 0.37,
        kind: "smoke",
      }),
    ]),
    requiredClues: Object.freeze(["PatrolFigures", "DryRiver", "SmokeVeil"]),
    actionLabel: "选择最后一批的路线",
    actionHint: "现有观察认为两案都可行，但人物无法预知绝对安全；你要选择承担哪一种已知代价。",
    choice: Object.freeze({
      id: "RouteChoice",
      prompt: "烟尘中的两条路",
      context: "两条路都存在风险。现有观察认为两案可行：干河沟隐蔽但必须弃车；石坡旧路能保住车，但要等待搜索人影离开。",
      options: Object.freeze([
        Object.freeze({
          id: "River",
          title: "走干河沟",
          cost: "人员更快进山；丢下手推车、被褥和部分农具",
          detail: "你还能赶上黄昏通话，但返乡后的生活损失更重。",
        }),
        Object.freeze({
          id: "StoneRoad",
          title: "等人影过去，走石坡旧路",
          cost: "保住手推车和被褥；错过黄昏前一次通话",
          detail: "依现有判断，人和车可以继续前往下一隐蔽点，线路却会更久没有确认。",
        }),
      ]),
    }),
    choiceDialogue: Object.freeze({
      River: Object.freeze([
        ["Liang", "走丙桥下的一号沟。车留在桥洞里，人先过。"],
        ["He", "收到。把丢下的东西也记上，不要只写“转移顺利”。"],
      ]),
      StoneRoad: Object.freeze([
        ["Liang", "等旧路人影过去，车不能再丢。下一次通话我可能赶不上。"],
        ["He", "收到。人和车都慢一点走。线路失联不等于人出了事，我会等约定铃声。"],
      ]),
    }),
    historyNote: "1942年5月25日，左权在辽县十字岭战斗中牺牲。这一史实只作为远方时间锚点，玩家没有“营救”或改写选项。",
  }),
  Object.freeze({
    id: "RollCall",
    order: 5,
    date: "1942年5月25日",
    time: "黄昏",
    title: "第六章 · 把每个人记下来",
    location: "风口梁观察哨",
    weather: "烟尘转薄，主线电阻升高",
    objective: "看着本地纸面名册，用编号核对六十七人的在册与编组记号，并决定在第六十三号后如何处理暴露线路。",
    palette: palettes.smoke,
    viewLabel: "黄昏的电话线向槐树坪延伸。画面只呈现线路、山风与姓名簿，不呈现枪战。",
    intro: Object.freeze([
      ["He", "总机准备停线。最后七个人已经编进转移队伍。交通员刚把乙村名册副本送到你那边。"],
      ["Liang", "六十七人，全核？"],
      ["He", "全核。你看着纸上姓名，线路里只报编号和编组记号。别快，快了又成了数字。"],
    ]),
    clues: Object.freeze([]),
    requiredClues: Object.freeze([]),
    actionLabel: "打开名册，开始按号核对",
    actionHint: "姓名只显示在本地纸面；电话中使用编号。核对到第六十三号时，线路会出现异常。",
    rollCall: true,
    choice: Object.freeze({
      id: "LineChoice",
      prompt: "第六十三号后，杂音变成连续低鸣",
      context: "可能有人沿暴露段追查，也可能只是接头进水。继续十秒能核完末四个编组记号；立即切断能带走一卷备用线。",
      options: Object.freeze([
        Object.freeze({
          id: "Listen",
          title: "再听十秒，核完末四个编组号",
          cost: "六十七人的编组记号当夜完整；备用线来不及带走",
          detail: "临时站恢复会更慢，但纸面名册不留下空白。",
        }),
        Object.freeze({
          id: "Cut",
          title: "立即切断暴露段",
          cost: "带走备用线；四个编组记号将在数日后以另一种墨迹补上",
          detail: "新站更快接通，纸面名册暂时留下四行空白。",
        }),
      ]),
    }),
    choiceDialogue: Object.freeze({
      Listen: Object.freeze([
        ["He", "六十四编入，六十五编入，六十六编入，六十七编入。"],
        ["Liang", "纸面四行都补上编组记号。六十七人，全核。"],
        ["He", "名册合上。现在切线。"],
      ]),
      Cut: Object.freeze([
        ["Liang", "山雀收到。线路可能暴露，按约停线。余下四个编组记号留空，只写“待回条”。"],
        ["He", "收到。末四号的编组回条我带着。新站接通以后，一项不少地补给你。"],
      ]),
    }),
    historyNote: "纸面名册中的六十七个姓名均为虚构；线路上只核对编号和编组记号。它不对应真实村庄或受难者名录。",
  }),
  Object.freeze({
    id: "StillConnected",
    order: 6,
    date: "1942年5月31日",
    time: "雨后清晨",
    title: "终章 · 线还通着",
    location: "北山口临时电话点",
    weather: "雨后初晴，东南山脊可见",
    objective: "听完约定铃声，把一颗杏核种在线旁。",
    palette: palettes.afterRain,
    viewLabel: "雨后太行山谷。新架的电话线从北山口向远处延伸，近处泥土里留着一颗杏核的位置。",
    intro: Object.freeze([
      ["narrator", "六天后，北山口的新线接了起来。那卷备用线和名册末四行，各自记着你在十秒里没有办法两全的事。"],
      ["narrator", "上午九点，电话先响两短一长。"],
    ]),
    clues: Object.freeze([
      Object.freeze({
        id: "NewLine",
        label: "新架的线路",
        hint: "雨后山口上一道绷紧的暗线",
        detail: "线路不是胜利的纪念碑。它只是让仍在山里的人重新知道彼此还在。",
        x: 0.61,
        y: 0.43,
        kind: "wire",
      }),
      Object.freeze({
        id: "AlmondPlace",
        label: "杏核该埋的地方",
        hint: "电话杆背风侧的一小块湿土",
        detail: "五颗杏核中的一颗留在这里。其余四颗跟着青石峪的人继续进山。",
        x: 0.43,
        y: 0.75,
        kind: "almond",
      }),
    ]),
    requiredClues: Object.freeze(["NewLine", "AlmondPlace"]),
    actionLabel: "接起两短一长",
    actionHint: "线路已经接通。完成最后一次通话。",
    dialogue: Object.freeze([
      ["He", "新站一号，听见吗？"],
      ["Liang", "山雀听见。"],
      ["He", "乙村六十七号，全到。东西丢了些，人都在。"],
      ["Liang", "你呢？"],
      ["narrator", "线路里只有三秒山风。"],
      ["He", "我也在。"],
      ["child", "梁叔，何先生说那颗杏核归你。别埋太深，春天找不着。"],
      ["narrator", "后来那棵杏树没有碑。每年春天，它先开花。"],
    ]),
    historyNote: "局部人物的存续属于虚构故事。全国抗战仍将经历漫长牺牲，并在全民族抗战和世界反法西斯战争共同作用下于1945年取得胜利。",
  }),
]);

export const rememberedConsequences = Object.freeze({
  Medicine: Object.freeze({
    label: "卫生所先接通",
    ledger: "药箱和绷带随队转移；一袋谷种留在青石峪暗窖，去向不明。",
    epilogue: "卫生员用保存下来的绷带重新包扎了三名伤员。",
  }),
  Seed: Object.freeze({
    label: "青石峪先接通",
    ledger: "谷种送进山洞；卫生所丢下一箱无法背走的器械。",
    epilogue: "那袋谷种在第二年春天分到了几处临时田地。",
  }),
  River: Object.freeze({
    label: "最后一批走干河沟",
    ledger: "最后一批弃车进入干河沟，向下一隐蔽点转移；手推车、被褥与部分农具留在石板桥附近。",
    epilogue: "人先到了，被褥和车没有。雨夜里几家人共用一床毡。",
  }),
  StoneRoad: Object.freeze({
    label: "最后一批等候旧路空窗",
    ledger: "最后一批带车等候旧路空窗，再向下一隐蔽点转移；槐树坪线路多失联一个时段。",
    epilogue: "车上的被褥保住了；青禾在无回音的线路边多等了一个时辰。",
  }),
  Listen: Object.freeze({
    label: "当夜核完六十七号",
    ledger: "纸面名册的编组记号当夜完整；一卷备用电话线没能带出槐树坪。",
    epilogue: "六十七个编组记号都用同一种铅笔补齐，新站晚接通了半日。",
  }),
  Cut: Object.freeze({
    label: "先切断暴露线路",
    ledger: "一卷备用电话线被带出；末四个编组记号等待回条。",
    epilogue: "新站早接通了半日，末四个编组记号在5月31日以蓝黑墨水补录。",
  }),
});

export function GetChapter(chapterIndex) {
  return chapters[Math.max(0, Math.min(chapters.length - 1, chapterIndex))];
}

export function GetConsequence(choiceId) {
  return rememberedConsequences[choiceId] ?? null;
}
